### ISSUE TITLE
移动应用内网发布工具（开源）

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#10]
https://github.com/pluosi/app-host

**Comment by lacklock** [comment]
+ 1

**Comment by lacklock** [comment]
+1

**Comment by kemchenj** [comment]
+1

**Comment by mmoaay** [comment]
一个轻量级的包托管网站，app-host 主要用于 iOS 和 Android 的包管理，作用类似于fir.im，不同之处是可以自由部署在内网，方便了公司项目保密。并且代码开源也可以方便根据各自需求进行定制化开发。
