### ISSUE TITLE
Swift 数据结构与算法学院，中文翻译

### ISSUE THREAD

**Issue by XanderXu** [SwiftOldDriver/iOS-Weekly#1009]
# 推荐收录

## 链接

https://github.com/KeithMorning/swift-algorithm-club-cn 

## 理由

Raywenderlich 家 https://github.com/raywenderlich/swift-algorithm-club 的中文翻译版，翻译仍在进行中

**Comment by olddonkey** [comment]
鉴于目前作者从原本的Raywenderlich fork下来之后只做了主readme的翻译，里面的内容暂时还没翻译，所以觉得以现在有的内容，不够推荐标准，暂时close，如果之后有更多的内容翻译，欢迎随时重新打开重新推荐。

**Comment by XanderXu** [comment]
换个源https://github.com/andyRon/swift-algorithm-club-cn
这个完成度很高，目前还在持续翻译中，接近完成
