### ISSUE TITLE
js在微信、微博、QQ、Safari唤起App的解决方案

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#101]
https://segmentfault.com/a/1190000012940046

**Comment by raozhizhen** [comment]
经过长时间的实验，总结微博、微信、QQ、Safari 在 iOS 及安卓平台唤起成功/失败的解决方案，实现用户点击 H5 页面的打开 App 或者下载按钮，如果用户已经安装了App，则根据业务跳转到相应的 Native 页面；如果用户没有安装该应用，则跳到 AppStore 或者应用市场去下载 App。
