### ISSUE TITLE
iOS 原生 App 是怎么 deselectRow 的？

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1012]
# 推荐收录

## 链接

https://kemchenj.github.io/2018-12-24/

**Comment by xiaofei86** [comment]
作者的调研存在问题，此效果是使用 UITableViewController 的默认效果，可以通过属性 clearsSelectionOnViewWillAppear 控制，并且官方文档 《Table View Programming Guide for iOS》里有明确说明，并不需要自己实现转场动画。此知识点太琐碎，而且不管作为普及此知识点推荐还是作为转场动画实现推荐都讲的不清楚，Table View Programming Guide 里还很多类似技巧的使用指南，古不推荐收录。

**Comment by hite** [comment]
@xiaofei86 你低估了transitionCoordinator 这个属性，我猜想你说的 clearsSelectionOnViewWillAppear 只是用 transitionCoordinator 实现的效果，其他的效果比方说，左滑时，键盘逐渐缩回底部等动效都可以用这个属性实现。更重要的效果，可以放置的 viewWillDisappear 里做文章。
