### ISSUE TITLE
ISO-8601, YYYY, yyyy, and why your year may be wrong

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#1014]
# 推荐收录

## 链接

[ISO-8601, YYYY, yyyy, and why your year may be wrong](https://ericasadun.com/2018/12/25/iso-8601-yyyy-yyyy-and-why-your-year-may-be-wrong/)

**Comment by zvving** [comment]
认领简评

**Comment by ParsifalC** [comment]
> 认领简评

ok

**Comment by zvving** [comment]
🐎[ISO-8601, YYYY, yyyy, and why your year may be wrong](https://ericasadun.com/2018/12/25/iso-8601-yyyy-yyyy-and-why-your-year-may-be-wrong/)
小写 `yyyy` 是我们常用的格式化日期 `年` 参数，如果误写成大写 `YYYY`，会有什么问题？
大部分情况下，它们似乎没有区别，但在每年的最后一周，它又会给我们带来意外的结果。
本文作者将带你了解 `YYYY` 对应的[ISO周日历](https://zh.wikipedia.org/wiki/ISO週日曆)，从而真正理解它们的不同。
