### ISSUE TITLE
A guide to writing your own iOS CI/CD integration script

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#1020]
# 推荐收录

## 链接

[A guide to writing your own iOS CI/CD integration script](https://medium.com/appssemble/a-guide-to-writing-your-own-ios-ci-cd-integration-script-186be1b99575)

**Comment by ParsifalC** [comment]
@zvving 这个你的

**Comment by zvving** [comment]
👌

**Comment by zvving** [comment]
[Fastlane](https://docs.fastlane.tools/)、[Jenkins](https://jenkins.io/) 构建是 CI/CD（持续集成/持续部署）工作流的常用工具。本文另辟蹊径，不使用第三方工具，只基于苹果的基础工具链构建一个包含编译、测试、检查代码覆盖、签名、分发等相对完整的 CI/CD 工作流。
如果你还不了解 CI/CD 原理，不妨对着本文做一遍，相信可以快速掌握其运行过程。
