### ISSUE TITLE
知识小集 2018 下半年文章汇总及年终总结

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1028]
# 推荐收录

## 链接

https://juejin.im/post/5c25a787f265da614b120eac

## 理由

知识小集内容不错，这种汇总类的文章我们考虑收录吗？

相关内容：https://github.com/SwiftOldDriver/iOS-Weekly/issues/514

**Comment by ParsifalC** [comment]
@nianran 也到总结那个分类吧

**Comment by nianran** [comment]
OK
