### ISSUE TITLE
软件工程师需要了解的网络知识：从铜线到HTTP（一）—— 前言

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#103]
https://lvwenhan.com/操作系统/485.html

**Comment by iblacksun** [comment]
这是一系列文章，其目标是让软件工程师了解网络各层的本质。系列文章从网线开始讲起，一路带你了解 `以太网`、`TCP/IP` 和 `HTTP/HTTPS`，建议精读。
