### ISSUE TITLE
[App探索]JSBox中幽灵触发器的实现原理探索

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1035]
# 推荐收录

## 链接

https://juejin.im/post/5c2c16b66fb9a049e12a4f0e?utm_source=gold_browser_extension

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
@GesanTung 这篇你来哈
