### ISSUE TITLE
How to use raw strings in Swift 5

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1041]
# 推荐收录

## 链接

https://www.hackingwithswift.com/articles/162/how-to-use-raw-strings-in-swift

**Comment by ParsifalC** [comment]
@zvving 这个就你自己吧

**Comment by zvving** [comment]
🐎[How to use raw strings in Swift 5](https://www.hackingwithswift.com/articles/162/how-to-use-raw-strings-in-swift)
当字符串应用于正则或初始化 JSON 等场景时，转义字符会给我们带来一些小烦恼。比如试试查找 `\(sth)` 的正则如何实现？
通读本文，可以快速了解 Swift 5 中的原始字符串`#"raw string"#`该如何应用。

扩展阅读：[SE-0200](https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md)

**Comment by iblacksun** [comment]
🐎 [How to use raw strings in Swift 5](https://www.hackingwithswift.com/articles/162/how-to-use-raw-strings-in-swift)
当字符串应用于正则或初始化 JSON 等场景时，转义字符会给我们带来一些小烦恼。比如试试查找 `\(sth)` 的正则如何实现？
Swift 5 中，新增了 Raw String 语法(用井号包裹，`#"raw string"#`)， 通读本文，可以快速了解 Swift 5 中的原始字符串该如何应用。

扩展阅读：[SE-0200](https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md)
