### ISSUE TITLE
小程序支持跳转APP了

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#106]
https://mp.weixin.qq.com/s/0etOZyu0XXbRcHE7vvqiDA

**Comment by lacklock** [comment]
我注意到饿了么分享链接到微信的时候，点击进去已经是小程序了。
还是 @mmoaay 来介绍一下这条新闻感觉有说服力。

**Comment by mmoaay** [comment]
对于开发人员来说，更需要关注的是[打开 App](https://mp.weixin.qq.com/debug/wxadoc/dev/api/launchApp.html) 以及 [App 链接分享到微信打开小程序](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317332&token=&lang=zh_CN)的代码怎么写？
