### ISSUE TITLE
[译]状态恢复入门教程

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1060]
# 推荐收录

## 链接

https://github.com/xitu/gold-miner/blob/master/TODO1/state-restoration-tutorial-getting-started.md

**Comment by iblacksun** [comment]
感觉这篇翻译质量有点差，要不要直接推原文？或者可以在摘要中附上译文。

**Comment by ParsifalC** [comment]
@GesanTung 这个给你~
