### ISSUE TITLE
Implementing Promises in Swift

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#1069]
# 推荐收录

## 链接

https://felginep.github.io/2019-01-06/implementing-promises-in-swift

**Comment by kemchenj** [comment]
### [Implenting Promises in Swift](https://felginep.github.io/2019-01-06/implementing-promises-in-swift)

目前网上很少有 Swift 实现 Promises 相关的文章，所以作者写了一篇文章分享了相关的内容，并且作者选择了测试驱动开发，不断地构建测试，然后再不断地调整代码满足测试，非常值得一看。
