### ISSUE TITLE
Cocoapods是如何做校验的（缺少支持i386导致pod lib lint失败）

### ISSUE THREAD

**Issue by caixindong** [SwiftOldDriver/iOS-Weekly#1072]
# 推荐收录
老司机iOS周报
## 链接
https://xiaozhuanlan.com/topic/5869024173

## 理由
Cocoapods不支持跳过i386架构校验这个痛点一直存在，文章除了提供解决方法以外，还提供阅读Cocoapods源码的方法论

**Comment by nianran** [comment]
您好，非常感谢您对于我们的支持。
目前我们周报更倾向于免费文章的推荐，付费内容更倾向于高质量的博文。
基于此原则，暂时先关闭此 issue。
建议可以将本文转免费，再同步给各个平台，文中推荐自己的专栏。
