### ISSUE TITLE
How to read Apple’s developer documentation

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1075]
# 推荐收录

## 链接

https://www.hackingwithswift.com/articles/167/how-to-read-apples-developer-documentation

## 理由

阅读开发文档是我们必须掌握的一个基本技能，尤其是现如今 Swift 的文档相比于 Objective-C 完善了很多，阅读文档在多数时候会比我们去网上随便搜索来的有用靠谱得多。

**Comment by kemchenj** [comment]
### [How to read Apple’s developer documentation](https://www.hackingwithswift.com/articles/167/how-to-read-apples-developer-documentation)

阅读技术文档是工程师必备的技能之一，但很有趣的是，阅读技术文档不只是国人入门编程的一道坎，其实很多以英语为母语的人也一样不擅长。Swift 技术网站 Hacking With Swift 过去一年收到最多的文章请求，就是帮助读者阅读和理解苹果的代码文档，所以就诞生了这么一篇文章。

作者首先帮助大家理清技术文档的内容和结构，接着以具体的例子带着大家一起“查文档”，找到对应的定义，例子和代码，最后还鼓励大家，其实苹果的文档也有很多不足的地方，大家找不到自己需要的东西的时候也不需要灰心。
