### ISSUE TITLE
It Looks Like You Are Trying to Use a Framework

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1078]
# 推荐收录

## 链接

https://www.bignerdranch.com/blog/it-looks-like-you-are-trying-to-use-a-framework/
https://www.bignerdranch.com/blog/it-looks-like-you%27re-still-trying-to-use-a-framework/

## 理由

非常详尽地介绍 Frameworks 的两篇文章。

**Comment by ParsifalC** [comment]
@zvving 这个给你的哈

**Comment by zvving** [comment]
🐕[It Looks Like You Are Trying to Use a Framework](https://www.bignerdranch.com/blog/it-looks-like-you-are-trying-to-use-a-framework/)
[It Looks Like You're Still Trying to Use a Framework](https://www.bignerdranch.com/blog/it-looks-like-you%27re-still-trying-to-use-a-framework/)

Frameworks 是打包资源和拆分代码的常用方式。拆分 Frameworks 的作用不仅仅是避免构建时的重复编译，合理的使用 Frameworks，可以让代码库层次清晰，提升调试效率，确保代码结构保持最大的可重用性。

[第一篇文章](https://www.bignerdranch.com/blog/it-looks-like-you-are-trying-to-use-a-framework/) 包含 Frameworks 相关的基础知识：
- 静态库
- 动态库
- Frameworks 及其内部结构
- 在 Xcode 中链接和嵌入 Frameworks
- 使用 Frameworks 前要考虑的因素
- 一些方便探索 Frameworks 的命令行工具

[第二篇文章](https://www.bignerdranch.com/blog/it-looks-like-you%27re-still-trying-to-use-a-framework/)则引导我们在逐步解决构建错误的过程中理解 Frameworks，还会介绍 Swift 和 Objective-C 混编时接口间是如何找到的。
