### ISSUE TITLE
iOS WebView跨域访问漏洞

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#108]
https://mp.weixin.qq.com/s/aRlxqxGw8etqep62qG4khA

**Comment by Awhisper** [comment]
UIWebView 此漏洞默认存在， WKWebView如果使用了不恰当的方式比如 [configuration.preferences setValue:@"TRUE" forKey:@"allowFileAccessFromFileURLs"]; 也会存在，WKWebView加载本地file页面，请使用别的姿势

漏洞效果 A APP如果存在这个漏洞，攻击者可以拿到 别的APP也就是iOS 手机沙盒内所有路径下的内容
