### ISSUE TITLE
漏洞预警 |iOS WebView跨域访问漏洞

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#109]
https://mp.weixin.qq.com/s/aRlxqxGw8etqep62qG4khA

UIWebView 此漏洞默认存在， WKWebView如果使用了不恰当的方式比如  [configuration.preferences setValue:@"TRUE" forKey:@"allowFileAccessFromFileURLs"]; 也会存在，WKWebView加载本地file页面，请使用别的姿势

漏洞效果 A APP如果存在这个漏洞，攻击者可以拿到 别的APP也就是iOS 手机沙盒内所有路径下的内容

**Comment by lacklock** [comment]
以后推到md文件里再close，免得忘记了。

**Comment by lacklock** [comment]
中英文混的时候前后要加空格，格式改一下。

**Comment by Awhisper** [comment]
收到 已经改了
