### ISSUE TITLE
Creating Flows

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#110]
https://mag.n26.com/creating-flows-f1c2e1bc8108
完整注册过程通常会分散为几个页面收集信息，这篇文章里通过声明一个protocol Step来统一这些步骤，提高可维护性。

**Comment by kemchenj** [comment]
### [Creating Flows](https://mag.n26.com/creating-flows-f1c2e1bc8108)

流程是用户交互设计的一个重点，例如说注册，我们不会给用户展示一个长长的列表去填写信息，而是会切分成多个页面去让用户逐步完成。那么我们该如何使用代码去组织这样的流程呢？在这篇文章里作者就深入地探讨了如何使用低耦合的组件来完成这样一套流程。
