### ISSUE TITLE
Simplifying Swift framework development

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#112]
https://davedelong.com/blog/2018/01/19/simplifying-swift-framework-development

介绍了两个使用swift framework时的简化小技巧。
- 使用 @_exported 声明引用，不用在每个swift文件中声明，类似oc中的pre header
- 更方便使用framework中资源文件的方式。

**Comment by mmoaay** [comment]
介绍了两个简化 Swift Framework 开发的小技巧：
- 使用 `@_exported` 声明引用，从而不用在每个 Swift 文件中都进行声明，类似  Objective-C 中的 Prefix Header；
- 通过 `class` 的方式生成 `Bundle`，并定义成 Constant，从而更方便地获取 Framework 中的资源文件。
