### ISSUE TITLE
Using protocols as composable extensions

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1122]
# 推荐收录

## 链接

https://mecid.github.io/2019/01/17/using-protocols-as-composable-extensions/

**Comment by kemchenj** [comment]
### [Using protocols as composable extensions](https://mecid.github.io/2019/01/17/using-protocols-as-composable-extensions/)

面向协议是 Swift 推崇的一种编程范式，标准库里的基础类型也都是基于协议搭建起来的，利用 protocol extensions 的特性去达成复用和组合，但这些范式如何落实到业务上呢？这篇文章的作者就介绍了如何通过 protocol extension 去完成一个加载动画，并且对比了继承和协议的两种实现方式。
