### ISSUE TITLE
不止于抢红包，功能丰富的微信插件。

### ISSUE THREAD

**Issue by DKJone** [SwiftOldDriver/iOS-Weekly#1129]
# 推荐收录

## 链接

[DKWechatHelper](https://github.com/DKWechatHelper/DKWechatHelper)

## 理由

年终将近，又到了抢红包的时刻，微信7.0可用的红包插件

## 推荐人信息

[DKJone](https://github.com/DKJone)

**Comment by Damonvvong** [comment]
对于技术人来说，研究逆向是一个不错的方向。

但我认为不应该宣传「抢红包」插件。所以建议关闭这个。 @ParsifalC
