### ISSUE TITLE
Top-down iOS error architecture

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#113]
https://medium.com/@londeix/top-down-error-architecture-d8715a28d1ad

构建了一套类似于 Responder Chain 的错误处理机制，主要是为了避免错误处理代码散乱的问题

**Comment by lacklock** [comment]
不是很懂。error的作用域通常都非常明显，没有层次的问题啊。

**Comment by lacklock** [comment]
@iblacksun 你觉得有必要收录吗？

**Comment by iblacksun** [comment]
@lacklock @kemchenj 我看懂了思路但是没看懂实现...

**Comment by Damonvvong** [comment]
我的理解和 @lacklock  一样，实际操作过程中 error 没有层次问题。
