### ISSUE TITLE
@dynamicCallable

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1137]
# 推荐收录

## 链接

[#1 Unix Tools as Swift Functions](http://www.alwaysrightinstitute.com/swift-dynamic-callable/)
[#2 Swift/ObjC Bridge](http://www.alwaysrightinstitute.com/swift-objc-bridge/)
[#3 Mustasheable](http://www.alwaysrightinstitute.com/mustacheable/)

## 理由

利用 Swift 5 新增的 @dynamicCallable 功能做了 Shell 和 Objective-C 的 Bridge，对于 Shell 的桥接让我看到了 Swift 作为胶水语言的可能性。

**Comment by zvving** [comment]
Magic!  👍
这个简评不好写，学习下先 ；）

**Comment by zvving** [comment]
🐢Swift5 新特性 @dynamicCallable 带来的动态魔法


一年前周报的第一期我们曾经提过：[Swift 快要可以和 Python 无缝交互了](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171204/042029.html)，一年后的今天伴随着 Swift5 新特性 `@dynamicCallable` 的发布，『用 Swift 写 Python 变成现实』。

起源是 Chris Lattner 大神的两个提案：`@dynamicMemberLookup` 提供动态查找成员的能力（Swift4.2），`@dynamicCallable` 则提供动态方法调用的能力（Swift5）。很难想象，两个语法糖重新定义语言动态性，让人看到 Swift 成为胶水语言的可能。

下面三篇系列文章带我们感受语法糖带来的神奇魔法：

- [#1 Unix Tools as Swift Functions](http://www.alwaysrightinstitute.com/swift-dynamic-callable/) 一层薄薄的封装让所有 Unix Tools 变成 Swfit 方法，提供这样的调用方式：`shell.env()`, `shell.ls("-a", "-l")`, `shell.python("--version")`；
- [#2 Swift/ObjC Bridge](http://www.alwaysrightinstitute.com/swift-objc-bridge/) 基于 @dynamicCallable 轻松实现一套 Swift - Objective-C 的桥接。实现思路类似 [PyObjC](https://pythonhosted.org/pyobjc/)；
- [#3 Mustasheable](http://www.alwaysrightinstitute.com/mustacheable/) 为模板语言[Mustache](http://mustache.github.io/)的生成器提供简洁优雅的调用方式。


相关阅读：[细说 Swift 4.2 新特性：Dynamic Member Lookup](https://juejin.im/post/5b24c9896fb9a00e69608a71)

**Comment by zvving** [comment]
这个不好写， @lacklock 帮忙 review 下
