### ISSUE TITLE
Swift 5 Exclusivity Enforcement

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1141]
# 推荐收录

## 链接

https://swift.org/blog/swift-5-exclusivity/

## 理由

Swift 5 的 Release Build 默认开启独占访问，这篇文章主要是解释为什么这会对 Swift 的内存安全性和性能起到本质性的作用。

**Comment by iblacksun** [comment]
@[ParsifalC](/ParsifalC) 这篇我要仔细读，延到下期吧？

**Comment by ParsifalC** [comment]
> @ParsifalC 这篇我要仔细读，延到下期吧？

好的

**Comment by iblacksun** [comment]
### 🐢 [Swift 5 Exclusivity Enforcement](https://swift.org/blog/swift-5-exclusivity/)

在 2017 年初，Swift 社区发了一篇长文介绍 Swift 4 将在内存安全方面做一些改进，@onevcat 翻译了此文 [所有权宣言 - Swift 官方文章 Ownership Manifesto 译文评注版](https://onevcat.com/2017/02/ownership/) 建议细读。

上文中提到的改变大多已在 Swift 4.x 落地，即将发布的 Swift 5 中，对「独占性访问」进行了增强：`在 Release 模式运行也默认开启。`

Swift 4 中，只有 Debug 模式下，Runtime 会做「独占性访问」的检查(编译时 Debug 与 Release 都会检查，但编译检查可能覆盖不全)，Swift 5 中， Release 模式 Runtime 也默认开启(可手动关闭)。文章仔细介绍了这个改变可能带来什么问题，以及如何应对。
