### ISSUE TITLE
ABI Stability and More

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1143]
# 推荐收录

## 链接

https://swift.org/blog/abi-stability-and-more/

**Comment by iblacksun** [comment]
### 🐕 [ABI Stability and More](https://swift.org/blog/abi-stability-and-more/)

Swift.org 二月初发文介绍了 Swift ABI Stability 当前状态及后续计划。Swift 5 在 macOS, iOS, watchOS, and tvOS 几个平台将实现 ABI Stability，预计很快就能发布，Linux 及 Windows 平台还需评估。文章还介绍了 `Module Stability` 及 `Library Evolution` 的后续计划 。

ABI Stability 能带给我们什么：上述系统以后将自带 `Swift runtime and standard library`，而不需嵌入到 App 中，能大大减小 Swift App 的打包大小。
