### ISSUE TITLE
每个APP都用得上的JXSegmentedView(swift)

### ISSUE THREAD

**Issue by pujiaxin33** [SwiftOldDriver/iOS-Weekly#1155]
# 推荐收录

## 链接

https://github.com/pujiaxin33/JXSegmentedView

## 理由

JXSegmentedView几乎实现了所有主流APP的列表分页切换效果。内置了丰富的指示器、cell样式效果，接入简单可灵活扩展。
- 指示器自定义：使用面对协议编程，只需遵从并实现`JXSegmentedIndicatorProtocol`协议即可自定义；
- cell自定义：通过继承相关类即可自定义；

## 推荐人信息

昵称：暴走的鑫鑫
Github主页：https://github.com/pujiaxin33

**Comment by zvving** [comment]
[效果丰富的分类切换组件：JXSegmentedView (Swift版)](https://github.com/pujiaxin33/JXSegmentedView)

SegmentedControl + PaggingView 组合实现的分类切换视图是资讯、电商类应用常用的基本组件。具体实现起来，动效细节和特殊交互场景要考虑的问题并不少。
[JXSegmentedView](https://github.com/pujiaxin33/JXSegmentedView) 胜在实现了大量主流应用分类切换组件的交互效果，如果你碰到对应需求，相信这会是个不错的参考。

如果你不幸还停留在 Objc，也可以看看同一作者实现的 Objc 版本 [JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)（已有 2k+ stars）。
