### ISSUE TITLE
多层 UIScrollView 嵌套滚动解决方案

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1156]
# 推荐收录

## 链接

https://jiar.me/article/Multi-tier-UIScrollView-nested-scrolling-solution

**Comment by Damonvvong** [comment]
作者文中的解决方案已经有很多类似的方案了, 比如：

https://github.com/ChangbaDevs/KTVPageViewController
https://github.com/yongyuandouneng/YNPageViewController

我觉得可以等作者把文中的 V3 实现了再做推荐

另外，在我电脑上无法执行 pod install...

综上，建议暂时关闭，后续我会跟进这个开源库。
