### ISSUE TITLE
Block hook 正确姿势？

### ISSUE THREAD

**Issue by caixindong** [SwiftOldDriver/iOS-Weekly#1157]
# 推荐收录
Block hook 正确姿势？
## 链接

https://juejin.im/post/5c653921e51d457fa676eafc

## 理由
从Mac逆向出发，解决block hook相关问题，深入block真正的调用原理。

**Comment by ParsifalC** [comment]
- [14期](https://github.com/SwiftOldDriver/iOS-Weekly/blob/59bfdf3859a67d5667319000e4ee70f8f9cd6f76/Reports/%2314-2018.04.09.md#-追踪-objective-c-方法中的-block-参数对象)
- [50期](https://github.com/SwiftOldDriver/iOS-Weekly/blob/bcdaaa19754c4a712c492a470f9587df750fce7f/Reports/2019/%2350-2019.01.02.md#-stinger)
- [9期](https://github.com/SwiftOldDriver/iOS-Weekly/blob/48427eac5663bacdb00beddf2653ff1c32f4d5d1/Reports/%239.md#hook-objective-c-block-with-libffi)

可以综合我们之前周报推荐的类似文章，评估是否收录。
@knightsj

**Comment by knightsj** [comment]
暂不建议收录此文章。原因是关于实现流程介绍得不够完整，且步骤不够清晰。
