### ISSUE TITLE
Deep Diving React Native Debugging

### ISSUE THREAD

**Issue by ShannonChenCHN** [SwiftOldDriver/iOS-Weekly#1168]
# 推荐收录

## 链接

[Deep Diving React Native Debugging](https://medium.com/@shaheenghiassy/deep-diving-react-native-debugging-ea406ed3a691)（需要翻墙）

## 理由

在开发 React Native 应用时，我们可以通过开启 `Debug JS Remotely` 来实现在 Chrome 中调试 JS，包括断点调试、查看堆栈信息、变量状态等，有时候我们可能还会在调试时遇到红屏错误 `Runtime is not ready.Make sure your packager server is running.`，但是不知道这背后都发生了什么。我们往往对这些每天日常开发中接触的东西既熟悉又陌生，不妨跟着这篇文章读读源码并调试一下，一切都将豁然开朗。

## 推荐人信息

@ShannonChenCHN

ps. 上一期的投稿 #1139 被收录了，但是不知道为什么没看到点评后面的推荐人信息？

**Comment by ParsifalC** [comment]
> # 推荐收录
> ## 链接
> [Deep Diving React Native Debugging](https://medium.com/@shaheenghiassy/deep-diving-react-native-debugging-ea406ed3a691)（需要翻墙）
> 
> ## 理由
> 在开发 React Native 应用时，我们可以通过开启 `Debug JS Remotely` 来实现在 Chrome 中调试 JS，包括断点调试、查看堆栈信息、变量状态等，有时候我们可能还会在调试时遇到红屏错误 `Runtime is not ready.Make sure your packager server is running.`，但是不知道这背后都发生了什么。我们往往对这些每天日常开发中接触的东西既熟悉又陌生，不妨跟着这篇文章读读源码并调试一下，一切都将豁然开朗。
> 
> ## 推荐人信息
> @ShannonChenCHN
> 
> ps. 上一期的投稿 #1139 被收录了，但是不知道为什么没看到点评后面的推荐人信息？

不好意思，可能是我们编辑漏了，我补充下。

**Comment by ShannonChenCHN** [comment]
@ParsifalC 好的，谢谢~
