### ISSUE TITLE
让Objective C也可以使用类型推导 let 和 var ，推荐两篇文章 

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#117]
让Objective C也可以使用类型推导 let 和 var ，推荐两篇文章 

https://medium.com/@maicki/type-inference-with-auto-type-55a38ef56372

https://pspdfkit.com/blog/2017/even-swiftier-objective-c/

英文也不怎么好，并且我不太通swift可能get不到点。。求review

**Comment by Awhisper** [comment]
有人说 这2个宏 和 RAC2.5冲突

也有人说 __auto_type 会增加编译速度

让编译器按自动类型处理？是这意思不╮(╯_╰)╭

**Comment by Damonvvong** [comment]
这个很早就有了。不建议放到周报里面

**Comment by Awhisper** [comment]
哟西 ~ 好滴好滴

**Comment by lacklock** [comment]
我也觉得这个技巧不是特别实用。
