### ISSUE TITLE
Localization in Swift like a Pro

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1177]
# 推荐收录

## 链接

[Localization in Swift like a Pro](https://gist.github.com/Dschee/700d28a34ad6d6a3c66885f592d99afd?utm_campaign=Indie%2BiOS%2BFocus%2BWeekly&utm_medium=rss&utm_source=Indie_iOS_Focus_Weekly_209)

## 理由

Are you still localizing the same way you did a couple of years ago? Did you know there are better ways? Localization has always been a pain, but if you read this post you'll find that it doesn't have to be so bad. Keeping localizations in sync is not an Xcode feature, but you can make it work with these tips. BartyCrouch and SwiftGen to the rescue!

**Comment by Damonvvong** [comment]
Swift 内容过多。延迟到下周。
