### ISSUE TITLE
Axios：苹果公司决定更改2018年的 iOS 软件开发计划，推迟了一些功能，以便重点解决性能和质量问题

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#118]
https://www.axios.com/scoop-apple-delays-ios-features-to-focus-on-reliability-performance-1517278421-d7722a3b-402e-4804-8f24-719154bf2a8e.html

我再找找有没有苹果官方出处

**Comment by Awhisper** [comment]
对 中文来自@林泰前 老师微博

**Comment by lacklock** [comment]
这种没有明确信息源的出于严谨我们还是不放了。虽然有消息说在苹果某次内部会议上提到的。
