### ISSUE TITLE
#1 本周话题 | Swift ABI

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1183]
# 关于 Swift ABI 稳定 

迟到三年的 ABI 稳定终于要来了。

苹果发布了 *[ABI Stability and More](https://swift.org/blog/abi-stability-and-more/)* 和 *[Evolving Swift On Apple Platforms After ABI Stability](https://swift.org/blog/abi-stability-and-apple/)* 两篇文章来阐述 Swift 5 发布以后 ABI 相关的内容所带来的改变。看不懂英文的也不要怕，细心的喵神帮我们做了一个很棒的总结: *[Swift ABI 稳定对我们到底意味着什么](https://onevcat.com/2019/02/swift-abi/)*。

Swift ABI 可以说是 Swift 的一个里程碑事件，让跨平台的能力更上了一层，但是 Swift ABI 对于 iOS 开发者使用来说，影响不是很大，有很多开发者误把 API 稳定当成了 Swift ABI 稳定。对于开发者来说，只有 API 稳定了，才是真正意义上的不需要迁移适配了。

如果不知道 Swift ABI 是什么的朋友，可以看看苹果去年发布的 *[Swift ABI Stability Manifesto](https://github.com/apple/swift/blob/master/docs/ABIStabilityManifesto.md)*。同时 **[泊学](https://boxueio.com)** 也做了一个很棒的翻译版: *[译：Swift ABI (一)](https://boxueio.com/blackboard/1)* 和 *[译：Swift ABI (二)](https://boxueio.com/blackboard/2)*。

**最后，关于 Swift ABI，你有什么看法，可以在这个 issue 上，发表你的看法，与周报编辑一起讨论。**

**Comment by Damonvvong** [comment]
### Swift ABI 稳定是否会影响你们的技术选型？

**Comment by alexlee002** [comment]
@Damonvvong 
关于问题1 的看法：
* 新项目可能会优先选择 swift, 但得看对公司原有技术栈的依赖程度。
* ABI 稳定是一个里程碑，如果 OC 和 swift 相互调用能做到 Java 和 Kotlin那样就更好。

**Comment by pc9527** [comment]
1. 终于稳定了！但根据swift社区的老传统，估计还得下一个版本才能放心
当年（2.1）静态编译了一个第三方http server模块进来，某次手抖一点升级（2.2）全崩了，把自己的语法修完之后发现还得去改第三方的，提issue仨礼拜没动静之后都想自己帮人家改后pr了....

**Comment by kemchenj** [comment]
## 1. Swift ABI 稳定是否会影响你们的技术选型？

小公司，不影响。

## 2. 你对 Swift ABI 有什么不一样的研究？

ABI 里其实可以看到很多功能都埋下了伏笔。例如 coroutine，其实已经实现了[底层的部分](https://github.com/apple/swift/blob/8fecc79940ef2f6c846efe4a39fc0be91e0a4f63/include/swift/AST/Types.h#L3601)，只是还没有暴露给上层去使用：

```cpp
/// SILCoroutineKind - What kind of coroutine is this SILFunction?
enum class SILCoroutineKind : uint8_t {
  /// This function is not a coroutine.  It may have arbitrary normal
  /// results and may not have yield results.
  None,

  /// This function is a yield-once coroutine (used by e.g. accessors).
  /// It must not have normal results and may have arbitrary yield results.
  YieldOnce,

  /// This function is a yield-many coroutine (used by e.g. generators).
  /// It must not have normal results and may have arbitrary yield results.
  YieldMany,
};
```

又例如 property 的 accessor 以后会新增的 `read` 和 `modify`，现在我们使用 `setter` 设置时其实会先将原有的值先复制一份拷贝，改变完之后再重新赋值回去，使用了新的 `modify` 的话就可以直接在原有的内存上直接进行操作，而不会产生一次复制行为，`read` 也是类似的。

并且 `read` 和 `modify` 都已经留了 [coroutine 的口子](https://github.com/apple/swift/blob/0181ea586d791b6bdf2b57c983f39f2aceb85ba2/include/swift/ABI/MetadataValues.h#L289)让我们以后可以使用 `async read` 和 `async modify`：

```cpp
enum class Kind {
  ...
  Getter,
  Setter,
  ReadCoroutine,
  ModifyCoroutine,
  ...
};
```

比起 ABI 稳定这件事情本身，我更期待接下来一两个大版本的更新，经历了前面三个大版本的铺垫，Swift 里已经做好了很多功能的基础建设，我个人猜测接下来一两个大版本会迎来一大波新功能😏。

## 3. Swift 跨平台开发的体验怎么样？

其实目前 Swift on Linux 还是有很多可以吐槽的地方的，例如虽然 Swift 5 打出的旗号是 ABI 稳定，但实际上是只在 Apple 的几个操作系统上稳定而已，Linux 上还没有稳定下来，亦或者是 Foundation 里的很多类型和方法都会抛出 `NSNotImplement` 的 exception。

但 Swift 也在加快 Linux 端开发的脚步，例如说现在在 Linux 上有 [monthly release](https://forums.swift.org/t/announcing-swift-4-2-2-and-monthly-swift-4-2-x-dot-releases-for-linux/20148)，每个月一个版本去修复 bug，加快迭代速度。
