### ISSUE TITLE
[代码] coobjc

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#1189]
# 推荐收录

## 链接

https://github.com/alibaba/coobjc

## 理由

alibaba团队出品，这个库为 Objective-C 和 Swift 提供了协程功能。coobjc 支持 await、generator 和 actor model，接口参考了 C# 、Javascript 和 Kotlin 中的很多设计。

**Comment by Damonvvong** [comment]
https://mp.weixin.qq.com/s/Vy_fsn95dgag4KumpQPlTw

这里有一篇源码解析。@Awhisper 顺带一起看一下吧。
