### ISSUE TITLE
仿点好玩的应用~仿@KITTEN-YANG 的Cosmos 

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#119]
https://github.com/zhnnnnn/ZHNCosmos

Cosmos的酷炫的动画，这有一份仿写的源码，可以深入学习阅读各种细腻动画效果的实战代码

**Comment by Damonvvong** [comment]
我看了一下，东西倒是挺多的。但是实际运行可以看的东西很少。
很多功能和截图是不符的。

**Comment by Damonvvong** [comment]
所以我不放到周报上了
