### ISSUE TITLE
UIView styling with functions

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1191]
# 推荐收录

## 链接

[UIView styling with functions](https://felginep.github.io/2019-02-19/uiview-styling-with-functions)

**Comment by iblacksun** [comment]
### [UIView styling with functions](https://felginep.github.io/2019-02-19/uiview-styling-with-functions)

在实际 App 中，视图通常只有几种样式，你可能会想各种办法做成视图组件。本文介绍了一种视图样式封装的方法，利用 Swift protocol extension 等特性组织代码，使得代码逻辑清晰易懂。
