### ISSUE TITLE
API Pollution in Swift Modules

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1192]
# 推荐收录

## 链接

[API Pollution in Swift Modules](https://nshipster.com/swift-api-pollution/)

## 理由

[此处填写您的推荐理由]

**Comment by kemchenj** [comment]
### [API Pollution in Swift Modules](https://nshipster.com/swift-api-pollution/)

本周 NSHisper 讨论的是 Swift 导入 Module 时可能发生的 API 污染，Swift 的静态方法查找是发生在编译时的，有时候可能会因为函数的声明不当，而导致意外情况的发生，例如我们本来想调用的是 a 函数，结果却调用了 b。

Matt 在文章里列举了几种 API 被污染的情况，最后还从调用方和声明方两个角度去探讨如何避免类似情况发生，值得一看。
