### ISSUE TITLE
CocoaPods 发布 1.6.0

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1195]
# 推荐收录

## 链接

http://blog.cocoapods.org/CocoaPods-1.6.0-beta/

## 理由

整理一下 CocoaPods 1.6.0 的更新

**Comment by nianran** [comment]
1.6.1 也发了，只不过修复了紧急 Bug，可以顺便提及一下

**Comment by knightsj** [comment]
@nianran 好的
