### ISSUE TITLE
The perfect guide to AppStore search optimization (ASO)

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1196]
# 推荐收录

## 链接

http://blog.rootshell.ir/2019/02/the-perfect-guide-to-appstore-search-optimization-aso/

**Comment by zvving** [comment]
🐎The perfect guide to AppStore search optimization (ASO)
本指南介绍了 App Store 产品页面每个基本信息的最佳实践，内容简明扼要，很有参考价值。
相关阅读：[App Store Product Page](https://developer.apple.com/videos/play/insights/app-store-product-page/)
