### ISSUE TITLE
John Sundell 的 Swift Tips 更新了 #53 —— 使用字符串枚举时的字符串交互小技巧

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#12]
https://github.com/johnsundell/swifttips#53-string-based-enums-in-string-interpolation

**Comment by lacklock** [comment]
没看懂这个的使用场景 @kemchenj

**Comment by kemchenj** [comment]
这一个我仔细想想，可能作用也不是很大，只能说是后端用 CN，US 之类的简写时，可以少写一个 `fullName` 属性，直接写为枚举值的名字而已

```swift
enum Country: String {
    case china = "CN"
    case canada = "CA"
}

print("\(Country.china)") // "china"
```

这一个技巧算是可有可无，但国内好像没有类似于 Swift Tips 这个项目，而且这个项目里一些技巧还是挺不错的，我觉得可以改成介绍这个项目

**Comment by kemchenj** [comment]
跟前面 iOS Tips 小集类似的项目，不同的是这个项目里讲的是一些 Swift 的小 Tips，里面 #7，#22 等技巧我都有实际用于项目中，非常推荐大家看一下
