### ISSUE TITLE
material-kit

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1201]
# 推荐收录

## 链接

https://github.com/creativetimofficial/material-kit

**Comment by nianran** [comment]
个人认为这篇文章暂时不适合推荐我们的群体。

- iOS 相关知识偏少
- 此库仅为一个标准的 UI 仓库，且交集仅在于 RN

**Comment by nianran** [comment]
@Damonvvong
