### ISSUE TITLE
Frontend Workshop from HTML/CSS/JS to TypeScript/React/Redux

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1202]
# 推荐收录

## 链接

https://github.com/Microsoft/frontend-bootcamp

**Comment by raozhizhen** [comment]
微软出版的从 HTML / CSS / JS 到 TypeScript / React / Redux 的前端训练营，为期两天，第一天搭建环境、介绍 web 的基础知识：HTML，CSS 和 JavaScript，通过演示代码了解一些核心概念。第二天演示和练习结合在一起，深入更高级的主题，如 TypeScript、测试和状态管理。（TypeScript 是由微软开源的编程语言。它是 JavaScript 的一个严格超集，并添加了可选的静态类型和基于类的面向对象编程，设计目标是开发大型应用，然后转译成 JavaScript）
