### ISSUE TITLE
#2 本周话题 | 协程

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1205]
说起协程，很多人可能还比较陌生，它是一个 60 年代就已经提出概念，是一种在非抢占式多任务场景下生成可以在特定位置挂起和恢复执行入口的程序组件。

目前在服务端中应用比较广泛，在高并发场景下使用极其合适，可以极大降低单机的线程数，提升单机的连接和处理能力，而在移动研发中，前端的 JavaScript，安卓的 kotlin 也都已经支持了协程，唯独对于 iOS 来说，Swift 的语言级协程支持还在路上，苹果官方也没有意愿给 objective-c 添加协程能力的意愿。

好在，上周阿里巴巴也开源的 [coobjc](https://github.com/alibaba/coobjc) 为我们 iOS 开发者解决了这个困惑， [coobjc](https://github.com/alibaba/coobjc) 同时给 objective-C 和 swift 都提供了协程功能。

**所以这周想和大家一起探讨一下协程相关的问题。**

### 1. 说一说你对协程的理解？

> 比如在移动开发中，适用于什么样的场景，解决什么样的问题？

### 2. 你们是否有过被异步编程的恐惧所支配的经历？

> 对于一个极其复杂的业务，写了多少层回调？或者在重构别人的代码时，看过多复杂的代码？

### 3.协程真的是性能神器吗？

> 有人说协程因为减少了线程切换所以可以提高代码运行效率，也有人说协程是一把双刃剑，玩不好写出来的代码会直接卡死，而对于这个问题来说，你怎么看呢？

### 4. 使用协程中需要注意什么？

> 相信有不少开发者接触过其他语言的协程，你是否有过什么踩坑的经历，和我们分享一下呢？

**Comment by a1049145827** [comment]
我曾经在别人博客上看到有关协程的描述：协程无法利用多核 CPU，nginx 的解决方式是多进程 + 协程。那么在不支持多进程的 iOS 上面应该用什么方案？

**Comment by alexlee002** [comment]
在移动端开发上， 没有觉得协程有多大的优势， 从 coobjc 官方测试数据上看， 也只是大于1000以上的并发才会有一些性能差异， 问题是， 客户端上有那么多1000以上的并发场景么？

我觉得 coobjc 最大的优势是， 提供了 async/await 语义支持(当然之前也已经有了其他库实现了类似语义， 比如 RJRouter,  SPAsync， 但 coobjc 是提供了比较完整的一套分发和管理机制。)， 可以很容易的用同步的方式写出异步逻辑调用， 这个比 promise / Rx 之类的解决方案要好的多， 让客户端的原先杂乱的异步逻辑变得有条理。

**Comment by Awhisper** [comment]
在淘宝内部的应用与探索上，和淘宝的同学聊过，他们给了一个实际的落地场景，在淘宝的业务中存在着大量老旧业务逻辑代码，

这些代码有以下几个缺点：
1  因为长年累月的开发，很多UI相关的计算代码与逻辑代码都是习惯上在主线程写逻辑，越写越大，越写越多，逐渐开始有耗时
2  这些“祖传代码”一直没时间进行重构梳理，一方面牵扯范围太大，另一方面核心主要大流量业务，改动太大测试压力也非常之重

常规解决方案：
1 本身应该合理开发方式是，进行合理的重构，把UI相关的复杂逻辑运算，与实际UI处理分开，以异步+回调的形式把耗时计算放入子线程处理，耗时结束异步回掉刷新UI

常规方案的问题：
1 原本大量用同步编写的逻辑，改为异步后，势必造成大规模的代码结构变更，从而加入异步+回掉的模式，即便有promise的解决方案，也无法根本解决异步+回掉模式与同步代码的代码结构差异，在淘宝核心主路径页面上进行这么大的改造，成本与风险控制是重中之中
2 即便愿意投入大量成本去做这样的逻辑变更，但因为如此大规模的代码结构变更，更加不易设计线上开关，代码回滚等功能（是不易，但不是说不能，成本问题）在重量级App中，保证native功能开关可回退回滚是很重要的一环

coobjc 的优势：
1 可以在原本就是同步书写的代码逻辑里进行直接改造，不必造成很大的代码结构变更
2 可以结合一些 runtime 通用生命周期 hook ，统一处理一些通用函数直接把原本主线程的函数，无感无侵入式放入协程的处理中
3 可以很方便的进行开关控制，远程控制协程部分的 打开/关闭，而不必大规模改造原代码结构变更

**Comment by alexlee002** [comment]
@Awhisper 那这个也不是协程的引用场景啊， 还是 async/await 。

另外， 关于祖传代码，如果实在难以清理， 那么用一个套子把那坨屎封起来限制异味，也是一种方案。
但是我觉得， RD 和 PM 的区别就是， RD 不能像 PM 那还样只顾着往上堆砌，一边开发一边重构还是必须得。不然祖传代码这坨屎会越来越大。

总结一下， 我觉得 coobjc 把解决祖传代码问题当做主要场景。
