### ISSUE TITLE
Swift Code Formatters

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1209]
# 推荐收录

## 链接

https://nshipster.com/swift-format/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Swift Code Formatters](https://nshipster.com/swift-format/)

最近几天，Swift 社区一直在讨论 [Tony Allevato](https://github.com/allevato) 和 [Dave Abrahams](https://github.com/dabrahams) 关于 [Swift 编码风格指南和格式化工具](https://forums.swift.org/t/pitch-an-official-style-guide-and-formatter-for-swift/21025) 的提案。

[Mattt](https://nshipster.com/authors/mattt/) 专门在 [NSHipster](https://nshipster.com) 撰文对社区现有代码格式化工具进行比较，包含 [SwiftFormat](https://github.com/nicklockwood/SwiftFormat)、[SwiftLint](https://github.com/realm/SwiftLint)、[Prettier with Swift Plugin](https://github.com/prettier/prettier) 及 [swift-format (proposed)](https://github.com/google/swift/tree/format)，分别从格式化结果及效率两个角度进行对比。
