### ISSUE TITLE
How to build a simple tracker blocker for iOS

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1219]
# 推荐收录

## 链接

https://medium.com/@nderkach/how-to-build-a-simple-tracker-blocker-for-ios-cc6c52a2d2d1

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [How to build a simple tracker blocker for iOS](https://medium.com/@nderkach/how-to-build-a-simple-tracker-blocker-for-ios-cc6c52a2d2d1)

跨网站追踪是一种广告商用于搜集用户信息的方式，Apple 作为一家注重用户隐私的公司，在 iOS 里内置了 Content Blocker 等功能帮助我们不被追踪。

这篇文章就教我们如何使用 Content Blocker 和第三方黑名单来搭建一个反追踪的插件，并且还提供了相关的网站以便我们进行测试。
