### ISSUE TITLE
Why we stopped using fastlane

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1230]
# 推荐收录

## 链接

[Life in the slow lane](https://silverhammermba.github.io/blog/2019/03/12/slowlane)

## 理由

分手的理由

**Comment by iblacksun** [comment]
### [Why we stopped using fastlane - Life in the slow lane](https://silverhammermba.github.io/blog/2019/03/12/slowlane)

> 相信现在很多团队都在用 Fastlane，推荐本文是期望大家听到更多的声音。

本文作者在 2018 年写了一篇 Fastlane 的使用文章，现在，他来回顾一些 Fastlane 不好的地方：
- 没有解决 Xcode 本身的问题
- Fastlane 本身很庞大，有太多的依赖项
- Fastlane 自身有许多 Bug
- 太多人在用以至于 issue 太多，核心问题得不到解决
