### ISSUE TITLE
Help! My app freezes but no error appears

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1231]
# 推荐收录

## 链接

[Help! My app freezes but no error appears](https://fluffy.es/help-my-app-freezes/)

**Comment by cupnoodle** [comment]
谢谢推荐! 我是这篇文章的作者, 在这篇文章我简单介绍了 Multithreading 的概念以及说明为什么在 UI thread 执行长时间的 code 会导致 UI 不能反应使用者的触摸输入.

**Comment by ParsifalC** [comment]
> 谢谢推荐! 我是这篇文章的作者, 在这篇文章我简单介绍了 Multithreading 的概念以及说明为什么在 UI thread 执行长时间的 code 会导致 UI 不能反应使用者的触摸输入.

真棒！你是国人在马来西亚工作？

**Comment by cupnoodle** [comment]
谢谢! 我是马来西亚籍华人 👋

**Comment by waz0820** [comment]
> 谢谢! 我是马来西亚籍华人 👋

已经是两本书的作者了啊，口碑不错，厉害厉害👏👍

**Comment by ztlyyznf001** [comment]
> 谢谢! 我是马来西亚籍华人 👋

你好，希望能写一篇中文版本或者可以帮忙翻译一篇中文版本，谢谢
