### ISSUE TITLE
最近很火的 Safe Area 到底是什么

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#124]
https://juejin.im/post/5a7178116fb9a01c9d322d91?utm_source=gold_browser_extension

**Comment by lacklock** [comment]
其实这safe area的文章已经很多了。不过这个作者写的还是很认真的，也可以提一下。

**Comment by kemchenj** [comment]
### [最近很火的 Safe Area 到底是什么](https://juejin.im/post/5a7178116fb9a01c9d322d91?utm_source=gold_browser_extension)

iOS 11 出来很久了，适配的文章也很多，第一眼看到的时候我会觉得这个时候来写已经挺晚了，但看完之后觉得总结得是最好的，配图跟代码示例都有，重点的地方有加粗展示出来，这篇绝对值得 Mark 下来。
