### ISSUE TITLE
使用 Flutter 开发的仿 Gmail App

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1241]
# 推荐收录

## 链接

https://github.com/AppleEducate/gmail_clone

**Comment by Damonvvong** [comment]
@ParsifalC 这周 @crazycodershi  因为时间问题，没能处理。下周会把这个处理掉。后面就会正常了。

**Comment by CrazyCoderShi** [comment]
@ParsifalC @Damonvvong 
个人觉得，这个repo的可推荐度一般，而且代码风格和质量没有想象的那么好，不建议推荐给新手，唯一的亮点可能就是[responsive_scaffold](https://pub.dartlang.org/packages/responsive_scaffold)

**Comment by ParsifalC** [comment]
> @ParsifalC @Damonvvong
> 个人觉得，这个repo的可推荐度一般，而且代码风格和质量没有想象的那么好，不建议推荐给新手，唯一的亮点可能就是[responsive_scaffold](https://pub.dartlang.org/packages/responsive_scaffold)

嗯，可以的，说明下就可以直接关掉~
