### ISSUE TITLE
Swift-Evolution: an Official Style Guide and Formatter for Swift

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1245]
# 推荐收录

## 链接

[Swift-Evolution: an Official Style Guide and Formatter for Swift](https://forums.swift.org/t/pitch-an-official-style-guide-and-formatter-for-swift/21025)

## 理由

一个拥趸者众的新提案：Swift 小组应该给出一套官方的代码风格指南，且提供对应的格式化工具，用于诊断和纠正代码风格。可以作为一个话题讨论，Swift 是否应该有一套官方的代码风格指南，提案下面已经很热闹了。

**Comment by ParsifalC** [comment]
可以考虑放到接下来的话题中
