### ISSUE TITLE
How to implement service oriented architecture using swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1249]
# 推荐收录

## 链接

https://itnext.io/service-oriented-architecture-in-swift-362dc454fc09

**Comment by kemchenj** [comment]
### [How to implement service oriented architecture using swift](https://itnext.io/service-oriented-architecture-in-swift-362dc454fc09)

基于服务的架构是一种组件模型，它将应用拆分成多个功能单元（服务）暴露给上层进行调用，并通过这些服务之间定义良好的接口和契约联系起来。

这篇文章讲的就是这种架构在 iOS 里的使用，作者讲述了他对于服务的定义，接口的构建，架构具体的分层，依赖注入的实现，并且基于这一套理论实现了一个用户信息管理功能。
