### ISSUE TITLE
Upload App Previews with Transporter

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#125]
https://developer.apple.com/news/?id=01312018

**Comment by mmoaay** [comment]
现在我们可以用 Apple 官方提供的分发工具 Transporter 来上传 App 预览信息了，具体细节请参考 [Transporter 用户指南](https://help.apple.com/itc/transporteruserguide/) 和 [App 元数据规范](http://help.apple.com/itc/appsspec/)，注意这两个文档都有中文版。
