### ISSUE TITLE
Upcoming App Store Submission Requirements

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1251]
# 推荐收录

## 链接

https://developer.apple.com/news/?id=03202019a

**Comment by iblacksun** [comment]
### [3 月 27 日起上传 App Store 最低需须使用 iOS 12.1 SDK 编译](https://developer.apple.com/news/?id=03202019a)

Apple 发布公告：3  月 27 日 起，提交到 App Store 的应用，最低需适配 iOS 12.1，且要支持  iPhone  XS Max 及 12.9 寸的 iPad pro，iTC 上对应的截图也是必须的；watchOS 则最低需要适配 watchOS 5.1。
