### ISSUE TITLE
即时翻译：Swift 5 Release Notes for Xcode 10.2

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#1261]
## 链接
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2

## 理由

ABI稳定的Swift大版本

**Comment by olddonkey** [comment]
这个任务应该算是完成了吧？是否可以关掉 @tom510230

**Comment by Damonvvong** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/blob/ee0e7f895dc2626397803eac112b5c8c13ef2e49/Posts/Swift5%20更新笔记.md
