### ISSUE TITLE
申请将996.icu加到文档集锦内

### ISSUE THREAD

**Issue by pengshengsongcode** [SwiftOldDriver/iOS-Weekly#1267]
https://github.com/996icu/996.ICU.git

**Comment by pengshengsongcode** [comment]
申请加到新闻模块

**Comment by ParsifalC** [comment]
> 申请加到新闻模块

我们商量了一下，觉得还是不太适合放到我们周报中。周报是以技术内容为导向的，这类内容对于我们的读者价值不大。当然，这种行为我们是支持的。

**Comment by ParsifalC** [comment]
> 申请加到新闻模块

https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/2019/%2362-2019.04.08.md#can-we-do-something-for-996-programmers-in-china

我们在最新一期周报，跟进了下这个事情。
