### ISSUE TITLE
代码自解释不是不写注释的理由

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1268]
# 推荐收录

## 链接

[代码自解释不是不写注释的理由](https://www.infoq.cn/article/eQlxAX013D9h5b-B356Q)

**Comment by iblacksun** [comment]
### [代码自解释不是不写注释的理由](https://www.infoq.cn/article/eQlxAX013D9h5b-B356Q)

代码注释通常有两种形式：要么没有和要么毫无用处 。作者认为`自解释的代码是不存在的` ，应该让注释成为代码的一部分。如果你对代码注释有任何疑问，推荐阅读此文。
