### ISSUE TITLE
谷歌的promise框架，不知道怎么样

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#127]
https://github.com/google/promises

**Comment by kemchenj** [comment]
### [谷歌开源了一个 Promise 框架](https://github.com/google/promises)

标准的 Promise 库，谷歌出品，质量肯定是有保证的，具有轻量，高性能，安全，测试完备的优点。核心使用了 Objective-C，Swift 的版本是在 Objective-C 的基础上封装了一层。（需要注意的是 Swift 版本暂时还[无法用 Cocoapods 集成](https://github.com/google/promises/issues/11)）
