### ISSUE TITLE
iOS app秒开H5优化总结

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#1275]
# 推荐收录

## 链接

https://juejin.im/post/5c9c664ff265da611624764d

**Comment by Awhisper** [comment]
这篇文章有点尴尬，指给我吧，现在大公司的离线包方式都不是他说的这几种，都是本地起webserver。。。最大限度的减少前端感知，完全模拟前端服务。。。。只不过成本比较大，而他介绍的几种方式都只是移动端最好实现，但会大幅度制约前端，大幅度侵入前端的方式。。。
