### ISSUE TITLE
flutter_go/flutter_ui

### ISSUE THREAD

**Issue by CrazyCoderShi** [SwiftOldDriver/iOS-Weekly#1282]
# 推荐收录

## 链接

[flutter_go](https://github.com/alibaba/flutter-go)
[flutter_ui](https://github.com/efoxTeam/flutter-ui)

## 理由

功能完善，代码规范，组件覆盖率高，新手友好

**Comment by Damonvvong** [comment]
@CrazyCoderShi  这个的推荐语你这周写好了提 PR 给我哈

**Comment by Damonvvong** [comment]
#1292
