### ISSUE TITLE
Swift Tip: Collection Protocols

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1289]
# 推荐收录

## 链接

https://www.objc.io/blog/2019/03/26/collection-protocols/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
###  [Swift Tip: Collection Protocols](https://www.objc.io/blog/2019/03/26/collection-protocols/)

在 Swift 中，有许多 `Collection` 相关的协议，每个都有自己的作用，了解这些协议各自的作用，在写算法时将非常有帮助。本文摘录自  [`Advanced Swift`](https://www.objc.io/books/advanced-swift/) 这本书，作者们正在更新 Swift 5 相关内容，如果你之前买过电子版的话，将能免费更新。
