### ISSUE TITLE
The Pragmatic Guide to Scalable Swift Architecture for 2019

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1295]
# 推荐收录

## 链接

https://blog.usejournal.com/the-pragmatic-guide-to-scalable-swift-architecture-in-2019-dbe662f7f516

**Comment by kemchenj** [comment]
### [The Pragmatic Guide to Scalable Swift Architecture for 2019](https://blog.usejournal.com/the-pragmatic-guide-to-scalable-swift-architecture-in-2019-dbe662f7f516)

这算是一篇架构散文，作者在文章里通过一问一答的形式去阐述自己对于架构的理解：

1. 高薪程序员是如何在团队里逐步推进架构改造的？
3. 如何解决异步代码逻辑分散的问题的？
3. 如何在依赖注入时保障安全性和可复用性？
4. 如何通过状态和事件的解耦让 ViewController 的代码质量变得更高？
5. 如何解耦 ViewController 里的跳转逻辑？
