### ISSUE TITLE
Smoke Framework 1.0 released

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1299]
# 推荐收录

## 链接

https://forums.swift.org/t/smoke-framework-1/22710

## 理由

Amazon 之前开源的 Web 应用框架 Smoke 发布 1.0 了，围绕着 AWS 的服务做了很多深度集成。

**Comment by iblacksun** [comment]
### [Smoke Framework 1.0 released](https://forums.swift.org/t/smoke-framework-1/22710)

[@享耳先森](https://github.com/iblacksun)：Amazon 之前开源的 Swift Web Framework 发布 1.0 了，围绕着 AWS 的服务做了很多深度集成。1.0 使用 Swift 4.2, SwiftNIO 1.x 开发，即将发布 Swift 5 及 SwiftNIO 2 的版本，包含 `SmokeHTTP`,`SmokeAWS`, `SmokeDynamoDB`, `SmokeAWSCredentials` 几个子模块。
