### ISSUE TITLE
再一次谈到mvc弊端的文章

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#130]
https://www.netguru.co/codestories/pragmatic-ios-development-in-defence-of-mvc

**Comment by raozhizhen** [comment]
社区里广为流传着“MVC 意味着非常臃肿的视图控制器”，但其实这起源于 5 年前 Twitter 上的一个玩笑。只要你使用得当， MVC 会是一个非常不错的架构设计模式。

**Comment by lacklock** [comment]
需要更详细的摘要。

**Comment by raozhizhen** [comment]
在开发中，大量的元素都需要一个外部委托，如果它们都委托给视图控制器，控制器将迅速的膨胀起来。

**Comment by raozhizhen** [comment]
社区里广为流传着“MVC 意味着非常臃肿的视图控制器”，但其实这只是 5 年前 Twitter 上的一个玩笑。
在开发中，大量的元素都需要一个外部委托，如果它们都委托给视图控制器，控制器将迅速的膨胀起来。
但我们可以尝试另一种做法，控制器将任务委托给单独的第三方对象，自身不包含任何业务逻辑，
只负责根据数据提供 UI 逻辑交互。如此便能使控制器保持小巧灵活。
