### ISSUE TITLE
Brooklyn

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1311]
# 推荐收录

## 链接

https://github.com/pedrommcarrasco/Brooklyn

**Comment by iblacksun** [comment]
[@享耳先森](https://github.com/iblacksun)：受苹果 2018.10.30 发布会启发，设计并开源的一个屏保程序，非常漂亮，可在终端执行 `brew cask install brooklyn` 安装。
