### ISSUE TITLE
Conditional Compilation

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#1322]
# 推荐收录

## 链接

https://davedelong.com/blog/2018/07/25/conditional-compilation-in-swift-part-1/
https://davedelong.com/blog/2018/07/25/conditional-compilation-in-swift-part-2/
https://davedelong.com/blog/2019/04/09/conditional-compilation-part-3/

之前应该收录过第一篇，这次加了两篇新的，可以看看

**Comment by kemchenj** [comment]
### Conditional Compilation [Part 1](https://davedelong.com/blog/2018/07/25/conditional-compilation-in-swift-part-1/) [Part 2](https://davedelong.com/blog/2018/07/25/conditional-compilation-in-swift-part-2/) [Part 3](https://davedelong.com/blog/2019/04/09/conditional-compilation-part-3/)

[@四娘](kemchenj.github.io)：之前我们在 [29 期周报](https://github.com/SwiftOldDriver/iOS-Weekly/blob/59bfdf3859a67d5667319000e4ee70f8f9cd6f76/Reports/%2329-2018.07.30.md#-conditional-compilation-in-swift-part-1)里介绍过这篇文章的第一篇：

> 本文讲述了 Swift 中方的条件编译。当然首先是传统的方法 arch()，作者对各个参数都做了详细的介绍。不过随着 Swift 4.1 的到来，你更应该了解一下方便好用的 targetEnvironment()(SE-0190)。其次是使用配置文件（.xcconfig），这个方式其实被 CocoaPods 大量使用。作者也用示例做出了详细的介绍，同学们不妨也在自己的工程中试一试。

后面陆续写了 Part 2 和 Part 3，主要是介绍了跨平台代码库编译选项的一些控制方式，对这方面有疑虑的同学可以看一看
