### ISSUE TITLE
Swift + RxSwift MVVM 模块化项目实践

### ISSUE THREAD

**Issue by CrazyCoderShi** [SwiftOldDriver/iOS-Weekly#1328]
# 推荐收录

## 链接

https://juejin.im/post/5c95edeaf265da60c576ecb1?utm_source=gold_browser_extension

## 理由

新手友好😄

**Comment by iblacksun** [comment]
@ParsifalC 这篇文章有点文不对题，对 `RxSwift` `MVVM` 是泛泛带过，`模块化`也没讲清楚，新手看了反而更蒙，不建议推荐。

**Comment by ParsifalC** [comment]
ok
