### ISSUE TITLE
How to generate Swift model class from JSON automatically? 

### ISSUE THREAD

**Issue by hhfa008** [SwiftOldDriver/iOS-Weekly#133]
How to generate Swift model class from JSON automatically? Such as: https://github.com/hhfa008/SwiftAI

**Comment by iblacksun** [comment]
[SwiftAI - Generate Model class from JSON](https://github.com/hhfa008/SwiftAI)

一个 Xcode 插件(也有独立 App)，可将 JSON 转换成 Model，支持 `Codable` 和 `HandyJSON`。
