### ISSUE TITLE
Assets Catalogs 与 I/O 优化

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#1330]
# 推荐收录

## 链接

https://juejin.im/post/5cb74d786fb9a068773948fc

**Comment by Dywane** [comment]
刚刚想自荐文章，看到已经有同学帮忙推荐了，感谢。

另外谈一下与[这篇](https://github.com/SwiftOldDriver/iOS-Weekly/issues/1329)文章相似的问题，的确是很碰巧大家共同关注到这个问题，我这篇文章起因也是项目中采用了在 Folder 中存放图片导致加载缓慢的问题，在那篇文章里是QQ阅读，这我这里是WiFi管家和手机管家，那么这个问题应该是鹅厂一些旧项目不愿尝试新功能的通病了。说回文章，那篇文章和我一样同样有参考[Reverse engineering the .car file format (compiled Asset Catalogs)](https://blog.timac.org/2018/1018-reverse-engineering-the-car-file-format/)这篇文章，但是它的涉及广度比我的大，还从BOM文件与内存映射方面去分析，而我的文章则是更多从 CoreUI 框架的源码实现上去分析，理解整个加载流程的区别，所以如果真的想深入了解 Assets Catalogs 与 I/O 优化的东西，应该两篇文章结合着去看，产生自己的思考会比较好
