### ISSUE TITLE
iOS中的Promise

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#1349]
# 推荐收录

## 链接

https://juejin.im/post/5cb6d1215188253fdd641c15

**Comment by kemchenj** [comment]
### [iOS 中的 Promise](https://juejin.im/post/5cb6d1215188253fdd641c15)

当你需要连续地执行多个异步过程时，总会无可避免的出现地狱回调，Promise 是一个不错的解决方案，这篇文章前半部分主要讲了 Promise 具体的实现，后面介绍了一些实用的 API，感兴趣的朋友可以看一下。
