### ISSUE TITLE
Xcode10 New Build System And CocoaPods

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1360]
# 推荐收录

## 链接

http://yuqiangcoder.com/2018/11/13/Xcode10-new-build-system-and-CocoaPods.html

## 理由

New Build System 目前跟 Cocoapods 一起使用时会出现一个问题，修改 Pod 引入的库的代码后不会生效，需要 clean 一次才可以。

这篇文章里介绍了 Cocoapods 引入的一个新选项，可以暂时解决这个问题，缺点是每次编译都需要 copy 一次 framework。

PS：开了这个选项之后，搭配 New Build System 我就再也没有 clean 过了。

**Comment by iblacksun** [comment]
### [Xcode10 New Build System And CocoaPods](http://yuqiangcoder.com/2018/11/13/Xcode10-new-build-system-and-CocoaPods.html)

[@享耳先森](https://github.com/iblacksun)：Xcode 10 发布之后，你可能发现修改了 CocoaPods 依赖库的源码之后立即编译并不生效，必须 clean 整个项目重新编译，这其实是 Xcode 10 默认采用 `New Build System` 导致的，本文介绍了两种解决方案。
