### ISSUE TITLE
Parallel programming with Swift: Operations

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#137]
https://medium.com/flawless-app-stories/parallel-programming-with-swift-operations-54cbefaf3cb0

**Comment by kemchenj** [comment]
### Parallel programming with Swift [1. Basics](https://medium.com/flawless-app-stories/basics-of-parallel-programming-with-swift-93fee8425287) [2. Operation](https://medium.com/flawless-app-stories/parallel-programming-with-swift-operations-54cbefaf3cb0)

第一篇介绍了使用 Swift 进行并行编程时的多种方式，从 Process 到更高级的抽象 Operation，如何控制并发的顺序，锁和信号的使用。第二篇主要是讲 Operation，包括 API，生命周期，依赖以及封装的介绍。这一系列由浅入深，配图清晰，顺便推荐一下他们团队 [Flawless 的博客](https://medium.com/flawless-app-stories/tagged/ios)，里面有很多技术分享，质量都很高。
