### ISSUE TITLE
How to use opaque return types in Swift 5.1

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1385]
# 推荐收录

## 链接

https://www.hackingwithswift.com/articles/187/how-to-use-opaque-return-types-in-swift-5-1

**Comment by iblacksun** [comment]
准备用 [泛型语法改进第一弹 —— Opaque Result Types](https://kemchenj.github.io/2019-05-05/) 替换，内容一致，但是中文，而且是我们编辑写的。

**Comment by iblacksun** [comment]
### 🐕 [泛型语法改进第一弹 —— Opaque Result Types](https://kemchenj.github.io/2019-05-05/)

[@享耳先森](https://github.com/iblacksun)：Swift 5.1 将包含针对范型的一个重要改进 —— `Opaque Result Types`：简单来讲，用 `some` 修饰的方法返回值或属性，其具体类型在编译时就能确定，并且是由被调用方去决定。
