### ISSUE TITLE
Library Evolution for Stable ABIs

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1396]
# 推荐收录

## 链接

https://github.com/apple/swift-evolution/blob/master/proposals/0260-library-evolution.md

**Comment by linwenbang** [comment]
emmm 好像搞错了，=。=

**Comment by kemchenj** [comment]
### [SE-0260 Library Evolution for Stable ABIs](https://github.com/apple/swift-evolution/blob/master/proposals/0260-library-evolution.md)

[四娘](kemchenj.github.io)：ABI 稳定的进程还没有剩下一些，Swift 5 里达成的是标准库的 ABI 稳定，但这种 Module ABI 稳定的机制还没有暴露给用户使用，所以这个提案的内容是讨论如何将这个机制更好地暴露给用户使用。

需要跟 SDK 打交道的同学可以看一下更具体的提案内容。
