### ISSUE TITLE
What to Expect From Marzipan

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1398]
# 推荐收录

## 链接

https://blog.iconfactory.com/2019/05/what-to-expect-from-marzipan/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B403

**Comment by iblacksun** [comment]
### [What to Expect From Marzipan](https://blog.iconfactory.com/2019/05/what-to-expect-from-marzipan/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B403)
> Marzipan 是项目代号，Apple 在 WWDC 2018 上发布：将 UIKit App 迁移到  macOS 上。 

WWDC 2019 不久就要开始，平台迁移没有想象中那么美好，不是光适配代码发布就完事了，作者从开发、设计及市场三个方面分析迁移可能会面对的难题。
