### ISSUE TITLE
代码：XLForm

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#14]
https://github.com/xmartlabs/XLForm

**Comment by jessecoding** [comment]
swift版 https://github.com/xmartlabs/Eureka

**Comment by Damonvvong** [comment]
XLForm 是一个 iOS 表单页面的一个解决方案。可以解决各种复杂交互的表单页面，功能十分强大。又 OC 实现，代码质量很高，其设计思想也很值得学习，是一份很不错的源码学习内容。

比较有意思的一点是，XLForm 的 Swift 版本 Eureka 并不是单纯的翻译 XLForm，而是用一种全新的方式去实现相同的功能，通过大量的函数符重载，让写出来的代码特别清晰。

但是，我觉得对于大部分的 app 来说，没有太过于复杂的表单需求，所以没有太大的必要引用这个库去实现一些简单的表单页面。会给人一种，用复杂的工具去解决简单的问题的感觉。

当然，如果是一个类似系统设置的 app 来说，使用 XLForm 一定是首选之一。
