### ISSUE TITLE
Run Swift in browsers

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1401]
# 推荐收录

## 链接

https://swiftwasm.org/

**Comment by raozhizhen** [comment]
将 Swift 代码编译为 [WebAssembly](http://webassembly.org.cn/) ，使它能在浏览器上直接运行。目前还是第一个版本，Swfit 的很多功能还需要支持，有兴趣可以加入 [swiftwasm](https://github.com/swiftwasm)
