### ISSUE TITLE
超级签名-原理/机制/技术细节-完全解析

### ISSUE THREAD

**Issue by yiios** [SwiftOldDriver/iOS-Weekly#1405]
# 推荐收录

## 链接

[https://juejin.im/post/5cdeb72151882525cc707729]

**Comment by iblacksun** [comment]
这种分发机制有悖 Apple 开发者协议，不建议推荐。 @ParsifalC

**Comment by ParsifalC** [comment]
@yiios 感谢自荐，不过我们考虑了之后，决定不收录这篇文章。这篇文章对”超级签名“确实做了较细致的分析，但正如你文中所述，这类技术手段是违背苹果审核条款的，我们不应该做这方面的推广。欢迎继续自荐自己其他方面的文章。谢谢。
