### ISSUE TITLE
Building a NFC Scanner App with CoreNFC in Swift

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1407]
# 推荐收录

## 链接

https://medium.com/appcoda-tutorials/building-nfc-product-scanner-ios-app-with-corenfc-alfian-losari-5da0365bcde5

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [Building a NFC Scanner App with CoreNFC in Swift](https://medium.com/appcoda-tutorials/building-nfc-product-scanner-ios-app-with-corenfc-alfian-losari-5da0365bcde5)

在 2014 年 Apple 发布 Apple Pay ，iPhone  7 和  iPhone 7 Plus 是第一批支持 NFC 功能的设备。iOS  11 终于发布了 CoreNFC 框架，第三方  App 可以在前台读取 NFC tags，iOS 12 增强了 CoreNFC 的能力，允许在后台读取 tags 并通过 Universal Link 技术唤起 App。iOS 13 马上就要发布了，相信开发者们十分期待 Apple 开放 NFC 写入功能。

文章详尽的描述了如何从零开发一个读取 NFC tags 的应用，甚至十分贴心的介绍了如何制作 tags 供测试使用，建议对 NFC 有兴趣的开发者们读一读。
