### ISSUE TITLE
Let’s dissect the differences between Generics and the Any type in Swift

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1408]
# 推荐收录

## 链接

https://medium.freecodecamp.org/lets-dissect-the-differences-between-generics-and-the-any-type-in-swift-86c8214c35e4

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
我觉得这篇文章还是不推吧，对于能看懂这种程度英文的人来说，内容显得太过基础了。
