### ISSUE TITLE
深入了解Swift中的初始化(Initialization)

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#1434]
# 推荐收录

## 链接

https://juejin.im/post/5ceb82056fb9a07efe2d9aab

**Comment by kemchenj** [comment]
### [深入了解Swift中的初始化(Initialization)](https://juejin.im/post/5ceb82056fb9a07efe2d9aab)

[@四娘](kemchenj.github.io)：类型安全是 Swift 的一大特点，其中一个表现就是初始化的确定性，只要一个实例完成了初始化过程，它的属性就必然初始化完成，不会处在不确定的状态。

这篇文章的作者总结了自己对于初始化过程的了解，加上一些更加接地气的例子和练习，如果有同学对于这一部分知识还比较模糊的话，推荐一看。
