### ISSUE TITLE
开启 Cocoapods 新选项，加快项目索引速度

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1435]
# 推荐收录

## 链接

https://kemchenj.github.io/2019-05-31/

## 理由

前几天 Cocoapods 1.7.0 正式版发布了，我最期待的一个功能是 Multiple Pod Projects，昨天顺手就给接入了，项目解析和索引效率有了非常明显的提升，过程中踩了些坑，这次一起把之前 debug 的经验分享一下。

**Comment by nianran** [comment]
建议修改一下文章标题
