### ISSUE TITLE
Inside SwiftUI (About @State)

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1446]
# 推荐收录

## 链接

https://kateinoigakukun.hatenablog.com/entry/2019/06/09/081831

## 理由

逆向了 SwiftUI 里的 State，分析 State 更新后自动同步到 View 这一段过程的原理。

**Comment by xiaofei86** [comment]
本期 SwiftUI 文章也太多了。本文并没有真正 Inside SwiftUI，知识点太小，没有太多内容，且只是个人推测（This post is just a my prediction），价值不大，不建议推荐。
