### ISSUE TITLE
Property wrappers to remove boilerplate code in Swift 5.1

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#1447]
# 推荐收录

## 链接

https://www.avanderlee.com/swift/property-wrappers/

**Comment by iblacksun** [comment]
### 🐢 [Property wrappers to remove boilerplate code in Swift](https://www.avanderlee.com/swift/property-wrappers/)

[@享耳先森](https://github.com/iblacksun)：`Property wrappers` 是在 WWDC 2019 随 Xcode 11 和 Swift 5.1 一起发布的，提案可以参考 [SE-0258](https://github.com/DougGregor/swift-evolution/blob/property-wrappers/proposals/0258-property-wrappers.md) 。

本文举例使用 `Property wrappers` 实现一个 `@UserDefault` wrapper，用来解决 UserDefault 读取与存储包含大量模板代码的问题，另外，Swift UI 也利用了 `Property wrappers` 实现 View 与 Model 的动态绑定。
