### ISSUE TITLE
iOS关键组件iBoot源代码泄露

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#145]
https://mp.weixin.qq.com/s/QsQ49LkK_suB30O2AQWh9Q

**Comment by Damonvvong** [comment]
https://www.cnet.com/news/apple-calls-leaked-iphone-source-code-outdated/

**Comment by iblacksun** [comment]
[iOS 关键组件 `iBoot` 源代码泄露](https://mp.weixin.qq.com/s/QsQ49LkK_suB30O2AQWh9Q)

> 有匿名开发者在 GitHub 上传了 iOS 核心组件 `iBoot` 的源代码，`iBoot` 是 iOS 关键的源代码之一，它确保了操作系统的可信任启动，换句话说，它是加载 iOS 的程序，是开启 iPhone 运行的第一个进程，它加载并验证内核是否被苹果正确签名，然后执行，就像 iPhone 的 BIOS 一样。

[Apple 已确认这一事件](https://www.cnet.com/news/apple-calls-leaked-iphone-source-code-outdated/)并表示泄漏的是 iOS 9 的代码。
