### ISSUE TITLE
苹果公司与内蒙古签订协议 将在中国国内建设第二个数据中心

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#146]
### [苹果公司与内蒙古签订协议 将在中国国内建设第二个数据中心](https://readhub.me/topic/1XVjDPeuSXk)
据了解，这是苹果公司继去年7月宣布，将与云上贵州大数据产业发展有限公司（以下简称「云上贵州」）合作在贵州省建设国内第一个数据中心后，即将落地的第二个数据中心。

**Comment by raozhizhen** [comment]
苹果公司将在内蒙古乌兰察布市，建设中国第二个数据中心，于 2020 年开始投入运营，继而形成 “南贵北乌“ 两个数据中心的格局。
