### ISSUE TITLE
适用于Linux / ARM板上硬件项目的Swift库

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#1468]
# 推荐收录

## 链接

https://github.com/uraimo/SwiftyGPIO

## 理由

适用于Linux / ARM板上硬件项目的Swift库

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [SwiftyGPIO](https://github.com/uraimo/SwiftyGPIO)

一个适用于Linux / ARM 硬件项目的Swift库，支持 GPIOs / SPI / I2C / PWM / UART / 1Wire 等主流协议，有丰富周边教学和衍生项目。
