### ISSUE TITLE
CocoaPods 1.7.2 - Master Repo CDN is Finalized!

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1475]
# 推荐收录

## 链接

http://blog.cocoapods.org/CocoaPods-1.7.2/

**Comment by iblacksun** [comment]
### [CocoaPods 1.7.2 - Master Repo CDN is Finalized!](http://blog.cocoapods.org/CocoaPods-1.7.2/)

[@享耳先森](https://github.com/iblacksun)：`CocoaPods` 近期发布了 1.7.2 版，支持 CDN，意味着我们不需要将整个 `Podspecs` 仓库 clone 并保存在本地，节省几 G 的硬盘空间。最新的版本中，需要在 `Podfile` 里将修改 `source 'https://cdn.cocoapods.org/'`，CDN 将会在未来版本变为默认设置。
