### ISSUE TITLE
Building a Lightweight Speedometer in React Native

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1487]
# 推荐收录

## 链接

https://medium.com/react-native-training/building-a-lightweight-speedometer-in-react-native-1eedaa039a40

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by anotheren** [comment]
这期是没内容么，我总觉得推荐 React Native 的控件实现不是很好
