### ISSUE TITLE
Swift 4.1 新增代码尺寸优化模式

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#150]
https://swift.org/blog/osize/

**Comment by iblacksun** [comment]
[Swift 4.1 新增 `-Osize` 优化模式降低代码尺寸](https://swift.org/blog/osize/)

Swift 4.1 将随 iOS 11.3、Xcode 9.3 一起发布。`Optimization Level` 新增 `-Osize` 模式，降低编译后代码尺寸。按官方描述，启用 `-Osize` 后代码尺寸将降低 5%-30%，而性能影响可以忽略不计(小于 5%)。

另外，还从 `Optimization Level`  独立出 `Compilation Mode`，可选 `Single File` 和  `Whole Module`。
