### ISSUE TITLE
Flutter — Visual Studio Code Shortcuts for Fast and Efficient Development

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1503]
# 推荐收录

## 链接

https://medium.com/flutter-community/flutter-visual-studio-code-shortcuts-for-fast-and-efficient-development-7235bc6c3b7d

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
文章 90% 的内容都在介绍 VSC 自身的快捷键操作，与 Flutter 关系不大，不推荐放到周报里。
