### ISSUE TITLE
Revisit iOS Autorelease 之不经意间可能被影响的优化

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1506]
# 推荐收录

## 链接

http://satanwoo.github.io/2019/07/02/RevisitAutorelease/

**Comment by raozhizhen** [comment]
非常硬核的一篇文章

**Comment by raozhizhen** [comment]
非常硬核的一篇文章，编译器会判断方法的名是否以 alloc / new / copy / mutableCopy 开头，如果不是，则自动将返回的对象注册到 Autorelease Pool 中。且编译器会对 objc_autoreleaseReturnValue 和objc_retainAutoreleasedReturnValue 进行基于 TLS(Thread Local Storage) 的判断优化，本质上并不会执行 autorelease。 
但这个优化逻辑很有可能被我们不知情下编写的代码所改变，产生奇怪的问题。作者构建了一个 demo，从汇编入手，逐步分析，一段不起眼的代码是如何使 autorelease 优化失效，导致 MemoryGraph 中存在大量被 @autoreleasepool content 持有的数据，产生内存不释放问题（并非是内存泄漏，Leaks 是查不出来的）。
