### ISSUE TITLE
Crash 符号化 3. Mach-O 与 ato

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#151]
http://saitjr.com/ios/symbolicatecrash-3.html

另外两篇貌似写的也很好：
http://saitjr.com/ios/symbolicatecrash-1.html
http://saitjr.com/ios/symbolicatecrash-2.html

**Comment by Damonvvong** [comment]
作者一共写了三篇文章，从**基本流程与相关命令**到 **symbolicatecrash 源码浅析与优化**以及最后的 **Mach-O 与 atos**，由浅入深的解释了 iOS Crash 从产生到符号化的整个过程。
