### ISSUE TITLE
Web 和移动端需要掌握的布局方式 - Flexbox

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1512]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/WVqnmIbIkxsvBMhHydwHAg

**Comment by iblacksun** [comment]
### 🐕 [Web 和移动端需要掌握的布局方式 - Flexbox](https://mp.weixin.qq.com/s/WVqnmIbIkxsvBMhHydwHAg)

[@享耳先森](https://github.com/iblacksun)：布局一直是用户端开发的重点，`Flexbox` 布局解决了原来 CSS 盒子模型的一些不便之处。 `Flexbox` 已不止用于 CSS：如 Android 的 `FlexboxLayout`、ReactNative 所使用的 `yoga`，都支持 `Flexbox`。本文浅显的介绍了 `Flexbox` 的基本用法，建议阅读。
