### ISSUE TITLE
Flutter 1.7

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1515]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/WZruGVpOpen2f4NNiSu7cw

**Comment by CrazyCoderShi** [comment]
https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf

**Comment by linwenbang** [comment]
过了一段时间了，录屏评估下是否还发~

**Comment by linwenbang** [comment]
过了一段时间了，路屏评估下是否还发~

**Comment by looping** [comment]
不用发了吧，flutter 1.7 发布很多地方都报道介绍了，这种新闻类的错过了再发意义就不大了。
