### ISSUE TITLE
Swift5.0 的 Runtime 机制浅析

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1526]
# 推荐收录

## 链接

https://juejin.im/post/5d29fb63e51d4510aa01159d

**Comment by raozhizhen** [comment]
Objective-C 的 Runtime 机制大家了解的比较多，而 Swift 底层原理研究文章比较少。作者通过与 OC 的对比，以及将程序运行时的汇编代码，翻译成 C 语言伪代码，向你解析 Swift 中内部对象是如何创建的，方法以及函数调用又是如何实现，成员变量的访问以及对象内存如何布局。
