### ISSUE TITLE
[译]在 Git 中保护 iOS 项目的敏感信息

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#153]
https://juejin.im/entry/5a7ae9225188257a5f1eb211

**Comment by raozhizhen** [comment]
如果要开源的代码涉及敏感信息，比如 API Key，HMAC secrets或密码，那么比较好的方式是把它们放在新建的 xcconfig 文件里，Git 再忽略这些文件。
最后新建不把值包含进去的示例配置 xcconfig 文件。其它开发者此时只需要将示例配置文件填值，再重命名一下即可轻松运行不包含敏感信息的项目。
