### ISSUE TITLE
Managing background tasks with the new Task Scheduler in iOS 13

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1530]
# 推荐收录

## 链接

https://medium.com/snowdog-labs/managing-background-tasks-with-new-task-scheduler-in-ios-13-aaabdac0d95b

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by linwenbang** [comment]
可以带上味精wwdc的session一起推荐

**Comment by zvving** [comment]
@linwenbang 你是指 https://xiaozhuanlan.com/topic/1806594273 这篇吗？不是味精写的
