### ISSUE TITLE
逆袭Futter? Facebook 发布全新跨平台引擎 Hermes！

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1531]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s?__biz=MzIyMjQ0MTU0NA==&mid=2247490343&idx=1&sn=2d7103bb3825fa87e6e334bd64a17a5f&chksm=e82c2200df5bab16643a4c035b344fb4525838351678b7ae5889da5ba487359e9afec6ddb83c&mpshare=1&scene=1&srcid=&key=2f4703df4564706ad813f74bdbbc290fc448c

## 理由

当新闻吧~

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
与 #1525  重复了，关闭。
