### ISSUE TITLE
揭秘苹果应用审核机制内幕：审核拒绝率高达 40%？

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1534]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/0mk3O3cK5ejqhUw0RV_UZw

**Comment by GesanTung** [comment]
和这篇重复了https://github.com/SwiftOldDriver/iOS-Weekly/issues/1480

**Comment by Damonvvong** [comment]
这个已经发过了。我先关闭了
