### ISSUE TITLE
 Dependency Injection in Practice

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1537]
# 推荐收录

## 链接

https://www.racecondition.software/blog/dependency-injection/

**Comment by ParsifalC** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/issues/957

之前也推过依赖注入的系列文章。

**Comment by xiaofei86** [comment]
都简单讲了依赖注入和 Swinject，感觉没有 #957 写的好，重复推荐必要性不强。
