### ISSUE TITLE
DiffableDataSources

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1544]
# 推荐收录

## 链接

[DiffableDataSources](https://ra1028.github.io/DiffableDataSources)

## 理由

向后移植 UITableView / UICollectionViewDiffableDataSource

**Comment by iblacksun** [comment]
### [DiffableDataSources](https://ra1028.github.io/DiffableDataSources/)

[@享耳先森](https://github.com/iblacksun)：Apple 在 WWDC 2019 新增了 `UITableView/UICollectionViewDiffableDataSource`，不过新  API 仅限 iOS 13，如需支持之前系统的话就用不了了，`DiffableDataSources ` 基于 [DifferenceKit](https://github.com/ra1028/DifferenceKit) 实现，提供了与官方近似的 API 。
