### ISSUE TITLE
QGrid

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#1549]
# 推荐收录

## 链接

[QGrid](https://github.com/Q-Mobile/QGrid)

## 理由

QGrid is the missing SwiftUI collection view. It uses the same approach as SwiftUI's List view, by computing its cells on demand from an underlying collection of identified data.

**Comment by Damonvvong** [comment]
看了一下源码，感觉功能稍微简单了一点。就不推荐了
