### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1550]
# 推荐收录

https://nshipster.com/formatter/

[此处替换为具体的资源地址]

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Formatter - NSHisper](https://nshipster.com/formatter/)

[@四娘](kemchenj.github.io)：将数据转化为人类可读的文本格式是一个重要且复杂的任务，需要根据用户的国家，语言，时区和货币等因素进行格式化，仅仅是调用对象的 `description` 是远远不够的，实际工作中我会用到一个存在于 Foundation 核心部分的类型 —— `Formatter`。

本周 NSHisper 为我们介绍的就是 `Formatter` 这个重要的工具，文章里为我们列举介绍了 Apple 平台上 `DateFormatter` / `NumberFormatter` 等等各种不同的 `Formatter` 以及它们对应的用途，对于这些格式化工具不熟悉的同学都可以看一下。
