### ISSUE TITLE
Swift 5 之后 &quot;Method Swizzling&quot;？

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1555]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/8z7A_-d0ZvvAJ3155DogvA

**Comment by kemchenj** [comment]
### [Swift 5 之后 "Method Swizzling"？](https://mp.weixin.qq.com/s/8z7A_-d0ZvvAJ3155DogvA)

[@四娘](kemchenj.github.io)：Swift 5.1 里新增了一个私有功能叫做 Dynamic Method Replacement，可以简单地理解为一个类型安全的 Method Swizzle。

瓜神在这篇文章里给我们介绍了这个功能的使用方法以及内部的实现，并且通过阅读源码解决了连环 Hook 失效的问题。
