### ISSUE TITLE
mac App可在后台偷偷截屏的bug

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#156]
https://krausefx.com/blog/mac-privacy-sandboxed-mac-apps-can-take-screenshots

mac App 可在后台偷偷截屏的 bug，详情推文见：
https://twitter.com/KrauseFx/status/962440588502052864，
现在已提交 bug 给苹果：
https://openradar.appspot.com/radar?id=5610698700750848

**Comment by lacklock** [comment]
感觉这种新闻不是太重要
