### ISSUE TITLE
sfsymbols

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1564]
# 推荐收录

## 链接

https://github.com/davedelong/sfsymbols

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
整体看了下代码，总体感觉推荐意义不大。
其主要是用 CoreText 部分 API 输出路径，然后拼接格式化代码，参考意义不大。
此 issue 先关闭了。
