### ISSUE TITLE
Rule-based logic in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1567]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/rule-based-logic-in-swift

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢[Rule-based logic in Swift](https://www.swiftbysundell.com/posts/rule-based-logic-in-swift)

[@享耳先森](https://github.com/iblacksun)：对于系统设计而言，只考虑技术架构的话其实相对简单(比如使用 MVVM 还是其他架构模式)，虽然架构模式非常重要，但我们还是可以通过对一些次要代码或结构进行改进来提升代码质量，所谓见微知著。本文通过 URL 匹配这一点入手，介绍如何将原来难以维护的代码抽象出一些规则来进行重构。
