### ISSUE TITLE
Swift API-Digester

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1573]
# 推荐收录

## 链接

https://github.com/apple/swift-nio/commit/07e7e01c76be20640ddc3770d7b16e87eedf20de

## 理由

Swift 5.1 里新增了一个 api-digester 功能，用来打印和比较编译产物的 API，Swift-NIO 在此基础上搭建了一个 API Diff 功能，可以预见未来开源框架都会使用这个功能来生成 API Diff，帮助检验 Pull Request 对于 API 的影响，ChangeLog 的生成等等。

示例：

```
==============================
ERROR: public API change in NIOWebSocket.json
==============================

/* Generic Signature Changes */

/* RawRepresentable Changes */

/* Removed Decls */
Constructor WebSocketFrameDecoder.init(maxFrameSize:automaticErrorHandling:) has been removed
EnumElement WebSocketOpcode.unknownControl has been removed
EnumElement WebSocketOpcode.unknownNonControl has been removed
Func NIOWebSocketUpgradeError.__derived_enum_equals(_:_:) has been removed
Func NIOWebSocketUpgradeError.hash(into:) has been removed
Func WebSocketErrorCode.==(_:_:) has been removed
Func WebSocketFrame.==(_:_:) has been removed
Func WebSocketOpcode.==(_:_:) has been removed
Var NIOWebSocketUpgradeError.hashValue has been removed
Var WebSocketFrameDecoder.cumulationBuffer has been removed

/* Moved Decls */
Enum NIOWebSocketUpgradeError has been changed to a Struct
Enum WebSocketOpcode has been changed to a Struct

/* Renamed Decls */
Func WebSocketFrameDecoder.decode(ctx:buffer:) has been renamed to Func WebSocketFrameDecoder.decode(context:buffer:)
Func WebSocketFrameDecoder.decodeLast(ctx:buffer:) has been renamed to Func WebSocketFrameDecoder.decodeLast(context:buffer:seenEOF:)
Func WebSocketFrameEncoder.write(ctx:data:promise:) has been renamed to Func WebSocketFrameEncoder.write(context:data:promise:)
Func WebSocketProtocolErrorHandler.errorCaught(ctx:error:) has been renamed to Func WebSocketProtocolErrorHandler.errorCaught(context:error:)

/* Type Changes */
Constructor UInt8.init(webSocketOpcode:) has return type change from UInt8? to UInt8

/* Decl Attribute changes */
EnumElement NIOWebSocketUpgradeError.invalidUpgradeHeader is now static
EnumElement NIOWebSocketUpgradeError.unsupportedWebSocketTarget is now static
EnumElement WebSocketOpcode.binary is now static
EnumElement WebSocketOpcode.connectionClose is now static
EnumElement WebSocketOpcode.continuation is now static
EnumElement WebSocketOpcode.ping is now static
EnumElement WebSocketOpcode.pong is now static
EnumElement WebSocketOpcode.text is now static
Func WebSocketFrameDecoder.decode(ctx:buffer:) is now throwing

/* Fixed-layout Type Changes */

/* Protocol Conformance Change */
Class WebSocketFrameDecoder has removed conformance to ChannelHandler
Class WebSocketFrameDecoder has removed conformance to ChannelInboundHandler
Class WebSocketFrameDecoder has removed conformance to _ChannelInboundHandler
Class WebSocketFrameDecoder has removed conformance to _EmittingChannelHandler
Enum NIOWebSocketUpgradeError has removed conformance to Hashable

/* Protocol Requirement Change */

/* Class Inheritance Change */
```

**Comment by iblacksun** [comment]
### [Swift API-Digester](https://github.com/apple/swift-nio/commit/07e7e01c76be20640ddc3770d7b16e87eedf20de)

[@享耳先森](https://github.com/iblacksun)：Swift 5.1 里新增了一个 `api-digester` 功能，用来打印和比较编译产物的 API，Swift-NIO 在此基础上搭建了一个 API Diff 功能，可以预见未来开源框架都会使用这个功能来生成 API Diff，帮助检验 Pull Request 对于 API 的影响，ChangeLog 的生成等等。

用类似这样的命令：`swift api-digester -diagnose-sdk --input-paths "dir1" -input-paths "dir2"` 就能比较两个编译产物的 API 区别，生成类似下面的结果：

> Removed Decls
> Constructor WebSocketFrameDecoder.init(maxFrameSize:automaticErrorHandling:) has been removed
> EnumElement WebSocketOpcode.unknownControl has been removed
> EnumElement WebSocketOpcode.unknownNonControl has been removed

> Renamed Decls
> Func WebSocketFrameDecoder.decode(ctx:buffer:) has been renamed to Func WebSocketFrameDecoder.decode(context:buffer:)
> Func WebSocketFrameDecoder.decodeLast(ctx:buffer:) has been renamed to Func WebSocketFrameDecoder.decodeLast(context:buffer:seenEOF:)
> Func WebSocketFrameEncoder.write(ctx:data:promise:) has been renamed to Func WebSocketFrameEncoder.write(context:data:promise:)
> Func WebSocketProtocolErrorHandler.errorCaught(ctx:error:) has been renamed to Func WebSocketProtocolErrorHandler.errorCaught(context:error:)

> Type Changes
> Constructor UInt8.init(webSocketOpcode:) has return type change from UInt8? to UInt8
