### ISSUE TITLE
GitHub - TannerJin/Swift-MemoryLayout: Swift MemoryLayout

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1574]
# 推荐收录

## 链接

https://github.com/TannerJin/Swift-MemoryLayout

**Comment by kemchenj** [comment]
### [Swift-MemoryLayout](https://github.com/TannerJin/Swift-MemoryLayout)

作者在学习 Swift 内存布局的过程中，写了一个简单的 Demo 演示如何使用指针去读取 Array / Dictionary 内部的变量，进一步验证各种类型的内存布局。

这个项目很好地演示了 Swift 里的指针操作，非常值得一看！！！
