### ISSUE TITLE
Phantom types in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1584]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/phantom-types-in-swift

**Comment by kemchenj** [comment]
### [Phantom types in Swift](https://www.swiftbysundell.com/posts/phantom-types-in-swift)

[@四娘](https://kemchenj.github.io)：这周 Swift by Sundell 为我们介绍的是一种叫做 Phantom Types 的技巧，在 Swift 里处理一些有限集合的时候，我们通常会将它声明为 enum，但经常会有一些特殊情况需要照顾：

```swift
func openEditor(for document: Document) {
    switch document.format {
    case .text: openTextEditor(for: document)
    case .html: openHTMLEditor(for: document)
    case .pdf:  assertionFailure("Cannot edit PDF documents")
    }
}
```

这样的代码无法通过类型系统去限制错误的调用，作者尝试从 Swift 的标准库里寻找解决方案，发现标准库里 `Unicode` 将 `UTF8` 等格式作为一个类型声明出来，而不是直接使用 enum case：

```swift
enum DocumentFormat {
    enum Text {}
    enum HTML {}
    enum PDF {}
}

func openTextEditor(for document: Document<DocumentFormat.Text>) { ... }
func openHTMLEditor(for document: Document<DocumentFormat.HTML>) { ... }
```
