### ISSUE TITLE
自荐自己写的轻量响应式框架支持OC和Swift

### ISSUE THREAD

**Issue by josercc** [SwiftOldDriver/iOS-Weekly#1589]
# 推荐收录

## 链接

https://github.com/combineobject

## 理由

`CombineObject` 响应式框架 ，`Value` 和 `View` 相互绑定。值更新就会更新所有绑定的`View`协议对象，更新`View`协议对象的值更新`Value`值从而全部更新绑定的`View`值。

![](https://github.com/combineobject/CombineObject-Swift/blob/master/images/image-20190806101237397.png?raw=true)

### 例子
> 假如我们界面一个UIView和UILabel，我们想让UIView的背景颜色和UILabel的文本颜色一直保持统一。做法很多种，我们看看这个库可以做什么。

![](https://github.com/combineobject/CombineObject-Swift/raw/master/images/UIView.gif)

1. 声明一个变量做控制
- Swift
```Swift
@CombineObjectBind var color = UIColor.gray
```
- OC
```objc
/// 声明绑定属性
@property (nonatomic, strong) UIColor *displayViewBackgroundColor;
/// 初始化
self.displayViewBackgroundColor = [UIColor grayColor];
```

2. 绑定到试图
- Swift
```Swift
self.displayLabel.bind(identifier: UILabelIdentifier.textColor, combineObject: self._color)
self.displayView.bind(combineObject: self._color)
```
- OC
```objc
/// 绑定到试图默认的 BackgroundColor 属性
self.displayView.viewBind(self.displayViewBackgroundColor.bind,@"");
/// 绑定UILabel 的文本颜色
self.displayColorText.viewBind(self.displayViewBackgroundColor.bind,UILabelIdentifier.textColor);
```

3.1 更新属性更新试图
- Swift
```Swift
self.color = UIColor.red
```
- OC
```objc
/// 更改属性的值
self.displayViewBackgroundColor.wrappedValue = [UIColor redColor];
```

3.2 直接更新一个试图的值
- Swift
```Swift
self.displayView.updateBindValue(value: UIColor.blue)
```
- OC
```objc
/// 更改试图的值
self.displayView.updateWrappedValue([UIColor blueColor],@"");
```

## 我们可以自定义在值改变时候更改内容
- Swift
```Swift
self._color.bind.combineValueChangedBlock {[weak self] (value) in
    if let boardColor = value as? UIColor {
        self?.displayLabel.layer.borderWidth = 1
        self?.displayLabel.layer.borderColor = boardColor.cgColor
    }
}
```
- OC
```objc
__weak typeof(self) weakSelf = self;
self.displayViewBackgroundColor.bind.contentChanged = ^(id<CombineValue>  _Nonnull content) {
    __strong typeof(weakSelf) strongSelf = weakSelf;
    strongSelf.displayLabel.layer.borderWidth = 1;
    strongSelf.displayLabel.layer.borderColor = [(UIColor *)content CGColor];
};
```

#### UIView

- backgroundColor
- userInteractionEnabled
- frame
- alpha
- hidden

#### UILabel

- text
- font
- textColor
- attributedText

#### UISwitch

- on

#### UITextField

- text
- placeholder

#### UISlider

- value

#### UIProgressView

- progress

#### UITextView

- text

### 扩展`UIView`的赋值支持属性方法

- Swift
```swift
public func setUIViewCombineValue(_ identifier: CombineIdentifier, _ value: CombineValue?)
```
- OC
```objc
- (void)setOtherCombineValue:(id<CombineValue>)value identifier:(NSString *)identifier 
```

### 让其他的对象支持属性绑定

> 实现`CombineView`协议

- Swift
```swift
func setCombineValue(_ identifier:CombineIdentifier, _ value:CombineValue?)
```

- OC
```objc
- (void)setCombineValue:(id<CombineValue>)value identifier:(NSString *)identifier
```

### 自定义赋值

> 实现属性`bine`值的代理方法``

- Swift
```swift
self.color.bine.setCombineValueBlock = { content in
}
```
- OC
```objc
self.color.bine.customSetWrappedValueBlock = ^(CombineBindBlockContent *content) {
}
```

## 推荐人信息
[君赏](https://github.com/josercc)

**Comment by iblacksun** [comment]
@josercc 你好，感谢自荐，想法很赞。

仔细阅读了源码，感觉 API 命名不够  Swift：
> 比如  `self.displayLabel.bind(identifier: UILabelIdentifier.textColor, combineObject: self._color)`

 `self.displayView.bind(combineObject: self._color)`  里根据  UIColor 推断 `backgroudColor` 也太隐晦，建议看看有没有更好的思路。

这次先不推荐了。
