### ISSUE TITLE
iOS Code Signing Tutorial Series

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#159]
https://medium.com/xcblog/ios-code-signing-tutorial-series-814b22eba507

**Comment by mmoaay** [comment]
由 Shashikant Jagtap 发布的 iOS Code Signing 相关系列博客，总共五篇。众所周知，iOS Code Signing 对于 iOS 开发者来说，一直都是最神秘的存在，尽管有所谓的官方文档。显然作者也发现了这个问题，所以他采用了亲身实践的方式，力求更简单的为读者解读 iOS Code Signing 的一些细节。（PS：有在做技术文章翻译的童鞋可以考虑把这个系列翻译成中文，造福更多开发者～）
