### ISSUE TITLE
以React思维二次封装UITableView和UICollectionView的API

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#160]
https://github.com/plangrid/ReactiveLists

**Comment by lacklock** [comment]
代码质量一般，但是我觉得api的思路还挺好的。

**Comment by ParsifalC** [comment]
https://github.com/marty-suzuki/FluxCapacitor

这个看下要不要也并到这部分？在iOS中使用FB的flux思维进行开发，相比于ReSwift这类基于Redux的大型框架，这个比较轻量级，我觉得也是蛮不错的一种设计思维尝试。

@lacklock @raozhizhen

**Comment by raozhizhen** [comment]
[ReactiveLists](https://github.com/plangrid/ReactiveLists)

ReactiveLists 基于 [React](https://reactjs.org/) 编程思想，封装 UITableView 和 UICollectionView 的 API，使用该 API 可以编写 [无状态函数](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions) 来生成列表页面。作者认为，在向 UIKit 组件提供数据上，这些无状态函数相比 ***DataSource**，***Delegate** 更易于阅读和迭代，而且还易于测试。

[Open Sourcing ReactiveLists for iOS](https://medium.com/plangrid-technology/open-sourcing-reactivelists-for-ios-3abdf41b770a)

**Comment by raozhizhen** [comment]
@ParsifalC FluxCapacitor 这个可以放到下周 或者你有时间的话可以新开一个 issues

**Comment by ParsifalC** [comment]
ok @raozhizhen 放到第九期吧。
