### ISSUE TITLE
KakaJSON

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1606]
# 推荐收录

## 链接

https://github.com/kakaopensource/KakaJSON

**Comment by raozhizhen** [comment]
Swift 内置了一套 Codable 机制，可以用于 JSON 转 Model。对于一些简单的模型结构，还是挺好用，但一旦牵扯到复杂的模型结构、一些个性化的需求（比如 KeyMapping、类型不匹配时的转换处理、自定义解析规则等），Codable 就不太能友善地完成任务了。
为了解决上述问题，作者编写了一套纯 Swift 实现的 JSON 与 Model 互相转换的框架：KakaJSON。KakaJSON 通过了大量的单元测试用例，应对各种常用的数据场景，对外提供了一些友善易用、扩展性强、可高度个性化定制需求的接口，内置了 Metedata 缓存等机制，加快转换速度。
