### ISSUE TITLE
Why you should stop using Git rebase

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1615]
# 推荐收录

## 链接

https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
###  [Why you should stop using Git rebase](https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1)

[@享耳先森](https://github.com/iblacksun): 文章作者认为现今大家使用 `git rebase` 的过程中过于追求 commit history 的线性，而忽略了 `git rebase` 相较于 `merge` 带来的隐患： 在一个长的 commit 链中使用 rebase 解决冲突是非常困难、易出错的。作者也给出了两种解决方案，详情请阅读原文。
