### ISSUE TITLE
HackMan

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1618]
# 推荐收录

## 链接

https://github.com/Cosmo/HackMan?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B417

**Comment by raozhizhen** [comment]
HackMan 是一个直接通过命令行生成样板代码的简单工具，几行命令，就可以帮你 run 起来一个简单的 APP。
