### ISSUE TITLE
The power of subscripts in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1624]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/the-power-of-subscripts-in-swift

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [The power of subscripts in Swift](https://www.swiftbysundell.com/posts/the-power-of-subscripts-in-swift)

[@四娘](https://kemchenj.github.io)：本周 SwiftBySundell 为我们带来的是 subscript 功能：

- subscript 和 method 的区别和各自的场景
- 如何自定义 subscript
- subscript 的重载
- subscript 的 getter 和 setter 写法以及泛型的使用
- Swift 5.1 中引入的 static subscript 

对于 subscript 功能还不熟悉的同学可以考虑通过这篇文章补充相关知识。
