### ISSUE TITLE
How Strings and Substrings work in Swift

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1625]
# 推荐收录

## 链接

https://medium.com/@suragch/how-strings-and-substrings-work-in-swift-fd4dc43ee91d

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这篇文章讲的都是基本的 API 使用，内容跟官方文档 [字符串与字符 - SwiftGG](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/03_strings_and_characters) 重合度很高，而且是英文的，我觉得对于我们读者来说价值可能不是那么大。
