### ISSUE TITLE
Code Review 最佳实践

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1631]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s?__biz=MzAxODI5ODMwOA==&mid=2666544605&idx=1&sn=56fe6b058f31d888e9df6509f97d06ca

**Comment by iblacksun** [comment]
### [Code Review 最佳实践](https://mp.weixin.qq.com/s?__biz=MzAxODI5ODMwOA==&mid=2666544605&idx=1&sn=56fe6b058f31d888e9df6509f97d06ca)

[@享耳先森](https://github.com/iblacksun): 作者认为 Code Review 是软件开发中的最佳实践之一：首先可以更好在团队内做到知识共享，其次可以有效提高整体代码质量，及时发现代码中可能存在的问题。作者还重点说明了 Code Review 应该怎么做，如果你团队中还没有实行 Code Review 或对 Code Review 有什么疑问，建议仔细读这篇文章。
