### ISSUE TITLE
ggtalk | 没事刷刷算法

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1635]
# 推荐收录

## 链接

https://talk.swift.gg/41?from=timeline&isappinstalled=0

**Comment by raozhizhen** [comment]
本期磊子和 wamaker 会聊聊算法。算法是个大话题，这期讲的只是两个从业者的小故事，看看他们如何认识算法，如何学习算法，如何看待算法。
