### ISSUE TITLE
Swift汇编看枚举、类、闭包

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#1643]
# 推荐收录

## 链接

https://juejin.im/post/5d5c0010e51d456201486e4c

**Comment by Damonvvong** [comment]
首先，汇编很不错，但是 Swift 作为开源语言，我觉得看源码比汇编反过来“猜”原理其实更好。

再加上我认为作者在内容上还有优化的空间，有待提高。

可以先看一下 https://github.com/apple/swift/blob/664e5659c50fb35c6b8e08d05ca6a4e81bdae7f3/docs/ABI/TypeLayout.rst 这个，以及 Swift 的源码，把缺失的地方补上~
