### ISSUE TITLE
KKJSBridge

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1645]
# 推荐收录

## 链接

https://github.com/karosLi/KKJSBridge

## 理由

一站式解决 WKWebView 支持离线包，Ajax 请求和 Cookie 同步的问题 (基于 Ajax Hook 和 Cookie Hook)

**Comment by iblacksun** [comment]
### [KKJSBridge](https://github.com/karosLi/KKJSBridge)

[@享耳先森](https://github.com/iblacksun): 一站式解决 WKWebView 支持离线包、Ajax 请求和 Cookie 同步的问题 (基于 Ajax Hook 和 Cookie Hook)：
- 基于 MessageHandler 搭建通信层
- 支持 ajax hook 避免 body 丢失
- Cookie 统一管理
- WKWebView 复用
- 兼容 WebViewJavascriptBridge
