### ISSUE TITLE
历时五天用 SwiftUI 做了一款 APP，阿里工程师如何做的？

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1647]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/QgDSuTFjwFlXzhksfgmkIQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [历时五天用 SwiftUI 做了一款 APP，阿里工程师如何做的？](https://mp.weixin.qq.com/s/QgDSuTFjwFlXzhksfgmkIQ)

[@四娘](https://kemchenj.github.io)：淘宝内部尝试使用 SwiftUI 编写一个内部数据监测的 App，简单介绍了一下 SwiftUI 的数据流以及 UI 的自定义，文末对于 SwiftUI 给出了很正面的评价：

> 此项目在短短的 10 个工作日内就能完成，不得不说 SwiftUI 的开发效率真的惊人，虽然目前还有一些 Bug ，但是相信在未来，SwiftUI 会是 Apple 平台 UI 布局的解决办法，关于 SwiftUI 如何在淘系落地业务，还在持续探索中。
