### ISSUE TITLE
SwifterSwift

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#165]
https://github.com/SwifterSwift/SwifterSwift

**Comment by Damonvvong** [comment]
SwifterSwift 是一个用 Swift 编写的 Extension 的集合，涵盖了开发过程中大部分会用到的方法和函数，是一个不错的工具库。同时 SwifterSwift 大概有 SwiftStdlib Extensions、Foundation Extensions、UIKit Extensions、AppKit Extensions、CoreGraphics Extensions、CoreLocation Extensions、Misc. Extensions 等一系列分类。
