### ISSUE TITLE
RxSwift异步事件追踪定位工具的研发历程

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1653]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/h48jcWghZBysU0-0gH8bog

**Comment by raozhizhen** [comment]
当你使用 RxSwift 来实现一些简单的功能如发送一次网络请求、监听按钮点击事件等会让你的代码看起来非常直观简洁，但是如果你使用 RxSwift 实现了一个异步热流且在不同的类之间层层传递和加工转换之后代码的可读性就大大降低，甚至因为抓不到异步事件产生的堆栈而出现难以调试的情况。

为解决 RxSwift 的调试难题，作者通过阅读源码分析 RxSwift 操作符实现原理，然后利用 Swift 反射机制来 dump “Observable Link”，最后又根据 Swift 语言的函数派发机制和命名空间机制设计了一套安全高效的 hook Swift 的动态及静态方法的方案，通过这套 hook 方案完成了对流事件传递链上的关键函数的拦截处理从而顺利实现了精准定位和调试 RxSwift 中异步事件的目标。

**Comment by IsanHu** [comment]
请问这个工具有开源吗？

**Comment by ParsifalC** [comment]
> 请问这个工具有开源吗？

并没有开源，不过文章已经把 RxSwift 的操作符原理以及他所用的 Swift Hook 方案讲得很明白了，代码也贴了很多，可以尝试一步步自己写下哈。
