### ISSUE TITLE
iOS  13 + Xcode 11 device token 取值问题

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1655]
# 推荐收录

## 链接

https://info.umeng.com/detail?id=174&&cateId=1

**Comment by iblacksun** [comment]
### [iOS 13 APNS  Device Token 兼容问题](https://info.umeng.com/detail?id=174&&cateId=1)

iOS 13 修改了 `[NSData description]` 实现，导致友盟、个推等 Push SDK 有兼容性问题。`description` 方法其实是 debug 用的，希望开发者们谨慎使用。
