### ISSUE TITLE
Apple Push Notification Device Tokens

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1672]
# 推荐收录

## 链接

https://nshipster.com/apns-device-tokens

**Comment by iblacksun** [comment]
### [Apple Push Notification Device Tokens](https://nshipster.com/apns-device-tokens/)

[@享耳先森](https://github.com/iblacksun)：iOS 13 发布后，不少推送厂商都通知开发者们升级 SDK，`Mattt` 特地写文章介绍此次改动。

APNS `DeviceToken` 的类型其实是 Data，具体含义和格式是个黑盒，只是 App 拿到 Data 后需要提交给各自的服务端，这就涉及到将 Data 进行格式转换的问题。

iOS 7 之前 Foundation 没有 `NSData -base64EncodedStringWithOptions` 方法，开发者们发现可以使用 `NSData description` 方法输出再进行转换，而 `description` 其实是一个 Debug 方法，具体实现随时会改。
