### ISSUE TITLE
iOS卡顿监测方案总结

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1677]
# 推荐收录

## 链接

https://juejin.im/post/5d81ff45e51d453b1d648393

**Comment by ParsifalC** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/issues/776

这个和我们之前推过的那篇相比，不够细致和清晰。

**Comment by Damonvvong** [comment]
好，那我关掉拉
