### ISSUE TITLE
我是怎么慢慢变懒的(2) : Jenkins 全自动化

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#169]
http://answerhuang.duapp.com/index.php/2018/02/15/jenkins-2/

3年前的该系列第一篇：
http://answerhuang.duapp.com/index.php/2015/04/19/jenkins/

**Comment by Damonvvong** [comment]
大致看了一下。
感觉有一种「我配置了一个怎样的Jenkins全自动发布系统」
而不是如何配置or配置中遇到一些什么样问题

**Comment by lacklock** [comment]
我觉得里面的思路挺好的。我也没细看。最终意见是什么？ @Damonvvong

**Comment by Damonvvong** [comment]
作者根据自己的实际项目经验，写了一篇总结。大概讲了「我搭建了一个怎么样的 Jenkins 环境」以及在搭建过程中遇到了那些问题。
