### ISSUE TITLE
A Comprehensive Guide to All 120+ Settings URLs Supported by iOS and iPadOS 13.1

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1697]
# 推荐收录

## 链接

https://www.macstories.net/ios/a-comprehensive-guide-to-all-120-settings-urls-supported-by-ios-and-ipados-13-1/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B424

**Comment by iblacksun** [comment]
### 🐕 [A Comprehensive Guide to All 120+ Settings URLs Supported by iOS and iPadOS 13.1](https://www.macstories.net/ios/a-comprehensive-guide-to-all-120-settings-urls-supported-by-ios-and-ipados-13-1/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B424)

[@享耳先森](https://github.com/iblacksun)：iOS 的 `Settings` App 一直都支持通过 URL Scheme 的方式打开某一个子项，本文作者收集了 120+ 个在 iOS 13 下支持的 URL，大家可以浏览看是否有满足自己需求的点。需要注意的是：这些 URLs 随时可能在未来 iOS 版本中移除或被 Apple 审核团队以 Private API 为由拒绝上架。
