### ISSUE TITLE
Data Driven SwiftUI

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1698]
# 推荐收录

## 链接

https://mentalfaculty.github.io/LLVS/2019/09/25/data-driven-swiftui.html?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B424

**Comment by zvving** [comment]
文章介绍的是怎么在 SwiftUI 中使用 LLVS。

LLVS 是一种分布式，版本化， KV 存储框架，对应场景还比较小众，可以再观察看看
