### ISSUE TITLE
IBLinter，终于有人撸了个工具去检查 Interface Builder 了

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#17]
https://github.com/kateinoigakukun/IBLinter

**Comment by EyreFree** [comment]
+1

**Comment by kemchenj** [comment]
这个 Linter 我试用了之后，觉得还是比较一般，只是基于 xib 和 storyboard 本身去分析，没有基于代码去构建上下文，所以类名错误，Outlet 不存在之类的问题还是无法检查出来

所以这个就不加入周报了
