### ISSUE TITLE
Alternatives to protocols in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1704]
# 推荐收录

## 链接

https://www.swiftbysundell.com/articles/alternatives-to-protocols-in-swift

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Alternatives to protocols in Swift](https://www.swiftbysundell.com/articls/alternatives-to-protocols-in-swift/)

[四娘](https://kemchenj.github.io/)：Swift By Sundell 这周探讨的是 protocol 的替代品，虽然 Swift 称自己为 protocol-oriented，但实际上有很多问题都不适合使用 protocol，作者列举了一些例子并且提供了更好的解决方案。
