### ISSUE TITLE
ASCollectionView

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1721]
# 推荐收录

## 链接

https://github.com/apptekstudios/ASCollectionView

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [ASCollectionView - A SwiftUI port of UICollectionView](https://github.com/apptekstudios/ASCollectionView)

[@享耳先森](https://github.com/iblacksun)：开始使用 SwiftUI 了吗？那你应该看看这个库：Swift UI 下对 UICollectionView 和 UITableView 的实现，支持 `preloading` 和  `onAppear/onDisappear`，还支持 `UICollectionViewCompositionalLayout`。
