### ISSUE TITLE
New Diagnostic Architecture Overview

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1737]
# 推荐收录

## 链接

https://swift.org/blog/new-diagnostic-arch-overview/

**Comment by kemchenj** [comment]
### [Swift 5.2 新诊断框架](https://juejin.im/post/5dac17efe51d4524d6748831) [Offical Version](https://swift.org/blog/new-diagnostic-arch-overview/)

[@四娘](https://kemchenj.github.io/)：`error: type of expression is ambiguous without more context` 可能是大家最经常在 Swift 看到的编译错误，它很准确地描述了问题，但却对于解决问题毫无帮助。

在完成了 ABI 和 Module 稳定之后，Swift 团队终于有时间静下来优化**诊断系统**的体验，他们近日在博客里更新了诊断系统的重构方向以及思路，著名开发者[图拉鼎](https://weibo.com/1846569133/Ic2BSxNBh?type=comment#_rnd1572227803117)也在微博表示对于这次优化表示期待：

> 我记得我刚开始学编程时，当时学 C 语言，用的编译器是 GCC。当时 GCC 的 Diagnostic 做的很差，经常给出一些不知所云的错误提示。当时 Apple 用的也是 GCC，但很快就换成了 LLVM/Clang，后者的一大改进就是 Diagnostic。有理由相信这次 Apple 会做好 Swift 的 Diagnostic。
