### ISSUE TITLE
Announcing the pod merge plugin for Cocoapods!

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1739]
# 推荐收录

## 链接

https://swiftier.co/2019-10-17/announcing-cocoapods-pod-merge?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B427

**Comment by kemchenj** [comment]
### [Announcing the pod merge plugin for Cocoapods!](https://swiftier.co/2019-10-17/announcing-cocoapods-pod-merge)

[@四娘](https://kemchenj.github.io/)：在使用 Cocoapods 时一个常见的问题就是动态库数量的增加会大幅降低 App 的启动速度，解决方案有两个方向，其中一个是动态库合并。但之前动态库的合并基本上都需要大家手写脚本去完成，现在 Cocoapods 社区就发布了一个新的插件去简化这个过程：

```ruby
group "Networking"
  pod "AFNetworking"
  pod "SDWebImage"
end
```

只要编写动态库合并的声明文件，在 `pod install` 时插件就会自动完成动态库的合并，使用这种方式可以减少 13-30% 的启动时间，唯一美中不足的就是无法接入二进制库，必须以源码接入才可以。
