### ISSUE TITLE
Draft Proposal: Package Resources

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1740]
# 推荐收录

## 链接

https://forums.swift.org/t/draft-proposal-package-resources/29941?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B427

**Comment by iblacksun** [comment]
### 🐕 [Draft Proposal: Swift PM Package Resources](https://forums.swift.org/t/draft-proposal-package-resources/29941?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B427)

[@享耳先森](https://github.com/iblacksun)：Swift PM 终于要有正式的资源打包及加载方式了。这个提案的主要内容想解决 Swift PM 如何约定资源存储路径及各平台下如何用一致的代码进行加载。
