### ISSUE TITLE
Metric​Kit

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1741]
# 推荐收录

## 链接

https://nshipster.com/metrickit/

**Comment by raozhizhen** [comment]
[MetricKit](https://developer.apple.com/documentation/metrickit?language=objc) 是 iOS 13 中的一个新框架，用于收集 APP 的各项性能指标。诸如耗电，启动时长，交互耗时，磁盘使用等指标。
文章介绍了 MetricKit，也提供了一个收集 MetricKit 数据的自建 Web 服务方案。帮助你，提供更好的用户体验。
