### ISSUE TITLE
CI/CD现代史，从Jenkins到GitHub Actions

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1754]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/vyIr2Sl_aQU-_j_147LrVg

**Comment by nianran** [comment]
本文是一个 Q&A 的文章，文中内容大多是为了后续大会演讲做铺垫。
建议等会议结束之后文章发布串联一下视频，再做推荐。
