### ISSUE TITLE
More Interface Builder Tips And Tricks

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#176]
https://useyourloaf.com/blog/more-interface-builder-tips-and-tricks/?utm_campaign=iOS%2BDev%2BWeekly&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B340

话说我用xib ib 用的不多 =。= 大家觉得如何？

**Comment by lacklock** [comment]
内容还不错，就是总感觉在哪里看到过。不过这种文章总有人不知道的技巧，就放吧

**Comment by ParsifalC** [comment]
这类似Xib Top ten tricks之类的有挺多的，我感觉可以统一放一次
