### ISSUE TITLE
Best resources for Advanced iOS Developer (Swift)

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#1766]
# 推荐收录

## 链接

[Best resources for Advanced iOS Developer (Swift)](https://medium.com/flawless-app-stories/best-resources-for-advanced-ios-developer-swift-ade30374593d)

**Comment by raozhizhen** [comment]
作者花了几年时间，收集整理的，对于他很有帮助的 iOS &Swift 文章和视频。涉及架构、组件化、面向协议、调试、SwiftUI 等多个分类。收藏它们并学习，对你会很有帮助。
