### ISSUE TITLE
SDWebImageSwiftUI

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1767]
# 推荐收录

## 链接

https://github.com/SDWebImage/SDWebImageSwiftUI

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI)

[@四娘](https://kemchenj.github.io/)：SDWebImage 的 SwiftUI 版，基于原版的 SDWebImage 进行封装，之前的生态也可以无缝对接过来，例如各种图片样式的支持等等。
