### ISSUE TITLE
Swift.org - Swift Numerics

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1769]
# 推荐收录

## 链接

https://swift.org/blog/numerics/

**Comment by iblacksun** [comment]
### [Swift.org - Swift Numerics](https://swift.org/blog/numerics/)

[@享耳先森](https://github.com/iblacksun)：Swift Standard Library 成员 Steve Canon 创建的开源项目，提供数学计算相关 API，弥补标准库中的不足。
