### ISSUE TITLE
一个把iOS app转化成安卓app的工具

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#177]
https://www.myappconverter.com/?utm_campaign=iOS%2BDev%2BWeekly&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B340#how-it-works

https://blog.myappconverter.com

只是个工具的官网和博客文章，我看看能不能深入看看挖掘一下

**Comment by lacklock** [comment]
我觉得这条新闻现在跟进太早了，他们才刚开始孵化。说不定过阵子就死了，后面做大了再看吧。
