### ISSUE TITLE
Android vs. iOS App Development: Which Is the Better Choice for Your Business in 2019?

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1770]
# 推荐收录

## 链接

https://medium.com/better-programming/android-vs-ios-app-development-which-is-the-better-choice-for-your-business-in-2019-933b20e4d9b8

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
内容老生常谈，没有干货，不建议录入。
