### ISSUE TITLE
Flutter 中文文档：使用 Mockito 模拟依赖关系

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1773]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/e9orvqzdLmFwMXDVLUtcLw

**Comment by raozhizhen** [comment]
本篇教程介绍了 Mockito 包的基本用法，模拟 Web 服务或数据库，根据条件返回特定结果，解决直接依赖 Web 服务或数据库的诸多不便。
访问线上服务或数据库会拖慢测试执行效率。
原本可以通过的测试可能会失败，因为 web 服务或数据库可能会返回不符合预期的结果。
使用线上 web 服务或数据库来测试很难覆盖全所有可能成功或失败的场景。
