### ISSUE TITLE
Message-ID and Mail.app Deep Linking on iOS and macOS

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1781]
# 推荐收录

## 链接

https://nshipster.com/message-id/

**Comment by kemchenj** [comment]
这篇我应该没办法按时完成评语，放到下周吧。

**Comment by kemchenj** [comment]
### [Message-ID and Mail.app Deep Linking on iOS and macOS](https://nshipster.com/message-id/)

[四娘](https://kemchenj.github.io/)：这周 NSHisper 给我们带来的是 Deep Linking 相关的内容，讲解 iOS / macOS 里 Mail.app 使用链接跳转时如何编码链接信息，避免信息泄漏。
