### ISSUE TITLE
带你入门 DissCode，从而攻克大厂面试题！

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1788]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/lcuK0fGDmnKKGbHC9XRX0w

## 推荐理由

一言不合就写个网站

**Comment by Damonvvong** [comment]
我大致看了一下，网站的完成度稍微有点低。目前各 LeetCode.cn 还有点差距。

个人建议再观察一段时间推比较合适。所以我先关闭了~
