### ISSUE TITLE
Foundation 里竟然有原生的自然语言处理方案

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#18]
https://www.appcoda.com/natural-language-processing-swift/?utm_campaign=Revue%20newsletter&utm_medium=Newsletter&utm_source=AppCoda%20Weekly

比较瞩目的是里面的分词功能，网上搜出来的基本都是用 CFStringTokenizer，几乎没人提到过这个处理方案

**Comment by iblacksun** [comment]
iOS 11 发布后我研究过，对中文能实现分词，但做不到词性标注。
