### ISSUE TITLE
使用 VSCode debug CocoaPods 源码和插件

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#1810]
# 推荐收录

## 链接

[使用 VSCode debug CocoaPods 源码和插件](https://github.com/X140Yu/debug_cocoapods_plugins_in_vscode/blob/master/duwo.md)

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
文章内容仅限安装配置插件，主流 iOS dev 也缺乏 debug cocopods 的使用场景，不建议收录。
