### ISSUE TITLE
技术文章配图指南

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1819]
# 推荐收录

## 链接

https://draveness.me/sketch-and-sketch

**Comment by iblacksun** [comment]
### [技术文章配图指南](https://draveness.me/sketch-and-sketch)

[@享耳先森](https://github.com/iblacksun)： 如果你是技术博主，相信都遇到过如何给文章配图的困惑，本文从配图的原则、工具、实践等方面进行论述，建议阅读。
