### ISSUE TITLE
MessageViewController

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#182]
https://github.com/GitHawkApp/MessageViewController

**Comment by Damonvvong** [comment]
MessageViewController 是 Swift 版本的 SlackTextViewController，是 slack 聊天界面的一个可交互的基础UI控件。MessageViewController 的功能完成度和代码质量都特别高。如果有类似 slack 聊天界面的需求或者想学习 slack 聊天界面的实现效果，不妨看一下 MessageViewController。
