### ISSUE TITLE
XCTKVOExpectation for native Swift key paths

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#183]
https://oleb.net/blog/2018/02/xctkvoexpectation-swift-keypaths/

**Comment by mmoaay** [comment]
文章介绍了 XCTest 测试框架新增 API [XCTKVOExpectation](https://developer.apple.com/documentation/xctest/xctkvoexpectation) 的一种使用方式，作者封装了 KVOException 并对 XCTestCase 进行扩展，以方便开发人员完成测试用例的编写。另外，作者已经把所有相关代码都开源在了 [Github](https://gist.github.com/ole/efe13925abd8e8ea2c7926e9a3131abf) 上。
