### ISSUE TITLE
纷争再起：Flutter-UI绘制解析

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#1832]
# 推荐收录

https://juejin.im/post/5c866cf6f265da2de165d89d

[此处替换为具体的资源地址]

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [纷争再起：Flutter-UI绘制解析](https://juejin.im/post/5c866cf6f265da2de165d89d)

[@四娘](https://kemchenj.github.io)：作者通过生动形象的方式跟我们讲述了 Flutter 的 Widget 树实现，如何通过轻量级的视图树达成高效的视图树重建，与我们熟知的 View 进行协作完成最终渲染。
