### ISSUE TITLE
bow

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#1836]
# 推荐收录

## 链接

[https://github.com/bow-swift/bow](https://github.com/bow-swift/bow)

## 理由

为 Swift 添加更多 `Typed Functional Programming` 支持。

## 推荐人信息

EyreFree

**Comment by iblacksun** [comment]
对初学者来说理解这些概念难度比较高，实际使用价值也不大，不推荐了。
