### ISSUE TITLE
iOS加载webp图片的更好方案

### ISSUE THREAD

**Issue by robinmo** [SwiftOldDriver/iOS-Weekly#1840]
# 推荐收录

## 链接

[https://juejin.im/post/5df0a172518825126d5a2610]

## 理由

[在iOS **webview**中目前网上较多的方案是拦截，但这太不优雅了
- 1.文中描述了网上的传播较为广泛的处理方案
- 2.笔者从OSS最简单低成本的方式完成了较为平滑的iOS中webview加载webp图片
- 3.笔者文风也和传统的技术文章迥异，比较有意思
- 4.好吧，原谅我自吹自擂😂]

## 推荐人信息
掘金：落魄诗人码农
如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by li6185377** [comment]
利用 OSS 在线转为 JPG 格式？

**Comment by robinmo** [comment]
> 利用 OSS 在线转为 JPG 格式？

不，是放参数，服务器直接转化。就是OSS已经有这个功能了，放了格式参数就直接返回指定合适的图

**Comment by looping** [comment]
看了下文章内容稍微有点初浅，只是作了简单调研介绍，期待能补充更详细的实践总结，那样读者会有更深的体会，效果会更好。

**Comment by robinmo** [comment]
> 看了下文章内容稍微有点初浅，只是作了简单调研介绍，期待能补充更详细的实践总结，那样读者会有更深的体会，效果会更好。谢谢！

ok
