### ISSUE TITLE
谈谈 dart_objc 混合编程引擎的设计

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1847]
# 推荐收录

## 链接

http://yulingtianxia.com/blog/2019/11/28/DartObjC-Design/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by SatanWoo** [comment]
没啥大的价值，下周讲那个符号那篇
