### ISSUE TITLE
Objective-C Direct Methods - NSHipster

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1856]
# 推荐收录

## 链接

https://nshipster.com/direct/

**Comment by raozhizhen** [comment]
[Objective-C Direct Methods](https://nshipster.com/direct/)

Direct Methods 是 Objective-C 上新的方法调用机制(最早可能出现在 Xcode 11.x 上)，调用 Direct Methods 时，它直接调用其基础实现，而不是通过 objc_msgSend。由于 objc_msgSend 在优化上已经做了很多，Direct Methods 并不会有太大的性能优势。实际的优点：Direct Methods 是私有方法，并不能被外部访问，也可以防止被 Objective-C 运行时动态的调用。不过根据实施此功能的 Pierre 所说，此优化的主要好处是减少了代码大小。
