### ISSUE TITLE
当Swift 遇上 JS

### ISSUE THREAD

**Issue by hhfa008** [SwiftOldDriver/iOS-Weekly#1858]
# 推荐收录
最近看了ECMAScript 的文档，JS有些设计可以借鉴。
JS的对象分两种：可执行和不可执行。
JS 的方法是一个可执行JS 的对像。
const sum = new Function('a', 'b', 'return a + b');
console.log(sum(2, 6));
对应到Swift，是什么场景呢？
Swift 5.x 加了两个特性:
@dynamicCallable
@dynamicMemberLookup
利用这两个特性，可以模拟出JS的语法。

## 链接

[https://xiaozhuanlan.com/topic/9248706153]

## 理由

灵活运用语法糖，写出优雅框架。

## 推荐人信息

微信号hhfa008

**Comment by ParsifalC** [comment]
这个尝试挺有意思，是一个蛮不错的点。不过出于以下两点考虑，暂不收录本篇文章。

- 内容还比较单薄，以一篇高质文章的角度来看，还有所欠缺
- 付费专栏对于我们读者门槛较高，我们收录的要求也会更高
