### ISSUE TITLE
Swift-NIO，用 Swift 实现的一个事件驱动非阻塞的 Web 通讯框架

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#187]
https://github.com/apple/swift-nio

**Comment by kemchenj** [comment]
贴点相关资料：

[try! Swift 的现场照片](https://twitter.com/NatashaTheRobot/status/969090290702172160)，苹果极少在社区的技术大会上发布东西，这次是在 try! swift 大会上发布的，一定程度上表明了苹果对于 Swift 的器重以及对于开源的态度

[社区大 V Jesse 吐槽这个库的依赖](https://twitter.com/jesse_squires/status/969271531137155073)，因为这个库没有用 libdispatch(GCD)，foundation，swiftserver/http 这几个库，Jesse 觉得没必要重新造轮子，这样会造成社区分裂。

但已经有人出来解释了，libdispatch 跟 Foundation 是有用到的，但 Foundation 里一部分功能重写了，因为作者觉得 Foundation 在平台间的实现差异太大，容易造成平台间性能差异。并且组件也不好替换，例如 Foundation 里的 SSL 是使用了 OpenSSL，不容易拆分出来。

**Comment by Damonvvong** [comment]
苹果官方在[try! Swift](https://twitter.com/NatashaTheRobot/status/969090290702172160)上发布了Swift-NIO，它是一个事件驱动的非阻塞的网络框架，用来写高性能网络应用。
苹果在 Server-Side 方面努力，看得出对 Swift 的重视和对它的期望都很高。
