### ISSUE TITLE
KeyedCodable

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#1870]
# 推荐收录

## 链接

https://github.com/dgrzeszczak/KeyedCodable

**Comment by kemchenj** [comment]
### [KeyedCodable](https://github.com/dgrzeszczak/KeyedCodable)

[@四娘](https://kemchenj.github.io)：KeyedCodable 是一个简化 Codable 逻辑的库，之前一些自定义的逻辑都需要通过手写 decode 和 encode 去完成，例如嵌套逻辑，默认值和自定义编码策略等，现在使用这个库就即可自动完成这部分逻辑。
