### ISSUE TITLE
多地图源业务向地图控件开发思路

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1871]
# 推荐收录

## 链接

https://juejin.im/post/5e01c75c51882512766f4cf0
https://juejin.im/post/5e01c8986fb9a0161d743ce2
https://juejin.im/post/5e01c953518825124768895b
https://juejin.im/post/5e01ca85f265da33e347fd59
https://juejin.im/post/5e01cb76f265da339260c753

## 理由

根据实际开发业务场景，谈论一些设计和重构的想法

**Comment by iblacksun** [comment]
### [系列文章：多地图源业务向地图控件开发思路](https://juejin.im/post/5e01c75c51882512766f4cf0)

[@享耳先森](https://github.com/iblacksun)：如果你在开发地图相关  App，应该知道服务商地图质量各有长短，所以，最好是能适配多种地图，让用户选择。

这系列文章介绍了如何对地图服务进行抽象，可以方便的切换地图服务，同时在地图之上封装了统一的  UI  交互。
