### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1893]
# 推荐收录

## 链接

https://github.com/johnsundell/publish

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Publish](https://github.com/johnsundell/publish)

[@四娘](https://kemchenj.github.io)：Publish 是一个使用 Swift 编写的静态网站生成器，支持主题和插件等自定义功能，前身是 [SwiftBySundell](https://swiftbysundell.com) 这个网站的生成工具，现在作者整理后将它开源了出来。
