### ISSUE TITLE
SwiftUI 官方英文教程译文

### ISSUE THREAD

**Issue by WillieWangWei** [SwiftOldDriver/iOS-Weekly#1897]
# 推荐收录

SwiftUI 官方英文教程译文

## 链接

https://github.com/WillieWangWei/SwiftUI-Tutorials

## 理由

SwfitUI 已经公布半年了，开始逐渐有大批开发者尝试学习和使用。此项目翻译了共十篇官方的 SwfitUI 教程，在保留官方的文字内容、配图、代码外，还进行了细微的优化。

这个项目旨在帮助更多开发者迅速入门，快速使用 SwfitUI 进行开发，并共同解决实际遇到的问题，同时推进 SwfitUI 和 Combine 两大框架在国内的传播，让 iOS 开发更加简洁、现代化。

## 推荐人信息

[@Willie](https://github.com/WillieWangWei)

**Comment by WillieWangWei** [comment]
@zvving 你好，谢谢收录我的推荐。但是能否将这个推荐放在最新一期的周报中？现在似乎是收录在了2020.01.13 中，但是这一期已经 release 挺久了😂。

**Comment by zvving** [comment]
@WillieWangWei 已经修正，感谢提醒
