### ISSUE TITLE
[译]为什么你的 APP 在 Sketch 上看起来更好: 探索 Sketch 和 iOS 的渲染差异

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#190]
https://juejin.im/post/5a9572575188257a61326630

**Comment by iblacksun** [comment]
谁了解 Sketch 49 新增的交互设计？要不要结合讲下？

**Comment by lacklock** [comment]
@iblacksun 49的新增的原型设计功能和这个没关系。那我单独加一条sketch 49 的把
