### ISSUE TITLE
Binary Frameworks in Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1901]
# 推荐收录

## 链接

https://pspdfkit.com/blog/2018/binary-frameworks-swift/

**Comment by kemchenj** [comment]
### [Binary Frameworks in Swift](https://pspdfkit.com/blog/2018/binary-frameworks-swift)

[@四娘](https://kemchenj.github.io)：PSPDFKit 从一个服务商的角度介绍了 Swift 二进制 SDK 分发的细节，包括了 ABI 稳定的含义和开发内容，以时间线的形式给我们介绍了整个开发过程。
