### ISSUE TITLE
BetterCodable

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1905]
# 推荐收录

## 链接

https://github.com/marksands/BetterCodable

**Comment by iblacksun** [comment]
### [BetterCodable](https://github.com/marksands/BetterCodable)

[@享耳先森](https://github.com/iblacksun)：Swift 4.0 开始引入 `Codable` 解决数据到模型转换的问题，但实际使用过程中经常需要自定义 `init(from decoder: Decoder) throws` 方法，`BetterCodable` 结合 Swift 5.1 引入的 `Property Wrappers` 来解决这个问题。
