### ISSUE TITLE
自荐两篇关于Swift Intermediate Language的文章

### ISSUE THREAD

**Issue by kingnight** [SwiftOldDriver/iOS-Weekly#1916]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/UQksScr_LZ1n7wLAVjzEMg
https://mp.weixin.qq.com/s/KHvWSsvKNxJq9IwAsZu4qw

## 理由

通过学习Swift Intermediate Language，理解Swift的语法特性和编译器内部语言的实现细节，解决开发过程中遇到的实际问题，解答一些表面上似懂非懂的困惑

**Comment by ParsifalC** [comment]
感谢推荐~我们会在年后第一期周报中处理。

**Comment by iblacksun** [comment]
### 🐢 [系列文章 - Swift Intermediate Language 初探](https://mp.weixin.qq.com/s/UQksScr_LZ1n7wLAVjzEMg)

[第二篇 - 真实案例引发的 iOS 底层实现窥探](https://mp.weixin.qq.com/s/KHvWSsvKNxJq9IwAsZu4qw)

[@享耳先森](https://github.com/iblacksun)：Swift 是构建在 LLVM 上，使用 LLVM 中间表示(IR) 和 LLVM 不同后端生成机器语言。除此之外，Swift 编译器在生成 IR 之前，还设计了一门新的高级中间语言 `Swift Intermediate Language`，简称 `SIL`，SIL 会对 Swift 进行高级别的语意分析和优化。

当你遇到一些无法理解的表面现象，没有办法通过文档或者前人经验解读问题的实质，想要尝试探究编程语言背后的实现细节，那么就需要跨越语言本身的了解，向下去专研编译器的实现细节。系列文章使用项目中实际遇到的一个真实案例，从一个具体的 `UITableView` 实现的例子引出，试图通过 `SIL` 这个中间语言，探究 Swift 背后的一些实现细节，帮助我们理解一些问题。

> 推荐人：[kingnight](https://github.com/kingnight)
