### ISSUE TITLE
Pure SwiftUI

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1926]
# 推荐收录

## 链接

https://github.com/CodeSlicing/pure-swift-ui

## 理由

**Comment by raozhizhen** [comment]
[Pure-Swift-UI](https://github.com/CodeSlicing/pure-swift-ui)

PureSwiftUI 是一个辅助 SwiftUI 的工具类，用于优化编写 SwiftUI 的体验。
- 删除了大量的显示参数，通过更能表达含义的接口，将参数配置组合起来，使代码结构更清晰。
- 只要你的变量是 Int，Double，Float，或者 CGFloat，PureSwiftUI 上都能混合着使用。
- 修改 geometryReader 的备份 GeometryProxy，不影响 geometryReader 布局。
- offsetToPosition 修饰符，可以将 View 的位置设置为任何坐标空间内的绝对位置。
- 条件修饰符替代三目运算符，根据状态有条件地对视图进行样式配置。
- SF Symbols 使用常量，替代字符串调用。
