### ISSUE TITLE
iOS微信内存监控

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#193]
https://mp.weixin.qq.com/s/r0Q7um7P1p2gIb0aHldyNw

**Comment by raozhizhen** [comment]
本文非常详细的从数据收集、数据存储、数据上报，页面展现、降低误判几个方向，讲解如何实现线上内存监控及 FOOM 导致的系统强杀上报。

FOOM 是指 APP 在前台因消耗内存过多引起系统强杀，微信每天 FOOM 次数与登录用户数比例接近 3%，同期 crash 率 1% 不到。为此，微信开发此线上内存监控工具，FOOM 率由 17 年年初 3%，降到目前 0.67%，效果显著。
