### ISSUE TITLE
为什么 SwiftPM 的开发进度比 Cocoapods 慢那么多？

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1930]
# 推荐收录

## 链接

https://artsy.github.io/blog/2018/12/21/why-is-swiftpm-taking-so-long/

**Comment by iblacksun** [comment]
### 🐢 [为什么 SwiftPM 的开发进度比 Cocoapods 慢那么多？](https://artsy.github.io/blog/2018/12/21/why-is-swiftpm-taking-so-long/)

[@享耳先森](https://github.com/iblacksun)：CocoaPods 开发者 [Orta Therox](https://github.com/orta) 写了篇文章分析为什么 SwiftPM 开发速度比 CocoaPods 慢？总的来说，两者所关注的层级不一样：SwiftPM 需要关注全链路的编译，需要支持 Linux 等系统，脱离了 Xcode；而 CocoaPods 是基于 Xcode 之上的，其产物是给 Xcode 用的，只需关注 macOS 平台。
