### ISSUE TITLE
Swift-Kuery-ORM

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#194]
https://github.com/IBM-Swift/Swift-Kuery-ORM

**Comment by lacklock** [comment]
师出名门，但是ORM影响很广，不知道又没人敢先吃这只螃蟹。

**Comment by iblacksun** [comment]
IBM 新开源了 `Swift-Kuery-ORM`，构建于 [Swift-Kuery](https://github.com/IBM-Swift/Swift-Kuery) 之上，可以通过插件连接 `PostgreSQL`、`SQLite`、`MySQL`。
