### ISSUE TITLE
swift-checkit

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1940]
# 推荐收录

## 链接

https://github.com/karwa/swift-checkit/

## 理由

当你遵循 Collection 协议自定义了一个集合类型之后，并不确定实现得是否正确，此时就应该通过测试去进行验证，但这些基本协议的测试用例实际上都一样，没必要每次都重新造轮子。

这个库就是为此而生的，面向协议的接口抽象了测试用例，一行代码即可完成协议 Conformance 的测试😆。

**Comment by iblacksun** [comment]
### [swift-checkit](https://github.com/karwa/swift-checkit/)

这个库起源于作者遇到一个 bug：自定义了一个  `collection`，但对 index 处理和 SDK  行为不一致。所以作者写了这个库，面向协议的接口抽象了测试用例，一行代码即可完成协议 Conformance 的测试。
