### ISSUE TITLE
ControlRoom

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#1944]
# 推荐收录

## 链接

[https://github.com/twostraws/ControlRoom](https://github.com/twostraws/ControlRoom)

## 理由

Control Room is a macOS app that lets you control the simulators for iOS, tvOS, and watchOS – their UI appearance, status bar configuration, and more. It wraps Apple’s own simctl command-line tool, so you’ll need Xcode installed.

Demo video: [https://twitter.com/twostraws/status/1227619436187803648](https://twitter.com/twostraws/status/1227619436187803648)

## 推荐人信息

EyreFree

**Comment by kemchenj** [comment]
### [ControlRoom](https://github.com/twostraws/ControlRoom)

基于 simctl，让你可以通过 GUI 来便捷地控制模拟器，例如发送推送通知，切换夜间模式等。
