### ISSUE TITLE
A History of Ruby inside iOS Development

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#196]
https://medium.com/xcblog/a-history-of-ruby-inside-ios-development-427b5a09f91e

**Comment by kemchenj** [comment]
### [Ruby 对于 iOS 开发发展的影响](https://medium.com/xcblog/a-history-of-ruby-inside-ios-development-427b5a09f91e)

今年是 Ruby 这门语言诞生的 25 周年，作者特别写了一篇文章介绍了 iOS 开发工具链发展史里 Ruby 发挥的作用，讲述 Cocoapods，Fastlane 等等这些工具当时选择 Ruby 的理由。
