### ISSUE TITLE
zld

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#1961]
# 推荐收录

## 链接

[https://github.com/michaeleisel/zld](https://github.com/michaeleisel/zld)

## 理由

A faster version of Apple's linker

Apple's approach is a very reasonable one, using C++ with STL data structures. However, there are a number of ways in which zld has sped things up, for instance:

Using Swiss Tables instead of STL for hash maps and sets
Parallelizing in various places (the parsing of libraries, writing the output file, sorting, etc.)
Optimizations around the hashing of strings (caching the hashes, using a better hash function, etc.)

## 推荐人信息

[SketchK](https://github.com/SketchK)

**Comment by kemchenj** [comment]
### [zld](https://github.com/michaeleisel/zld)

[@四娘](https://kemchej.github.io/)：一个更快的 linker。在大型项目里增量编译 link 阶段的耗时占用非常大，这个项目在 Apple 版本的基础上改为使用更加高效的 Hash 实现，增加任务的并行处理，Benchmark 显示 link 时间比原本缩短了 40% 左右。

> 推荐人：[SketchK](https://github.com/SketchK)
