### ISSUE TITLE
Vue.js - The Documentary

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1963]
# 推荐收录

## 链接

https://www.bilibili.com/video/av92525472/

## 理由

以 Vue.js 诞生过程为主题的纪录片。

**Comment by iblacksun** [comment]
### [Vue.js - The Documentary，Vue.js 纪录片，配中文字幕](https://www.bilibili.com/video/av92525472/)

[@享耳先森](https://github.com/iblacksun)：纪录片总长 30 分钟，记录 Vue 的发展过程。
尤雨溪在片中讲了 Vue 名字由来，介绍了关键时间节点的发展过程，也和 `Angular` `React` 做了些对比。
