### ISSUE TITLE
纪录Vue.js尤雨溪 - 中英CC字幕 - Honeypot呈现

### ISSUE THREAD

**Issue by zvving** [SwiftOldDriver/iOS-Weekly#1967]
# 推荐收录

## 链接

https://www.bilibili.com/video/av91714806

## 理由

记录 Vue.js 的创建过程

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
与 #1963 重复了
