### ISSUE TITLE
Thoughts on rewriting the Messenger App by Facebook.

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#1989]
# 推荐收录

## 链接

https://dmtopolog.com/fb-rewriting-messenger/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
主要是发对很多人借机推销自己的观点，有用的信息不多。不做推荐
