### ISSUE TITLE
Advanced debugging with Xcode

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#199]
https://medium.com/@vin.pradeilles/advanced-debugging-with-xcode-5e6c8dabd311

**Comment by ParsifalC** [comment]
看了下这篇文章，感觉没什么有新鲜的东西啊？如果要转 Xcode 调试相关的，个人感觉直接转一篇国内的感觉会更合适一些。

**Comment by mmoaay** [comment]
看了感觉确实比较基础，建议不推荐
