### ISSUE TITLE
WWDC 2020 改为线上举行

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#1992]
# 推荐收录

## 链接

https://developer.apple.com/news/?id=03132020a

## 理由

> This June, WWDC20 brings a completely new online experience to millions of talented and creative developers around the world.

**Comment by iblacksun** [comment]
### [WWDC20  改成线上举行](https://developer.apple.com/wwdc20/)

受新冠疫情影响，苹果宣布一年一度的  WWDC 大会改为线上举行，具体日期及形式还未定，只指明将在六月举行。
