### ISSUE TITLE
AppStore 审核速度受疫情影响

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#1998]
# 推荐收录

## 链接

https://developer.apple.com/cn/news/?id=03142020a

**Comment by iblacksun** [comment]
### [App Store 对 COVID-19 相关应用的审核要求](https://developer.apple.com/cn/news/?id=03142020a)

[@享耳先森](https://github.com/iblacksun)：苹果此前发出通知：为了保证数据源的可靠性，要求 COVID-19 相关应用必须以机构身份提交。同时，正常的审核流程可能需要比较长的时间，鼓励 COVID-19 相关应用在提交审核时发起「TimeSensitive Event」请求优先审核。
