### ISSUE TITLE
如何获得微信小游戏跳一跳源码

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#20]
https://www.v2ex.com/t/419352

**Comment by EyreFree** [comment]
这篇是 Android 的，iOS 貌似没看到对等方案，[捂脸]

所以需要换成这一篇么：(微信跳一跳可以直接更改分数，POST 请求没有校验「附完整代码&教程&讨论」)[https://gist.github.com/feix/6dd1f62a54c5efa10f1e1c24f8efc417]

**Comment by lacklock** [comment]
我已经添加了
