### ISSUE TITLE
手淘 App 如何落地 Swift ？一边探索实践，一边“打怪升级”

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2012]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/_iweRWQCjnoASCmUAKHDFA

**Comment by ParsifalC** [comment]
结合这篇一起看：https://mp.weixin.qq.com/s/oHGkoGzhMs-l8TX6t0831w
