### ISSUE TITLE
Repeat - Modern alternative to NSTimer in Swift

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#202]
https://github.com/malcommac/Repeat

**Comment by raozhizhen** [comment]
Swift 中的 Timer 需要提供 @objc 修饰的方法，这让人并不愉快，更别提 Timer 本身的诸多问题， 如[强引用 target](https://github.com/100mango/zen/blob/master/iOS%E5%A4%AF%E5%AE%9E%EF%BC%9AARC%E6%97%B6%E4%BB%A3%E7%9A%84%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86/%23iOS%E5%A4%AF%E5%AE%9E%EF%BC%9AARC%E6%97%B6%E4%BB%A3%E7%9A%84%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86.md)，依赖 Runloop，不支持闭包等。

你需要一个更为优雅的计时器， [Repeat](https://github.com/malcommac/Repeat) 基于 GCD 的 DispatchSource，实现一个 Swift 风格的轻量级计时器。

原理：DispatchSource 用于监听系统底层事件的发生，DispatchSourceTimer 会创建 Timer 事件对应的 dispatch source，然后给这个 source 指定一个闭包，指定一个 Dispatch Queue。当 source 监听到  Timer 事件时，就会将该闭包自动加到 queue 中执行。
