### ISSUE TITLE
What’s new in Swift 5.2 - Swift 5.2 的几个新特性

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2036]
# 推荐收录

## 链接

小集合翻译版：
https://mp.weixin.qq.com/s/U-BH2qfLrnnlbt3F8qx2sQ

英文原版
https://www.hackingwithswift.com/articles/212/whats-new-in-swift-5-2

**Comment by ParsifalC** [comment]
这个上周讲 5.2 发布的时候提过两个重要的特性了，这期就不重复推了。
