### ISSUE TITLE
区块链交易中心被黑

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#204]
https://mp.weixin.qq.com/s/z39hBMif1bQJeb4Ar_zRAw

一则区块链新闻，黑客手段很有意思

**Comment by mmoaay** [comment]
币圈本周最佳！虽然只是**币安 Binance 交易所**被黑，并不是 BTC 本身的缺陷，但是比较讽刺的是：币圈和链圈都在一边吹捧去中心化，一边又通过中心化的交易所炒币。真可以说是嘴上笑嘻嘻，心里 MMP …
