### ISSUE TITLE
唱唱反调：风口上的技术不要盲目追

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2043]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/8HyCsZTuiXpvNoV453vLQw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by aaaron7** [comment]
这文章没啥内容。感觉不用推荐了 @ParsifalC

**Comment by ParsifalC** [comment]
> 这文章没啥内容。感觉不用推荐了 @ParsifalC

ok
