### ISSUE TITLE
必看|阿里集团内如何进行Flutter体系化建设？

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2044]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s?__biz=MzAxNDEwNjk5OQ==&mid=2650406081&idx=1&sn=f4015647138b2b26c68b3e57c6a39c1f&chksm=839534d9b4e2bdcfa94ce2b6b22ae30c8ac18494d76afb595cf078c86cd51e2726ccb956e826&scene=0&xtrack=1&rd2werd=1#wechat_redirect

**Comment by ParsifalC** [comment]
标题不同，但内容大部分重复。
