### ISSUE TITLE
网页版 iWork 里使用 Objc + WebAssembly

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2058]
# 推荐收录

## 链接

https://twitter.com/lrz/status/1250455566213877760

## 理由

苹果员工在 Twttier 透露，最近上线的网页版 iWork 10.0 里，将原生 App 的 C++ / Objc 代码改为使用 WebAssembly 编译，直接使用到网页上。

是的，就是 Objc + WebAssembly！！！

**Comment by looping** [comment]
发现这篇把 Twitter 内容整理了下，比较清晰，我把它换成标题链接了 https://mjtsai.com/blog/2020/04/17/iwork-10-in-webassembly/
