### ISSUE TITLE
书：《Continuous Delivery for Mobile with Fastlane》

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#206]
https://doronkatz.com/fastlane

**Comment by iblacksun** [comment]
你还在手动打包、上传 App 吗？是时候试试 `Fastlane` 了。本书将带你了解 `Fastlane` 的方方面面：如证书管理、TestFlight 管理、如何与现有的 `CI` 系统结合。另外，`Fastlane` 的 [官方文档](https://docs.fastlane.tools) 也是非常好的快速上手资源。
