### ISSUE TITLE
Flutter 究竟是如何渲染的？

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2064]
# 推荐收录

## 链接

https://www.jianshu.com/u/6663b66c3df3

**Comment by raozhizhen** [comment]
是不是链接贴错了

**Comment by raozhizhen** [comment]
https://juejin.im/post/5e931cd0e51d4546f5790806

**Comment by raozhizhen** [comment]
本文从原理层面讲解 Flutter 渲染架构、渲染策略及渲染工作流水线。文章简单易懂，配合作者的另一篇文章 [iOS 浅谈GPU及“App渲染流程”](https://www.jianshu.com/p/8b0572f2c23a) 阅读，能比较快的对 Flutter 的渲染原理有一定了解。
