### ISSUE TITLE
Contact Tracing

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2067]
# 推荐收录

## 链接

https://nshipster.com/contact-tracing/

**Comment by iblacksun** [comment]
### 🐢[Contact Tracing](https://nshipster.com/contact-tracing/)

[@享耳先森](https://github.com/iblacksun)：为应对 COVID-19，苹果和谷歌宣布将在未来几个月内部署联系人追踪功能，声明中两家公司分享了这一技术的规范草案。在这篇文章中，[Matt](https://nshipster.com/authors/mattt/) 介绍了是苹果公司提出的 ContactTracing 框架，简单来说：ContactTracing 会为设备生成随机代码，利用蓝牙技术进行广播并记录所有近期接触过的设备。当某个用户被确诊了，卫生机构将请求得到 Ta 的随机码并进行登记，设备会间隔的向卫生机构进行比对，万一与名单中的设备接触过则提醒用户尽早需求医治。
