### ISSUE TITLE
Swift Logging

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2068]
# 推荐收录

## 链接

https://nshipster.com/swift-log/

**Comment by kemchenj** [comment]
### [Swift Logging](https://nshipster.com/swift-log/)

[@四娘](https://kemchenj.github.io/)：当 App 或者服务上线之后，出了问题最有效的 Debug 手段之一就是查看日志，那么该如何构建一套可靠的日志系统呢？这周 NSHisper 带来的是 swift-log 的介绍，推荐感兴趣的同学阅读。
