### ISSUE TITLE
Cross-Pollination

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2079]
# 推荐收录

## 链接

https://nshipster.com/cross-pollination/

**Comment by raozhizhen** [comment]
有很多好想法，从被批评到整合进苹果产品中，如：
- Windows 上的应用程序切换  ⌥⇥（macOS 上 ⌘⇥）
- Android 的黑暗模式（已在 iOS 13 中添加）
- Java 和其他语言的泛型（Swift 的核心功能， 后来添加到 Objective-C）
- JSX 风格的 dsl 声明性 UI（SwiftUI 中的函数构建器）
但在苹果公司这么做之前，为什么我们认为这些好主意是异端的？如果你将竞争技术的存在，视为善恶斗争，自豪的去宣布”Pure Swift”或“100％ 无 JavaScript”时，如果没有通过一系列的权衡来评估解决方案，那只是一种效忠，这种效忠，并不能让你很好的完成所有的工作。
