### ISSUE TITLE
@main: Type-Based Program Entry Points

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2080]
# 推荐收录

## 链接

https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md

## 理由

Swift 5.3 发布

**Comment by kemchenj** [comment]
### [SE-0281: @main: Type-Based Program Entry Points](https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md)

[@四娘](https://kemchenj.github.io)：在 ArgumentParser 发布了之后，大家也想要类似于 @UIApplicationMain 这样的注解去声明入口函数，并且 windows 平台支持多种入口函数类型，此时 main.swift 就无法很好地满足使用。

SE-0281 就是为了解决这些问题而出现的，提案的内容也非常简单，可以使用 @main 注解声明入口函数：

```swift
@main 
struct MyProgram: ApplicationRoot {
    static func main() { ... }
}
```

这个提案已经通过并且完成了实现，预计将会在 Swift 5.3 里发布。
