### ISSUE TITLE
Debugging superpowers with FLEX

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2083]
# 推荐收录

## 链接

https://alejandromp.com/blog/debugging-superpowers-with-flex

**Comment by iblacksun** [comment]
### [Debugging superpowers with FLEX](https://alejandromp.com/blog/debugging-superpowers-with-flex/)
[@享耳先森](https://github.com/iblacksun)：FLEX 是 Flipboard 团队出品的 App 调试工具，在开发过程中集成 FLEX 可以监控网络请求、查看 UI 树、查看沙盒文件等，注意：FLEX 不能包含在 Release 环境中，否则可能被拒。
