### ISSUE TITLE
一次关于 Swift 在 iOS 生态圈里的现状调研

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2096]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/Ib48PWpKJNALlNoL4lm4-g

**Comment by iblacksun** [comment]
###  [一次关于 Swift 在 iOS 生态圈里的现状调研](https://mp.weixin.qq.com/s/Ib48PWpKJNALlNoL4lm4-g)

> SketchK 的一篇数据调研笔记，可以帮助大家看清当前国内 iOS 开发形式。

总的来说，国外 Swift 社区活跃度已经比 Objective-C 高了，国内大厂也在推进，具备 Objective-C 与 Swift 混编能力，如果你还没上车，现在买票吧。
