### ISSUE TITLE
What’s new in Swift 5.3?

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2117]
# 推荐收录

## 链接

https://www.hackingwithswift.com/articles/218/whats-new-in-swift-5-3

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [What’s new in Swift 5.3?](https://www.hackingwithswift.com/articles/218/whats-new-in-swift-5-3)

[@享耳先森](https://github.com/iblacksun)：Swift 5.3 即将发布，本文给你介绍 Swift 5.3 的新特性，最显著的两个就是 多尾随闭包(`Multiple trailing closures`) 与 多重异常捕获(`Multi-pattern catch clauses`)，其余特性请阅读原文。

- 5.3 以前尾随闭包只能作于最后一个 `closure` 类型参数，对于有多个 `closures` 参数的情况，也不建议使用尾随闭包，Swift 5.3 开始将支持多 `closures` 参数使用尾随闭包模式。
- 以前一条 catch 语句中只能匹配一种 error，5.3 开始将支持多个 error
```
do {
    let result = try checkReactorOperational()
    print("Result: \(result)")
} catch TemperatureError.tooHot, TemperatureError.tooCold {
    print("Shut down the reactor!")
} catch {
    print("An unknown error occurred.")
}
```
