### ISSUE TITLE
Implementing design system components on iOS

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2133]
# 推荐收录

## 链接

https://medium.com/chili-labs/implementing-design-system-components-on-ios-6afe873ea586

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [Implementing design system components on iOS](https://medium.com/chili-labs/implementing-design-system-components-on-ios-6afe873ea586)

Native View 如何进行组件化抽象并复用一直是个难题，作者通过一个实例介绍他的思路，并提供了 demo 项目。作者将可能复用的 View  抽取成  components，并提供对应的 ViewModel，同时，ViewModel 可以组合实现不同的 Protocol   完成诸如选中等事件分发。
