### ISSUE TITLE
哈啰出行-开源的Flutter混合栈路由解决方案

### ISSUE THREAD

**Issue by foxsofter** [SwiftOldDriver/iOS-Weekly#2141]
# 推荐收录

## 链接

[flutter_thrio](https://github.com/hellobike/flutter_thrio)

## 理由

[flutter_thrio](https://github.com/hellobike/flutter_thrio)是哈啰出行开源的 Flutter 混合栈插件，对比主流的 flutter_boost有以下优势：

* 三端一致且完备的路由 API，你不需要做任何改造就可以获得跟 Flutter 内置的 Navigator 一样的能力；
* 边界的跨端页面间通信 API，原生与Dart之间可以避免很多不必要的 channel 通信；
* 在 iOS 上连续打开 Flutter 页面占用更少的内存；
* 在 Android 上连续打开 Flutter 页面具有更快的页面打开速度；
* 支持在 Flutter 端自定义转场动画；

更多的，如 iOS 手势的处理，导航栏的处理等。

![对比图](http://static.zybuluo.com/Aadan/krqfsurry081fmukjmozn0ri/image_1e9ck016q1qr31cqd1826cr81cm713.png)
参考文档: [如何无缝的将Flutter引入现有应用？
](https://xie.infoq.cn/article/bfb252351094df2327e15c5ca)

## 推荐人信息

稻子

**Comment by ParsifalC** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/search?q=thrio&unscoped_q=thrio

你好，这个已经在之前的周报中推荐过，不重复推荐了。

**Comment by foxsofter** [comment]
> https://github.com/SwiftOldDriver/iOS-Weekly/search?q=thrio&unscoped_q=thrio
> 
> 你好，这个已经在之前的周报中推荐过，不重复推荐了。

好吧，这就尴尬了，😅，但前面的issue好像没能描述清楚 flutter_thrio 真正的优势是什么
