### ISSUE TITLE
苹果强制要求更换启动方式的解决方案

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#2143]
https://mp.weixin.qq.com/s/mdReGqt5E7T8VWC2q7ImKw

**Comment by iblacksun** [comment]
### [](https://mp.weixin.qq.com/s/mdReGqt5E7T8VWC2q7ImKw)

[评估要求在 6 月 30 日以后，所有的 App 必须使用  storyboard 作为 App 的启动图](https://developer.apple.com/news/?id=03262020b)，本文介绍了 LaunchImage 切换到 LaunchScreen.storyboard 的一些常见问题，特别是黑屏问题，建议阅读。
