### ISSUE TITLE
给 Bundle 实现 current 方法

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#215]
http://bou.io/NSBundle.current.html

**Comment by ParsifalC** [comment]
通过 callstack 找出函数指针，然后再找出对应函数所在的文件，再遍历所有 bundle 和 framework 匹配对应资源所在的 bundle，很开脑洞的一种做法。至于效率上，这个方法添加了一层 Cache，在一定程度上降低了同一资源多次查找的效率损耗。
