### ISSUE TITLE
Understanding Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2150]
# 推荐收录

## 链接

https://www.hackingwithswift.com/quick-start/understanding-swift

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
我觉得这一系列的文章更像是新手入门教学里的小 tips，单独拿出来作为总结阅读显得太过零碎，还是不推荐了吧。
