### ISSUE TITLE
OCRunner

### ISSUE THREAD

**Issue by SilverFruity** [SwiftOldDriver/iOS-Weekly#2152]
# 推荐收录
## 链接
https://github.com/SilverFruity/OCRunner
## 理由
oc2mango基于Lex&Yacc识别OC语法。
OCRunner动态运行OC脚本，核心实现可选libffi或者自定义arm64 libffi。
## 优势:
1.  可选libffi或者内置自定义实现的arm64 libff(基于TypeEncode不再是ffi_type)。
2. 支持结构体。内置结构体内存布局，结构体取值与赋值等。
3. 支持可变参数函数和方法。
4. 支持枚举声明。
5. 支持全局C函数声明，直接获取函数指指针。
6. 除去预编译、C数组声明、Protocol，其他语法皆已支持。

**Comment by ParsifalC** [comment]
我们商量了一下，由于类似基于 Libffi 的方案我们之前推过了，比如 [OCEval](https://github.com/lilidan/OCEval)，原则上不会重复推，或者你能说明下 OCRunner 区别于目前业内方案的地方和它独有的优势么？我们再重新评估。

**Comment by SilverFruity** [comment]
> 我们商量了一下，由于类似基于 Libffi 的方案我们之前推过了，比如 [OCEval](https://github.com/lilidan/OCEval)，原则上不会重复推，或者你能说明下 OCRunner 区别于目前业内方案的地方和它独有的优势么？我们再重新评估。
目前的优势，我没想到。libffi的替代方案有一点头绪，实现了以后，我再来投稿吧。嘻嘻。

**Comment by ParsifalC** [comment]
> 再来

好的，欢迎再来自荐~
