### ISSUE TITLE
iOS 渲染原理解析

### ISSUE THREAD

**Issue by knightsj** [SwiftOldDriver/iOS-Weekly#2153]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/6ckRnyAALbCsXfZu56kTDw

## 理由

图文并茂地讲解了 iOS 的渲染原理，后面也讲解了离屏渲染。

**Comment by ParsifalC** [comment]
我们推过原文了。https://github.com/SwiftOldDriver/iOS-Weekly/commit/a64216165770939ac9159f29451b46d45b5accf6
