### ISSUE TITLE
Decode and Flatten JSON with Dynamic Keys Using Decodable

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#2155]
# 推荐收录

https://swiftsenpai.com/swift/decode-dynamic-keys-json/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Decode and Flatten JSON with Dynamic Keys Using Decodable](https://swiftsenpai.com/swift/decode-dynamic-keys-json/)

[@四娘](https://kemchenj.github.io/)：有时候后端下发的 JSON 文件会采取动态 key 的形式，那在 Codable 里该如何实现呢？这篇文章就介绍了如何动态 key 的结构该如何解析以及封装的方式。
