### ISSUE TITLE
关于medium.com上的文章国内打不开的问题

### ISSUE THREAD

**Issue by allanGoldZhiKang** [SwiftOldDriver/iOS-Weekly#2156]
medium.com上的文章国内打不开，能帮忙搬一下吗

**Comment by ParsifalC** [comment]
最好自配梯子哦，如果只有一篇的话，你说下哪一篇？

**Comment by allanGoldZhiKang** [comment]
> 最好自配梯子哦，如果只有一篇的话，你说下哪一篇？

https://medium.com/chili-labs/implementing-design-system-components-on-ios-6afe873ea586

**Comment by ParsifalC** [comment]
![image](https://user-images.githubusercontent.com/7930911/83590164-b1c70680-a587-11ea-846f-ae5555e077a7.png)
[Implementing design system components on iOS - Chili Labs - Medium_ - medium.com.pdf](https://github.com/SwiftOldDriver/iOS-Weekly/files/4720759/Implementing.design.system.components.on.iOS.-.Chili.Labs.-.Medium_.-.medium.com.pdf)

**Comment by allanGoldZhiKang** [comment]
> ![image](https://user-images.githubusercontent.com/7930911/83590164-b1c70680-a587-11ea-846f-ae5555e077a7.png)
> [Implementing design system components on iOS - Chili Labs - Medium_ - medium.com.pdf](https://github.com/SwiftOldDriver/iOS-Weekly/files/4720759/Implementing.design.system.components.on.iOS.-.Chili.Labs.-.Medium_.-.medium.com.pdf)

thank you！有什么好的梯子可以推荐一下吗

**Comment by EtherLiu** [comment]
> > 最好自配梯子哦，如果只有一篇的话，你说下哪一篇？
> 
> https://medium.com/chili-labs/implementing-design-system-components-on-ios-6afe873ea586

您好，请问有好用的TZ推荐吗
