### ISSUE TITLE
Apple reveals lineup for its biggest-ever Worldwide Developers Conference

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2170]
# 推荐收录

## 链接

https://www.apple.com/newsroom/2020/06/apple-reveals-lineup-for-its-biggest-ever-worldwide-developers-conference/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [苹果公布史上最大规模的 WWDC20 阵容](https://www.apple.com/newsroom/2020/06/apple-reveals-lineup-for-its-biggest-ever-worldwide-developers-conference/)

WWDC20 已经进入第 31 个年头，WWDC20 将于 6 月 22 至 26日以前所未有的虚拟方式将全球超过 2300 万的苹果开发者社区聚集在一起，将成为迄今为止规模最大的 WWDC。

Keynote 主题演讲在北京时间 23 日凌晨 1 点开始，对于中国的观众来说，主题演讲也将在腾讯、爱奇艺、Bilibili 和优酷上进行直播。同时，超过 1000 名苹果工程师将在 Developer Forums 回答问题并参与技术讨论，开发者可以发布自己的问题，直接向苹果专家学习。
