### ISSUE TITLE
What Adding Dependencies Will Do To Your App in 2020

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2173]
# 推荐收录

## 链接

https://xavierlowmiller.github.io/blog/2020/06/04/Swift-Dependencies

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
选择第三方库比较少，没有更细致的比较。结论不意外，意义不是很大。
结论：SPM ~> CocoaPods >> Carthage.

不建议收录
