### ISSUE TITLE
iOS 后起之秀-刷新控件

### ISSUE THREAD

**Issue by liangxiuchen** [SwiftOldDriver/iOS-Weekly#2179]
# 推荐收录

## 链接

https://github.com/liangxiuchen/CLXRefresh

## 理由

demo 中充分解决了iOS10以上的痛点，和UI解耦合，更容易实现自定义，轻松实现支付宝刷新效果。毛遂自荐，望了解下demo。谢谢

## 推荐人信息

陈良秀，iOS 程序员。该控件的作者。

**Comment by EyreFree** [comment]
@liangxiuchen 

我们在对项目进行了解后得出以下结论：

1. 相对于 [MJRefresh](https://github.com/CoderMJLee/MJRefresh) 等类似项目没有明显的优势，突出自身特色可能会更好；
2. 目前该项目功能与演示相对比较单一，如果添加更多样式或对主流 App 类似功能实现的实例可能会更好；
3. 缺乏项目相关文档。

所以目前暂时不会收录到周报中，感谢您的推荐。
