### ISSUE TITLE
Apple Clip 技术详解

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2196]
# 推荐收录

## 链接

https://juejin.im/post/5ef41c9b6fb9a07e6143b0d0

**Comment by iblacksun** [comment]
### [Apple Clip 技术详解](https://juejin.im/post/5ef41c9b6fb9a07e6143b0d0)

[@享耳先森](https://github.com/iblacksun)：苹果在 WWDC2020 上发布了 App Clip，本文从产品定位及实现细节上介绍了 App Clip 的方方面面，还与 `PWA`、`Instant Apps`、`小程序` 进行横向比对，推荐阅读。
