### ISSUE TITLE
iOS 知识小集

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#22]
https://github.com/southpeak/iOS-tech-set

**Comment by kemchenj** [comment]
国内知名开发者 [@南峰子](https://weibo.com/touristdiary) 把过去微博上发出来的 iOS 开发 Tips 整理了出来，重新整理之后发在了 GitHub 上，据介绍这一系列的微博已经有 1000w 的阅读量了，这是项目的部分简介：

> iOS知识小集的初衷是希望用300字左右（外加代码和效果展示）来说明一个小知识点，这样读者可以在上下班路上，花个2分钟就能了解一个iOS开发的小知识。当然，短短几百字无法说清楚一个知识点，要详细的了解，还需要查阅更多的资料并且去实践一下。另外由于是零零散散地记录，所以成不了体系。
>
> ...
>
> 如果微博数据没有造假的话，这个话题已经有1000w的阅读量了。所以又萌生了把之前零零散散的小tip整理起来的念头，于是就在Github上开了这个Repository，方便大家阅读。

**Comment by lacklock** [comment]
已经添加
