### ISSUE TITLE
iOS 一步步带你实践组件二进制方案

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2201]
# 推荐收录

## 链接

https://juejin.im/post/5efaf0655188252e42157e8a

**Comment by nianran** [comment]
@linwenbang 
这个方案有点过时了，文章内的方案 3-4 年前就有了，现有很多新的方案更优于此篇方案。
此方案还有很多诟病，比如 pod search 也会执行脚本内容、pod install 不能直接替换仓库等。

**Comment by nianran** [comment]
这篇就不推荐了
