### ISSUE TITLE
打造一个通用、可配置、多句柄的数据上报 SDK

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2208]
# 推荐收录

## 链接

https://juejin.im/post/5f02c48be51d4534b55a3953

**Comment by raozhizhen** [comment]
一个 App 一般会存在很多场景去上传 App 中产生的数据，比如 APM、埋点统计、开发者自定义的数据等等。本篇文章讲如何设计一个通用的、可配置的、多句柄的数据上报 SDK。内容比较详细，既可以作为设计数据上报 SDK 的参考，也可以用来了解数据上报 SDK 的原理。
