### ISSUE TITLE
WWDC18 Registration Now Open

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#221]
https://developer.apple.com/wwdc/

**Comment by iblacksun** [comment]
🐎 [WWDC 2018 时间确定](https://developer.apple.com/wwdc/)

Apple 宣布 WWDC 2018 将于 6 月 4 日至 8 日在圣何塞举行，现已开发注册(注册截至时间是 3 月 22 日)，届时将已抽签方式确定资格。

**Comment by ApolloZhu** [comment]
不知可否让我毛遂自荐一下：https://apollozhu.github.io/2018/03/16/wwdc18-scholarships-info-cn/
稍微分享了下作为 WWDC Scholarship 获得者的经验和分析

**Comment by iblacksun** [comment]
@ApolloZhu 感谢，这是我更新之后的介绍文案，或者你也可以直接更新 11.md ，然后提 PR.

🐎 [WWDC 2018 时间确定](https://developer.apple.com/wwdc/)

Apple 宣布 WWDC 2018 将于 6 月 4 日至 8 日在圣何塞举行，现已开发注册(注册截至时间是 3 月 22 日)，届时将已抽签方式确定资格。

另外，Apple 还有 Scholarships 计划为优秀在校学生提供免费门票，这有一篇 WWDC 2017 Scholarships 获得者写的 [WWDC18 奖学金指北](https://apollozhu.github.io/2018/03/16/wwdc18-scholarships-info-cn/)

**Comment by ApolloZhu** [comment]
谢谢，就按您写的来吧。我照抄提 PR 有点过意不去，还是劳烦您更新了。
