### ISSUE TITLE
iOS14 隐私适配及部分解决方案

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2212]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/CJML-2YUv6sqEEnI8rI0Bw

**Comment by iblacksun** [comment]
### 🐕 🌟 [iOS14 隐私适配及部分解决方案](https://mp.weixin.qq.com/s/CJML-2YUv6sqEEnI8rI0Bw)

[@享耳先森](https://github.com/iblacksun)：隐私一直是 iOS 系统的重中之重，在刚刚结束的 WWDC 2020 ，苹果向我们展示了新的 iOS14 系统。iOS14 的适配，很重要的一环就集中在用户隐私和安全方面。本文介绍了 iOS 14 系统隐私方面的调整以及开发者如何跟进适配，涉及以下方面的调整：
- 相册增加 Limited
- 地理位置增加模糊定位
- 局域网信息
- 剪贴板
- 相机和麦克风
- IDFA
