### ISSUE TITLE
 Swift globals and static members are atomic and lazily computed

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2215]
# 推荐收录

## 链接

https://www.jessesquires.com/blog/2020/07/16/swift-globals-and-static-members-are-atomic-and-lazily-computed/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
只有和标题相同的结论，正文缺乏内容阐述。不推荐
