### ISSUE TITLE
A Best in Class iOS App

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2216]
# 推荐收录

## 链接

https://www.swiftjectivec.com/a-best-in-class-app/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
作者维护了一个列表，去支持列表里提到的每一个细节，帮助你使 APP 变得更好，它涵盖五个部分：
- 辅助功能：最好的应用，为每个人的使用而设计，例如支持视力辅助功能 Voice Over，足够高的色彩对比度（至少7:1）。
- 平台技术：去支持苹果提供的统一功能，例如暗模式，iPadOS 的多任务处理。
- 用户体验：好的用户体验让人无需思考，一切理应如此。例如使用正确的音频设置并优雅地响应音频中断，所有可点击的界面元素至少为 44*44 大小。
- 设计：这部分列出了经过深思熟虑的设计规范。例如使用正确的系统边距（layoutMarginsGuide，safeAreaLayoutGuide 等）。
- App Store：App Store 展示资料经过精心的设计，例如创建预览视频，对关键词和类别进行仔细研究。
