### ISSUE TITLE
快速用上 Swift 静态库

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#222]
https://blog.dianqk.org/2018/03/08/use-static-framework/

**Comment by mmoaay** [comment]
文章记录了作者在 Swift 静态库上使用的一些实践。作者使用了一个比较 trick 的技巧，通过在 Podfile 中添加自定义脚本的方式，快速为每个第三方库添加 static_framework 支持。不过因为是实践类型的，如果要引入到自己的项目中，可能还会有一些坑需要自己处理。
