### ISSUE TITLE
[PRODUCT THINKING · 产品沉思录精选]

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#2237]
# 推荐收录

## 链接

https://sourl.cn/CbfDW5

## 理由

与技术无关，纯粹发现了个宝藏。
作者：少楠Plidezus
产品沉思录の主理人，丁香医生首席产品架构师

**Comment by iblacksun** [comment]
这条 @Damonvvong 或 @zvving 来处理吧？
