### ISSUE TITLE
一文入门DNS？从访问GitHub开始

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2239]
# 推荐收录

## 链接

https://juejin.im/post/5f18683af265da22f84d7602

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by KyoLi** [comment]
太基础了，而且不是与 iOS 技术直接相关的
