### ISSUE TITLE
Swift Code Injection using dyld_dynamic_interpose

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2241]
# 推荐收录

## 链接

http://johnholdsworth.com/dyld_dynamic_interpose.html

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Swift Code Injection using dyld_dynamic_interpose](http://johnholdsworth.com/dyld_dynamic_interpose.html)

[@四娘](https://kemchenj.github.com)：Injection 是一个代码注入工具，可以在不重启 App 的情况下让代码修改生效（也就是俗称的热刷新），在最早的 Objective-C 版本里，这件事情很简单，只要在加载完 dylib 之后调用 Runtime API 进行替换即可。

问题在于 Swift，最早 Swift 1.0 发布之后，作者只能使用修改 vtable 的方式去修改 non-final 的函数，但 struct 和 enum 的声明和函数派发一直是个问题。

在最近发布的 InjectionIII 里这个问题终于得到了解决，作者在 Twitter 的讨论里发现了一个 dyld 的私有 API `dyld_dynamic_interpose`，这个 API 可以在加载 dylib 时便捷地替换掉函数实现，在此基础上作者还添加了 SwiftUI 的支持，感兴趣的同学可以看一下。
