### ISSUE TITLE
Swift 5.3 又更新了什么新奇爽快的语法？

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2249]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/pQiLyl572fSgMX1Fq3RDhw

**Comment by iblacksun** [comment]
### 🐕[Swift 5.3 又更新了什么新奇爽快的语法？](https://mp.weixin.qq.com/s/pQiLyl572fSgMX1Fq3RDhw)

[@享耳先森](https://github.com/iblacksun)：Swift 从 WWDC14 发布至今，已经经过了五年多的迭代，5.3 随着 WWDC20 一起发布，看过相关 Session 的同学一定对 `[SE-0279] Multiple trailing closure` 印象深刻。本文作者给大家列出了 Swift 5.3 的一些改动点，同时对 Swift 的现状与未来，作者也给出了他自己的一些看法。
