### ISSUE TITLE
解决「 HTTPDNS + HTTPS 」的证书校验问题

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#225]
https://mp.weixin.qq.com/s?__biz=MzA5NzMwODI0MA==&mid=2647759635&idx=1&sn=237807cd1b9740169a3bf77d09aec4b0&from=1083293010&wm=3333_2001&weiboauthoruid=3321824014

**Comment by lacklock** [comment]
相比 joy 的这篇 https://juejin.im/post/5a81bbd66fb9a0634c266fe1 没有太多新的内容。
不建议上。
