### ISSUE TITLE
基于 unicorn + capstone 动态分析生成 objc_msgSend 交叉引用并导入 IDA

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2259]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/LInn-tYkR6VbvXhYDupkTg

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by SatanWoo** [comment]
我都没看懂。。。。
