### ISSUE TITLE
iOS 微信基于特殊字符的保护方案

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#226]
https://mp.weixin.qq.com/s/3xmpJqn361HGtUloOVsIZg

**Comment by iblacksun** [comment]
### 🐢 [iOS 微信特殊字符保护方案](https://mp.weixin.qq.com/s/3xmpJqn361HGtUloOVsIZg)

相信大家对之前 iOS 设备碰到特殊字符导致崩溃的问题记忆犹新，后来微信团队对特殊字符做了保护。
> 由于无法事先知道字符串里包含特殊字符，所以只能先让它排版/绘制，看看是否出现问题。做法是，在排版/绘制字符串前，先设置标记位，排版/绘制结束后，移除标记位；一旦发现标记位存在，就意味着这字符串可能有问题，下次就不显示这个字符串。
