### ISSUE TITLE
Dependency Injection via Property Wrappers

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2264]
# 推荐收录

## 链接

https://www.kiloloco.com/articles/004-dependency-injection-via-property-wrappers/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这周有事，放到下周。

**Comment by kemchenj** [comment]
### [Dependency Injection via Property Wrappers](https://www.kiloloco.com/articles/004-dependency-injection-via-property-wrappers/)

[@四娘](https://kemchenj.github.io/)：依赖注入是一种解决高低层级抽象耦合的方式，这篇文章介绍了在 Swift 里如何简单地实现这种模式，并且使用 `@propertyWrapper` 优化它的语法：

```swift
struct ContentView: View {
    @Inject var dependency: MyDependency
    
    var body: some View {
        Button("Tap Me", action: dependency.doSomething)
        // prints "Next level injection 💉" when tapped
    }
}
```
