### ISSUE TITLE
周报增加阅读时间提示

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#228]
把提示方案订一下

**Comment by raozhizhen** [comment]
🚀  🚕  🛴

**Comment by raozhizhen** [comment]
阅读时间从短到长  @Damonvvong  你看看

**Comment by lacklock** [comment]
我觉得这三个和阅读时间的关联不太正向。三种交通工具体现的关联是速度，但是汽车的相对概念是五分钟，是十五分钟则表达的不清晰。

**Comment by raozhizhen** [comment]
emoji 里好像没有比较合适的了  我再想想其他方案 @lacklock

**Comment by raozhizhen** [comment]
我这边先根据 emoji 出几个方案 @lacklock 

🚀 阅读速度很快（简单易理解的推荐）  5 分钟内
  
🚕 阅读速度一般（中等长度难度的推荐） 5 - 20 分钟

🛴 阅读速度慢（长篇或者难理解的推荐）  20 分钟以上

🍌 吃根香蕉就能看完

🍔 吃个汉堡包时间就看完了

🍱 吃顿饭时间才能看完

🚬 抽根烟的时间看完了

🚽 上个厕所的时间就看完了

🛀 泡个澡的时间看完了


🐢 很慢才能看完

🐕 一般速度看完

🐎 马上能阅读完

用乌龟的多少来形容内容的长短

🐢  短 

🐢🐢 中

🐢🐢🐢  长

用表情来表示阅读体验

😀  快速阅读不吃力

😗  一般一般 hold 住

😵  太长了看晕了
