### ISSUE TITLE
苹果 ResearchKit 中居然有图表的控件可以直接用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#229]
http://researchkit.org/docs/docs/ChartsAndGraphs/ChartsAndGraphs.html

**Comment by iblacksun** [comment]
用 ResearhKit 显示图表不知道会不会违反 App Store Review Guideline 2.5.1? 

> App 使用的 API 和框架应该是为了实现预期用途，并在 app 描述中说明集成详情。例如，HomeKit 框架应提供家居自动化服务；而HealthKit 则应该用于保持健康和健身目的，并集成在“健康”app 中。

**Comment by lacklock** [comment]
不过heathKit是开源的，不知道能不能直接看到这些控件的源码
