### ISSUE TITLE
SwiftDump

### ISSUE THREAD

**Issue by neil-wu** [SwiftOldDriver/iOS-Weekly#2296]
# 推荐收录

## 链接

[https://github.com/neil-wu/SwiftDump](https://github.com/neil-wu/SwiftDump)

## 理由

SwiftDump是从Mach-O文件中获取swift对象定义的命令行工具，类似大家都用过的OC类dump工具class-dump，SwiftDump专注于处理swift对象(当前只支持swift 5)。
工具采用Swift编写，代码简短，可以借此一窥Mach-O中是如何处理swift相关信息的。

## 推荐人信息
作者自荐

**Comment by iblacksun** [comment]
### [SwiftDump](https://github.com/neil-wu/SwiftDump/blob/master/README_zh.md)

SwiftDump 是从 Mach-O 文件中获取 Swift 对象定义的命令行工具，类似大家都用过的 OC dump 工具 class-dump，SwiftDump专注于处理 Swift对象(当前只支持 Swift 5)。
工具采用 Swift编写，代码简短，可以借此一窥 Mach-O 中是如何处理 Swift 相关信息的。

> 推荐人 [@neil-wu](https://github.com/neil-wu)
