### ISSUE TITLE
8月10号的内容，与8月3号的有重复

### ISSUE THREAD

**Issue by matthewyan** [SwiftOldDriver/iOS-Weekly#2299]
3号的这篇：必读 | 深入理解布局约束
10号的这篇：Flutter 初学者必读的高级布局规则

这两篇内容是一样的

**Comment by ParsifalC** [comment]
> 3号的这篇：必读 | 深入理解布局约束
> 10号的这篇：Flutter 初学者必读的高级布局规则
> 
> 这两篇内容是一样的

收到！已调整。感谢指出。
