### ISSUE TITLE
微信团队出品：MMKV--基于 mmap 的 iOS 高性能通用 key-value 组件

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#230]
https://mp.weixin.qq.com/s/cZQ3FQxRJBx4px1woBaasg

**Comment by ParsifalC** [comment]
这个和 #226 重复了

**Comment by EyreFree** [comment]
### 🐕 [MMKV--基于 mmap 的 iOS 高性能通用 key-value 组件](https://mp.weixin.qq.com/s/cZQ3FQxRJBx4px1woBaasg)

MMKV 是基于 mmap 内存映射的 key-value 组件，底层序列化/反序列化使用 protobuf 实现，性能远远优于 iOS 自带的 NSUserDefaults，同时 MMKV 即使触发数据重整，也能保持稳定高效的性能，稳定性强。不过可惜的是目前 MMKV 仅在鹅厂内部开源，本文，想研究源码的同学可能还需要等上一段时间。

**Comment by EyreFree** [comment]
由于 MMKV 暂未开源，本条暂时搁置。
