### ISSUE TITLE
国外weekly编辑整理的一份他认为不错的ios开发者博客

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#233]
https://iosdevdirectory.com

**Comment by kemchenj** [comment]
### [iOS Weekly 的作者整理了一份他的 iOS 博客订阅](https://iosdevdirectory.com/)

最近 iOS Weekly 的作者就整理了一份他的 iOS 博客订阅，小编全部导入了之后，在列表里看到了最新很活跃的 Swift by Sundell，老牌大佬 Ole Begemann...，感兴趣的同学可以直接下载 OPML 文件然后直接导入到你们的 RSS 阅读器里，开始你们的英文阅读之路😉。
