### ISSUE TITLE
3. CocoaPods 命令解析 - CLAide

### ISSUE THREAD

**Issue by knightsj** [SwiftOldDriver/iOS-Weekly#2340]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/JMG04U-7737GGlnoOKg1Fw

**Comment by JonyFang** [comment]
### 🐕 [3. CocoaPods 命令解析 - CLAide](https://mp.weixin.qq.com/s/JMG04U-7737GGlnoOKg1Fw)

[@JonyFang](https://github.com/JonyFang)：本篇主要介绍了 CocoaPods 提供的命令行解析器 CLAide。它负责解析我们使用到的 Pods 命令，如 `pod update Alamofire --no-repo-update --exclude-pods=SwiftyJSON`命令执行时 CLAide 的解析过程。作者主要描述的几个点：

- 简介 Ruby 中的 Open Classes 特性，其中需要留意的是 Open Class 可以跨文件、跨模块进行访问。
- 概述 GLAide 功能及其目录结构
- 介绍用于构建命令行界面的基础抽象类 Command。我们添加的命令都需要继承自 Command，不同的配置得到 `abstract command` 和 `normal command`。pod 命令正是由多个 `Pod::Command < CLAide::Command` 的子类组成 `abstract command`，通过这种方式达到多级嵌套命令的效果。
- 以 `pod update Alamofire --no-repo-update --exclude-pods=SwiftyJSON` 为例介绍 CLAide 中 ARGV 是如何解析命令行传入的参数的。
- 介绍 Command 的管理类 PluginManager 的执行流程。它会在第一次运行命令 self.run 时进行加载，且仅加载命令类中指定前缀标识的文件下的命令。
- 最后，结合前面介绍的类职责及执行流程，通过创建一个 CLAide 命令来自己实现一款 🥤 贩卖机。（作者提供的 [Demo 源码](https://github.com/looseyi/BeverageMaker)）
