### ISSUE TITLE
不同角度看问题 - 从 Codable 到 Swift 元编程

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#235]
https://onevcat.com/2018/03/swift-meta/

**Comment by mmoaay** [comment]
喵神新文，围绕“将一个类型转换为字典”这个问题，向读者介绍了三种解决思路和实现细节：Codable、Mirror 以及代码生成。而更为重要的点在于喵神想向大家传递的思想：如何利用“元编程”的思维来解决项目中碰到的重复体力劳动问题。（PS：喵神最近开通了[小专栏](https://xiaozhuanlan.com/onevcat)，非常值得关注！）
