### ISSUE TITLE
SF Symbols Changes in iOS 14

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2350]
# 推荐收录

## 链接

https://medium.com/@hacknicity/sf-symbols-changes-in-ios-14-4731937c5dc7

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [SF Symbols Changes in iOS 14](https://medium.com/@hacknicity/sf-symbols-changes-in-ios-14-4731937c5dc7)

SF Symbols 是苹果在 WWDC 2019 介绍的一套矢量图形，iOS 14 中，苹果对 SF Symbols 进行了大量更新：
- 新增近 900 个新符号(有些符号的使用受到限制)。
- iOS 13 中的 60 个符号已被重新命名。
- 158个符号有多色支持。
- 本地化支持：新增许多右到左的的符。
- 错误修复 修复了一些与名称不匹配的图片。
