### ISSUE TITLE
如何提高代码质量

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2355]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/Dl7umd-Z3QuvOwzjmy3Z4w

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🌟🐕 [如何提高代码质量](https://mp.weixin.qq.com/s/Dl7umd-Z3QuvOwzjmy3Z4w)

[@享耳先森](https://github.com/iblacksun)：高质量代码简单来说就是「好看和好用」，好看是指代码可读性好，容易理解、容易维护，别人接手了不骂你；好用则指代码健壮，不容易出错，机器跑着不骂你。即使出错，也容易定位，容易止损和恢复。

如何才能拥有高质量的代码，有两种途径：
- 第一种途径：先有好的设计--->然后用优秀的编码去实现--->再把优秀的编码风格延续下去
- 第二种途径：从糟糕的代码开始--->不断去重构，向优秀的设计方案和代码风格不断逼近--->再延续下去

本文重点从「途径一」的角度介绍如何能产生好代码，分别从规范、实践、度量及改进几个角度深入阐述，建议阅读。
