### ISSUE TITLE
App Clip离落地有多远？

### ISSUE THREAD

**Issue by GCSNNB** [SwiftOldDriver/iOS-Weekly#2359]
# 推荐收录

## 链接

[App Clip离落地有多远](https://gcsnnb.github.io/2020/09/10/App-Clip%E7%A6%BB%E8%90%BD%E5%9C%B0%E6%9C%89%E5%A4%9A%E8%BF%9C/)

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by JonyFang** [comment]
### 🐕 [App Clip离落地有多远？](https://gcsnnb.github.io/2020/09/10/App-Clip%E7%A6%BB%E8%90%BD%E5%9C%B0%E6%9C%89%E5%A4%9A%E8%BF%9C/)

[@JonyFang](https://github.com/JonyFang)：WWDC2020 引出了 App Clips，之前的《WWDC20内参》已经介绍过[《App Clips 的配置及链接处理》](https://xiaozhuanlan.com/topic/5820361974)。截止这里，我们已经知道了 App Clips 所带来的利，如及时可用等。本篇从业务和技术两个角度，列出了 App Clips 真正落地可能会遇到的问题，度量的角度可以作为我们实际业务确定过程中的参考。

这里列出 App Clips 落地过程中值得思考的几点：
- 业务角度
	- 国内市场线下支付的支持
	- 国内小程序的竞争
	- 仅支持 iOS 14+ 用户
	- 虽然提供了多种唤起 App Clips 的方式，但触发的条件比较严苛。如 Clip Code 只能通过`系统相机`才能够唤起
	- 对于纯线上 App 最有利的唤起方式是通过 Safari，但操作路径步骤比较多
- 技术角度
	- 需要针对业务做代码拆分或做足够彻底的组件化
	- 10M App Clips 包大小的限制
	- App Clips 不支持后台处理活动。如`后台不支持网络请求`等
	- App Clips 的用户怎么和对应的 App 用户一样做到唯一标识和绑定
	- App Clips 支持唤起三方 App，但三方 App 不支持唤起 App Clips。所以会影响到三方登录、三方分享、三方支付的场景
	- 不支持企业包
	- Cocoapods 对 App Clips 的支持还不完善
