### ISSUE TITLE
iOS Dev Directory 

### ISSUE THREAD

**Issue by ShannonChenCHN** [SwiftOldDriver/iOS-Weekly#236]
[iOS Dev Directory](https://iosdevdirectory.com/) 是 [iOS Dev Weekly](https://iosdevweekly.com/issues/341#start) 作者 [Dave Verwer](https://twitter.com/daveverwer) 创建维护的一个跟 iOS 开发相关的网站/博客列表，其内容涉及开发、设计、运营等多个方向。

目前已经收集的网站列表大概分为以下几类：
- Official Apple Blogs
- iOS Development Blogs
- iOS Design Blogs
- iOS Marketing Blogs
- iOS Development Company Blogs
- Korean Language Blogs
- Turkish Language Blogs
- iOS Podcasts
- Inactive Blogs

ps：我在 Twitter 上问了下 Dave，看看能不能把一些优秀的中文 blog 也添加进去，目前正在等待答复中。

**Comment by ParsifalC** [comment]
感谢提供反馈，这部分内容我们已经在[第十一期周报(本周)](https://github.com/SwiftOldDriver/iOS-Weekly/blob/b2524720761ff589f8ed0000964292fd69c5e3df/Reports/%2311.md)中编辑上了。敬请期待发布。

**Comment by Damonvvong** [comment]
@ShannonChenCHN 感谢建议，我觉得推荐他的 iOS Dev Directory 比推荐里面的内容更好一点。
因为我们已经推荐了，所以这个issue我就关闭了~
