### ISSUE TITLE
Managing Model Data in Your App

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2365]
# 推荐收录

## 链接

https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app

## 理由

苹果新出的 SwiftUI 管理 model 的文档

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
纯官方文档 State and Data Flow 的一部分，内容也比较短，不建议收录
