### ISSUE TITLE
Private APIs, Objective-C runtime, and Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2367]
# 推荐收录

## 链接

https://medium.com/@victor.pavlychko/private-apis-objective-c-runtime-and-swift-ceaeefbb6e48

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Private APIs, Objective-C runtime, and Swift](https://medium.com/@victor.pavlychko/private-apis-objective-c-runtime-and-swift-ceaeefbb6e48)

[@四娘](https://kemchenj.github.io)：Foundation 里有一些 API 被标记为 `NS_SWIFT_UNAVAILABLE`，例如 `NSInvocation` / `NSMethodSignature`，由于它们不安全或者没办法很好地融入到 Swift 的体系里所以被标记为不可用。

但有时候我们面对平台 SDK 的问题，又不得不跟这些 API 打交道，那么此时在 Swift 里如何调用并且封装这些 API 就成了一个问题，这篇文章的作者就详细地介绍了他的解决方案：

```swift
let object = NSDate()
let objectPrivate = object as! NSObjectPrivate
let selector = Selector("description")
let signature = objectPrivate.methodSignature(for: selector)!
let invocation = NSInvocationClass.invocation(methodSignature: signature)
invocation.selector = selector
invocation.invoke(target: object)
var unmanagedResult: Unmanaged<NSString>? = nil
invocation.getReturnValue(&unmanagedResult)
let result = unmanagedResult?.takeRetainedValue()
print(result ?? "<nil>")
```
