### ISSUE TITLE
Memory Safety

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2379]
# 推荐收录

## 链接

https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html

**Comment by kemchenj** [comment]
放到下周。

**Comment by kemchenj** [comment]
### [Memory Safety - The Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html)

[@四娘](https://kemchenj.github.io)：这是 Swift 官方文档的其中一节，默认情况下，Swift 会阻止你代码里不安全的行为。例如，Swift 会保证变量在使用之前就完成初始化，在内存被回收之后就无法被访问，并且数组的索引会做越界检查。

Swift 也保证同时访问同一块内存时不会冲突，通过约束代码里对于存储地址的写操作，去获取那一块内存的访问独占权。因为 Swift 自动管理内存，所以大部分时候你完全不需要考虑内存访问的事情。然而，理解潜在的冲突也是很重要的，可以避免你写出访问冲突的代码。
