### ISSUE TITLE
建议：在 readme 中给最新一期周报一个链接

### ISSUE THREAD

**Issue by Josscii** [SwiftOldDriver/iOS-Weekly#238]
目前查看最新一期的周报，需要点击“周报列表”，在十几期中根据序号筛选出最新一期，对于追更党实在是不方便，而且后续如果内容越来越多就更不好检索了。

**Comment by Damonvvong** [comment]
谢谢您的建议，关于后续检索管理的问题，我们会抽个时间讨论一下。现在这个因为数量不多，所以考虑不周到。

**Comment by lacklock** [comment]
我们增加了公众号和 rss 渠道，希望可以解决你的问题。
