### ISSUE TITLE
用 Swift 实现一个 Swift Runtime

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2381]
# 推荐收录

## 链接

- https://belkadan.com/blog/2020/08/Swift-Runtime-Heap-Objects/
- https://belkadan.com/blog/2020/09/Swift-Runtime-Type-Layout/
- https://belkadan.com/blog/2020/09/Swift-Runtime-Type-Metadata/

## 推荐语

这个系列的文章来自于今年愚人节的一个项目，作者[让 Mac OS 9 支持运行 Swift 程序](https://belkadan.com/blog/2020/04/Swift-on-Mac-OS-9/)，其中 Swift Runtime 没有将 C++ 的实现迁移过来，而是使用 Swift 实现了一套，文章里就分享了具体的实现细节，包含了大量的 Swift 指针操作技巧，推荐一读。

PS：作者 Jordan Rose 之前是 Swift 团队的一员，负责 bugs.swift.org 相关的工作，在去年离职，离职的时候还在发了一条推 `Sorry for the bugs` 😂，如果大家有印象的话，应该记得当时喵神截图转发到微博上。

**Comment by iblacksun** [comment]
### [系列文章：用 Swift 实现一个 Swift Runtime](https://belkadan.com/blog/2020/08/Swift-Runtime-Heap-Objects/)

这个系列的文章来自于今年愚人节的一个项目，作者让 [Mac OS 9 支持运行 Swift 程序](https://belkadan.com/blog/2020/04/Swift-on-Mac-OS-9/)，其中 Swift Runtime 没有将 C++ 的实现迁移过来，而是使用 Swift 实现了一套，文章里就分享了具体的实现细节，包含了大量的 Swift 指针操作技巧。

通过阅读系列文章，你应该对 Swift Runtime 会有更深的理解，推荐阅读。
https://belkadan.com/blog/2020/08/Swift-Runtime-Heap-Objects/
https://belkadan.com/blog/2020/09/Swift-Runtime-Type-Layout/
https://belkadan.com/blog/2020/09/Swift-Runtime-Type-Metadata/

> 作者 Jordan Rose 之前是 Swift 团队的一员，负责 bugs.swift.org 相关的工作，在去年离职。
