### ISSUE TITLE
js-native 通信的 6 种方式

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2392]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/_Xo6O3NoE1z9AIMJm_uSsA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [JS-Native 通信的 6 种方式](https://mp.weixin.qq.com/s/_Xo6O3NoE1z9AIMJm_uSsA)

[@享耳先森](https://github.com/iblacksun)：本文列出了 Hybrid 架构中，JS 与 Native 通信的几种技术方案，这些方案你都了解吗？

> 题外话：Hybrid 通信大多是异步方式的，不妨深入研究下，是否可以实现同步呢？
