### ISSUE TITLE
Swift 的 MemoryLayout 是如何工作的（1）

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2393]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/JB1oUf25cp8O4s5OLNpmSA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Swift 的 MemoryLayout 是如何工作的](https://ai-chan.top/hexo/2020/09/13/Swift-MemoryLayout/)

[@四娘](https://kemchenj.github.io)：`MemoryLayout` 是标准库里一个很神奇的类型，通过它我们可以在运行时获取到特定类型的内存布局信息，之前我们介绍过的 `HandyJSON` 和 `Runtime` 库都有使用到它，但对于它的原理的介绍文章却不是很多。

这篇文章就从 Swift 编译器的视角出发，介绍了 `MemoryLayout`  的工作原理，例如从源码到 IR 的过程中如何确定类型的内存布局，如何把这些编译期的元信息变成可调用的语言接口，希望读者读完之后也可以对此有所了解。
