### ISSUE TITLE
Swift正式登录Windows：苹果跨平台语言值几钱？

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2397]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/q8F7dtdmcjSHah6l7cosFw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
原文太标题党，推荐了 https://mp.weixin.qq.com/s/088RdJNxa79t1Y9Q04A3Xw
