### ISSUE TITLE
Binary Frameworks as Swift Packages

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2399]
# 推荐收录

## 链接

https://pspdfkit.com/blog/2020/binary-frameworks-as-swift-packages/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Binary Frameworks as Swift Packages](https://pspdfkit.com/blog/2020/binary-frameworks-as-swift-packages/)

[@四娘](https://kemchenj.github.io/)：今年 Swift Package Manager 最重要的更新之一就是支持了二进制分发，PSPDFKit 第一时间就做了 SPM 的支持，也给 Swift 团队提了一些反馈意见（Bug），并且赞助 Cocoapods 团队去开发 xcframework 相关的功能，文章里简短地介绍了 SPM 的接入流程和遇到的问题，感兴趣的朋友可以看一下，在这里也感谢他们对开源社区的回馈。
