### ISSUE TITLE
建议: 是否每一期可以加入发刊日期,

### ISSUE THREAD

**Issue by RedRainDHY** [SwiftOldDriver/iOS-Weekly#240]
建议: 周报中的一些信息是具有时效性的同时为了方便和时间对应, 是否每一期可以加入发刊日期
 例如: 
- 2018-12周
- 2018年3月第3期
- 正文顶部加入发刊日
  - 码农周刊第208期（2018-03-20）

**Comment by ParsifalC** [comment]
很好的建议，我们会沟通下选择一种方式添加下。感谢反馈！

**Comment by RedRainDHY** [comment]
感觉编辑们付出!!! 加油~ (๑•̀ㅂ•́)و✧加油

**Comment by lacklock** [comment]
加入发刊日期是一个好主意。

**Comment by ParsifalC** [comment]
@RedRainDHY 已在[最新的第十二期](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%2312-2018.03.25.md)中加入发刊时间，之后每期也都会增加，再次感谢建议，欢迎继续关注我们周报，随时提供您的想法与建议。
