### ISSUE TITLE
想用 Docker 部署 Flutter Web 应用，咋办？

### ISSUE THREAD

**Issue by OHeroJ** [SwiftOldDriver/iOS-Weekly#2405]
# 推荐收录

## 链接

https://juejin.im/post/6876759421003923470

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
感谢自荐。不过这篇内容太过少了，知识点对于移动端也不是很主流，如果是一篇比较完整的基于 Flutter Web 搭建博客的科普教程，倒是可以考虑下。
