### ISSUE TITLE
不会吧，这也行？iOS后台锁屏监听摇一摇

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2418]
# 推荐收录

## 链接

https://juejin.im/post/6881420727371694093

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [iOS 后台锁屏也能监听摇一摇？](https://juejin.im/post/6881420727371694093)

[@享耳先森](https://github.com/iblacksun)：直觉来说，iOS App 如果进入后台了能做的东西就非常少了，碰到「后台检测手机摇一摇」类需求时如何实现呢？作者给出了完整的研究和实现过程。
