### ISSUE TITLE
Overriding UserDefaults for improved productivity

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2419]
# 推荐收录

## 链接

https://www.avanderlee.com/xcode/overriding-userdefaults-launch-arguments/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
应用内的 UserDefaults 是一个易于访问的数据存储，用于保存状态，统计信息和其他与应用程序相关的数据。我们可以通过配置启动参数覆盖 UserDefaults 的数据，
无需修改代码，更改 UserDefaults 默认值，提高开发效率。
