### ISSUE TITLE
What does @main do in Swift 5.3?

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2420]
# 推荐收录

## 链接

https://useyourloaf.com/blog/what-does-main-do-in-swift-5.3/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
之前 [2020-04-27](https://github.com/SwiftOldDriver/iOS-Weekly/blob/6c9d8336a2efe1399d02c5c68b02f25d7b072346/Reports/2020/%23111-2020.04.27.md#-se-0281-main-type-based-program-entry-points) 和 [2020-08-31](https://github.com/SwiftOldDriver/iOS-Weekly/blob/0b89dfd4a8e842201261b163891c70c8107ba686/Reports/2020/%23126-2020.08.31.md#-entry-points-in-swift-how-main-and-uiapplicationmain-work-internally) 都有介绍过这个特性，而且 @main 本身也很简单，没有太多可讲的东西，这篇还是不推荐了。
