### ISSUE TITLE
使用 GitLab Runner 和 Fastlane 构建持续集成环境

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#244]
https://medium.com/flawless-app-stories/how-to-set-up-gitlab-continuous-integration-for-ios-projects-without-a-hustle-53c2b642c90f

GitLab CI 虽然没有 Travis CI 那么强大，但考虑到比较多的私有项目都是存在 GitLab 上的，使用 GitLab CI 与 Fastlane 配合使用在大型团队中也是很有用的。

**Comment by iblacksun** [comment]
### 🐢 [使用 GitLab Runner 和 Fastlane 构建持续集成环境](https://medium.com/flawless-app-stories/how-to-set-up-gitlab-continuous-integration-for-ios-projects-without-a-hustle-53c2b642c90f)

相信很多团队都在用 `GitLab` 作为源码管理工具，本文介绍如何使用 `GitLab Runner` 和 `Fastlane` 构建 iOS 持续集成环境

> 如果你还没有使用 `Fastlane`，别等了，现在开始用起来吧。
