### ISSUE TITLE
还记得苹果 HomePod 广告里会动的公寓吗？它们竟然是这样拍出来的

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#245]
http://www.ifanr.com/1000374

赏心悦目。

**Comment by raozhizhen** [comment]
挺好玩的  但好像技术不一定会感兴趣，你们觉得呢？

**Comment by ParsifalC** [comment]
我觉得挺有意思的😄，iOS 开发很多都是果粉吧，苹果的广告一直很有创意，我个人每次也都会多看看相关的东西。
