### ISSUE TITLE
Swift, Wasm, and Algorithms

### ISSUE THREAD

**Issue by SunsetWan** [SwiftOldDriver/iOS-Weekly#2452]
# 推荐收录

## 链接

https://garrepi.dev/swal
https://github.com/johngarrett/swal-wasm

## 理由

在这个项目里，开发者可以实时观察和学习使用 [Swift Algorithms](https://github.com/apple/swift-algorithms) 中的 API。这有助于开发者快速上手 [Swift Algorithms](https://github.com/apple/swift-algorithms) 这个官方库。
## 推荐人信息
sunset，iOS 开发初级工程师。

**Comment by zvving** [comment]
感谢 @SunsetWan 推荐，swal 思路不错，值得推荐。不过目前完成度还太低（只有 3 个 func），当前对开发者使用意义不大。

我先把 issue 关掉，建议完成度高一些后，再推荐到周报里。
