### ISSUE TITLE
Slow Swift Compiler Performance

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2485]
# 推荐收录

## 链接

https://useyourloaf.com/blog/slow-swift-compiler-performance/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by EyreFree** [comment]
内容简单无新意，关闭了...

Swift 编译时间相关优化可参考：

https://github.com/fastred/Optimizing-Swift-Build-Times
