### ISSUE TITLE
Swift overloading and @_disfavoredOverload

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2493]
# 推荐收录

## 链接

https://fivestars.blog/swift/disfavoredOverload.html

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Swift overloading and @_disfavoredOverload](https://fivestars.blog/swift/disfavoredOverload.html)

[@四娘](https://kemchenj.github.io/)：Swift 允许我们定义多个同名函数，并且有不同的返回值和参数，但有时候重载会引起歧义，了解 Swift 的重载规则有助于解决或者避免不必要的歧义，这篇文章还介绍了一个 SwiftUI 里大量使用的私有注释 `@_disfavoredOverload`，感兴趣的朋友可以看一下。
