### ISSUE TITLE
Apple announces App Store Small Business Program

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2497]
# 推荐收录

## 链接

https://www.apple.com.cn/newsroom/2020/11/apple-announces-app-store-small-business-program/

## 理由

苹果宣布小型商业扶持计划，从明年 1 月份开始，年收入不到 100 万美元的开发商只抽成 15%。（Epic 你坐下，你还是 30%）

**Comment by ParsifalC** [comment]
https://www.apple.com.cn/newsroom/2020/11/apple-announces-app-store-small-business-program/

用这个中文链接吧

**Comment by JonyFang** [comment]
> https://www.apple.com.cn/newsroom/2020/11/apple-announces-app-store-small-business-program/
> 
> 用这个中文链接吧

👍
