### ISSUE TITLE
Inspect your iOS application at runtime -- Peek 

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#250]
https://github.com/shaps80/Peek
Peek 5.0 全新发布

**Comment by kemchenj** [comment]
-1

我试了一下 Demo，感觉这个框架的定位有点小尴尬，通过手势可以呼出调试窗口，查看 view 的各个属性。

但是对于**开发者**来说，我们有更好的工具，基本的操作都可以通过 Xcode 来完成，而且更加方便，不用在模拟器里点来点去，如果使用 Reveal 的话更加方便，可以在局域网内直接无线 Debug。

而对于**测试人员**来说，光是暴露一个 view 的最终的呈现结果出来其实作用并不大，因为 frame 错了或者颜色错了这些肉眼基本上就可以看出来了，而指望 QA 看懂 AutoLayout 或者 CALayer 的属性也不抬可能，另外一个是对于测试来说熟悉这些属性的学习成本太高。Peek 其中一个亮点是可以通过把某个 view 当前的属性全部导出然后通过 Share Sheet 分享出来，但默认所有属性都是没有选中的，需要点选的，没有全选按钮...，QA 可能也没办法判断说哪些属性跟 bug 有关，可能还不如一张截图来得直接。
