### ISSUE TITLE
Dark Mode 一篇吃透，搞定“暗黑/深色”适配|UI|教程|海边来的设计师 - 原创文章 - 站酷 (ZCOOL)

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2509]
# 推荐收录

## 链接

https://www.zcool.com.cn/article/ZMTAzNzQ5Mg==.html

**Comment by raozhizhen** [comment]
本文讲述 APP 中各组件适配 Dark Mode（暗黑模式 或 深色模式）的方式和注意事项，以及一些细节的处理建议。
但更重要的，是让大家掌握适配暗黑模式的工作量。避免轻易开工，导致进退两难。
- 从“层级”、“颜色”两方面讲述 iOS 安卓适配方法。
- 讲述 Dark 适配需要关注的细节：字色、图标、插图等
- Dark 适配的难点：适配场景多，Dark 模式下无障碍阅读的适配，以及容易出现遗漏。
