### ISSUE TITLE
UIView 动画降帧探究

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#2512]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/EcVrrT1M4mI4f4d2b3qV0Q

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
上期刚推过的。
