### ISSUE TITLE
App Store Connect 放假安排：12月23日-27日

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2513]
# 推荐收录

## 链接

请确保您的 App 为最新版本，以准备迎接假期。App Store Connect 在12月23日至27日（太平洋时间）期间不接受新 App 和 App 更新，因此请提前处理任何与发布相关的计划、提交和审批事宜。其他 App Store Connect 功能将不受影响。

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
https://developer.apple.com/news/?id=83m4plrb
