### ISSUE TITLE
MongoDB Realm 使用初体验

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2516]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/HhhqkHtu9P1hib9L2Miyhg

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [MongoDB Realm 使用初体验 ｜ 奇谈](https://mp.weixin.qq.com/s/HhhqkHtu9P1hib9L2Miyhg)

Realm 是一个专门为移动端设计的数据库。主要特点是性能好，易使用。MongoDB 是一个流行的 NoSQL 数据库，主要是在服务器端使用。MongoDB 收购 Realm 半年后推出全新的 MongoDB Realm。移动端的数据库还是 Realm，本地的数据存取接口几乎保持一致。通过 Realm sync 这个程序把数据同步到 MongoDB Atlas 中。本文介绍了 MongoDB Realm 的基本功能和使用方法。
