### ISSUE TITLE
DispatchSource: Detecting changes in files and folders in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2518]
# 推荐收录

## 链接

https://swiftrocks.com/dispatchsource-detecting-changes-in-files-and-folders-in-swift.html

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [DispatchSource: Detecting changes in files and folders in Swift](https://swiftrocks.com/dispatchsource-detecting-changes-in-files-and-folders-in-swift.html)

[@四娘](https://kemchej.github.io/)：GCD 里的 DispatchSource 家族包含了一系列监听系统事件的 API，例如 Mach 事件通知，文件变更通知等等，在这篇文章里，作者以日志为例展示了这套 API 的使用方式，感兴趣的同学可以看看。
