### ISSUE TITLE
Adding Views and Modifiers to the Xcode Library

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2527]
# 推荐收录

## 链接

https://useyourloaf.com/blog/adding-views-and-modifiers-to-the-xcode-library/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
关闭原因：跟内参文章重叠（https://xiaozhuanlan.com/topic/6920751348）
