### ISSUE TITLE
张星宇的 2017 年度总结

### ISSUE THREAD

**Issue by raozhizhen** [SwiftOldDriver/iOS-Weekly#253]
https://github.com/bestswifter/blog/blob/master/articles/2017-conclusion.md

今年张星宇学了很多东西，让人对比起来觉得自己又划水一年，

觉得挺有意义的，如果也能通过他的总结来审视自己过去的一年，应该会有收获

**Comment by EyreFree** [comment]
## [bestswifter 的 2017 年度总结](https://github.com/bestswifter/blog/blob/master/articles/2017-conclusion.md)

百度 iOS 大佬 bestswifter 的 2017 年度总结，回顾了他一年的所学内容并且穿插了相应知识点的总结博文，对比 / 对比我们自己过去一年的学习与生活，或许能够使我们每个人有所感悟或收获。
