### ISSUE TITLE
滴滴开源小桔棱镜：一款专注移动端操作行为的利器

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#2538]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/Cc-8BMoJGacPCeHnMs6Ekw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
上周推荐过了。
