### ISSUE TITLE
A helper for working with temporary files in Swift

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#254]
https://oleb.net/blog/2018/03/temp-file-helper/

编辑器为了在非正常退出的情况下总是会使用一个临时文件去保留当前编辑进度，很多其它情况我们也需要有临时文件的存在。Ole 想到了一种抽象去把这些模版代码封装了起来...

**Comment by lacklock** [comment]
虽然感觉很简单，但是感觉抽象出来确实也有一点好处

**Comment by iblacksun** [comment]
相信大家在 App 中经常需要操作临时文件，但文件的维护是件麻烦事，`Ole Begemann
` 对此进行了封装。
