### ISSUE TITLE
一个map家族常用场景吹一波Swift

### ISSUE THREAD

**Issue by cgcym1234** [SwiftOldDriver/iOS-Weekly#2541]
# 推荐收录

## 链接

[一个map家族常用场景吹一波Swift](https://juejin.cn/post/6899711727298936840)

## 理由

通过Swift中一个map家族常用场景结合链式语法，来体现Swift语法的简洁，优雅。

## 推荐人信息

自己

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
全文整体思路没问题，是链式调用的典型场景，局部有优化空间。

为了使用 flatmap 解包，不得不引入括号避免歧义。带来的问题可能比好处更大。拆分语句整体可读性更好些。

可能会让新手片面追求链式调用，暂不推荐

**Comment by cgcym1234** [comment]
关于这点文章里面有提到是特意的哦，使用URLComponents(string:)，而不是URLComponents(url:, resolvingAgainstBaseURL:)可以多遇到一个问题，就是括号的问题，只是顺便展示下解决方案。
使用后面的API就不会哦：url.flatMap { URLComponents(url: $0, resolvingAgainstBaseURL: true) }?，不会有括号。
