### ISSUE TITLE
App 内购买项目现已支持“家人共享”功能

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2544]
# 推荐收录

## 链接

https://developer.apple.com/cn/news/?id=4zbvn7u9

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [App 内购买项目现已支持「家人共享」功能](https://developer.apple.com/cn/news/?id=4zbvn7u9)

 [@享耳先森](https://github.com/iblacksun)：现在，开发者可以为自动续期订阅和非消耗型内购买项目启用「家庭共享」功能，从而允许用户与最多 5 位其他家庭成员共享购买内容。
