### ISSUE TITLE
Diversity in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2561]
# 推荐收录

## 链接

https://swift.org/blog/diversity-in-swift/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
目前只有两篇文章，更多是对 swift 开源社区多样性的倡导和鼓励，暂时不合适周报推荐，有更多内容再看
