### ISSUE TITLE
通过实际开发中的调试惨案，介绍了 insetsLayoutMarginsFromSafeArea  这个大家不太熟悉的属性的作用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#258]
https://juejin.im/post/5aae37576fb9a028bf051a2c

**Comment by mmoaay** [comment]
作者通过实际开发中的调试惨案，介绍了 insetsLayoutMarginsFromSafeArea 这个大家不太熟悉的属性的作用。另外推荐大家看一下 **《iOS成长之路3期·WWDC17内参》**中的文章[让你的 UI 适配 iOS 11 吧](https://xiaozhuanlan.com/topic/8497036152)，文章对包括 Safe Area 在内的 Layout Margin 有很详细的介绍。
