### ISSUE TITLE
LLDynamicLaunchScreen

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2584]
# 推荐收录

## 链接

https://github.com/internetWei/LLDynamicLaunchScreen

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by GesanTung** [comment]
作者 引用 https://github.com/iversonxh/DynamicLaunchImage 开源库，多处代码连注释都一致，但并未给出引用出去或鸣谢，真不要脸
