### ISSUE TITLE
Preventing Data Races in the Swift Concurrency Model

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2585]
# 推荐收录

## 链接

https://forums.swift.org/t/preventing-data-races-in-the-swift-concurrency-model/43175
https://gist.github.com/DougGregor/10db898093ce33694139d1dcd7da3397

## 理由

Swift 核心成员 Doug 写了一篇文章，介绍 Swift 加入了新的并发模型之后，有哪些方式可以避免数据竞争。

**Comment by iblacksun** [comment]
### 🐢 [Preventing Data Races in the Swift Concurrency Model](https://gist.github.com/DougGregor/10db898093ce33694139d1dcd7da3397)

[@享耳先森](https://github.com/iblacksun)：并发一直是现代语言的重要部分，根据 Swift Roadmap，预计 Swift 6.0 将推出基于协程的 async/await 模型及新的 Actor Isolation 并发模型，Swift 核心成员 Doug 写了一篇文章，介绍 Swift 加入了新的并发模型之后，有哪些方式可以避免数据竞争。
> 参考：
- [Swift Concurrency Roadmap](https://forums.swift.org/t/swift-concurrency-roadmap/41611)
- [Protocol-based Actor Isolation: Draft #2](https://docs.google.com/document/d/1BEO6QwzcYCUhaGyA-WRoM_phRa7O7mGPNIMdSV4StEE/edit)
