### ISSUE TITLE
从babel讲到AST

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#259]
https://juejin.im/entry/5ab35c5af265da23906bec8c

Babel是前端里使用的把JS的ES6语法转换成JS的ES5语法，虽然是前端才会用到，这里面确包含一些编译方面的知识，客户端，前端，各个语言都可以学习与参考

本文介绍了纯字符串的代码，机器是如何分析，如何理解，最后整合成机器可以识别，运算，遍历，处理的抽象语法树 AST

**Comment by aaaron7** [comment]
上面已经有了简单的介绍，是需要写另外一个版本？

**Comment by Awhisper** [comment]
@aaaron7 我猜应该是 assign的人应该和提议者不是同一人，这样保证每个link 至少2个编辑推荐，由assign人录入周报，至于内容要不要重写，就随意了，我觉得都还好，assign人自己定就好了

**Comment by aaaron7** [comment]
Done
