### ISSUE TITLE
离线Hybrid容器如何做到接近100%秒开？

### ISSUE THREAD

**Issue by GesanTung** [SwiftOldDriver/iOS-Weekly#2607]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/inAFLg85TfmXOWXS50pEfg

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by authorRen** [comment]
本文介绍了Hybrid从交互体验到性能优化等多维度的提升与改善，让Hybrid容器在正常情况下几乎达到100%秒开的效果
