### ISSUE TITLE
AudioKit

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#263]
https://github.com/AudioKit/AudioKit

**Comment by lacklock** [comment]
这个库其实很多人都知道了，如果没有特别的事件感觉不太合适推

**Comment by RedRainDHY** [comment]
我认为可以加一个著名库<名人堂>的模块, 每一期可以推荐1~2个, 
我觉得这类东西是常转常新, 而且`老司机`关注人群越来越多,  就当科普也不错.

**Comment by ParsifalC** [comment]
@RedRainDHY 这个想法很有意思，其实我们目前对于这些已经被较多人熟悉的开源库上周报的标准是有较大版本更新，这样受众会更多些。不过现在这些更新我们没有单独列出一个模块做，我们会再讨论下你的这个建议的。感谢反馈。

**Comment by RedRainDHY** [comment]
辛苦各位了!  (๑•̀ㅂ•́)و✧加油
