### ISSUE TITLE
swift-create-xcframework

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2649]
# 推荐收录

## 链接

https://github.com/unsignedapps/swift-create-xcframework

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/2021/%23146-2021.01.25.md#swift-create-xcframework

**Comment by ParsifalC** [comment]
ok
