### ISSUE TITLE
Is Apple Banning Free Analytics SDKs?

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2656]
# 推荐收录

## 链接

https://steamclock.com/blog/2021/02/apple-tracking-analytics-sdks

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Is Apple Banning Free Analytics SDKs?](https://steamclock.com/blog/2021/02/apple-tracking-analytics-sdks/)

[@享耳先森](https://github.com/iblacksun)：iOS 14.5 发布时间临近，新版系统中，如果 App 使用了 IDFA，系统将请求用户授权，本文探讨了新的隐私机制对 App 开发者及统计 SDK 开发者有哪些影响，以及改如何应对。
