### ISSUE TITLE
从预编译的角度理解Swift与Objective-C及混编机制

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2662]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/gI9vL1KlHuMzMoWWf2tnIw

**Comment by iblacksun** [comment]
### 🌟🐢  [从预编译的角度理解 Swift 与 Objective-C 及混编机制](https://mp.weixin.qq.com/s/gI9vL1KlHuMzMoWWf2tnIw)

[@享耳先森](https://github.com/iblacksun)：相信不少 iOSer 对于编译器如何将你的源码编译成可执行文件一直都是一知半解，本文从编译器预编译阶段的如何查找头文件开始，深入剖析项目中使用到的技术和各种参数的作用，由此来指导开发者如何进行混编。
