### ISSUE TITLE
我在Uber亲历的最严重的工程灾难

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#2671]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/T1RqYrCTOpQvkWdunoxqww

**Comment by ParsifalC** [comment]
原文之前推荐过，我更新下译文吧，就不重复推了，https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/2020/%23140-2020.12.14.md#-uber-%E5%B7%A5%E7%A8%8B%E5%B8%88%E4%BA%B2%E8%BF%B0%E4%BD%BF%E7%94%A8-swift-%E9%87%8D%E5%86%99-app-%E7%9A%84%E6%83%A8%E7%97%9B%E7%BB%8F%E5%8E%86
