### ISSUE TITLE
Flutter 2.0 发布 | 针对 Web，移动端和桌面端构建的下一代 Flutter

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#2674]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/rqf4tJR23Yzf3L3J5JY3Qw

**Comment by AlexV525** [comment]
你们呐，用着别人的标题，推荐另一个人的文章，做事还是要干净点。

**Comment by ParsifalC** [comment]
> 你们呐，用着别人的标题，推荐另一个人的文章，做事还是要干净点。

修改了，不过澄清一下，issue 只是我们作为 todo list 使用，正式推荐是在文章里。issue 确实这里之前疏忽了没改过来，正文推荐是没有错的。
