### ISSUE TITLE
Swift 5.4 新特性

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2679]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/p6oeWwcgJJFqP2NgYaJXYw

**Comment by kemchenj** [comment]
## [Swift 5.4 新特性](https://mp.weixin.qq.com/s/p6oeWwcgJJFqP2NgYaJXYw)

[@四娘](https://kemchenj.github.io)：之前我们介绍过 Hacking Swift 写的 [What's New in Swift 5.4](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/2021/%23148-2021.02.08.md#-whats-new-in-swift-54)，最近知识小集翻译了中文版。

按照往年的时间安排，包含 Swift 5.4 的 Xcode 11.5 大概会在这个月的月底发布，之前还没看过的朋友可以趁这个机会提前了解一下 Swift 5.4 的新特性。
