### ISSUE TITLE
cocos 认为区块链技术在游戏上的使用可能

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#268]
http://www.cocoachina.com/blockchain/20180327/22792.html

**Comment by Awhisper** [comment]
标题：区块链游戏，其实也没什么神秘的

Cocos2dx宣布开发基于区块链的游戏引擎，给现在火爆的区块链圈子又多了一种应用形态。每个游戏有自己的游戏金币货币与金融交易体系，发币与交易在游戏里是一个很自然并且有意义的事情，而区块链技术能给现在的游戏价值体系解决了一些问题
1 跨游戏之间的金币流通
2 玩家点对点去中心化的可信道具交易
3 游戏智能合约防止游戏公司，增发减法随意调控游戏物价，洗用户
先写一半。。要出门。。。回来继续写
