### ISSUE TITLE
听说你想写个 shell

### ISSUE THREAD

**Issue by silan-liu** [SwiftOldDriver/iOS-Weekly#2681]
# 推荐收录

## 链接

[听说你想写个 shell](https://mp.weixin.qq.com/s?__biz=Mzg4MjU2Mzc1MQ==&mid=2247484944&idx=1&sn=3366f8efc0d21d0b598a9333b1782d45&chksm=cf5589d8f82200ce12ff6bed0d4a6363927e0a41fef5cb26545a6cc03db1757ffdf3c0a1bf24&token=884735378&lang=zh_CN#rd)

## 理由

这篇文章主要介绍了 shell 是什么，以及如何动手实现 shell 的主体功能，包括等待输入命令、解析命令、执行命令、内置命令等。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
这篇整体内容还是比较简单，而且也不是那么对口，要么考虑试试 Swift 实现个？这样对于周报读者受众会广一些。

**Comment by ParsifalC** [comment]
这篇整体内容还是比较简单，而且也不是那么对口，要么考虑试试 Swift 实现个？这样对于周报读者受众会广一些。
