### ISSUE TITLE
苹果的无直播发布会

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#269]
https://weibo.com/ttarticle/p/show?id=2309404222454724750665

**Comment by raozhizhen** [comment]
发布了支持 Apple Pencil 的 9.7 寸 iPad。
芯片升级为 A10 Fusion，较上代在 CPU 性能提升了 40%，在图形运算提升了 50%。
32GB 价格由 2688 降至 2588。
除此之外，苹果还更新了一系列服务，为在校师生提供更好的授课和学习体验。
