### ISSUE TITLE
Frameworks: embed or not embed that's the question

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2694]
# 推荐收录

## 链接

https://holyswift.app/frameworks-embed-or-not-embed-thats-the-question

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
```
The "Do Not Embed" choice you are literally saying: please don't pack all the contents of this framework with the main application. This implies that the final application package will note contain a folder called (by default) Frameworks with all the framework code.
```
这篇文章读下来这边有点问题，这个 Do Not Embed，打出来的包应该是不包含 Frameworks 目录，或者是我哪边理解错了？

**Comment by nianran** [comment]
我自己试验了下，静态 Framework，Do Not Embed 是不会包含 Framework，用 Embed 才会有默认的 Framework

**Comment by nianran** [comment]
感觉有点问题，暂时先关闭了。

**Comment by ParsifalC** [comment]
> 我自己试验了下，静态 Framework，Do Not Embed 是不会包含 Framework，用 Embed 才会有默认的 Framework

他说的和你实验的一样啊？
