### ISSUE TITLE
冰霜的ML入门笔记

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#270]
https://github.com/halfrost/Halfrost-Field/blob/master/contents/Machine_Learning/contents.md

**Comment by mmoaay** [comment]
冰霜的文章在一直都是以深入全面、通俗易懂著称。《冰霜的 ML 入门笔记》包含了他在学习斯坦福机器学习视频课程的全部笔记。如果你没有足够的时间去看这些视频，或者听英文的能力没有那么强，这些笔记对你来说一定非常有用了，而且你也不用担心会错过视频中的一些内容，因为这些笔记和冰霜以往的风格一样，内容比视频只多不少。
