### ISSUE TITLE
对iOS架构的见解深刻且务实

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#271]
https://medium.com/@martinmitrevski/pragmatic-ios-app-architecture-f7d6334fd8e4

**Comment by iblacksun** [comment]
### 🐢 [Pragmatic iOS app architecture](https://medium.com/@martinmitrevski/pragmatic-ios-app-architecture-f7d6334fd8e4)

文章从多个角度评估一种架构是否适合你的项目，并从经典的 `MVC` 一路引申到 `RXSwift`、`MVVM`、`VIPER`，值得细读。
