### ISSUE TITLE
Writing High-Performance Swift Code

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2711]
# 推荐收录

## 链接

https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst

**Comment by kemchenj** [comment]
### [Writing High-Performance Swift Code](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst)

[@四娘](https://kemchenj.github.io)：
