### ISSUE TITLE
新工具开源！一款iOS自动化利器

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2712]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/P95Fr93mlf5CvV02-Oi9zw

**Comment by ParsifalC** [comment]
https://github.com/SwiftOldDriver/iOS-Weekly/blob/323c960090366d14830fd9b461b3bbf29ecd0b2b/Reports/2021/%23148-2021.02.08.md#tidevice

这个也推过了
