### ISSUE TITLE
What’s New in Swift 4.1

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#272]
Xcode 9.3 发布，随之而来的是 Swift 4.1

https://www.raywenderlich.com/187826/whats-new-in-swift-4-1

**Comment by lacklock** [comment]
知识小集翻译了： https://mp.weixin.qq.com/s/2PNE2yPIiyn4y-cqHZgWiQ

**Comment by kemchenj** [comment]
### [Swift 4.1 新特性概览](https://mp.weixin.qq.com/s/2PNE2yPIiyn4y-cqHZgWiQ)

这周 Swift 4.1 伴随着 Xcode 9.3 一起发布了，没有破坏性的 API 修改，大幅优化编译速度，并且还加入了几个实用的小功能，知识小集在这篇文章里给我们深入介绍了新增的特性，强烈推荐大家在代码迁移之前过一遍这篇文章！！！
