### ISSUE TITLE
Exploring some of the lesser-known, built-in Formatter types

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2730]
# 推荐收录

## 链接

https://www.swiftbysundell.com/articles/exploring-some-of-the-lesser-known-formatter-types/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [Exploring some of the lesser-known, built-in Formatter types](https://www.swiftbysundell.com/articles/exploring-some-of-the-lesser-known-formatter-types/)

[@享耳先森](https://github.com/iblacksun)：开发者们对常用的 `NumberFormatter` 和 `DateFormatter` 可能比较熟悉，本文介绍了 Foundation 库里其他好用的 Formatter，如 `PersonNameComponentsFormatter` `CNPostalAddressFormatter` `RelativeDateTimeFormatter` 等
