### ISSUE TITLE
DWARF文件初探——提取轻量符号表

### ISSUE THREAD

**Issue by pilaf-king** [SwiftOldDriver/iOS-Weekly#2733]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/s8iwQLNtla5nxF_Tmj2wJg
## 理由

从实践出发，一步步介绍如何实现提取轻量符号表
## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
@pilaf-king 
文章上提几个小建议
1. 缩短一下符号内容。
2. 可以添加适当 Demo ，🌰：已还原某一行为例，已例子触发，去看符号表，能加深印象
