### ISSUE TITLE
跪求 cocoapods-hmap-prebuilt源码

### ISSUE THREAD

**Issue by YanGuang-Chang** [SwiftOldDriver/iOS-Weekly#2747]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
https://mp.weixin.qq.com/s/uBpkelG8q_xmskWPYyWONA，其实文章已经讲得比较清楚了，咨询过相关人员，美团目前没有这方面的开源计划。

**Comment by chenxGen** [comment]
老哥可以看看我这个：https://github.com/chenxGen/cocoapods-project-hmap
