### ISSUE TITLE
Bringing Polymorphism to Codable

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2748]
# 推荐收录

## 链接

https://lostmoa.com/blog/BringingPolymorphismToCodable/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
Struct 使用 Codable 有一定的简化，但不支持 Class 继承，应用很有限，暂不推荐
