### ISSUE TITLE
TextBuilder

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2749]
# 推荐收录

## 链接

https://github.com/davdroman/TextBuilder

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
模仿 ViewBuilder，基于 [Result builders](https://github.com/apple/swift-evolution/blob/main/proposals/0289-result-builders.md)，实现 TextBuilder。可以方便的通过 String 不定参数快速生成 Text 视图，支持自定义分隔符。

Result builders 在 Swift5.4 中实现（unreleased），repo 实现也比较简单，暂不推荐。
