### ISSUE TITLE
Avoiding SwiftUI’s AnyView

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2762]
# 推荐收录

## 链接

https://www.swiftbysundell.com/articles/avoiding-anyview-in-swiftui/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这篇文章开篇就抛出结论，说 SwiftUI 会使用一套基于类型的算法去追踪哪些 View 需要被更新，由此得出 AnyView 会造成性能问题，但这一套结论并没有很好的证明。

并且 SwiftUI 刚发布的时候就有人做过测试 [Performance Battle: AnyView vs Group](https://nalexn.github.io/anyview-vs-group/)，测试结果表示使用 AnyView 并不会产生明显的性能差异，甚至部分情况下会更好，虽然 Swift 开发团队的成员有[提到这个 benchmark 有点不太准确](https://twitter.com/jckarter/status/1203409740019073024)，但也没有给予否定，而且[重新生成 View 也不一定比更新 View 的性能更好](https://github.com/Instagram/IGListKit/blob/4.0.0/Source/IGListDiffKit/IGListExperiments.h#L22)。

后面的内容也只是提到可以使用泛型和 ViewBuilder 去避免 AnyView，我觉得推荐价值不大。
