### ISSUE TITLE
iOS 11.3 正式发布

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#278]
https://www.apple.com/newsroom/2018/03/ios-11-3-is-available-today/

虽然只是个小版本更新，但由于『降频门』事件，且这个版本更新的内容还是相对较多的，感觉还是能作为一则业内新闻发布。

**Comment by iblacksun** [comment]
### [iOS 11.3 正式发布](https://www.apple.com/cn/newsroom/2018/03/ios-11-3-is-available-today/)

iOS 11.3 正式发布，针对之前的「降频门」事件，11.3 可在 “设置”->“电池” 中查看电池效能并关闭「电源管理」功能。
One more thing， 北京、上海地区用户还有专有福利，可用 Apple Pay 绑定「交通卡」，此功能与广州、杭州等地目前的 Apple Pay 支付不同，使用 NFC，刷卡时候不用「刷脸」了。
