### ISSUE TITLE
Animatable

### ISSUE THREAD

**Issue by GodL** [SwiftOldDriver/iOS-Weekly#2781]
# 推荐收录

## 链接

https://github.com/GodL/Animatable

## 理由

使用swift PropertyWrapper调用动画的一种方式

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [Animatable - 使用 PropertyWrapper 实现动画代码复用](https://github.com/GodL/Animatable)

[@享耳先森](https://github.com/iblacksun)：`PropertyWrapper` 结合 `Codable` 实现 Model 的安全解析相信大家在使用了，作者利用 `PropertyWrapper` 实现了一个 CAAnimation 复用的库，代码非常简单，可以直接跳到 Github 浏览。

> 自荐：[GodL](https://github.com/GodL)
