### ISSUE TITLE
Announcing the Swift Mentorship Program

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2786]
# 推荐收录

## 链接

https://swift.org/blog/swift-mentorship-program/

小集译文：https://mp.weixin.qq.com/s/0B7kTL3UkvA_Nfpkzy7jUw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Announcing the Swift Mentorship Program](https://swift.org/blog/swift-mentorship-program/)

> [知识小集译文](https://mp.weixin.qq.com/s/0B7kTL3UkvA_Nfpkzy7jUw)：近日，Swift 官方针对 Swift 社区的新贡献者，发布了 Swift 导师计划。这一计划旨在为成为 Swift 项目积极开源贡献者的开发人员提供帮助与支持，同时可以获得社区中经验丰富的贡献者的直接指导。
> 
> 参与计划的每位开发者都有机会与 Swift 社区中经验丰富的开发人员联系，并向他们学习。同时，根据自己的学习目标，开发者可以为 Swift 项目甚至 Swift 编译器项目贡献代码。社区会根据学习目标来匹配开发者和导师，并让他们一起在开源项目上合作 12 周时间。
> 
> 一方面，对于新贡献者而言，降低了贡献代码的准入门槛，不需要事先为项目做出贡献，同时能提升更多的技能；另一方面，对于导师来说，也是一个不错的增加领导技能的机会。对于双方而言，都是有益的。
> 
> 感兴趣的小伙伴们，特别是在校的学生朋友们，可以考虑加入这一计划，相信一定能从中受益匪浅。该计划的详情可点击原文链接查看。
