### ISSUE TITLE
 AAChartKit ios上开源图表库

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#279]
https://github.com/AAChartModel/AAChartKit

**Comment by ParsifalC** [comment]
这个其实是和 #263 的性质是一样的，这些工具类库都是开发维护挺久的了，也可能已经被很多人知晓，我们是不是需要重新考虑对于这类信息的定位和标准是什么样的？

**Comment by Awhisper** [comment]
其他人咋看捏

**Comment by lacklock** [comment]
@zangqilong198812 觉得这条要加吗、？

**Comment by zangqilong198812** [comment]
感觉我们不是github trending ，库不是重点吧。

**Comment by Damonvvong** [comment]
对于开源库的话我感觉可以从下面几点去考虑：

1.  开源时间，越新越好~
2. 功能支持越完善越好，简单的几个功能就没必要了。（当然我觉得比较有新意也是可以的）
3. 代码质量也要有所保证。

不知各位怎么看？
