### ISSUE TITLE
在 UIKIt 中使用类 SwiftUI 的语法糖

### ISSUE THREAD

**Issue by foxsin10** [SwiftOldDriver/iOS-Weekly#2791]
# 推荐收录

## 链接

[UStack](https://github.com/foxsin10/UStack)

## 理由

更加直观的 `viewTree` 结构，更少的代码
<img width="639" alt="WX20210516-204122@2x" src="https://user-images.githubusercontent.com/11630650/118397606-74b82f00-b687-11eb-8f53-cf2f8bd69434.png">

## 推荐人信息

[foxsin10](https://github.com/foxsin10)

**Comment by raozhizhen** [comment]
库的使用场景看起来有点小，暂时不太适合推荐哈~
