### ISSUE TITLE
普通技术人的成长路径 - 一位客户端老兵的经验之谈

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2798]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/IrSQyyc0J3SXBuWs9M3SYA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Awhisper** [comment]
fixed
