### ISSUE TITLE
巧妙的接近一个动画完成后开始另外一个动画的场景，链式动画的思路。

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#280]
https://twittemb.github.io/swift/animations/reactive%20programming/rxswift/2018/03/24/elegantly-chaining-uiviewpropertyanimators

**Comment by raozhizhen** [comment]
在 iOS 10 之前，如果想按顺序播放动画，会通过 UIView.animate() 里的 completed blok 嵌套起来。
代码看起来并不优雅。iOS 10 引入了面向对象版本的 UIViewPropertyAnimator。
它允许将每个动画的定义与它们连接方式区分开来。拥有更好的可读性，也方便解耦。
还可以将 UIViewPropertyAnimation 兼容 RxSwift，通过“完成流”将所有的动画连接起来。
然而还有更为巧妙的实现方式，通过自定义操作符，连接两个 UIViewPropertyAnimator 对象，
最终效果：self.animator1 ~> self.animator2 ~> self.animator3 ~> self.animator4。
