### ISSUE TITLE
源码级调试 App Store 包

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#2805]
# 推荐收录

## 链接

https://blog.indigo.codes/2021/05/23/debug-your-app-store-app/

**Comment by iostalks** [comment]
你是否曾为本地 Debug 没问题，Release 包却能稳定复现 Bug 而感到苦难？本文作者 @靛青 介绍了如何从一个壳工程开始，一步步实现调试 AppStore / TestFlight 包。

文中提供了自动化构建调试工程的脚本，你只需要提供自己的 ipa 和 dSYM 文件，使用少量的 `lldb` 命令，即可完成源码级断点调试。
