### ISSUE TITLE
硅谷生活半年记

### ISSUE THREAD

**Issue by raozhizhen** [SwiftOldDriver/iOS-Weekly#281]
https://mp.weixin.qq.com/s/ydHLBmt0FpNwgvCKTCnnVw

**Comment by raozhizhen** [comment]
北京，上海，深圳，杭州。我们都在想自己将来要定居何处。
文章写了大量自己的切身感受，以及丰富的配图，去展现湾区的生活。
多了解一点，未来也多一种选择

**Comment by EyreFree** [comment]
# [硅谷生活半年记](https://mp.weixin.qq.com/s/ydHLBmt0FpNwgvCKTCnnVw)

作者对自己最近半年在硅谷切身经历的小结，从医、食、住、行、环境、薪酬等方面对硅谷生活进行了介绍并与国内做了简单对比，同时配以大量图片，让我们了解了一种完全不同的生活方式的同时，也给我们对未来的规划提供了些许参考。
