### ISSUE TITLE
The iOS Developer’s guide to WWDC 2021

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2817]
# 推荐收录

## 链接

https://www.donnywals.com/the-ios-developers-guide-to-wwdc-2021/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
WWDC21 开幕在即，Xcode/iOS/macOS/... beta 版本、大量更新内容集中释出，作者告诉我们不必着急追赶咨询，而是以自己的节奏通过 State of the Union，Lab 去筛选了解感兴趣的新内容，以及值得学习的最佳实践。

本文内容比较基础，闲聊比较多，不建议推荐。

不过下周 WWDC21，可以周报第一条建议加 WWDC21 及老司机/swiftgg 活动的引导 cc @ParsifalC @Damonvvong
