### ISSUE TITLE
Swift for TensorFlow - TFiwS (TensorFlow Dev Summit 2018)

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#282]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ✅] I have read the [README.md](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/README.md), but there is no information I need.
- [ ❎] I have searched in [existing issues](https://github.com/SwiftOldDriver/iOS-Weekly/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description
- Swift for TensorFlow - TFiwS (TensorFlow Dev Summit 2018)
https://www.tensorflow.org/community/swift
https://www.youtube.com/watch?v=Yze693W4MaU&feature=youtu.be
https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/xtXCEvtDe5Q

**Comment by lacklock** [comment]
代码还没开源，所以这条应该算新闻。

**Comment by iblacksun** [comment]
### [Swift for TensorFlow](https://www.tensorflow.org/community/swift)

TensorFlow 社区在 TensorFlow Dev Summit 2018 上宣布将于四月开源 Swift for TensorFlow 项目。
