### ISSUE TITLE
A Swift developer’s WWDC dreams - 2021 edition

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2820]
# 推荐收录

## 链接

https://www.swiftbysundell.com/articles/a-swift-developers-wwdc-dreams-2021

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [A Swift developer’s WWDC dreams - 2021 edition](https://www.swiftbysundell.com/articles/a-swift-developers-wwdc-dreams-2021/)

[@四娘](https://kemchenj.github.io/)：今年 SwiftBySundell 今年也在博客里分享了他作为 Swift 开发者的心愿单，包括：

- SwiftUI 提供更多可以自定义的接口
- 让所有接口都 Async/await 化
- 可交互的 Widget
- 更加强大可靠的工具链
- Xcode on iPad
- 使用 Swift 全栈开发
