### ISSUE TITLE
Swift Hook新思路--虚函数表

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2831]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/mjwOVdPZUlEMgLUNdT6o9g

**Comment by kemchenj** [comment]
### [Swift Hook新思路--虚函数表](https://mp.weixin.qq.com/s/mjwOVdPZUlEMgLUNdT6o9g)

[@四娘](https://kemchenj.github.io)：这是由 58 团队带来的文章，深入分析 Swift 的类结构以及基于 vtable 的函数调用过程，并且提出了通过修改 vtable 实现 method swizzle 的方法。
