### ISSUE TITLE
从探索到实践，iOS动态库懒加载实录

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2832]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/g5FKnOcW6KonqBSW8XO9Jw

**Comment by linlinyao1** [comment]
链接写错了

**Comment by nianran** [comment]
> 链接写错了

@linlinyao1 哪个链接？

**Comment by ParsifalC** [comment]
> > 链接写错了
> 
> @linlinyao1 哪个链接？

我之前更新过了，你看到的是对的
