### ISSUE TITLE
compactMap了解一下

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#284]
https://juejin.im/post/5abfc462f265da2377198af0

**Comment by kemchenj** [comment]
### [compactMap 了解一下？](https://kemchenj.github.io/2018-04-01/)

Swift 4.1 里将 `flatMap` 的其中一个版本重命名为 `compactMap`，但无论全局替换或者是逐个编译警告消除都不是一个好办法，这篇文章就介绍了如何使用方法重载以及重构工具，精准快速地替换掉项目里弃用掉的 `flatMap`。
