### ISSUE TITLE
WWDC 21 内参

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2843]
# 推荐收录

## 链接

https://xiaozhuanlan.com/wwdc21

## 理由

WWDC 21 圆满结束，但关于 WWDC 21 的学习才真正开始~本周我们更新了 3 篇 WWDC 21 Session 的解读，每篇文章都是经过不断推敲和审核才完成。

- [【WWDC21 10114】 初见 StoreKit 2](https://xiaozhuanlan.com/topic/6138790425)，黄骋志
- [【WWDC21 10101】使用 ReplayKit 记录你的高光时刻](https://xiaozhuanlan.com/topic/1068759324)，七夜
- [【WWDC21 10019】在 SwiftUI 中遇见并发编程](https://xiaozhuanlan.com/topic/2957164803)，Edmond

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
#2835 单独一篇不好推，建议放在这里多加一句介绍，比如：

WWDC 21 圆满结束，但关于 WWDC 21 的学习才真正开始~ 苹果官方汇总了[新技术和已有框架的重点变化](https://developer.apple.com/documentation/New-Technologies-WWDC-2021)，本周我们针对部分内容更新了 3 篇 WWDC 21 Session 的深度解读，每篇文章都是经过不断推敲和审核才完成。

- [【WWDC21 10114】 初见 StoreKit 2](https://xiaozhuanlan.com/topic/6138790425)，黄骋志
- [【WWDC21 10101】使用 ReplayKit 记录你的高光时刻](https://xiaozhuanlan.com/topic/1068759324)，七夜
- [【WWDC21 10019】在 SwiftUI 中遇见并发编程](https://xiaozhuanlan.com/topic/2957164803)，Edmond


cc @kemchenj
