### ISSUE TITLE
深入理解 WKWebView（入门篇）—— WebKit 源码调试与分析

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2853]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/VdkVBIQwj7WkAk8-5wppmQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [深入理解 WKWebView（入门篇）—— WebKit 源码调试与分析](https://mp.weixin.qq.com/s/VdkVBIQwj7WkAk8-5wppmQ)

[@享耳先森](https://github.com/iblacksun)：移动互联网时代，网页依旧是内容展示的重要媒介，开发者经常需要与 `WKWebView` 打交道，但当遇到疑难问题时官方文档不足以解惑。本系列文章介绍了如果从 WebKit 源码入手，建立可调试工程，基于此深入理解 WebKit 核心内容。
