### ISSUE TITLE
iOS Pod 构建缓存方案，避免 Pod 二进制风险

### ISSUE THREAD

**Issue by WeijunDeng** [SwiftOldDriver/iOS-Weekly#2857]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/zWhgpuhq3r799ZYQPMsdFw

## 理由

对标上周 SwiftGG 的技术沙龙的话题，同样面对Pod二进制的风险，这篇文章提出并实践了自研的一套自动化脚本，近乎完美的安全的缓存查询策略，显著的命中提速效果，较低的开销，值得交流。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by WeijunDeng** [comment]
@nianran 你好，我是作者。看到你 commit 的 "文中，作者使用 XCache 来做缓存机制。使得每次编译都是增量编译而不是全量编译~感兴趣的同学可以看下作者的适配历程~"，请问这个可以改改吗？改为"文中，作者使用基于 MD5 和 Xcode Cache 来做缓存机制。使得每次编译都是增量编译而不是全量编译~感兴趣的同学可以看下作者的方案描述~"

因为这个是完全自研的，并不是采用别人的方案，算不上适配。。

**Comment by nianran** [comment]
@WeijunDeng 
master 分支已经修改了~
刚用词不当，相关语句已经调整，加上了读者自荐，有疏漏抱歉~

**Comment by WeijunDeng** [comment]
@nianran 嗯嗯，看到了。谢谢推荐～
