### ISSUE TITLE
limboy's telescope

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2859]
# 推荐收录

## 链接

https://github.com/lzyy/telescope

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
看了一下作者分享的博客，还是都挺不错的，不过在老司机周报里没找到用于推荐这个的分类。
分享有价值的信息、文章、工具。但文章集合，或者个人博客，暂时没有这个分类，我先 close 了，有疑问我们可以微信讨论讨论哈 ~
