### ISSUE TITLE
如何在App内用Go搭建服务

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#286]
https://medium.com/@matryer/tutorial-calling-go-code-from-swift-on-ios-and-vice-versa-with-gomobile-7925620c17a4

**Comment by EyreFree** [comment]
### [Calling Go code from Swift on iOS and vice versa with Gomobile](https://medium.com/@matryer/tutorial-calling-go-code-from-swift-on-ios-and-vice-versa-with-gomobile-7925620c17a4)

本文详细介绍了作者在 iOS 工程中调用 Go 的踩坑过程，主要包括以下内容：

- 一些常见错误或意外状况，以及针对它们的解决方案；
- 怎样在 Swift 中调用一个 Go 的构造函数来创造一个 Go 的结构体实例；
- 怎样在 Go 中定义一个需要用 Swift 代码来进行实现的接口；
- 将 Swift 实现传递给 Go 的构造函数，并发起双向通信。

对 Go 在 iOS 端的应用感兴趣的同学可以看一下，应该能有不少收获。
