### ISSUE TITLE
GitHub Copilot

### ISSUE THREAD

**Issue by faimin** [SwiftOldDriver/iOS-Weekly#2863]
# 推荐收录

## 链接

[https://copilot.github.com/](https://copilot.github.com/)

## 理由

 > 以下文案转载自 GithubDaily

GitHub 与 OpenAI 联手发布了一款开发神器：GitHub Copilot，旨在借助 AI 的力量，帮助开发者快速完成代码编写，大幅提升开发效率。

开发者在 VSCode 上安装后，便可使用 Copilot，实现智能代码补全的操作。

传统的代码补全手段，大多是对函数、参数、或内置代码片段上进行快速补充，而 Copilot 则是能通过代码注释，自动生成一段完整代码。

这些代码，都是基于 GitHub 公有仓库的庞大代码量，以及 AI 对上下文的判断，自然语言的理解训练而成。

随着开源项目的不断增长，代码训练数据的持续填充，Copilot 生成的代码精准度将越来越高，而开发者的编码效率也会跃迁到一个新层次。AI 与开发者，两者相辅相成，进一步推动科技行业的发展。

2021.06.29，22:35。Copilot，一个跨时代产品诞生。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by mayingjie198448** [comment]
想知道支持中文注释吗？
