### ISSUE TITLE
深入理解 WKWebView（基础篇）—— WKWebView 加载生命周期与代理方法剖析

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2870]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/ZFui9IiMTWyLXGKZlbnzwQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [深入理解 WKWebView（基础篇）—— WKWebView 加载生命周期与代理方法剖析](https://mp.weixin.qq.com/s/ZFui9IiMTWyLXGKZlbnzwQ)

[@享耳先森](https://github.com/iblacksun)：本篇是系列第二篇，第一篇见 [深入理解 WKWebView（入门篇）—— WebKit 源码调试与分析](https://mp.weixin.qq.com/s/VdkVBIQwj7WkAk8-5wppmQ)，本篇在上一篇的基础上介绍了 `WebKit` 内部的三个进程是如何协作及通信的。
