### ISSUE TITLE
Pulse

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2872]
# 推荐收录

## 链接

https://github.com/kean/Pulse

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
Pulse 是适用于 Apple 平台的强大日志记录系统，基于 SwiftUI 构建。使用 Pulse Console 直接从你的 iOS 应用程序中检查网络请求和日志，并通过 PulseUI 展示出来。你的 QA 团队在问题反馈时可以轻松共享它们，附带在错误报告中。你可以在 Pulse macOS 应用程序中查看共享日志。
