### ISSUE TITLE
深入理解 WKWebView（基础篇）—— 聊聊 cookie 管理那些事

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2893]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/jZP2DsAa5OV91wdNMw39cA

**Comment by iblacksun** [comment]
### 🐢 [深入理解 WKWebView（基础篇）—— 聊聊 Cookie 管理那些事](https://mp.weixin.qq.com/s/jZP2DsAa5OV91wdNMw39cA)

[@享耳先森](https://github.com/iblacksun)：本篇是系列第三篇，文章首先介绍了 Cookie 相关 API，然后深入介绍 WebKit 内部 Cookie 管理方式及技术原理。前两篇见：
- [深入理解 WKWebView（入门篇）—— WebKit 源码调试与分析](https://mp.weixin.qq.com/s/VdkVBIQwj7WkAk8-5wppmQ)
- [深入理解 WKWebView（基础篇）—— WKWebView 加载生命周期与代理方法剖析](https://mp.weixin.qq.com/s/ZFui9IiMTWyLXGKZlbnzwQ)
