### ISSUE TITLE
Cocopods组件化架构下的OC与Swift混编有哪些经验可以分享

### ISSUE THREAD

**Issue by SimonCY** [SwiftOldDriver/iOS-Weekly#2894]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
@SimonCY 请问有推荐链接吗？还是说这是个问题，想跟我们交流？
如果是交流的话，可以在公众号「老司机技术周报」找到加入我们读者群进行答疑~
如果是推荐的话，要放上链接哦~我在 Google 没有搜索到你这篇文章的 title 相关内容。

**Comment by ParsifalC** [comment]
@SimonCY 关注我们公众号，下周会发布上回沙龙倾寒分享的《手淘工程渐进式拥抱 Swift》

**Comment by SimonCY** [comment]
> @SimonCY 请问有推荐链接吗？还是说这是个问题，想跟我们交流？
> 如果是交流的话，可以在公众号「老司机技术周报」找到加入我们读者群进行答疑~
> 如果是推荐的话，要放上链接哦~我在 Google 没有搜索到你这篇文章的 title 相关内容。

是个问题哈
