### ISSUE TITLE
LSAnimator

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#29]
https://github.com/Lision/LSAnimator

**Comment by mmoaay** [comment]
iOS 链式动画库，相比业界另外一个 Swift 动画库 [IBAnimatable](https://github.com/IBAnimatable/IBAnimatable)，有如下特性：
- 支持并发链式动画；
- 提供 OC 版；
- 侧重对每一步动画的可定制性。
