### ISSUE TITLE
CalendarApp - Apple 日历的克隆

### ISSUE THREAD

**Issue by richardtop** [SwiftOldDriver/iOS-Weekly#2902]
# 推荐收录

## 链接

https://github.com/richardtop/CalendarApp

## 理由

我创建了一个 Apple Calendar 应用程序的简单克隆来帮助初学者入门。 这是一个非常简单但功能齐全的应用程序，仅用几百行代码编写。 有兴趣与中国 iOS 社区分享我的工作并获得新的贡献者。
也可以随意在中国内部网络中复制和分享我的内容。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

理查德·托普奇（Richard Topchii）
https://github.com/richardtop
https://www.youtube.com/channel/UCx1gvWpy5zjOd7yZyDwmXEA

**Comment by ParsifalC** [comment]
Good Job!
I'll check it out.
