### ISSUE TITLE
React Native迎来重大架构升级，性能将大幅提升

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2908]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/bIkShX_pDWgO_a2BSGznUA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iostalks** [comment]
质量不太好，这篇不推荐了。

**Comment by iostalks** [comment]
标题党了，新框架并没有开源，也没讲什么新架构的东西。
