### ISSUE TITLE
一个统计pod库下载,解压耗时的cocoapods插件

### ISSUE THREAD

**Issue by cxr0715** [SwiftOldDriver/iOS-Weekly#2917]
# 推荐收录

## 链接

https://github.com/cxr0715/cocoapods-TSPodfileTimeWatch

## 理由

一个开箱即用的统计pod库下载，解压耗时的插件（图片看不到可以多刷新几次）
可以收录在工具集中

## 推荐人信息

Ke哀，目前就于职手机QQ，从事手Q基础开发

**Comment by ParsifalC** [comment]
@cxr0715 这个我们下周会安排处理，为啥关掉了？

**Comment by cxr0715** [comment]
@ParsifalC 哈，看到没有回复，所以就先关掉了……
如果可以上周刊的话也很好呀，这个是自己写的一个统计cocoapods下载解压耗时的插件，有任何问题都可以直接留言哈
