### ISSUE TITLE
Allowing Your Users to Manage Data Stored in iCloud

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#293]
https://developer.apple.com/support/allowing-users-to-manage-data/

**Comment by raozhizhen** [comment]
允许用户管理存储在 iCloud 中的数据

为帮助开发者遵守欧盟即将推出的《通用数据保护条例》(GDPR)，苹果提供相应原生 API 和 Web API，支持开发者帮助用户对 CloudKit 里的数据进行导出、限制或者删除。且当用户停用其 Apple ID 或者限制其数据时，开发者需要处理 CloudKit API 返回的错误信息。
