### ISSUE TITLE
Swift by Sundell: “WWDC21, two months later”

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2930]
# 推荐收录

## 链接

https://www.swiftbysundell.com/podcast/102/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
我觉得这期内容推荐的价值不是很大，主要是聊了一下今年 WWDC 的内容，没有很多深入的内容。
