### ISSUE TITLE
cocoapods 1.5 支持 swift 静态库

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#294]
http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by kemchenj** [comment]
### 🐎 [CocoaPods 1.5 支持 Swift 静态库了](http://blog.cocoapods.org/CocoaPods-1.5.0/)

CocoaPods 这周更新到了 1.5，主要是加强了对于 Swift 静态库的支持，新增一个选项去自动处理 Module 头文件的搜索路径，给 Podfile.lock 增加了更多信息。正在维护开源库的同学建议仔细阅读这篇 Release Note。
