### ISSUE TITLE
Swift每个版本新特性一览

### ISSUE THREAD

**Issue by faimin** [SwiftOldDriver/iOS-Weekly#2944]
# 推荐收录

## 链接

https://www.whatsnewinswift.com/?from=5.4&to=5.5

## 理由

可以帮我们快速的了解每个`Swift`版本新增的新特性，同时也方便我们定位现在使用的特性是在什么版本添加的

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
@faimin 这个以前有推荐过哈，就不重复推荐了 https://github.com/SwiftOldDriver/iOS-Weekly/blob/6e674f2bf7c30bea62eac77b723e349040f750a2/Reports/2018/%2317-2018.05.02.md#whats-new-in-swift-%E7%BB%88%E6%9E%81%E7%89%88

**Comment by faimin** [comment]
OK
