### ISSUE TITLE
Xcode Deployment targets, simulator, and Swift versions

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#2948]
# 推荐收录

## 链接

https://developer.apple.com/support/xcode

## 理由

from https://iosdevweekly.com/issues/520#start

**Comment by ParsifalC** [comment]
主要看更新的这个 Minimum requirements and supported SDKs table

**Comment by iblacksun** [comment]
@Damonvvong 这个表格似乎作用不大？先不推了。

**Comment by lijianfeigeek** [comment]
不如用这个 https://xcodereleases.com/

iblacksun ***@***.***> 于2021年8月22日周日 下午8:30写道：
