### ISSUE TITLE
How iOS 15 makes your app launch faster

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#2951]
# 推荐收录

## 链接

https://www.emergetools.com/blog/posts/iOS15LaunchTime

## 理由

This was because the LC_DYLD_INFO_ONLY load command was missing, it had been replaced by LC_DYLD_CHAINED_FIXUPS and LC_DYLD_EXPORTS_TRIE.

Before iOS 15, rebases, binds and lazy binds were each stored in a separate table. Now they have been combined into chains, with pointers to the starts of the chains contained in this new load command

dyld苹果也搞二进制重排了，可能对现有的方案有冲突。需要注意下...

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
其实不算搞重排，重排只是把启动阶段的函数调用挪到同一张 page，但由于 iOS 13 已经不在 Page In 的时候进行解密了，所以自己做二进制重排的收益就很少了。苹果这是把 rebases, binds and lazy binds 合并处理了，当然从结果上看，都是减少了启动阶段的 page fault 耗时从而加快了启动速度。

PS：iOS 15 Beta 5 后确实很快，甚至让你有种不是冷启动或热启动，而是只从后台进前台的错觉
