### ISSUE TITLE
一个有趣的可视化编程开源库

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#297]
https://github.com/NathanFlurry/VisualProgrammingLanguage

**Comment by raozhizhen** [comment]
一个有趣的可视化编程开源库

这是一个有趣的可视化编程开源库，只需要动动手指或者 Apple Pencil，即可新建语法节点，连接节点的输入与输出，然后生成目标代码。不过它现在只能算一个可行性证明，效率还很低，如果你有兴趣，可以帮助作者一起完善。（也许以后它能让编程教学变得更轻松简单，而且有趣。）
