### ISSUE TITLE
RTL适配经验

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#298]
https://www.jianshu.com/p/3383ca5f6de0

**Comment by EyreFree** [comment]
### [RTL 适配历程](https://www.jianshu.com/p/3383ca5f6de0)

RTL 语言（如阿拉伯语）的适配一直是一个比较令人头疼的问题，本文以 [Apple 官方文档](https://link.jianshu.com/?t=https%3A%2F%2Fdeveloper.apple.com%2Flibrary%2Fcontent%2Fdocumentation%2FMacOSX%2FConceptual%2FBPInternational%2FSupportingRight-To-LeftLanguages%2FSupportingRight-To-LeftLanguages.html) 为基础同时结合作者的自身实践，从布局、手势、图片等多个方面对 iOS 9 之后的 RTL 适配做了详细的归纳与总结，同时给出了具体的示例代码，有相应需求的同学绝对不要错过。
