### ISSUE TITLE
URLServiceRouter

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2981]
# 推荐收录

## 链接

https://github.com/lightank/URLServiceRouter

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by lightank** [comment]
感谢推荐，[URLServiceRouter](https://github.com/lightank/URLServiceRouter) 刚刚发布了0.0.6版本，完善了readme的中文文档，新增了部分示例。
