### ISSUE TITLE
Preventing Data Races Using Actors in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#2993]
# 推荐收录

## 链接

https://swiftsenpai.com/swift/actor-prevent-data-race/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Preventing Data Races Using Actors in Swift](https://swiftsenpai.com/swift/actor-prevent-data-race/)

[@享耳先森](https://github.com/iblacksun)：数据竞争一直是并行编程下的难点，其往往难以检测与解决。本文先介绍了数据竞争的的基础，再介绍 Swift 5.5 引入的 Actor 如何优雅的解决这个问题。
