### ISSUE TITLE
关于 Swift Package Manager 的一些经验分享

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#3000]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/s2GZ13PVdVa5t-SABArtdA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [关于 Swift Package Manager 的一些经验分享](https://mp.weixin.qq.com/s/s2GZ13PVdVa5t-SABArtdA)

[@四娘](https://kemchenj.github.io/)：这是一篇来自字节跳动团队的 SPM 经验分享，介绍了 SPM 基本的使用方式，团队内部的实践经验，常见问题以及与 Cocoapods 的对比。
