### ISSUE TITLE
How To Keep Learning After 50 and Other Ways to Hack Your Brain at any Age

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#301]
https://www.raywenderlich.com/189082/how-to-keep-learning-after-50-and-other-ways-to-hack-your-brain-at-any-age

很有意思的一篇文章。我们总说活到老学到老，但却又在担心码农是一件干不长久的事业，这篇文章调查了一些年龄在 50+ 以上的开发者如何保持持续学习的动力和方法。

这期来不及了，放 15 期吧。

**Comment by lacklock** [comment]
ray的文章不需要翻墙吧？
