### ISSUE TITLE
 Performance: Actor vs. queue vs. lock

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3016]
# 推荐收录

## 链接

https://trycombine.com/posts/performance-actor-queue-lock-benchmark/

**Comment by zvving** [comment]
通过一个简洁的自增计数器实现 Benchmark，对比 actor、DispatchQueue.sync、os_unfair_lock。性能结论并不意外 actor <<< DispatchQueue.sync < os_unfair_lock。

讨论、分析内容过少，建议周报暂不推荐。
