### ISSUE TITLE
iOS 隱私與便利的前世今生

### ISSUE THREAD

**Issue by zhgchgli0718** [SwiftOldDriver/iOS-Weekly#3039]
# 推荐收录

## 链接

https://medium.com/zrealm-ios-dev/ios-%E9%9A%B1%E7%A7%81%E8%88%87%E4%BE%BF%E5%88%A9%E7%9A%84%E5%89%8D%E4%B8%96%E4%BB%8A%E7%94%9F-9a05f632eba0

## 理由

盤點 iOS 這幾年的隱私功能調整及 Apple 隱私政策

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 🚧 [iOS 隱私與便利的前世今生](https://medium.com/zrealm-ios-dev/ios-隱私與便利的前世今生-9a05f632eba0)

本文综述性的介绍了从 iOS 7 到 15 Apple 在隐私方面做的持续改进：这些改进背后的原因以及对用户来说有什么好处？

> 推荐人 [zhgchgli0718](https://github.com/zhgchgli0718)
