### ISSUE TITLE
[工具] iPhone, iPad, Mac Buyer's Guide: Know When to Buy - 近期是否该买苹果产品

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#304]
https://buyersguide.macrumors.com/

结合 Apple 往期新产品的发布规律和近期发布会信息，给出某款苹果产品近期是否推荐购买的建议。

**Comment by raozhizhen** [comment]
苹果更新其产品的时候往往是该产品的最佳购买时机，如果错过了，那么可以在这个网站上找到购买建议，网站会根据该产品距离上次更新的时长，以及历史以来的平均更新周期给出建议，并收集了产品相关的最新传闻给与你作为参考。
