### ISSUE TITLE
ByteTalk - 1. 与飞书的几位小伙伴聊聊程序员的那些事

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#3041]
# 推荐收录

## 链接

https://www.xiaoyuzhoufm.com/episode/6177bab6b69226ed16a3ed42?s=eyJ1IjogIjYxNmFlZTVhZTBmNWU3MjNiYjhjNzE4MCJ9

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
这周团建，节目没听完。应该可以推荐，改下期

cc @ParsifalC

**Comment by ParsifalC** [comment]
> 这周团建，节目没听完。应该可以推荐，改下期
> 
> cc @ParsifalC

👌

**Comment by zvving** [comment]
播客内容有些散，不作推进。

改为推荐

 [5G，华为，土耳其——我花了两个月，搞懂了5G背后的秘密](https://www.bilibili.com/video/BV1fq4y1g7hq)

5G 技术中的极化码是一个非常复杂的通信概念，UP 主作为一个『通信小白』，暴肝三个月，梳理信息论、信道容量、香农极限诸多知识，在此基础上介绍极化码及其背后的故事。视频是在讲解 5G 技术，更是表述刨根问底、用平和心态长期坚持的科研精神，分享给每一位有好奇心的朋友们。
