### ISSUE TITLE
技术人员成长的一些误区与方式方法

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#305]
http://mp.weixin.qq.com/s/t1P0mw9Hf4y27EiZB2biXw

原文太标题党了，改了下。虽然不怎么认同阿里洗脑式地价值观文化，但是这里提到的「Do More」、「Do Better」和「Do Exercise」的观点还是深有同感的。这样一篇文章，应该能帮助到目前对自己未来发展还存在困惑的职场新猿吧。

**Comment by iblacksun** [comment]
### [如何快速成长为技术大牛](https://mp.weixin.qq.com/s/t1P0mw9Hf4y27EiZB2biXw)

技术人员`天天写业务代码还加班，如何才能成为技术大牛?`，文章列出了一些典型的误区及正确做法：**Do more**、**Do better**、**Do exercise**。
