### ISSUE TITLE
市面唯一的Swift热更新技术

### ISSUE THREAD

**Issue by sotservice** [SwiftOldDriver/iOS-Weekly#3053]
# 推荐收录

## 链接

[文档](https://www.sotvm.com/doc/)

## 理由

此项技术支持iOS全语言的热更新，例如能热替换Swift的各种函数。还有一个亮点是直接修改源码即可实现修复，无需转译为js等脚本语言。

功能和易用性大大超越了同类型框架或者方案，为下一代苹果动态化指明了方向。

**Comment by ParsifalC** [comment]
感谢自荐。我看了下文档，还是描述的太简单了，对于开发者而言技术价值不是很大。如果是普通的工具，够好用我们也会考虑推荐，但对于热修复这个比较敏感的内容，我们可以推荐关于这方面的技术文章或者开源方案的分享和讨论，但直接推工具就不太合适了。如果后续有计划开源或者发布详解的方案设计文章，欢迎继续联系我们。
