### ISSUE TITLE
这篇文章对Swift中的派发讲的很不错

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#306]
https://www.raizlabs.com/dev/2016/12/swift-method-dispatch/?utm_campaign=This%2BWeek%2Bin%2BSwift&utm_medium=email&utm_source=This_Week_in_Swift_1

@kemchenj 还翻译过这篇文章

**Comment by lacklock** [comment]
@kemchenj 文章是不错，这种适合再推一次吗？

**Comment by kemchenj** [comment]
### [深入理解 Swift 派发机制](https://kemchenj.github.io/2016-12-25-1/)
