### ISSUE TITLE
闲鱼唤端的背后

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#3064]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/MQ2XlroLF6vhM7qP1H-tBQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [闲鱼唤端的背后](https://mp.weixin.qq.com/s/MQ2XlroLF6vhM7qP1H-tBQ)

[@享耳先森](https://github.com/iblacksun)：如果你的 App 非常重运营，那么你一定非常想知道在每个运营活动中，带来多少新用户或日活，本文介绍了闲鱼 App 是如何做跨 App 启动以及所见即所得的。所见即所得依赖各端统一的数据上报与解析逻辑。
