### ISSUE TITLE
swift tips：函数嵌套声明计算属性优化重复代码，涨知识

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#308]
https://www.objc.io/blog/2018/04/10/local-vars/

**Comment by EyreFree** [comment]
### [Swift Tip: Local Computed Variables](https://www.objc.io/blog/2018/04/10/local-vars/)

本文介绍了一种通过在函数体内部声明计算属性从而实现局部代码复用的编码方法，不过也仅仅是代码复用，性能方面木有任何提升，类似于一个局部函数，感兴趣的同学可以了解一下。
