### ISSUE TITLE
SwiftTreeSitter

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#3084]
# 推荐收录

## 链接

https://github.com/ChimeHQ/SwiftTreeSitter

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
# 2021-11-19 10:47:19 AM 

### [SwiftTreeSitter](https://github.com/ChimeHQ/SwiftTreeSitter)

[@四娘](https://kemchenj.github.io)：语法高亮的实现一直困扰着 GitHub/Atom 的工程师，网页和编辑器并不像 IDE 那样，它们没有完整的上下文，它们不了解每个单词背后代表着的是变量还是函数。

除此之外，性能也是一个问题，传统的多次正则匹配会让性能变得很差，而且不支持增量解析，这意味着每次敲下一个字编辑器都需要重新完整地解析一次，这对于大文件来说尤其致命。

TreeSitter 就是为了在这个场景下更好地进行词法分析的一个语法解析器，输入文件就可以输出 AST，它真正地实现了语法解析，支持增量解析，支持多语法的解析，例如 html 里的 javascript 和 css 也可以被正确解析，目前 GitHub 已经在线上启用了很长一段时间。

这个项目是 TreeSitter 的 Swift Binding，让我们可以使用 Swift 去调用 TreeSitter 的相关功能呢。另外，对于 Tree-sitter 感兴趣的同学也可以看一下[他们的工程师在某个技术大会上的演讲介绍](https://www.youtube.com/watch?v=Jes3bD6P0To)。
