### ISSUE TITLE
Get started with in-app events

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3115]
# 推荐收录

## 链接

https://developer.apple.com/videos/play/tech-talks/10889/

**Comment by iblacksun** [comment]
### [Get started with in-app events](https://developer.apple.com/videos/play/tech-talks/10889/)
[@享耳先森](https://github.com/iblacksun)：从 Apple 在 WWDC 21 提起 In-app events 开始，到前段时间正式开放已经有一段时间了，建议回顾下本视频，包含了 in-app events 的一些建议和最佳实践。
