### ISSUE TITLE
【Hold，系列完成后推荐】TCA - SwiftUI 的救星？(一) | OneV's Den

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3119]
# 推荐收录

## 链接

https://onevcat.com/2021/12/tca-1/
https://onevcat.com/2021/12/tca-2/

**Comment by zvving** [comment]
###  [TCA - SwiftUI 的救星？(一)](https://onevcat.com/2021/12/tca-1/)

[@zvving](https://github.com/zvving)：从 UIKit 到 SwiftUI，声明式布局、数据传递、状态管理都带来极大的变化，在复杂项目中，如何通过 SwiftUI 构建可组合、易维护、可测试的项目架构本身就是一件很有挑战的事，受 Elm 启发诞生的 TCA (The Composable Architecture) 是可能的答案之一。

- 借鉴状态机：通过 Action 统一 State 的变化方式，事件处理代码更内聚
- 分割 Store/ViewStore：避免不必要的 view 更新，细粒度 view 有灵活的组合能力
- 跨 UI 框架能力：为 UIKit 到 SwiftUI 提供更稳妥的过渡路径

王巍通过系列文章介绍 TCA（目前是第一篇，内容非常好，建议完结后再重新 review，一并推荐）
