### ISSUE TITLE
一个把pdf转成对应尺寸图片的工具，不确定是否实用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#313]
https://github.com/kreait/convertappicon

**Comment by Damonvvong** [comment]
这个工具只解决了由 pdf 生成不同尺寸的图标问题。实际上，对于大部分素材来说，Xcode 都会支持自动生成不同尺寸的图标。只有App 的 Icon是个例外。

我的理解的话，实际用处其实不大。毕竟提供不同素材图片应该不是工程师需要去关系的问题。而且大部分设计软件也有对应的插件。
