### ISSUE TITLE
onevcat/Rainbow: Delightful console output for Swift developers.

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3139]
# 推荐收录

## 链接

https://github.com/onevcat/Rainbow

## 理由

Rainbow adds text color, background color and style for console and command line output in Swift. It is born for cross-platform software logging in terminals, working in both Apple's platforms and Linux.

**Comment by iblacksun** [comment]
### [Rainbow](https://github.com/onevcat/Rainbow)

[@享耳先森](https://github.com/iblacksun)：Rainbow 是 [onevcat](https://github.com/onevcat) 开源的一个控制台和终端日志输出库，可以给文字添加颜色、背景色、样式等信息，支持 Apple 和 Linux 平台。
