### ISSUE TITLE
Swift implemented in Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3140]
# 推荐收录

## 链接

https://github.com/apple/swift/tree/main/SwiftCompilerSources

**Comment by kemchenj** [comment]
### [Swift implemented in Swift](https://github.com/apple/swift/tree/main/SwiftCompilerSources)

[@kemchenj](https://kemchenj.github.io)：Swift 仓库近日添加了一个 Swift implemented in Swift 的项目，旨在使用 Swift 实现 Swift 编译器的部分功能。目前实现了 SIL 的桥接，以便逐步将 SIL Optimizer 的功能改为使用 Swift 进行实现。
