### ISSUE TITLE
Unobtrusive runtime warnings for libraries

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3145]
# 推荐收录

## 链接

https://www.pointfree.co/blog/posts/70-unobtrusive-runtime-warnings-for-libraries

## 理由

写代码的过程中，API 调用的一部分错误是无法通过类型检查处理的，但直接 fatalError 也不好，在业务层使用 `#if DEBUG` 进行检查也很容易错漏。

Point-Free 就在这篇文章里就为我们介绍了更好的处理方式，例如通过代码进入断点，亦或者是通过 Xcode 抛出 Runtime Warning，给上层用户更好的提示，并且将这些逻辑封装起来。

**Comment by GesanTung** [comment]
![image](https://user-images.githubusercontent.com/5457612/150674570-0f590b35-07a7-4fdc-8fa1-5fbc456376cf.png)
尝试有点问题

**Comment by ChengzhiHuang** [comment]
洛阳铲一下，今天把我公司的项目加了一下，发现一定得 dynamic link **SwiftUI.framework** 才能在 Xcode 的边栏里展示出来。
