### ISSUE TITLE
谷歌开源 iOS 自动测试框架 GTXiLib

### ISSUE THREAD

**Issue by chenjunpu** [SwiftOldDriver/iOS-Weekly#318]
https://opensource.googleblog.com/2018/03/open-sourcing-gtxilib-accessibility.html
https://github.com/google/GTXiLib
可用于：
1. 重用测试： GTXiLib 集成整合到现有的功能测试流程中，能大幅提升现有测试价值。
2. 增量可访问性测试： GTXiLib 可安装在单一测试用例、测试类或测试的特定子集上，以允许灵活地增加可访问性测试。
3. 编写属于自己的检查： GTXiLib 有一个简单的 API 来根据你的应用的特定需求创建自定义检查。比如，可以检测应用中的每一个按钮是否都具备 accessibilityHint 属性。

**Comment by raozhizhen** [comment]
谷歌开源 iOS 辅助功能自动测试框架 GTXiLib #318

![GTXiLib](https://github.com/SwiftOldDriver/iOS-Weekly/issues/318) 采用 Objective-C 编写，能与现存的 XCTests 测试框架整合。并在 XCTest 结束调用 tearDown 前，执行所有注册的可用性检查。当 GTXiLib 检测失败时，XCTest 的测试也会失败，两者相辅相成，能够帮助开发者更好的为每个人提供无障碍服务。
