### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3191]
# 推荐收录

## 链接

https://www.swiftbysundell.com/basics/loops/

**Comment by iblacksun** [comment]
### [Loop](https://www.swiftbysundell.com/basics/loops/)

[@享耳先森](https://github.com/iblacksun)：Swift 有多种内置语法对集合类型进行迭代：`for` `forEach` `enumerated()` `while` 等，本文介绍了各种语法的具体差异，建议阅读。
