### ISSUE TITLE
objccn 期刊

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3198]
# 推荐收录

## 链接

https://objccn.io/issues/

**Comment by Damonvvong** [comment]
@kemchenj 这个期刊是有什么新内容吗？

**Comment by kemchenj** [comment]
> @kemchenj 这个期刊是有什么新内容吗？

没有，不过我最近查资料的时候又重新进去看了一下，感觉内容总结得很好，可以再推荐一波。

**Comment by Damonvvong** [comment]
@kemchenj 这个知道的人应该是蛮多的。内容也相对已经存在挺久了的。我觉得如果没有内容新增是不是就不推荐了？不过咱们周报可以学习下这个方式，把过去内容按主题划分下。
