### ISSUE TITLE
Mirror原理探索

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3200]
# 推荐收录

## 链接

https://juejin.cn/post/7053398906394116127

**Comment by Damonvvong** [comment]
建议配合 https://juejin.cn/post/7053397610303848478 一起推荐

**Comment by zvving** [comment]
作者用一个序列化例子介绍 Swift 中自带反射读取属性及值的用法，然后通过追溯 Mirror 的源码，通过了解属性内存布局模拟实现 Mirror 的部分功能。

很好的原理学习过程，但整体表达罗列代码较多（不完整），思路表述不够清晰，读起来不好理解。暂不推荐
