### ISSUE TITLE
fb 的 ios 架构

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#321]
https://youtu.be/-G8nZpif1rA?t=24m8s

**Comment by ParsifalC** [comment]
看时间其实有点久了，15 年的，最后上不上周末找时间看完我再做决定。

**Comment by ApolloZhu** [comment]
其实主要是讲 https://github.com/facebook/componentkit

**Comment by ParsifalC** [comment]
我看了一遍，确实如 @ApolloZhu 所说的，主要是介绍了 Facebook 在面临复杂界面的业务时如何使用 ComponentKit 编写维护性更高又不会随着业务的不断累加对性能形成影响的代码。从这个角度上来看，我的意见是直接上一篇 ComponentKit 的相关文章会比上这个视频价值更高。

@lacklock 你也看下吧，这个内容我就先不写了。

**Comment by lacklock** [comment]
@ParsifalC 好的，周末去上海没处理这个。这周我看一下。
