### ISSUE TITLE
metalkit.org全站翻译

### ISSUE THREAD

**Issue by XanderXu** [SwiftOldDriver/iOS-Weekly#322]
出于学习目的,翻译了metalkit.org全站的文章,目前共42篇
https://juejin.im/post/5a31fcdc51882531b15b8294

**Comment by iblacksun** [comment]
### 🐕 [metalkit.org 全站翻译](https://juejin.im/post/5a31fcdc51882531b15b8294)

推荐一个学习 Metal 的资源：[`metalkit.org`](http://metalkit.org) 有一系列 MetalKit 教程，网友 [@XanderXu](https://github.com/XanderXu) 将其翻译成中文，推荐给对 Metal 有兴趣的同学。
