### ISSUE TITLE
A library for safer types.

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#324]
https://github.com/pointfreeco/swift-tagged

更加安全的类型支持，为同一类型的不同字段值增加标记，使其能够被当做不同类型对待，在编码阶段避免字段值误传的问题。

**Comment by kemchenj** [comment]
### [Swift Tagged](https://github.com/pointfreeco/swift-tagged)

同样都是 id，同样都可以用 `Int` 来表示，但用户的 id 和文章的 id 明显是不能混用在一起的，Swift Tagged 这个库就为我们提供了一种便利的类型声明方式 `typealias Id = Tagged<User, Int>`，能够让我们在编译期避免字段误传的问题。

BTW，这是 Kickstarter 两位前任工程师，创办的网站 [Point Free](https://www.pointfree.co/episodes/ep12-tagged) 出品的一部分内容。
