### ISSUE TITLE
iOS微信全文搜索技术优化

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3242]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/Ph0jykLr5CMF-xFgoJw5UQ

**Comment by kemchenj** [comment]
### [iOS微信全文搜索技术优化](https://mp.weixin.qq.com/s/Ph0jykLr5CMF-xFgoJw5UQ)

[@kemchenj](https://kemchenj.github.io/)：这篇文章讲述了微信团队 2021 年优化 iOS 客户端搜索体验的过程，从技术选型开始，到方案落地以及最后的性能调优，非常具有学习价值，强烈推荐有类似需求的同学阅读。
