### ISSUE TITLE
AVPlayer一直是一个蛋疼的存在，JPVideoPlayer 不知道是否改良的足够好用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#326]
https://juejin.im/post/5ad168c2518825555e5e44dd

**Comment by Damonvvong** [comment]
相比较来说我可能会更推荐看 https://github.com/casatwy/CTVideoPlayerView 这个？

**Comment by zangqilong198812** [comment]
finished.
JPVideoPlayer我在我那个足球项目里用过。
很好用。
