### ISSUE TITLE
Publishing DocC Documentation as a Static Website on GitHub Pages

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3264]
# 推荐收录

## 链接

https://www.createwithswift.com/publishing-docc-documention-as-a-static-website-on-github-pages/

**Comment by kemchenj** [comment]
### [Publishing DocC Documentation as a Static Website on GitHub Pages](https://www.createwithswift.com/publishing-docc-documention-as-a-static-website-on-github-pages/)

[@kemchenj](https://kemchenj.github.io/)：去年 WWDC 苹果发布了 Swift 专用的文档生成工具 docc，接近一年过去了，社区主流的库都没有采用这个工具，其中一个重要的原因是 docc 不支持生成静态网页，无法部署在类似 github.io 之类的服务上，必须有服务器支持才可以。

最近在社区的帮助下，docc 也加入了静态网页生成的功能，预计会跟随 Xcode 13.3 一起发布，这篇文章的作者就分享了如何使用 Xcode CLI 命令调用 docc 生成静态网页，以及最终的效果。

另外跟随 Xcode 13.3 发布的 SPM 预计也会加入 [Command Plugin](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md) 功能，苹果官方也发布了[对应的 docc 插件](https://github.com/apple/swift-docc-plugin)，使用这个插件就可以在 CLI 里 `swift package generate-documentation` 一键生成文档。
