### ISSUE TITLE
Native Network Monitoring In Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3267]
# 推荐收录

## 链接

https://digitalbunker.dev/native-network-monitoring-in-swift/

**Comment by iblacksun** [comment]
### 🐕 [Native Network Monitoring In Swift](https://digitalbunker.dev/native-network-monitoring-in-swift/)

[@享耳先森](https://github.com/iblacksun)：对于 App 内的网络状态监控，大家常用的是 `Reachability` 或 `Alamofire` 内部的 `NetworkReachabilityManager`。本文介绍了基于 iOS 12 后 `Network.framework` 内置的 `NWPathMonitor` 实现的网络状态监控。
