### ISSUE TITLE
Tips for getting the most out of DocC

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3268]
# 推荐收录

## 链接

https://rhonabwy.com/2022/02/10/tips-for-getting-the-most-out-of-docc/

**Comment by kemchenj** [comment]
### [Tips for getting the most out of DocC](https://rhonabwy.com/2022/02/10/tips-for-getting-the-most-out-of-docc/)

[@四娘](https://kemchenj.github.io/)：文档工具 DocC 发布了已经快要一年，这段时间里加上了 static hosting，C/Objective-C 的支持以及 SPM 插件等功能，依托它来构建内部文档工具是一个不错的选择，也是一个顺便梳理项目内部代码的机会。

本文作者提供了一个渐进式接入 DocC 的步骤建议，让我们可以最大化 docc 的作用：

1. 给 class/struct/enum 等类型添加注释文档
2. 给公开的函数和属性添加注释文档
3. 添加 documentation catalog 和 overview
4. 给主要的类型和函数分组
5. 编写一篇大致的介绍文档
6. 添加常用的代码模版
7. 给其余的代码分组
