### ISSUE TITLE
如何让云音乐iOS包体积减少87MB

### ISSUE THREAD

**Issue by iostalks** [SwiftOldDriver/iOS-Weekly#3274]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

https://mp.weixin.qq.com/s/GTbhvzMA-W0ANlars7mKog

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Damonvvong** [comment]
建议可以提一下 ODR 的思路。
