### ISSUE TITLE
SafeDecoder

### ISSUE THREAD

**Issue by GodL** [SwiftOldDriver/iOS-Weekly#3289]
# 推荐收录

## 链接

https://github.com/GodL/SafeDecoder

## 理由

SafeDecoder支持在Codable解码某个字段失败时设置默认值，并且默认值可配置。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [SafeDecoder](https://github.com/GodL/SafeDecoder)

SafeDecoder支持在Codable解码某个字段失败时设置默认值，并且默认值可配置。

> 推荐人：[GodL](https://github.com/GodL)
