### ISSUE TITLE
Conditional conformances in Swift

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#329]
https://medium.com/@johnsundell/conditional-conformances-in-swift-f6601d40aabb
还分析了 conditional confromance 的实用场景

**Comment by mmoaay** [comment]
介绍了 Swift 4.1 新引入的特性 Conditional Conformaces 的基本用法以及优势，并分析了两个实用场景：递推设计（Recursive design）和多重请求（Multipart request）。
