### ISSUE TITLE
Xcode Tips

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3299]
# 推荐收录

## 链接

For the developers out there, Xcode 13.3 has a new opt-in build mode that results in faster builds. Activate with `defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1`.

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-13_3-release-notes#Build-System

**Comment by iWECon** [comment]
`efaults` fix to `defaults`
