### ISSUE TITLE
自己实现一个clang 代码检查插件

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#330]
https://www.jianshu.com/p/c27b77f70616?utm_campaign=hugo&utm_medium=reader_share&utm_content=note
自己实现一个clang 代码检查插件

**Comment by Damonvvong** [comment]
作者从 **给OC代码添加类型检查** 的需求入手，大致介绍了一下 **Clang 插件能做什么** 和 **Clang插件怎么去开发** 两件事情。对于想尝试 **Clang插件开发** 的人来说，是一篇不错的参考文章。
