### ISSUE TITLE
Optimization in Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3300]
# 推荐收录

## 链接

https://trycombine.com/posts/swift-performance-concurrency-1/

https://trycombine.com/posts/swift-performance-concurrency-2/

https://trycombine.com/posts/swift-performance-concurrency-3/

https://trycombine.com/posts/swift-performance-concurrency-4/

**Comment by kemchenj** [comment]
### Optimization in Swift

作者以 filter 为例，带着我们进行一次算法性能优化，包括算法性能的测算，结果的分析以及后续针对性的优化：

1. [如何测量算法性能](https://trycombine.com/posts/swift-performance-concurrency-1/)
2. [使用 Concurrency 算法](https://trycombine.com/posts/swift-performance-concurrency-2/)
3. [内存预分配](https://trycombine.com/posts/swift-performance-concurrency-3/)
4. [总结](https://trycombine.com/posts/swift-performance-concurrency-4/)
