### ISSUE TITLE
swift-docc-plugin

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3303]
# 推荐收录

## 链接

https://github.com/apple/swift-docc-plugin

**Comment by kemchenj** [comment]
### [swift-docc-plugin](https://github.com/apple/swift-docc-plugin)

[@kemchenj](https://kemchenj.github.io)：跟随 Xcode 13.3 发布的 SPM 加入了 [Command Plugin](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md) 功能，苹果官方也发布了[对应的 docc 插件](https://github.com/apple/swift-docc-plugin)，只要在 Package.swift 里引入这个 plugin，就可以在 CLI 里用 `swift package generate-documentation` 一键生成文档。：

```swift
let package = Package(
    // name, platforms, products, etc.
    dependencies: [
        // other dependencies
        .package(url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0"),
    ],
    targets: [
        // targets
    ]
)
```
