### ISSUE TITLE
AnyObject, Any, and any: When to use which?

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3308]
# 推荐收录

## 链接

https://www.avanderlee.com/swift/anyobject-any/

**Comment by iblacksun** [comment]
### 🐕 [AnyObject, Any, and any: When to use which?](https://www.avanderlee.com/swift/anyobject-any/)

[@享耳先森](https://github.com/iblacksun)：Swift 5.6 在 [SE-355](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) 引入了 `any` 关键词，加上之前已有的 `AnyObject` 和 `Any`(注意是大写)。本文介绍了三个关键词各自的使用场景并着重介绍新引入的 `any` 的作用。
