### ISSUE TITLE
Asynchronous programming with SwiftUI and Combine

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3314]
# 推荐收录

## 链接

https://peterfriese.dev/posts/combine-vs-async/

**Comment by zvving** [comment]
结论是合理的：combine 处理响应式问题，基于连接事件流确保状态始终一致；async/await 处理并发。但例子本身就更适合 combine 来处理，强行引入 async/await 解决的是不同纬度的问题，提问本身带有迷惑性。不建议引入周报。
