### ISSUE TITLE
AVFoundation系列文章推荐

### ISSUE THREAD

**Issue by GuanyingWang** [SwiftOldDriver/iOS-Weekly#3323]
# 推荐收录

## 链接

[https://juejin.cn/post/7077870149239308324]
[https://juejin.cn/post/7077875029161017380]
[https://juejin.cn/post/7079397452192841735]

## 理由

[AVFoundation视频编辑方向的资料少且旧，重复度较高，本系列文章由浅入深，从实际的编辑功能入手介绍了AVFoundation在视频编辑中提供的API，最重要的是新]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by JonyFang** [comment]
放到下周
