### ISSUE TITLE
非touchbar的mbp 13寸 电池问题召回计划

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#333]
http://www.jiguo.com/article/article/59786.html?jguo=zhidx&code=MTUyNDMyNTUwNw==

帮老卓录的

**Comment by iblacksun** [comment]
### [非 Touch Bar 版 13 寸 MacBook Pro 存电池隐患，苹果将免费修理](https://www.apple.com/cn/support/13inch-macbookpro-battery-replacement/)

> Apple 已经确定，少数 13 英寸 MacBook Pro（无触控栏）电脑的某个组件可能会出现故障，导致内建电池发生膨胀。这并不是安全问题，Apple 会免费更换符合条件的电池。受影响的设备生产日期在 2016 年 10 月至 2017 年 10 月之间，根据产品序列号确定电池是不是符合更换条件。
