### ISSUE TITLE
Flutter使用source_gen快速提升开发效率

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3338]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/kwgI1FsEo5BGE7bRqKM7Mw

**Comment by linwenbang** [comment]
这篇 https://mp.weixin.qq.com/s/lrEzYdbafrqfDVFQl2ebRQ  更为详细，换这个然后这个作为参考链接
