### ISSUE TITLE
Weak self, a story about memory management and closure in Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3345]
# 推荐收录

## 链接

https://benoitpasquier.com/weak-self-story-memory-management-closure-swift

**Comment by kemchenj** [comment]
### [Weak self, a story about memory management and closure in Swift](https://benoitpasquier.com/weak-self-story-memory-management-closure-swift/)

[@kemchenj](https://kemchenj.github.io/)：在 Swift 里我们经常需要使用 weak 和 unowned 来解决循环引用的问题。

只使用一个闭包的时候，引用的逻辑关系很简单明了，但闭包嵌套的时候，即使使用了 weak 也有可能会不小心产生循环引用，这篇文章就针对这种情况进行了仔细的说明，并且提供对应的解决方案。
