### ISSUE TITLE
Swift协议与关联类型

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3365]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/Rglm0aJny-WO3zYd9ibqZQ

**Comment by kemchenj** [comment]
这文章前面讲 TabBarItem 的部分我感觉举例不是很好，抛出的问题也没有很好的解答，后面的部分甚至直接摘了其它文章的原文过来（参考文章里放了对应的链接）。

总体感觉就是写得很乱，我认为没有推荐的价值。
