### ISSUE TITLE
Remove Data Clump to Decrease Developer Cognitive Load in Swift

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3368]
# 推荐收录

## 链接

https://holyswift.app/remove-data-clump-to-decrease-developer-cognitive-load-in-swift

**Comment by kemchenj** [comment]
文章内容主要是想要解答 data clump 该如何解决以及对应的结构分层逻辑，但感觉解答得不是很完善。

意识流的内容加上是英文写的，估计看的人也不会很多，也没有什么查阅的价值，我感觉没必要推荐，先关了。
