### ISSUE TITLE
Custom Keyboard Extensions: Getting Started

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#338]
https://www.raywenderlich.com/180180/keyboard-extensions

**Comment by raozhizhen** [comment]
自定义键盘扩展的入门教程，从 0 到 1 的讲解如何创建一个摩尔斯电码键盘，包括自定义键盘的界面，自适应键盘配色方案，自动纠正和建议，请求位置信息等权限等功能。
