### ISSUE TITLE
Violet: Python VM written in Swift

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3393]
# 推荐收录

## 链接

https://github.com/LiarPrincess/Violet

## 理由

Violet is one of those Swift <-> Python interop thingies, except that this time we implement the whole language from scratch.

作者很有趣，还有一些其它项目，例如用 Swift 写了一个 GameBoy 模拟器...

**Comment by zvving** [comment]
项目以及作者的风格都很有趣，不过项目方向很小众，不作推荐。


那个 GB 模拟器项目也很有趣，我再看看…
