### ISSUE TITLE
网易 HubbleData 无埋点 SDK 在 iOS 端的设计与实现

### ISSUE THREAD

**Issue by 100mango** [SwiftOldDriver/iOS-Weekly#340]
https://neyoufan.github.io/2017/04/19/ios/%E7%BD%91%E6%98%93HubbleData%E6%97%A0%E5%9F%8B%E7%82%B9SDK%E5%9C%A8iOS%E7%AB%AF%E7%9A%84%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0/

推荐理由：详细地展示如何在 iOS 端构建一个无埋点的数据采集方案。

**Comment by zangqilong198812** [comment]
finished
