### ISSUE TITLE
Swift调试性能的优化方案

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#3402]
# 推荐收录

## 链接

http://dreampiggy.com/2022/05/07/Swift-%E8%B0%83%E8%AF%95%E6%80%A7%E8%83%BD%E7%9A%84%E4%BC%98%E5%8C%96%E6%96%B9%E6%A1%88/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Damonvvong** [comment]
https://mp.weixin.qq.com/s/n6cRVhr5Sw1CSOqAYWiBRw

**Comment by Damonvvong** [comment]
配合这个一起看哈。

**Comment by iblacksun** [comment]
### 🐢 [Swift 首次调试断点慢的问题解法](https://mp.weixin.qq.com/s/n6cRVhr5Sw1CSOqAYWiBRw)

[@享耳先森](https://github.com/iblacksun)：在 Swift 项目开发过程中，相信大家最近两年都深受「首次断点调试启动慢」问题困扰，根据项目大小和结构不同，首次调试时间从十几秒到几分钟不等，最近中文社区对此问题进行深入研究。

优酷团队发文 [Swift 首次调试断点慢的问题解法](https://mp.weixin.qq.com/s/n6cRVhr5Sw1CSOqAYWiBRw) 通过以下命令优化 LLVM 配置：
```
settings set target.memory-module-load-level minimal
settings set symbols.use-swift-clangimporter false
```
字节团队发文 [Swift 调试性能的优化方案](https://dreampiggy.com/2022/05/07/Swift-%E8%B0%83%E8%AF%95%E6%80%A7%E8%83%BD%E7%9A%84%E4%BC%98%E5%8C%96%E6%96%B9%E6%A1%88/) 通过自定义项目所使用 LLVM 工具链的形式进行优化。

>需要说明的是，以上方案与主工程项目结构有关，依赖的二进制库越多，效果越明显。
