### ISSUE TITLE
创业公司做数据分析（三）用户行为数据采集系统

### ISSUE THREAD

**Issue by 100mango** [SwiftOldDriver/iOS-Weekly#341]
https://zhuanlan.zhihu.com/p/26270699

推荐理由：揭示了数据采集的采集内容和采集方式。

**Comment by lacklock** [comment]
感觉和ios开发不是很相关

**Comment by 100mango** [comment]
是的。但是卓同学不是最开始就说过不需要一定和iOS有关么？这篇文章我觉得对客户端数据采集范畴是挺有帮助的。

**Comment by 100mango** [comment]
不过这期已经有了网易那篇。这篇可以去掉。
