### ISSUE TITLE
Flutter 3 新特性

### ISSUE THREAD

**Issue by CrazyCoderShi** [SwiftOldDriver/iOS-Weekly#3417]
# 推荐收录

## 链接

https://medium.com/flutter/whats-new-in-flutter-3-8c74a5bc32d0
https://medium.com/flutter/introducing-flutter-3-5eb69151622f
https://medium.com/dartlang/dart-2-17-b216bfc80c5d

## 理由

Flutter 3

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by linwenbang** [comment]
https://mp.weixin.qq.com/s/XjBWXflwBJy5IMXxv-S4qg
@CrazyCoderShi 介绍的不少，一起看下哪个合适，中文可能看起来比较舒服
