### ISSUE TITLE
字节跳动 DanceCC 工具链系列之 Swift 调试性能的优化方案

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3420]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/TXrY1bbSdYCkaeE8aq2NKg

**Comment by zvving** [comment]
@iblacksun 这两个文章相关，我跟你之前写的合在一起：

- 链接换上老司机的链接
- 描述微调，我们团队试了：字节的方案改善明显，优酷的方案效果不明显。
