### ISSUE TITLE
Scripting in Swift: Git Hooks

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3427]
# 推荐收录

## 链接

https://www.polpiella.dev/scripting-in-swift-git-hooks

**Comment by iblacksun** [comment]
### 🐕 [Scripting in Swift: Git Hooks](https://www.polpiella.dev/scripting-in-swift-git-hooks)

[@享耳先森](https://github.com/iblacksun)：Swift 除了用于 App 还可以干什么？本文作者使用 Git Hooks 结合 Swift `Command Line Tool` 解决真实工作场景中遇到的问题，如果你也有类似需求又不熟悉其他脚本语言，Swift 是很好的解决方案。
