### ISSUE TITLE
Unobtrusive runtime warnings for libraries

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3433]
# 推荐收录

## 链接

https://www.pointfree.co/blog/posts/70-unobtrusive-runtime-warnings-for-libraries

## 理由

assert/runtime-issues -> log，开发时本地抛出异常时，体验比弹窗或者主线程捕获 ``NSThread.mainThread.threadDictionary[NSAssertionHandlerKey]`` 好一些。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这篇文章之前推荐过了 https://github.com/SwiftOldDriver/iOS-Weekly/issues/3145

**Comment by ChengzhiHuang** [comment]
@kemchenj 我的锅，那我这个 issue 就先关掉了。
