### ISSUE TITLE
iOS新闻类App内容页技术探索

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#344]
https://dequan1331.github.io

对webview的深度hybrid玩的很6，虽然只是新闻内容页一个场景，但好多方案其实都可以迁移，webview这么玩才有意思啊，其实本文很多思路部分是我正在挖坑还没写的 hybrid黑脑洞第三篇文章的想法

**Comment by Awhisper** [comment]
留个我个人在自己微博上的推荐评论吧 ╮(╯_╰)╭

Hybrid这么玩才有意思！webview慢？webview渲染卡？webview交互差？什么是Hybrid？Hybrid就是纯web做不到想尽一切办法用native补，别局限在一个用个jsbridge，掉几个oc函数就叫hybrid了，所有webview的痛点都能用Hybrid的思路让native补齐，Hybrid就相当于不依赖谷歌苹果支持，在自己的App里实现自己的能力更激进的PWA，Hybrid就相当于不依赖微信支持，让自己的WebView也做到小程序那样的体验，这才是真正有意思的Hybrid！本文中部分方案其实部分想法也在我挖坑拖欠的第三篇文章Hybrid开脑洞里面，当然只是部分，我的脑洞还有不少

**Comment by 100mango** [comment]
文章针对新闻类 App 内容页的技术实现进行了探索和分析。并将成果封装成三个框架：[HybridPageKit](https://github.com/dequan1331/HybridPageKit)、[ReusableNestingScrollview](https://github.com/dequan1331/ReusableNestingScrollview)以及[WKWebViewExtension](https://github.com/dequan1331/WKWebViewExtension)。
    文章不仅从技术方案选择，组件化架构，加载速度优化给我们高屋建瓴地展示了新闻类的Hybrid技术应该如何构建，更重要地开启了我们的脑洞：真正Hybrid应该怎么玩才有意思。不是简单地嵌入webview,使用一下JSBridge。而是取长补短，WebView和Native技术携手构造更优秀的应用体验。

**Comment by 100mango** [comment]
done
