### ISSUE TITLE
设计高效的 UI 测试

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3440]
2022 年 5 月 31 日

了解如何设计测试，来帮助你发现和诊断最棘手的漏洞。我们将解释如何使用 XCTest 改进您的自动化测试，以找到代码中的隐忧，以及如何准备测试以应对失败。从而更轻松地对问题进行分类，以便您可以快速解决问题，并修复错误。理解中断，学习如何预测 App 的潜在中断、创建智能测试以识别它们。通过使用 UI 中断处理，构建更好的测试，管理预期的警报。

报名预计开放时间：2022 年 5 月 26 日

**Comment by raozhizhen** [comment]
这个 issues 是不是过期不需要处理了
