### ISSUE TITLE
“The evolution of SwiftUI” with special guest Chris Eidhof

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3441]
# 推荐收录

## 链接

https://www.swiftbysundell.com/podcast/116/

**Comment by GesanTung** [comment]
fix #3441 Chris Eidhof在播客中讲述了SwiftUI自最初发布以来的发展，分享了过去几年使用它的一些关键经验，并讨论了应用架构和状态管理等概念，没特别的内容。纯英文博客，无字幕对应文章，门槛较高
