### ISSUE TITLE
Flutter 3.0 之 PlatformView ：告别 VirtualDisplay ，拥抱 TextureLayer

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3443]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/dBGpH6gHA9errCzrDxRDQg

**Comment by CrazyCoderShi** [comment]
这篇可以跟[另一篇](https://github.com/SwiftOldDriver/iOS-Weekly/issues/3501)一起综合发，这俩文章作者和要讲的内容大致相同，我先关掉
