### ISSUE TITLE
yyjson 0.5.0

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#3447]
https://github.com/ibireme/yyjson/releases/tag/0.5.0

**Comment by iblacksun** [comment]
### 🐕 [YYJSON 0.5.0 Released](https://github.com/ibireme/yyjson/releases/tag/0.5.0)

[@享耳先森](https://github.com/iblacksun) YYJSON 是用 C 写的 JSON 解析库，以性能著称，近日发布了 0.5.0 版，有许多新特性与改进。
