### ISSUE TITLE
Swift for TensorFlow 文档库

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#345]
https://github.com/tensorflow/swift
https://github.com/google/swift/tree/tensorflow
https://github.com/tensorflow/swift-models

**Comment by iblacksun** [comment]
###  [Swift for TensorFlow 正式发布](https://github.com/tensorflow/swift)

TensorFlow 社区在 TensorFlow Dev Summit 2018 上宣布将开源 Swift for TensorFlow 项目，现在终于正式发布了，这里是[源码](https://github.com/google/swift/tree/tensorflow)及示例 [Models](https://github.com/tensorflow/swift-models).
