### ISSUE TITLE
Swift 中的幻象类型

### ISSUE THREAD

**Issue by fanbaoying** [SwiftOldDriver/iOS-Weekly#3455]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/HLWu24LrfqSfbhd9x6Q_ag

## 理由

利用 Swift 的类型系统在编译时执行更多种类的数据验证——消除更多潜在的歧义来源，并帮助我们在整个代码库中保持类型安全——通过使用幻象类型(phantom types)。

## 推荐人信息

公众号『Swift社区』主编，做最好的 Swift 社区，希望更多的人学习和使用 Swift。

**Comment by iblacksun** [comment]
### 🐕 [Swift 中的幻象类型(phantom types)](https://mp.weixin.qq.com/s/HLWu24LrfqSfbhd9x6Q_ag)

[@享耳先森](https://github.com/iblacksun)：`Phantom Types` 是一种编码技巧，让你可以利用 Swift 的强类型特性写出更安全的代码，本文介绍了一些可使用 Phantom Types 的场景及使用技巧。

建议结合下面文章一起阅读：
[Phantom Types in Swift](https://zhuanlan.zhihu.com/p/35696032)
[Swift tricks-Phantom Types](https://www.jianshu.com/p/72cd63cf9393)

> 推荐人：[@Swift社区]()，本文翻译自 [swiftbysundell.com](https://www.swiftbysundell.com/articles/phantom-types-in-swift/)
