### ISSUE TITLE
Reimplementation of Implicitly Unwrapped Optionals

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#346]
https://swift.org/blog/iuo/

强制解包现在变成了一个操作符，而不再是一个类型，预计 Swift 5 会有不小的的 Source Break

**Comment by mmoaay** [comment]
为了提升类型检查的一致性，Swift 的下个版本计划对 `ImplicitlyUnwrappedOptional ` 类型相关的一些操作进行重新实现，其实说到底所有的操作都是为了去掉 `ImplicitlyUnwrappedOptional ` 类型，这样可选值类型就剩 `Optional<T>`，`!` 则只是一个操作符而已，不包含 `ImplicitlyUnwrappedOptional ` 这个特殊类型的含义。不过小编看了下所有的改动，目测应该都是可以用代码迁移器搞定的，大家不用特别担心下个版本需要做代码的大变动。
