### ISSUE TITLE
ios中对证书加密技术的介绍

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#348]
https://medium.com/xcblog/secure-ios-certificates-using-modern-cryptography-3441bf8661a4

**Comment by 100mango** [comment]
文章的主题为使用现代加密技术保护 iOS 证书（certificates）。我们平时测试，提交应用到AppStore都需要用到苹果给我们的开发证书。阅读本文，我们可以学习到如何通过 openSSL 对 iOS 开发证书进行加密。

**Comment by 100mango** [comment]
done
