### ISSUE TITLE
LLVM Pass 其零：新的Pass机制

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3481]
# 推荐收录

## 链接

https://homura.live/2022/06/19/llvm-pass-0/

**Comment by kemchenj** [comment]
- [LLVM Pass 其一：PassManager](https://homura.live/2022/06/26/llvm-pass-1/)
- [LLVM Pass 其二：Analysis与AnalysisManager](https://homura.live/2022/07/03/llvm-pass-2/)

作者好像还在更新，考虑等后续更完了再推荐吧。

**Comment by kemchenj** [comment]
### LLVM New Pass Manager

[@kemchenj](https://kemchenj.github.io/)：LLVM 13 修改了默认的 PassManager，新的 PassManager 最大的改变是将 Pass 和 Analysis 拆分开。

更加合理的架构除了让逻辑变得更加清晰，也让性能得到了提升，Rust 编译器在迁移到新的 API 之后观测到了 5-20% 的性能提升，Swift 近日也开始[迁移到新的 API](https://github.com/apple/swift/pull/60077)。

如果你好奇什么样的修改可以让性能有如此大的提升，那就一定不要错过，这一系列文章详细讲解了新 API 的设计和使用方式，以及与之前 API 的对比。

- [LLVM Pass 其零：新的Pass机制](https://homura.live/2022/06/19/llvm-pass-0/)
- [LLVM Pass 其一：PassManager](https://homura.live/2022/06/26/llvm-pass-1/)
- [LLVM Pass 其二：Analysis与AnalysisManager](https://homura.live/2022/07/03/llvm-pass-2/)
- [LLVM Pass 其三：PassBuilder](https://homura.live/2022/07/10/llvm-pass-3/)
- [LLVM Pass 其四：PassManager的改进与迁移现状](https://homura.live/2022/07/17/llvm-pass-4/)
