### ISSUE TITLE
Model View Controller Store: Reinventing MVC for SwiftUI with Boutique

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3493]
# 推荐收录

## 链接

https://build.ms/2022/06/22/model-view-controller-store/?o=ios

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
介绍基于  https://github.com/mergesort/Boutique 一套 SwiftUI MVCS 架构实现，内容展开较多，但复杂度不高，表达风格上也不易于国内读者理解，不做推荐。
