### ISSUE TITLE
Existential any in Swift explained with code examples

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3494]
# 推荐收录

## 链接

https://www.avanderlee.com/swift/existential-any/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [Existential any in Swift explained with code examples](https://www.avanderlee.com/swift/existential-any/)

[@享耳先森](https://github.com/iblacksun)：在 Swift 5.6 中，[SE-335](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) 引入了 `existential any`，Swift 5.7 对其进行了增强。本文详细介绍了 `any` 关键词具体用法、和 `some` 的差异及对性能的影响。
