### ISSUE TITLE
用swift写编译脚本

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#350]
https://medium.com/rosberryapps/swift-plist-and-two-smoking-scripts-94bb54cbeded

**Comment by EyreFree** [comment]
### [Swift, Plist and Two Smoking Scripts](https://medium.com/rosberryapps/swift-plist-and-two-smoking-scripts-94bb54cbeded)

有没有想过整个项目从前端到后端全部用 Swift 来开发？甚至包括脚本？本文介绍了怎样用 Swift 在十五分钟内开发一个能够帮助我们对项目设置进行检查的 Build Phase 脚本，值得一看。
