### ISSUE TITLE
Flutter 3.0下的混合开发演进

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3501]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/yUxr-NN9pU8bYvZ8gu6MGA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
结合：https://mp.weixin.qq.com/s/dBGpH6gHA9errCzrDxRDQg

**Comment by linwenbang** [comment]
这篇文章和之前写的重复了（看上去是分享课的重新编写），3.0 的 platformviews 之前推荐了不少，不重复推荐了
