### ISSUE TITLE
codable vs objectmapper

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#351]
https://medium.com/bbc-design-engineering/codable-vs-objectmapper-af5fe8e8efd5

**Comment by kemchenj** [comment]
### [Codable vs. ObjectMapper](https://medium.com/bbc-design-engineering/codable-vs-objectmapper-af5fe8e8efd5)

作者分析了 Codable 和 ObjectMapper 的区别，并且拓展 Codable 实现了 ObjectMapper 的主要几个 feature。
