### ISSUE TITLE
USD-Cookbook

### ISSUE THREAD

**Issue by XanderXu** [SwiftOldDriver/iOS-Weekly#3520]
# 推荐收录

## 链接

https://github.com/ColinKennedy/USD-Cookbook

## 理由

关于 USD 格式的示例、讲解、工具链

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by waterXu** [comment]
这个USD的工具偏游戏向的读者会关注，对于我们的读者来说，尝试的难度比较高，而且没有实际的应用场景。暂不推荐~
