### ISSUE TITLE
抢先体验! 在浏览器里写 Flutter 是一种什么体验？

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3523]
# 推荐收录

## 链接

[抢先体验! 在浏览器里写 Flutter 是一种什么体验？](https://mp.weixin.qq.com/s/BZgc2VWWqOvUjZyo1FS3nw)

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
极速已经完成相关 issue，现手动关闭
