### ISSUE TITLE
App Store Connect API 更新，支援 In-app purchases、Subscriptions、Customer Reviews 管理

### ISSUE THREAD

**Issue by zhgchgli0718** [SwiftOldDriver/iOS-Weekly#3527]
# 推荐收录

## 链接

https://medium.com/zrealm-ios-dev/app-store-connect-api-%E7%8F%BE%E5%B7%B2%E6%94%AF%E6%8F%B4-%E8%AE%80%E5%8F%96%E5%92%8C%E7%AE%A1%E7%90%86-customer-reviews-f1365e51902c

## 理由

- App Store Connect API v2 更新消息
- JWT 产生范例
- Customer Reviews API 实验

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
感谢你的推荐，我大致阅读了一遍，文章介绍 App Store Connect API v2 的内容并不多，有很大的篇幅在讲解 JWT 的使用方式，跟前几周推荐过的 [App Store Server API 实践总结](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/2022/%23206-2022.06.27.md#-app-store-server-api-实践总结) 内容有部分重复，并且那篇文章介绍的内容更加全面一些，所以我认为这篇文章不适合收录。
