### ISSUE TITLE
Care and Feeding of Xcode Configurations

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#353]
http://americanexpress.io/care-and-feeding-of-xcode-configurations

**Comment by Damonvvong** [comment]
大致理解了一下：
文章大致描述了一下团队协同过程中，现有的 Xcode 配置容易造成不少问题。
所以他推荐自己来编写 Xcode Configurations 文件来解决这类问题。
最后阐述了一下他自己 编写 Xcode Configurations 文件的组织模式。

**Comment by iblacksun** [comment]
### 🐢 [Care and Feeding of Xcode Configurations](http://americanexpress.io/care-and-feeding-of-xcode-configurations)

Xcode 默认的 `build setting` 机制在团队协作中经常会因误操作等原因导致编译问题，文章介绍了引入 `xcconfig` 文件来解决此类问题(如果你使用了 `Cocoapods`，那么你已经引入了)，由此带来 `share configurations`、`change history` 等好处，最后还介绍了如何组织 `xcconfig` 文件以及一些 `ProTips`.
