### ISSUE TITLE
通过file是直接查看应用的doucments里的内容，对于调试会有帮助

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#354]
https://twitter.com/olebegemann/status/987346188591681536

**Comment by EyreFree** [comment]
### [Inspect your app’s Documents directory in the Files.​app](https://twitter.com/olebegemann/status/987346188591681536)

小技巧，如果我们在 `Info.​plist` 中设置了 `LSSupportsOpeningDocumentsInPlace=YES` 和 `UIFileSharingEnabled=YES`，就能够从苹果官方的文件管理器 [Files](https://itunes.apple.com/cn/app/Files/id1232058109?mt=8) 对 App 的 Documents 目录进行查看，更多信息可参考 [苹果官方文档](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW13)。
