### ISSUE TITLE
跨全端SDK技术演进

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3542]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/NMsZWEzP3oE-KexRQMesmQ
https://mp.weixin.qq.com/s/cAPAHzlChV-TjbAIj4YQ_Q

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这个系列好像总共有三篇，等第三篇发布后一并推荐吧。

**Comment by ChengzhiHuang** [comment]
第三篇来了：https://mp.weixin.qq.com/s/t7apHNc9ZHF__dab1KKwIQ

**Comment by kemchenj** [comment]
### 阿里跨端技术演进

[@kemchenj](https://kemchenj.github.io/)：阿里巴巴的千牛团队为我们带来的跨端技术演进分享，这个系列总共三篇文章：

- [跨全端 SDK 技术演进](https://mp.weixin.qq.com/s/NMsZWEzP3oE-KexRQMesmQ)：伴随业界跨平台技术发展与演进，千牛团队也沉淀了一整套基于 C++ 的跨平台技术体系，本文将以消息SDK为例，详述这一技术演进历程。
- [跨桌面端 Web 容器演进](https://mp.weixin.qq.com/s/cAPAHzlChV-TjbAIj4YQ_Q)：从容器的架构演进，容器的功能增强和稳定性保障及未来的演进，这3个方面介绍一下千牛的应用程序如何对接浏览器的能力。
- [跨桌面端之组件化实践](https://mp.weixin.qq.com/s/t7apHNc9ZHF__dab1KKwIQ)：主要介绍了千牛PC跨端框架中，关于组件化部分的思考、方案选择、遇到的一些问题和解法。
