### ISSUE TITLE
Hummer 引擎优化系列 - Flutter SurfaceView 动态切换方案

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3545]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/mUDmWbvjjtqFcaIB6Bi_Rw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by anotheren** [comment]
内容是基于 Android 的不太合适
