### ISSUE TITLE
iOS 16 Live Activity

### ISSUE THREAD

**Issue by wang9262** [SwiftOldDriver/iOS-Weekly#3547]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/aKD-WBYHsepg96zOC378cg

## 理由

文章介绍了 iOS 16 Live Activity 的适配及注意事项，也分享了下开发/使用体验，文章最后也提供了一个Demo供大家参考。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [iOS 16 Live Activity](https://mp.weixin.qq.com/s/aKD-WBYHsepg96zOC378cg)

[@享耳先森](https://github.com/iblacksun)：WWDC 2022 Keynote 中介绍了 iOS 16 中一个比较亮眼的更新：Live Activity，开发者可以在锁屏页面上放置一个可以「实时」更新的 Widget，比如外卖或者打车应用，开启 Live Activity 后在锁屏页上实时看到外卖小哥/司机与我们的距离及预计到达时间。

这一 API 及对应功能终于在 iOS 16 Beta4 一起放出，但 Apple 明确不会随正式版的 iOS 16.0 一起发布，而是在今年晚些时候释出，具体时间没有给。

本文介绍了 iOS 16 Live Activity 的适配及注意事项，也分享了下开发/使用体验，文章最后也提供了一个Demo供大家参考，可以与[Experimenting with Live Activities](https://oleb.net/2022/live-activity/) 关联阅读。
