### ISSUE TITLE
tcmalloc 源码解析

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3550]
# 推荐收录

## 链接

https://dirtysalt.github.io/html/tcmalloc.html#sec-4-2

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
tcmalloc是Google开发的内存分配器，在Golang、Chrome中都有使用该分配器进行内存分配。有效的优化了ptmalloc中存在的问题。当然为此也付出了一些代价，按下不表，先看tcmalloc的具体实现。

**Comment by halfrost** [comment]
你们居然推荐了 tcmalloc 这篇文章。tcmalloc 的源码，在 go 的高级开发岗位的面试中，一定会被问到。我碰巧读过这部分的源码。还是比较痛苦的。后来人如果还想读它的源码，我建议从大的方向来掌握它的思路。死钻某一行代码的用途没有意义，因为那部分代码可能是很早以前遗留下来的，或者是解决奇怪问题打补丁打上去了。学习学习它在锁，多线程上的处理方法和思路。
