### ISSUE TITLE
iOS 16 新 NSException: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application circumvented Objective-C runtime dealloc initiation for <UIViewController> object.'

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3551]
# 推荐收录

2. iOS 16里 UIViewController 多了一个方法叫 _objc_initiateDealloc，内部代码是用来保证VC在主线程释放的。 调用链为：release - > -[UIViewController _objc_initiateDealloc] -> dispatch_async(_objc_deallocOnMainThreadHelper) -> -[UIViewController dealloc] 。以前的系统也有这个机制，看起来是iOS 16换了实现方式
3. _objc_initiateDealloc 这个名字 和 异常里的 “dealloc initiation” 看起来关联很大，而且是 runtime里判断 对象释放的时候 是调用 dealloc 还是调用 _objc_initiateDealloc

iOS16有个“新要求”：由于系统 UIView/UIViewController  有了initialize方法，大家不能在自己category里覆盖 +initialize方法了，
这样会导致不调用_class_setCustomDeallocInitiation([UIViewController class])，会发生崩溃的。（需要使用Xcode 14编译才能复现崩溃）。
如果一定要覆盖+initialize方法，那就要想办法先调用官方的，再调用自己的+initialize方法~（不建议这么做）

## 推荐人信息

https://github.com/pudge62

**Comment by LeoTnT** [comment]
How to solve it

**Comment by FuzzyFade** [comment]
How to solve it

**Comment by LimingZou** [comment]
How to solve it

**Comment by ChengzhiHuang** [comment]
不要在 category里覆盖 UIView/UIViewController 的 +initialize 方法，换一个时机做对应的 hook 即可。
如果不担心启动劣化的话，可以直接挪到 +load 里。
