### ISSUE TITLE
Shared with You implementation and testing explained

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3563]
# 推荐收录

## 链接

https://www.avanderlee.com/swift/shared-with-you/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [Shared with You implementation and testing explained](https://www.avanderlee.com/swift/shared-with-you/)

[@享耳先森](https://github.com/iblacksun)：WWDC 22 中苹果将原来仅 Apple 可用的 `Shared with you` 开放给所有开发者，本文详解了其工作机制和适配方式。
