### ISSUE TITLE
MachO code signature profiling

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3567]
# 推荐收录

## 链接

https://www.mo4tech.com/macho-code-signature-profiling.html

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
好像这篇文章是洗稿洗出来的，首先是超链没加上：

<img width="899" alt="Screen Shot 2022-08-14 at 19 42 20" src="https://user-images.githubusercontent.com/11192474/184535105-0eea48c2-74f3-44d1-8eb8-3631ae30972c.png">

接着是用了微信作为例子，然而作者是个外国人，在谷歌也没有收到类似作者的信息：

<img width="924" alt="Screen Shot 2022-08-14 at 19 42 40" src="https://user-images.githubusercontent.com/11192474/184535126-927d07ff-90ab-4bd7-a741-e01edef7aab1.png">

应该是扒了国内的这篇文章 https://juejin.cn/post/7017842746937311246 。

**Comment by kemchenj** [comment]
### [MachO 代码签名剖析](https://juejin.cn/post/7017842746937311246)

[@kemchenj](https://juejin.cn/post/7017842746937311246)：验证代码的正确性是计算机科学中最难的问题之一，因为不存在普遍意义的正确的算法，所以这一验证通常使用数字签名处理。大家可以通过阅读此文思考代码来源是否合法和代码是否被修改过的验证是如何实现的。
