### ISSUE TITLE
Codable与JSONSerialization性能测试

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#357]
https://flight.school/articles/benchmarking-codable/
https://github.com/Flight-School/CodablePerformance

**Comment by kemchenj** [comment]
### [Codable与JSONSerialization性能测试](https://flight.school/articles/benchmarking-codable/)

Swift 4 的新功能 Codable 可以自动生成解析 JSON 的构造器，但这些自动生成的代码跟我们手写的有什么区别呢？这篇文章的作者写了一个性能测试去比较 JSONDecoder 和 JSONSerialization，文末作者表示虽然 Codable 生成的代码效率只有手动解析的一半，但绝大部分情况下 Codable 带来的便利远重要于这点性能消耗。
