### ISSUE TITLE
微信小程序 Skyline 渲染引擎 Beta

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3579]
# 推荐收录

## 链接

https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/introduction.html

**Comment by CrazyCoderShi** [comment]
这个我觉得不太合适，因为这个是一个相关平台的文档，读者们可能看起来摸不到头脑？
但这确实是个值得钻研的好东西，所以我先去研究研究，post 我就不贴进去了 😂
