### ISSUE TITLE
 A New Swift Parser for SwiftSyntax

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3581]
# 推荐收录

## 链接

https://forums.swift.org/t/a-new-swift-parser-for-swiftsyntax/59813

## 理由

Goals:

- Adopt in the compiler
- Replace existing SwiftSyntaxParser

**Comment by zvving** [comment]
https://forums.swift.org/t/implementing-parts-of-the-swift-compiler-in-swift/59524 用 Swift 实现 Swift 编译器的的第一步工作，预期提升编译器相关代码维护效率、优化编译错误定位效率、（性能差别不大），看讨论并不清晰，还有非常长的路要走，暂不推荐。
