### ISSUE TITLE
正则测试、编写、debug 网站

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#3585]
# 推荐收录

## 链接

https://regex101.com/ 

## 理由

测试正则准确性的网址。非常实用，还有 Code Generate，牛逼

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by faimin** [comment]
遇到个坑，如果用的是 `Microsoft Edge` 浏览器需要关闭`增强安全`选项，否则这个网站无法正常显示

**Comment by nianran** [comment]
哈~感谢提醒~
编辑同学可以帮忙注明一下~
