### ISSUE TITLE
基于汇编实现objc_msgSend hook方法耗时的方案

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3586]
# 推荐收录

## 链接

https://juejin.cn/post/7134877291716280328

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [基于汇编实现 objc_msgSend hook 方法耗时的方案](https://juejin.cn/post/7134877291716280328)

[@kemchenj](https://kemchenj.github.io/)：测算函数/方法执行耗时，对于每一位开发同学来说，似乎都是一道绕不过的坎。

本文通过引入货拉拉移动端研发过程中的痛点，产生方法耗时分析的需求，在调研业内各种分析工具和方案后，结合需求整合出他们的方案，感兴趣的同学可以点击前往阅读。
