### ISSUE TITLE
在滑动选择app页面中如何隐藏敏感信息

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#360]
https://medium.com/@dfplaughton/ios-springboard-security-revisited-f55d7f057e4a

**Comment by EyreFree** [comment]
### [iOS Springboard Security - Revisited](https://medium.com/@dfplaughton/ios-springboard-security-revisited-f55d7f057e4a)

本文介绍了一种在 iOS 的 App 切换页面替换 / 隐藏 App 原始缩略图的方法，有类似安全需求的同学可以作为参考。类似地，可以实现“后台模糊”效果，比如蚂蚁金服旗下的 [蚂蚁财富](https://itunes.apple.com/cn/app/AntWealth/id1025628019?mt=8) 就采用了类似的安全措施，感兴趣的同学可以参考这里的 [示例代码](https://github.com/EyreFree/VSCAM/tree/master/VSCAM/3rdPart/SecurityStrategy)。
