### ISSUE TITLE
How to improve iOS build times with modularization

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3604]
# 推荐收录

## 链接

https://www.runway.team/blog/how-to-improve-ios-build-times-with-modularization

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕  [How to improve iOS build times with modularization](https://www.runway.team/blog/how-to-improve-ios-build-times-with-modularization)

[@享耳先森](https://github.com/iblacksun)：随着业务的迭代，项目代码的复杂度越来越高，如果不能很好的架构我们的应用，将严重拖慢编译速度，从而影响开发体验。本文介绍「模块化」的方式(很多大厂也是这么做的)，利用模块间的横向依赖(而不是垂直依赖)来解决这一问题。
