### ISSUE TITLE
What's the "any" keyword? Understanding Type Erasure in Swift

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3614]
# 推荐收录

## 链接

https://swiftrocks.com/whats-any-understanding-type-erasure-in-swift

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [What's the "any" keyword? Understanding Type Erasure in Swift](https://swiftrocks.com/whats-any-understanding-type-erasure-in-swift)

[@享耳先森](https://github.com/iblacksun)：Swift 的强类型是程序健壮性的基石。但在过去，有些特殊场景下强类型给开发者带来一些不必要的规避工作，Swift 5.7 引入的 `any` 关键词很好的解决了这一问题。本文解释类型擦除的概念，以及过去是如何做的？有 `any` 后有什么不同？建议结合 [Existential any in Swift explained with code examples](https://www.avanderlee.com/swift/existential-any/) 一起阅读。
