### ISSUE TITLE
50道 iOS 面试题，还是有一些不错的知识点

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#363]
https://medium.com/@duruldalkanat/50-ios-interview-questions-and-answers-part-5-de6241374a8f

**Comment by iblacksun** [comment]
### [50 iOS Interview Questions And Answers Part 5](https://medium.com/@duruldalkanat/50-ios-interview-questions-and-answers-part-5-de6241374a8f)

50 道 iOS 面试题，有一些不错的知识点，还有 part1-4。如果有换工作的打算，建议细看，查缺补漏，技术面试时一些基础知识掌握不全的话很减分的。
