### ISSUE TITLE
iOS灵动岛【电商商品秒杀】开发实践

### ISSUE THREAD

**Issue by erduoniba** [SwiftOldDriver/iOS-Weekly#3638]
# 推荐收录

## 链接

https://juejin.cn/post/7153236337074634788

## 理由
iOS灵动岛【商品秒杀】开发实践，详细讲解了灵动岛的基本概念、开发基本要素及细节。Demo中展示了主工程和灵动岛Widget的通讯方式及灵动岛Widget的布局方式。

## 推荐人信息
邓立兵，京喜App端iOS开发者

**Comment by ChengzhiHuang** [comment]
with #3625
