### ISSUE TITLE
计算机系应届生求职指北

### ISSUE THREAD

**Issue by raozhizhen** [SwiftOldDriver/iOS-Weekly#364]
[计算机系应届生求职指北](https://media.weibo.cn/article?id=2309404230281430219666) 

讲的都挺有道理的，还在学校的学生越早知道这些越好

**Comment by lacklock** [comment]
点不进去啊，被作者删除了？

**Comment by raozhizhen** [comment]
@lacklock 很奇怪 我能点进去啊  我微信分享给你

**Comment by lacklock** [comment]
微博太傻逼了，用github的链接： https://github.com/easychen/career-guide-for-cs-graduate

**Comment by raozhizhen** [comment]
两点之间，直线最短，方向对了，你走的就是捷径。

文章分享了职业规划、校招、求职策略、技术职位选择、语言和技术栈的选择、技术栈的优化、简历的书写等经验，这些东西对于还在学校的计算机系的学生，非常有帮助，早点思考这些问题，未来能走的更顺利。
