### ISSUE TITLE
Placement: Polyfill for SwiftUIs iOS 16 Layout protocol

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3642]
# 推荐收录

## 链接

https://github.com/sampettersson/Placement

## 理由

A polyfill for the new Layout protocol from iOS 16. Supports iOS 14 and above, on iOS 16 Placement favors the built in Layout protocol and uses that instead of Placements own layouter.

**Comment by zvving** [comment]
把 iOS16+ Layout 的降级至支持 iOS14+ ，通过框架重写 _overrideSizeThatFits 以及根据自定义布局实现 placeSubviews 完成。
项目还比较早期，未经过验证，暂不推荐。
