### ISSUE TITLE
MetalBuilder:方便在 iPad 上写 Shader 的框架

### ISSUE THREAD

**Issue by XanderXu** [SwiftOldDriver/iOS-Weekly#3659]
# 推荐收录

## 链接

https://github.com/gadirom/MetalBuilder

使用效果演示见
https://github.com/gadirom/Art-in-Swift

## 理由

MetalBuilder is an open source Swift Package for declarative dispatching of Metal shaders.

It can extremely simplify your Swift and Metal code, especially if you use Metal in SwiftUI apps.

Also, if you're new to Metal or to GPU programming in general, MetalBuilder will make it easy for you to start.

Since MetalBuilder is purely Swift Package, you can import it in Swift Playgrounds on an iPad.

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by olddonkey** [comment]
我对 Metal 相关的库不是特别的熟悉，鉴于这是个新的库，帮我reassign一下？

**Comment by ChengzhiHuang** [comment]
交给对 Metal 比较熟悉(？)的 AidenRao

**Comment by ChengzhiHuang** [comment]
我问下组织里对 Metal 比较熟悉的同学来负责审核吧

**Comment by ChengzhiHuang** [comment]
@XanderXu 是有新的文章了吗？抱歉我们这里对 Metal 熟悉的确实不多...可以带上自荐语～
