### ISSUE TITLE
Thoughts on SwiftUI vs UIKit

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3665]
# 推荐收录

## 链接

https://swiftrocks.com/my-experience-with-swiftui

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by linwenbang** [comment]
看着没啥干货，就介绍了一下心得体会，给新人阅读吧，英文又费劲，给熟练的人看吧，好像也没啥干货
