### ISSUE TITLE
AB 实验为何值得信赖？

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3677]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/2sE-KxdRAvnp3GBOBU4Cfg

## 理由

非客户端技术内容，但是 ab 实验很多人都会用到，所以可以了解了解

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
对于客户端同学，AB 实验挺值得介绍，但本文全篇都是概念，对随机方式、显著/置信判断也纯概念介绍，没深入接触过的同学通读下来很难理解。

找了下也没看到合适的 ab 入门文章，这次不做推荐，有合适的 ab 介绍文章再推荐。
