### ISSUE TITLE
Flutter 多引擎渲染，在稿定 App 的实践

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3680]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/fpbVBg-Usuu7I6lCbPhlsQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
少庸自己推了一篇 ffi ，这篇我就重新分配下 https://github.com/SwiftOldDriver/iOS-Weekly/issues/3691

**Comment by GesanTung** [comment]
已经fix，未关联
