### ISSUE TITLE
三代终端容器 KUN 的首次大考【架构演进】

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3683]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/26SCEM6QPhAazydRUq9h3Q

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
with https://github.com/SwiftOldDriver/iOS-Weekly/issues/3697
