### ISSUE TITLE
RWDEVCon 2018 视频，不过要99刀

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#369]
https://store.raywenderlich.com/products/rwdevcon-2018-vault-video-bundle

**Comment by iblacksun** [comment]
### [RWDevCon 2018 Vault Video Bundle](https://store.raywenderlich.com/products/rwdevcon-2018-vault-video-bundle)

此系列视频收费 $99，共 18 个主题：如 `Serialization in Swift`、`Auto Layout`、`Clean Architecture`、`Android`、`TDD`、`WKWebView`、`ARKit`、`Metal` 等，如对其中两个主题感兴趣也就值回票价了。
