### ISSUE TITLE
CSProgress: A higher-performing, easier-to-use replacement class for Apple's NSProgress, written in Swift.

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3692]
# 推荐收录

## 链接

https://github.com/CharlesJS/CSProgress

**Comment by iblacksun** [comment]
### [CSProgress](https://github.com/CharlesJS/CSProgress)
[@享耳先森](https://github.com/iblacksun)：`CSProgress` 是一个高性能且易使用的 `NSProgress` 替代方案。 或许你对 `NSProgress` 并不熟悉，因为在业务开发中比较少用到，但还是建议你阅读下 `CSProgress` 项目的 READMEe，详细阐述了 NSProgress 性能问题及糟糕的 API 设计，对自己也是种警惕。
