### ISSUE TITLE
探秘越来越复杂的ImageIO框架

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3693]
# 推荐收录

## 链接

https://dreampiggy.com/2022/11/07/探秘越来越复杂的ImageIO框架/

**Comment by ChengzhiHuang** [comment]
哈哈哈嗝（公众号推过了再推荐一遍也没毛病

**Comment by JonyFang** [comment]
update link：https://mp.weixin.qq.com/s/nbPIScJEZ3ReMSFuvNLkzQ
