### ISSUE TITLE
一个 WebKit Bug 导致小程序页面跳转失败的问题的排查经历

### ISSUE THREAD

**Issue by White-White** [SwiftOldDriver/iOS-Weekly#3708]
# 推荐收录

## 链接

https://www.yuque.com/whiteshouse/nbwimi/ncrw66

## 理由

文章记录了一个艰深问题的排查过程，其中的思考定可以引起大家的共鸣

## 推荐人信息

老王

**Comment by Damonvvong** [comment]
考虑加入原创计划。https://mp.weixin.qq.com/s/lurct-E-sJJQk-QHa33VPg
