### ISSUE TITLE
Combining opaque return types with primary associated types

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3711]
# 推荐收录

## 链接

https://www.swiftbysundell.com/articles/opaque-return-types-primary-associated-types/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@waterXu 这篇指导下 Zoe 进行简评吧

**Comment by zoeGuo** [comment]
Swift5.7引入了associated type的概念，即可以在protocol里使用associated type。文章就引入associated type的原因，以及associated type 结合some、any关键字的使用展开介绍。

**Comment by ChengzhiHuang** [comment]
@zoeGuo 我给你添加了可以建 PR 的权限。

PR 的标题一般为：fix #xxxx ，例如 fix #2322 ，数字就是 issue_id ，这样可以自动关联 issue 。

同时书写简评时需要参考：[中文排版指南](https://github.com/sparanoid/chinese-copywriting-guidelines)。目前格式存在一些空格相关的问题。

然后个人觉得这样的描述有些过于抽象，我们一般会希望读者读了简评就能了解文章大概，是否可以再详细展开一些。
