### ISSUE TITLE
Standardizing build system using modern Swift Packages in LINE

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3715]
# 推荐收录

## 链接

https://speakerdeck.com/giginet/standardizing-build-system-using-modern-swift-packages-in-line?slide=36

## 理由

从 Cocoapods/Basel/Jojo 转 SPM （时代的倒退？手动狗头

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Standardizing build system using modern Swift Packages in LINE](https://attendees.bizzabo.com/417034/agenda/activity/1022649)

[@kemchenj](https://kemchenj.github.io/)：来自 LINE 的工程师介绍了他们使用 SPM 改造构建系统的过程。随着 LINE iOS 端的迭代，代码行数现在已经增长到了两百万以上，编译速度也就慢慢成为了一个“问题”。

他们自然而然也选择业界流行的方案 Bazel 来解决这个问题，整个构建过程分为两步：

1. 所有依赖库都使用 Bazel 进行打包成二进制库
2. 主工程 App 引用上一步的库，使用 Xcode 进行编译和调试

但使用 Bazel 的同时也带来了一些问题，学习成本高，维护成本高，缺乏依赖管理。付出如此高的代价，但实际带来的编译速度提升还不如 Apple Silicon(M1) 的升级。

于是他们将眼光投向了 SPM，打算直接使用它来替代 Bazel 打包二进制库，同时也为此开发了一个工具 [Scipio](https://github.com/giginet/Scipio)，用于将 Swift Package 打包为 XCFramework，并且自定义了一套缓存策略。
