### ISSUE TITLE
Memory Leaks in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#372]
#### 链接
https://medium.com/flawless-app-stories/memory-leaks-in-swift-bfd5f95f3a74

#### 理由
Leaks 相关的内容在业内虽然已经有很多文章了，但多数是以 OC 来做示例，这是一篇基于 Swift 的文章。文中上半部分对 Leaks 的相关概念进行阐述，下半部分主要介绍了检测 Leaks 的多种方式。

**Comment by iblacksun** [comment]
### 🌟 [Memory Leaks in Swift](https://medium.com/flawless-app-stories/memory-leaks-in-swift-bfd5f95f3a74)

`Leaks` 相关的内容在业内虽然已经有很多文章了，但多数是以 OC 来做示例，文章从 Swift 角度讲 `Memory Leaks` 是什么、有哪些危害？为什么会发生 `Leak`？最后重点介绍了消除 `Leaks` 的几种方式。
