### ISSUE TITLE
Using complex gestures in a SwiftUI ScrollView

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3727]
# 推荐收录

## 链接

https://danielsaidi.com/blog/2022/11/16/using-complex-gestures-in-a-scroll-view

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Using complex gestures in a SwiftUI ScrollView](https://danielsaidi.com/blog/2022/11/16/using-complex-gestures-in-a-scroll-view)

[@享耳先森](https://github.com/iblacksun)：Swift UI 因其高级的封装大大的简化了界面搭建复杂度，但在某些特定场景中显得能力不足。本文介绍了在 ScrollView 内部嵌套其他手势时遇到的问题以及可能的解决方案。
