### ISSUE TITLE
swift开发团队对 Tensorflow 表示了重视

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#373]
https://forums.swift.org/t/swift-for-tensorflow-to-be-developed-on-tensorflow-branch-on-apple-swift-on-github/12595

**Comment by raozhizhen** [comment]
Swift for TensorFlow 的 Swift 编译器开发在 google/swift 分支，Ted Kremenek （Swift 项目新主管）和  Chris Lattner（Swift 之父）都认为将这个分支上的工作移动到 Apple/Swift 上直接开发，对 Swift 社区更有益处。

**Comment by raozhizhen** [comment]
[Swift for TensorFlow](https://www.tensorflow.org/community/swift) 的 Swift 编译器开发在 [google/swift](https://github.com/google/swift) 分支上，Ted Kremenek （Swift 项目新主管）和 Chris Lattner（Swift 之父）都认为将这个分支上的工作移动到 [Apple/Swift](https://github.com/apple/swift) 上直接开发，对 Swift 社区更有益处。这样会让 Swift 编译器开发的协同工作集中到一个中心，而且也能避免大家对于 Swift 产生方言的担忧。

新分支 tensorflow 将会在近期创建，tensorflow 上开发的新功能，会通过 [Swift 发展流程](https://github.com/apple/swift-evolution)，将一部分合入 Swift 主分支，tensorflow 分支本身，也会密切追踪 Swift 主分支的更新。
