### ISSUE TITLE
七月之后应用商店只有用 ios 11 sdk 编译的app才能上传

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#374]
https://developer.apple.com/news/?id=05072018a&utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B351

**Comment by mmoaay** [comment]
2018 年 7 月份开始，所有上传 App Store 的应用都必须是基于 iOS 11 SDK 编译并适配 iPhone X 的分辨率。当然，Apple 也对上传流程做了进一步的优化。更多细节，请参照：[https://developer.apple.com/ios/submit/](https://developer.apple.com/ios/submit/)
