### ISSUE TITLE
Collecting Github Action workflow metrics using Swift

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3751]
# 推荐收录

## 链接

https://www.polpiella.dev/collecting-gihub-actions-workflow-metrics-with-swift/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
示例展示如何创建一个 swift cli 工具：配置程序入口、token 等访问 GitHub API，解析 action workflow 日期数据。

可以了解到 swift cli 写法，示例复杂度一般，国内解析 GitHub Action 数据使用场景也不算多，故不作推荐。
