### ISSUE TITLE
How to manage build settings using Xcode configuration files

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#3767]
# 推荐收录

## 链接

https://www.danijelavrzan.com/posts/2022/11/xcode-configuration/

**Comment by iblacksun** [comment]
### 🐕 [How to manage build settings using Xcode configuration files](https://www.danijelavrzan.com/posts/2022/11/xcode-configuration/)

 [@享耳先森](https://github.com/iblacksun)：相信大家的 App 都会遇到多环境构建的问题，比如 QA、预发、Production 环境，一不小心在提审时候还容易搞错版本。本文介绍了利用 `xcconfig` 文件做环境配置，比如不同环境使用不 App Icon 或 App Name。
