### ISSUE TITLE
哔哩哔哩Android打包优化与云编译

### ISSUE THREAD

**Issue by BarneyZhaoooo** [SwiftOldDriver/iOS-Weekly#3775]
# 推荐收录

## 链接
https://mp.weixin.qq.com/s/xls_AL9IyR3580zz8CfCOA

## 理由
哔哩哔哩Android打包优化与云编译

## 推荐人信息
barney

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
还好我们有 Android 开发了，不然都不知道怎么写简评
