### ISSUE TITLE
关于 MVC 的一个常见的误用

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#378]
#### 链接
http://onevcat.com/2018/05/mvc-wrong-use/

#### 理由

17期有收录过『[A Better MVC](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%2317-2018.05.02.md#-a-better-mvc)』系列，而王巍前辈的这篇则是通过一个简单例子，说明了 MVC 的一些误用场景并给出了更加合理的使用方式。

**Comment by 100mango** [comment]
如何避免把 Model View Controller 写成 Massive View Controller 已经是老生常谈的问题了。我们可以通过 
 MVVM , Reactive 模式或 Reducer 模式等进行优化改造。但比起模式和框架，更重要的是认识到解决的问题本质在于，我们要如何才能更清晰地管理“用户操作，模型变更，UI 反馈”这一数据流动的方式。本文则是通过一个简单的 To Do 列表来阐述如何清晰地管理数据流动。
