### ISSUE TITLE
Swift Concurrency – Things They Don’t Tell You

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3795]
# 推荐收录

## 链接

https://wojciechkulik.pl/ios/swift-concurrency-things-they-dont-tell-you

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
update：这周事情比较多，放下周

cc @ChengzhiHuang
