### ISSUE TITLE
源码看微信小程序启动过程

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#380]
https://tech.youzan.com/weapp-booting/?from=timeline&isappinstalled=0

**Comment by ParsifalC** [comment]
### 🐢 [从源码看微信小程序启动过程](https://tech.youzan.com/weapp-booting/)

这篇文章记录了作者经过 3 个礼拜研究后，对小程序框架的基本代码结构，启动流程以及程序实例化过程的理解，并且从小程序的启动流程入手一步步解答了“框架对传入的对象等到底做了什么”的疑问。
