### ISSUE TITLE
Fastlane and App Store Connect API keys

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3808]
# 推荐收录

## 链接

https://www.polpiella.dev/fastlane-appstore-connect-api-and-github-actions

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
@ChengzhiHuang 本文主要篇幅在介绍 Github Action 的场景下使用 Connect API， 与实际工作场景不符，暂时不推了，等找到更好的 Fastlane + App Store API Key 再推吧。
