### ISSUE TITLE
XCode 14.2/Swift 5.7 memory corruption on Task creation when app is launched on iOS < 16.

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3833]
# 推荐收录

## 链接

https://github.com/apple/swift/issues/63420

## 理由

是一个iOS 15-的 $toolchain/usr/lib/swift/iphoneos/libswiftCompatibilityConcurrency.a 的Runtime兼容库bug，不涉及系统Runtime问题

iOS 15-系统上如果出现了crash，请考虑升级一下 Xcode / Swift Toolchain到Swift 5.8+版本，Swift 5.7.0-5.7.3的toolchain都会含有该bug

**Comment by Kyle-Ye** [comment]
补充下context，Forums Post: https://forums.swift.org/t/memory-corruption-due-to-swift-concurrency-when-deploying-on-ios-15-and-below/63001

**Comment by kemchenj** [comment]
### [Swift 5.7 在 iOS 16 以下的系统创建 Task 时发生 Bad access](https://github.com/apple/swift/issues/63420)

Swift 团队在迭代的过程中删去了 Concurrency 相关代码的一个字段，内存布局产生变化，导致 iOS 16 以下的系统在创建 Task 时，在部分情况下内存访问会出错，导致崩溃。

目前已经完成修复，按照去年的发布节奏，可能会在三月份发布的 Xcode 里带上这个修复。遇到这个问题的同学如果着急的话，可以先回退到 Xcode 13.x 版本。
