### ISSUE TITLE
iOS自动化埋点探索

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#384]
https://mp.weixin.qq.com/s/u-HmmrSAgtER1N2pKxCm0A

这篇发过么？

**Comment by ParsifalC** [comment]
京东的这套没发过，之前发的是网易的 Hubble Data。

**Comment by ParsifalC** [comment]
### 🐕 [手机京东技术团队对iOS自动化埋点探索](https://mp.weixin.qq.com/s/u-HmmrSAgtER1N2pKxCm0A)

客户端埋点是产品分析用户数据的重要途径，常见的埋点方式有以下三种：

- 代码埋点，最直接的手动埋点方式，由开发人员完成；
- 可视化埋点，本文将会介绍的方式，可由埋点维护人员自行完成；
- 无埋点，相当于全埋点，网易 [HubbleData](https://neyoufan.github.io/2017/04/19/ios/%E7%BD%91%E6%98%93HubbleData%E6%97%A0%E5%9F%8B%E7%82%B9SDK%E5%9C%A8iOS%E7%AB%AF%E7%9A%84%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0/) 中有使用到。

本文整体介绍可视化埋点的使用方式和技术细节，另外针对可视化埋点中遇到的问题，尝试给出解决方案和并提出了一些思考。
