### ISSUE TITLE
从大前端“穿越”到终端，开发者应该必备什么技能？ | 解读终端的 2022

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3851]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/t0xLKrMF4al4cgAXeCwyow

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [从大前端“穿越”到终端，开发者应该必备什么技能？ | 解读终端的 2022](https://mp.weixin.qq.com/s/t0xLKrMF4al4cgAXeCwyow)

[@享耳先森](https://github.com/iblacksun)：现下裁员不断，新增招聘岗位越来越少，终端开发者何去何从？本文介绍了过去几年移动端领域技术发展；对比了现有跨端技术；同时，针对未来技术演化作者也给出了一些预测，希望对大家有帮助。
