### ISSUE TITLE
ChatGPT App

### ISSUE THREAD

**Issue by chenxi92** [SwiftOldDriver/iOS-Weekly#3858]
# 推荐收录

## 链接

https://github.com/chenxi92/ChatGPT

## 理由

SwiftUI 编写的Mac menu bar 和 iOS App， 使用 OpenAI API 来交互。无需保持「科学上网」环境即可使用。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
下周，本周 cooper 身体不适

**Comment by apguo** [comment]
我是小白！想下载chatGPT APP，不知道咋弄！

**Comment by chenxi92** [comment]
> 我是小白！想下载chatGPT APP，不知道咋弄！

Mac App: 在 [Release](https://github.com/chenxi92/ChatGPT/releases) 页面下载 ChatGPT.dmg 文件即可
iOS App：下载源码，然后使用自己的打包证书即可
