### ISSUE TITLE
Safely pinning SPM dependencies to exact versions

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3859]
# 推荐收录

## 链接

https://www.polpiella.dev/safely-pinning-spm-depedencies-to-exact-versions/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Safely pinning SPM dependencies to exact versions](https://www.polpiella.dev/safely-pinning-spm-depedencies-to-exact-versions/)

[@kemchenj](https://kemchenj.github.io)：使用 Cocoapods 集成依赖时，我们通常会将 Podfile.lock 也加入到 Git 的文件追踪列表里，保证在每次运行 `pod install` 后就能能够导入一样的依赖库版本，让所有人都在同样的环境下开发。

但 Xcode 项目直接集成 Swift Package 时情况会稍微不同，它不会根据 lock 文件来决定导入的 Package 版本，而是会在**版本约束的范围内升级到最高版本**。

例如说 Xcode 项目里 Alamofire 的版本约束是 `2.0.0 - Next Major`（`~> 2.0`），我们在开发时本地使用了 2.0 版本，传到 CI 上打包时刚好 2.1 版本发布了，就会自动升级到 2.1，导致 CI 打出来的包跟本地不同。

这篇文章就介绍了相关的情况以及他们的解决方法，如果大家在工作中也遇到了类似的问题，可以参考这篇文章进行解决。
