### ISSUE TITLE
监控启动崩溃

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#386]
#### 链接

http://sindrilin.com/apm/2018/05/12/observe_crash_at_launch.html

#### 理由

另外一套监控启动闪退的方案，与以前通过检测 app 在某段时间后是否仍存货的方式相比，这套方案的检测时机更加提前，通过 hook `msg_send` 函数实现，自己处理 crash 后的日志上报功能。

**Comment by mmoaay** [comment]
一套监控启动闪退的方案，与以前通过检测 App 在某段时间后是否仍然存活的方式相比，这套方案的检测时机更加提前，通过 hook `msg_send` 函数实现，并且自己处理了 crash 后的日志上报功能。
