### ISSUE TITLE
OC底层原理：应用程序的dyld4流程 上+下

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3862]
# 推荐收录

## 链接

https://juejin.cn/post/7198176378918764603#heading-18
https://juejin.cn/post/7198602089924657208#heading-38

## 理由

卷，都可以卷（

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
Leo 哥哥本周团建（下周

**Comment by LeoMobileDeveloper** [comment]
@ChengzhiHuang 我团建你都知道....

**Comment by LeoMobileDeveloper** [comment]
文章源码分析的很细，但整体可读性不强，第一篇有些基本知识错误，不推荐了
