### ISSUE TITLE
[Tools] ZMarkupParser

### ISSUE THREAD

**Issue by zhgchgli0718** [SwiftOldDriver/iOS-Weekly#3866]
# 推荐收录

## 链接

https://github.com/ZhgChgLi/ZMarkupParser

## 理由

自行使用纯 Swift 开发，透过 Regex 剖析出 HTML Tag 并经过 Tokenization，分析修正 Tag 正确性(修正没有 end 的 tag & 错位 tag)，再转换成 abstract syntax tree，最终使用 Visitor Pattern 将 HTML Tag 与抽象样式对应，得到最终 NSAttributedString 结果；其中不依赖任何 Parser Lib。

(相较于[现有套件](https://github.com/malcommac/SwiftRichString)，使用 XML Parser 无法兼容错位 Tag or 未关闭 Tag，遇到 `<u>test<b>rere</u>fsdf</b>`/`<br>`/`<Hot!>` 都会直接出错。

主要特色是:
- 自动修正标签错误(漏 Close/错位)
- 不吃字，例如: <Hot>
- 支援高度客制化 HTML 标签样式及扩充
- 比传统 `NSAttributedString.DocumentType.html` 更好的效能

主要实现原理是：
1. Input HTML String
2. 使用正则挖出 HTML Tag e.g.: <a>
3.  [Tokenization]: 转换成 startTag,rawString,closeTag....
4.  [Normalization]: 遍历 Token，自动修正错位及遗漏 Close 的 Tag & 判断是否为 <Hot> 这种正常文字
5. [Abstract syntax tree] 转换成结构树
6. 搭配 Tag/Style 抽象宣告，透过 Visitor Pattern、递回组合出最终 NSAttributedString 样式继承渲染结果

## 推荐人信息

自荐

**Comment by nianran** [comment]
@zhgchgli0718 Sorry，由于部分原因，原定于今天发布的本条推荐，挪至下周发布。

**Comment by zhgchgli0718** [comment]
辛苦了，没有问题

**Comment by ChengzhiHuang** [comment]
已经挪到下周的周报中，抱歉

**Comment by zhgchgli0718** [comment]
@ChengzhiHuang 抱歉容我補充一下，這幾天才花時間撰寫了一篇[技術細節文章](https://medium.com/zrealm-ios-dev/%E6%89%8B%E5%B7%A5%E6%89%93%E9%80%A0-html-%E8%A7%A3%E6%9E%90%E5%99%A8%E7%9A%84%E9%82%A3%E4%BA%9B%E4%BA%8B-2724f02f6e7)，不知道可否放在一起抑或是我在開一則 issue 推薦到另一期的 report?

**Comment by ChengzhiHuang** [comment]
@nianran 看看呢？要不合并在一起我再挪到下周？
红纸今天应该在忙（

**Comment by nianran** [comment]
@ChengzhiHuang 好的，我这周末再看看

**Comment by nianran** [comment]
### [手工打造 HTML 解析器的那些事](https://medium.com/zrealm-ios-dev/%E6%89%8B%E5%B7%A5%E6%89%93%E9%80%A0-html-%E8%A7%A3%E6%9E%90%E5%99%A8%E7%9A%84%E9%82%A3%E4%BA%9B%E4%BA%8B-2724f02f6e7)

[@红纸](https://github.com/nianran)：ZMarkupParser 是作者开发的 HTML 转 NSAttributedString 仓库。本篇介绍了其实现过程，其中包括代码解析、语法标准化、转换抽象树、MarkupComponent 转换、解析 MarkupSyle、转换 NSAttributedString 等。文章提供了详细的代码实现和实例演示，对于 HTML 解析器实现由兴趣的读者来说，该篇文章可以作为入门参考资料。

> 推荐人：[ZhgChgLi](https://github.com/zhgchgli0718)

**Comment by nianran** [comment]
@zhgchgli0718 看到了 「96 min read」有点劝退，文章稍微有点长，建议下次拆分写会有更多的读者哦~
简单写了下推荐语，如有不合适。请及时联系我。

**Comment by zhgchgli0718** [comment]
感謝，不好意思因為把文章當成是技術手冊來寫，所以特別長，感謝推薦。
