### ISSUE TITLE
XCode 编译加速之Compile Asset Catalog

### ISSUE THREAD

**Issue by gbfansheng** [SwiftOldDriver/iOS-Weekly#3885]
# 推荐收录

https://juejin.cn/post/7207848485856231482

[此处替换为具体的资源地址]

## 理由

针对Xcode Compile Asset Catalog过程的优化方案，应该是全网罕有的简单好用的方案。
[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
只适用于 Debug 下。
