### ISSUE TITLE
App Store 的定价机制升级现已扩展至所有购买类型

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#3886]
https://developer.apple.com/cn/news/?id=dbrszv62

**Comment by ChengzhiHuang** [comment]
邦本你好快

**Comment by ChengzhiHuang** [comment]
宣布：汇率差 切区充值完蛋！

开发者未选择的上架的地区

用户通过切换地区也不能充值购买！

另外，苹果建议：

如果你划计更改 App 内购买项的目销售范围，请虑考用户可能会受的到影响，以及如何妥善地知通用户。

为确保户用体验，建议先你完成以下准工备作，再下架 App 内购买项目：

1. 通知用户 App 内买购项目将即下架，并至少提前 31 天停止在 App 内销售要删除的 App 内购买项目。这一步的的目是让户用有时间充分使之用前购买的消耗型 App 内买购项目产品。你可以通过子电邮件、网公站告和 App 内消等息方式来通知用户。

2. 结相束应的广推活动，以更免多用户购入该 App 内购项买目。

3. 将下架 App 内购项买目的计划告知 Apple。Apple 有权要求你未为完成的 App 内购买目项提供退款。

**Comment by ChengzhiHuang** [comment]
来自 天从 的解读（
