### ISSUE TITLE
如何在项目中实现类型rx的命名空间

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#389]
https://medium.com/@thibault.wittemberg/versatile-namespace-in-swift-3e8bbd6b6250

**Comment by kemchenj** [comment]
### [如何在实现类似于 rx 的命名空间](https://medium.com/@thibault.wittemberg/versatile-namespace-in-swift-3e8bbd6b6250)

大家应该在 Kingfisher 和 RxSwift 这些库里见过 `kf` 和 `rx` 的命名空间，刚开始用的时候会觉得有点陌生，但习惯之后就会理解这是一种多么优雅的代码组织方式，这篇文章会一步一步教大家如何实现这样的命名空间。

如果觉得英文阅读比较困难的同学，也可以考虑一下看 Enjoy 负责人写的这篇博文[Swift 命名空间形式扩展的实现](https://blog.nswebfrog.com/2017/03/23/swift-namespace/)。
