### ISSUE TITLE
使用Playground的一些技巧，感觉挺实用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#390]
https://fluffy.es/xcode-playground-tips

**Comment by raozhizhen** [comment]
虽然 Xcode  Playground 老爱崩溃，但 Playground 的确很适合测试一小段代码。文章介绍如何设置手动运行，来降低 Playground 的 CPU 使用率及崩溃率，以及如何为手动运行添加 ⌘R 快捷键。另外 Playground 在最后一行代码执行完毕之后就会立即停止，并不会等待还没有执行的异步回调，可以设置停止方式为手动停止，或者代码来控制停止。

**Comment by cupnoodle** [comment]
感谢载入我的小文章, 希望能帮助到大家用Playground  🙌
