### ISSUE TITLE
一个用在 Swift 中的模块管理框架

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#3923]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/aFM_4OqDYcXPRIdF7x_41w

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [一个用在 Swift 中的模块管理框架](https://mp.weixin.qq.com/s/aFM_4OqDYcXPRIdF7x_41w)

[@kemchenj](https://kemchenj.github.io/)：在 OC 里，我们一般是可以通过 `__attribute((used, section("__DATA,"#sectname" ")))` 这种编译器提供的修饰符来将模块信息存到 Mach-O 的 section 去，等到运行时，在 `+load` 或其他时机取出进行注册，这种类似于自动注册的方式自然是很方便。

但是在 Swift 中，上面这种方式自然是不行的，本文作者封装了一套 Module Manager，通过扫描 Mach-O 中的 `__objc_classlist` 节拿到所有的 class，继而过滤出符合模块要求的 class 进行后续操作。

另外 Swift 官方在几个月前也提出过[一个草案](https://forums.swift.org/t/pitch-custom-metadata-attributes/62016)提供自定义注解 API，让我们可以通过类型安全的方式提供元数据，并且可以在运行时进行读取和操作，感兴趣的同学也可以查看。
