### ISSUE TITLE
TouchID 和 FaceID 实战使用的一些经验

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#393]
http://michael-brown.net/2018/touch-id-and-face-id-on-ios/

**Comment by iblacksun** [comment]
### 🐢 [TouchID 和 FaceID 实战使用的一些经验](http://michael-brown.net/2018/touch-id-and-face-id-on-ios/)

`LocalAuthentication ` 虽然只有 `LAContext` 一个 class，但并不代表清晰好用，其文档不够清晰甚至有错误。作者在实际 App 中使用过 `LocalAuthentication` 之后列出了文档的一些错误并给出了许多最佳实践。
