### ISSUE TITLE
Facebook/lexical-ios

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#3935]
# 推荐收录

## 链接

https://github.com/facebook/lexical-ios

## 理由

Lexical iOS is an extensible text editor framework that integrates the APIs and philosophies from Lexical Web with a Swift API built on top of TextKit.

**Comment by ChengzhiHuang** [comment]
https://swiftpackageindex.com/facebook/lexical-ios?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B603

https://facebook.github.io/lexical-ios/documentation/lexical/

**Comment by ChengzhiHuang** [comment]
@KyoLi 富文本交给专业的

**Comment by ChengzhiHuang** [comment]
@KyoLi 富文本交给专业的
