### ISSUE TITLE
音视频骚操作，FFmpeg 如何播放带「图片」的 M3U8 视频，IJKPlyaer 适配非标 TS 文件

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3936]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/H10UxzcofjK2cR8ci7Rvdw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
通过非标适配『民间免费CDN』的 TS 封装方案，细节较多，不具有通用参考意义，不做推荐。
