### ISSUE TITLE
Xcode 15 Leaked. Here is What iOS Developers Can Expect

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#3938]
# 推荐收录

## 链接

https://stevenpcurtis.medium.com/xcode-15-leaked-here-is-what-ios-developers-can-expect-e74432ef6162

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by JonyFang** [comment]
Just wishlist, LOL 🤣

**Comment by iblacksun** [comment]
哈哈，我看了文章发布日期之后就想问呢。 @JonyFang

**Comment by JonyFang** [comment]
> 哈哈，我看了文章发布日期之后就想问呢。 @JonyFang

😂 无疑
