### ISSUE TITLE
Using Dedicated Objects as Delegates & Datasources

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#394]
#### 链接

http://alisoftware.github.io/architecture/2018/05/20/dedicated-datasources/

#### 理由

将 TableView 的 Delegate 和 DataSource 抽离到不同的对象中管理的一次尝试，以减轻 VC 层的负担，并实现 Delegate 和 DataSource 的复用。

**Comment by raozhizhen** [comment]
使用专门的对象去作为 tableView 的 delegates 和 datasources，即可减少 viewController 的代码，又能使这些代码被多个 viewController 重用，需要的话，还能方便的进行数据展示形式的切换。也可以为多个 tableview 写一个 datasources 展示不同的 cell 样式，做到数据展示形式的复用。
