### ISSUE TITLE
抖音 Swift 编译优化 - 基于自定义 Toolchain 编译提速 60%

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3952]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/MT5MHhZIlyrhuVNM3Ckteg

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
这周有事，放到下周

**Comment by kemchenj** [comment]
这周有事，放到下周

**Comment by kemchenj** [comment]
关于 re-export 的一些讨论和解释 https://forums.swift.org/t/exported-and-fixing-import-visibility/9415/36

**Comment by kemchenj** [comment]
### [抖音 Swift 编译优化 - 基于自定义 Toolchain 编译提速 60%](https://mp.weixin.qq.com/s/MT5MHhZIlyrhuVNM3Ckteg)

[@kemchenj](https://kemchenj.github.io/)：抖音基础技术团队在这篇文章里分享了一个很有趣的编译问题：

1. Swift 和 OC 混合的模块里，Swift 自动生成的 xxxx-Swift.h 文件里会 import 所有直接和间接依赖的模块。（这种行为也被称为 re-export）
2. 所以依赖了这个混合代码的模块的 OC 模块，它的所有间接依赖都会变成直接依赖。
3. 而对于编译器来说，当一个模块直接依赖的模块 API 发生变化时，它的编译缓存就会失效，需要重新进行编译。

由于上述的三点，底层库的 API 修改很容易触发大面积的编译缓存失效，并且由于上层模块的直接依赖变多，导致缓存失效的判断逻辑也会变得更加复杂，最终导致编译时间增长。

Swift 这么设计的原因主要是**为了兼容 C/OC 头文件的行为**，[在 Swift 的论坛里开发组也曾经解释过具体的细节](https://forums.swift.org/t/exported-and-fixing-import-visibility/9415/36)。

但实际代码里很少会依赖这个行为，抖音的技术团队就尝试定制 Toolchain，增加更多选项去限制这个行为的生效范围，从而**最终实现编译提速 60%**，感兴趣可以进行阅读。
