### ISSUE TITLE
Monorepo 解决方案之 Remote Execution

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#3961]
https://mp.weixin.qq.com/s/2EgCx8TL-mBpuelULW7z6Q

**Comment by JonyFang** [comment]
iOS Monorepo 全源码解决方案

https://mp.weixin.qq.com/s?__biz=Mzg2NTYyMjYxNg==&mid=2247488340&idx=1&sn=64b578f25228aa9432f8cc1628452e41&scene=21#wechat_redirect

**Comment by ChengzhiHuang** [comment]
@JonyFang 这篇文章内部有些争议，不是很推荐推😂

**Comment by JonyFang** [comment]
> @JonyFang 这篇文章内部有些争议，不是很推荐推😂

😂 关掉了
