### ISSUE TITLE
Mastering Canvas in SwiftUI

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3965]
# 推荐收录

## 链接

https://swiftwithmajid.com/2023/04/11/mastering-canvas-in-swiftui/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [Mastering Canvas in SwiftUI](https://swiftwithmajid.com/2023/04/11/mastering-canvas-in-swiftui/)

[@享耳先森](https://github.com/iblacksun)：SwiftUI 中，绘制图形可以使用高级的 `ShapAPI`，也可以使用 `Canvas` 直接绘制。本文介绍 `Canvas` 的基本用法，也介绍了如何使用 `Canvas` 绘制文本、图片，甚至给 `Canvas` 添加动画。
