### ISSUE TITLE
绕过 Cloudflare 指纹护盾

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3974]
# 推荐收录

## 链接

https://sxyz.blog/bypass-cloudflare-shield/

## 理由

这种事我不信 EF 不感兴趣

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by EyreFree** [comment]
这个主题离我们周报目前的内容好像有点远，先 close 掉了，😌
