### ISSUE TITLE
只有 13 台 DNS 根域名服务器原因

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#398]
https://jaminzhang.github.io/dns/The-Reason-of-There-Is-Only-13-DNS-Root-Servers/

**Comment by lacklock** [comment]
DNS因为UDP的包大小限制只能包含13个地址，这个很容易知道。
但是这个文章还是没有说明为什么一个udp包只能包含13个dns服务器
