### ISSUE TITLE
心遇iOS端会话页性能优化 — ReactiveObjC实践篇

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3982]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/_nYM42vgSEqlJuoMlPdCUw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [心遇 iOS 端会话页性能优化 — ReactiveObjC 实践篇](https://mp.weixin.qq.com/s/_nYM42vgSEqlJuoMlPdCUw)

[@享耳先森](https://github.com/iblacksun)：`ReactiveObjC` 是 `Objective-C` 下的响应式编程框架，可以将各种通知、代理等转换成事件流进行分发，`Swift` 下有 `RxSwift` 及 `Combine`。本文介绍了「心遇」团队如何使用 `ReactiveObjC` 解决项目中逻辑分散的问题。

> Tips: 开发者们在上手  `RAC` 类库前建议先评估学习曲线及维护、调试问题。
