### ISSUE TITLE
App Marketing by App Masters

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#3986]
# 推荐收录

## 链接

https://podcasters.spotify.com/pod/show/app-marketing-podcast

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
我自己没看，发给老卓看了，老卓说还不错，感觉对独立开发者比较有用。

**Comment by ChengzhiHuang** [comment]
编辑可以再 double check 下，判断内容价值

**Comment by iblacksun** [comment]
### [App Marketing by App Masters](https://podcasters.spotify.com/pod/show/app-marketing-podcast)

[@享耳先森](https://github.com/iblacksun)：这个系列播客专注 App Store 发行与优化，如果你是独立开发者，或有做独立开发者的想法，建议关注或收藏，找到自己感兴趣部分收听。
