### ISSUE TITLE
Swift静态代码检测工程实践

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4003]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/fnCCU4OeudV2XnATyhv2SQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
概念和 swiftlint 基础配置信息介绍较多，实践经验和思考较少。行文细节过多，结构偏散，对新人理解不够友好，暂不推荐。
