### ISSUE TITLE
The Book of Modern C++

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4004]
# 推荐收录

## 链接

https://github.com/lkimuk/the-book-of-modern-cpp

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
10个主题，83章，954页，包含去年到最近超多作者的优质文章，值得反复阅读，难度等级普遍三星到五星。

所含内容一是新，二是深，三是广。

https://mp.weixin.qq.com/s/UpHvAWp3BdLtjn6YKcwL-g

**Comment by kemchenj** [comment]
### [The Book of Modern C++](https://github.com/lkimuk/the-book-of-modern-cpp)

[@kemchenj](https://kemchenj.github.io/)：这是国内 C++ 开发者整理出版的一本书，内容来自于网络上优质作者编写的文章，本书包含了十大主题：

- Basics
- Modern C++
- C++23
- Metaprogramming
- Concurrency
- Performance
- Algorithms
- Techniques
- Tricks
- Miscellaneous

> 序：既致之以广大，又尽之以精微，合之以主题，以成本书内容之深广也。而每章独立，各有所论， 故本书针对高级开发者。饶是如此，新手亦可依此进阶，小大靡遗，纤悉洞了，查漏补缺，得窥其理。
