### ISSUE TITLE
Flutter 3.10 适配之单例 Window 弃用，一起来了解 View.of 和 PlatformDispatcher

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4012]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/2GPKiNVLudzxrvOPxmCKKQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by CrazyCoderShi** [comment]
多部分跟桌面端有关，先关闭吧 😄
