### ISSUE TITLE
使用 SwiftUI 开发 RSS 阅读器

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4045]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/8DFqljikD7FKvHTdZj2weA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [使用 SwiftUI 开发 RSS 阅读器](https://mp.weixin.qq.com/s/8DFqljikD7FKvHTdZj2weA)

[@享耳先森](https://github.com/iblacksun)：本文是戴铭在苹果加速器活动的一次分享，介绍了如何使用 SwiftUI + CoreData 实现一个 RSS 阅读器，新手友好。
