### ISSUE TITLE
移动端APP组件化架构实践

### ISSUE THREAD

**Issue by helele90** [SwiftOldDriver/iOS-Weekly#4046]
# 推荐收录

## 链接

[移动端APP组件化架构实践](https://juejin.cn/post/7240333779222167608)

## 理由

文章介绍了组件化移动端APP组件化开发中会遇到的一些困难和挑战，同时也提供了一些不错的实践帮助维护一个高质量的组件化项目。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@helele90 提示文章找不到，是掘金还未通过审核吗？

**Comment by helele90** [comment]
@ChengzhiHuang 不好意思，，链接贴成审核中的了。已经修改啦
