### ISSUE TITLE
Writing self-documenting Swift code

### ISSUE THREAD

**Issue by 100mango** [SwiftOldDriver/iOS-Weekly#405]
#### 链接

https://www.swiftbysundell.com/posts/writing-self-documenting-swift-code
#### 理由

介绍了如何在Swift中编写良好，自解释的代码

**Comment by raozhizhen** [comment]
我们应该尽可能使我们的代码和我们设计的 API 更容易被理解，可以拆分复杂的方法，使用清晰明了的 API， 为标识符创建新类型或别名。写好自解释代码，可以让我们的注释专注于架构设计，而不是经常变化的实现细节。
