### ISSUE TITLE
AppIntents for Widgets

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4069]
# 推荐收录

## 链接

https://alexanderweiss.dev/blog/2023-06-10-appintents-for-widgets

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [AppIntents for Widgets](https://alexanderweiss.dev/blog/2023-06-10-appintents-for-widgets)

[@享耳先森](https://github.com/iblacksun)：`AppIntents` 是 iOS 16 推出的 Swift only framework，用于开发 `App Shortcut` 以简化之前复杂的配置项。从 iOS 17 开始，`AppIntents` 也可用于 Widgets 开发了。
