### ISSUE TITLE
Core ML入门：构建一个简单的图像识别应用

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#407]
http://swift.gg/2018/05/28/coreml-introduction/

**Comment by mmoaay** [comment]
由 SwiftGG 翻译组翻译自 Sai Kambampati 的博客。文章一步一步地教大家实现一个基于 CoreML 的图像识别器，而且特别贴心的是，作者提供了一系列的 Demo 工程，让读者可以随意跳过一些准备步骤，提高学习效率。完整的 Demo 工程请在 [Github](https://github.com/appcoda/CoreMLDemo) 上查看。

**Comment by DonghaoQiao** [comment]
你好，我一步一步做完以后。运行的时候，读取图片了，然后不显示图片，无法识别是什么情况？谢谢。

**Comment by ParsifalC** [comment]
> 你好，我一步一步做完以后。运行的时候，读取图片了，然后不显示图片，无法识别是什么情况？谢谢。

可以按如下步骤断点调试一下的：

- 给 ImageView 的 image 是否为空？->否->应该只是纯 UI 上没 set 进去，或者 ImageView 加的有问题
- 为空的话，沿着像上查，image 的绘制是否有问题？image 的 CoreML 处理是否有问题？image 的相册选择是否有问题？

**Comment by DonghaoQiao** [comment]
你好，感谢您的回答。我设置了背景颜色也可以正常显示。感觉image不是空的。我也觉得有可能是连接问题，但是我imageView也连接到UIImageView了，而且也修改了Info.plist。但是image view就是不显示图片。

**Comment by ParsifalC** [comment]
> 你好，感谢您的回答。我设置了背景颜色也可以正常显示。感觉image不是空的。我也觉得有可能是连接问题，但是我imageView也连接到UIImageView了，而且也修改了Info.plist。但是image view就是不显示图片。

 那就先用你的 ImageView 加载一张本地图片试试。

**Comment by DonghaoQiao** [comment]
添加图片也可以正常添加。我写的放在这了https://github.com/DonghaoQiao/Swift，可以麻烦您帮我看看吗？这几天闲着没事的时候就一直在搞这个。。。我觉得是extension ViewController: UIImagePickerControllerDelegate中的func imagePickerController一直没有被调用，但是没有查到一个好用的修改方法。我的微信号是qiaodh，我是swift纯新手，希望以后可以多交流。谢谢。

**Comment by DonghaoQiao** [comment]
添加图片也可以正常添加。我写的放在这了https://github.com/DonghaoQiao/Swift 可以麻烦您帮我看看吗？这几天闲着没事的时候就一直在搞这个。。。我觉得是extension ViewController: UIImagePickerControllerDelegate中的func imagePickerController一直没有被调用，但是没有查到一个好用的修改方法。我的微信号是qiaodh，我是swift纯新手，希望以后可以多交流。谢谢。

**Comment by DonghaoQiao** [comment]
> > 你好，感谢您的回答。我设置了背景颜色也可以正常显示。感觉image不是空的。我也觉得有可能是连接问题，但是我imageView也连接到UIImageView了，而且也修改了Info.plist。但是image view就是不显示图片。
> 
> 那就先用你的 ImageView 加载一张本地图片试试。

你好，我这个好使了。就是修改了一下func imagePickerController，可能是因为版本更新了，我还得去读一读。非常感谢您之前的帮助！不过还是希望您能加我微信，以后多交流，哈哈，感谢！
