### ISSUE TITLE
iOS多语言解决方案全面指南

### ISSUE THREAD

**Issue by erduoniba** [SwiftOldDriver/iOS-Weekly#4076]
# 推荐收录

## 链接
https://juejin.cn/user/3245414058055880/posts

## 理由
本文以及相关工具和代码旨在为已上线的iOS项目提供一种快速支持多语言的解决方案。由于文案显示是通过hook实现的，因此对App的性能有一定影响；除了特殊场景的文案显示需要手动支持外，其他任务均已实现自动化。

## 推荐人信息
Harry

**Comment by ChengzhiHuang** [comment]
链接贴错了，更新成这个：https://juejin.cn/post/7248811984748462141
