### ISSUE TITLE
快手主播稳定性 - Mach Port 超限问题治理

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#4077]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/hzKQZjQEp7Gpv6Uhl1xVSA

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
只有巨无霸 app 会遇到

还有一种是 FD 耗尽 也会导致崩溃233333
