### ISSUE TITLE
RunLoop 源码阅读

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#408]
https://juejin.im/post/5aaa15d36fb9a028d82b7d83

**Comment by iblacksun** [comment]
### 🐢 RunLoop 源码阅读](https://juejin.im/post/5aaa15d36fb9a028d82b7d83)

现在大部分 iOS 简历上都会写「理解 RunLoop」细问之后却是一知半解。本文通过源码方式讲解 RunLoop 相关知识，包含：
- 为什么需要 RunLoop?
- 如何做到一个线程只有一个 RunLoop(Thread-specific data)
- CFRunLoopDoObservers
- 如何让线程在空闲时休眠及唤醒(mach_msg)
