### ISSUE TITLE
Dependency Graph, Dependabot Alerts, and Advisory Database now support Swift advisories

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4083]
# 推荐收录

## 链接

https://github.blog/changelog/2023-06-19-dependency-graph-dependabot-alerts-and-advisory-database-now-support-swift-advisories

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [GitHub 的 Dependency Graph, Dependabot Alerts 和 Advisory Database 现在正式提供 Swift 的支持](https://github.blog/changelog/2023-06-19-dependency-graph-dependabot-alerts-and-advisory-database-now-support-swift-advisories)

之前[在 244 期周报](https://github.com/SwiftOldDriver/iOS-Weekly/releases/tag/%23244)里曾经提到过 GitHub 的代码扫描功能计划提供 Swift 的支持，现在这个功能已经正式上线了，感兴趣的朋友可以赶紧去尝试一下。

> GitHub 的 Code Scanning 会扫描和索引项目的 Dependency 信息，并且提供：
> 
> - **Dependency Graph**。
>   - 这意味着开发者可以在 GitHub 上看到有哪些项目依赖了自己的 Swift 库。
>   - 可以使用 [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts)，在依赖库更新时，自动提交 Pull Request 更新依赖库版本。
> - **安全漏洞警告**。如果一个代码库出现安全漏洞时，它可以在发布修复版本后使用 GitHub 内建的功能进行记录，此时 GitHub 就会通知所有依赖了这个库的下游项目，并且自动提交 Pull Request 将依赖更新到已修复的版本。 

需要注意的是，这个功能只支持 SwiftPM，不支持 Cocoapods。
