### ISSUE TITLE
Swift Package Index Supporting visionOS

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4098]
# 推荐收录

## 链接

https://blog.swiftpackageindex.com/posts/supporting-visionos/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by kemchenj** [comment]
### [Swift Package Index Supporting visionOS](https://blog.swiftpackageindex.com/posts/supporting-visionos/)

Swift Package Index 宣布添加 visionOS 的支持，所有在这上面发布的库都会运行兼容性测试，并且在网站上展示：

![](https://blog.swiftpackageindex.com/images/visionos-build-results~light.png)
