### ISSUE TITLE
iOS App 使用 GCD 导致的卡顿问题

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#410]
#### 链接
http://mrpeak.cn/blog/ios-gcd-bottleneck/

#### 理由
Peak 排查 GCD 卡顿问题的过程，通过联系苹果技术支持，最后梳理了这个问题可能的原因和可尝试的解决方法。

**Comment by iblacksun** [comment]
### 🐢 [iOS App 使用 GCD 导致的卡顿问题](http://mrpeak.cn/blog/ios-gcd-bottleneck/)

在我们通常的认知中，都认为 `dispatch_async` 非常高效不会卡顿，Peak 在实际项目中发现一个卡顿堆栈可能与 `dispatch_async` 有关， 之后利用 TSI 向 Apple 寻求 technical support，通过问答形式解释了为什么 `dispatch_async` 有时也会卡顿。
