### ISSUE TITLE
iOS 防 dump 可行性调研报告

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4108]
# 推荐收录

## 链接

https://juejin.cn/post/7251501966592917563

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by xiaofei86** [comment]
如果这期文章数量够就先不推荐这篇了吧。刚想了下 revert 掉了，如果要保留就再 revert 这个提交（a8c054b）。这篇 GPT 的痕迹太重，将了太多知识点，但有点散，作者串联的也不是太好，没有补充细节。借助合适的 prompts 感觉可以批量生成这种介绍性文章，其内容质量可能不如用户直接使用 GPT。
