### ISSUE TITLE
iOS 17 UIGraphicsBeginImageContext Deprecated

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4114]
# 推荐收录

## 链接

只要业务上用了截图相关 ``UIGraphicsBeginImageContextWithOptions`` && ``UIGraphicsEndImageContext`` 都会报出 Assert。

UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={382, 0}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iostalks** [comment]
<img width="786" alt="image" src="https://github.com/SwiftOldDriver/iOS-Weekly/assets/12881129/ed34e816-7738-4714-829d-1df82f703bdb">

在 iOS 17 设置的宽高如果有一项为 0 会触发 Assert，非零 size 该 API 功能正常。

**Comment by ChengzhiHuang** [comment]
@iostalks 以你的最终测试为准，我测的时候还是 Beta 2 。

不过这个 api 还是被标注为废弃了，可能最终还是得换：[UIGraphicsBeginImageContextWithOptions(_:_:_:)](https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho)
