### ISSUE TITLE
2023 European LLVM Developers' Meeting

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4125]
# 推荐收录

## 链接

https://www.youtube.com/watch?v=XWBVLcdzmFg

https://llvm.org/devmtg/2023-05/

## 理由

实不相瞒，我感觉在听天书...

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
的确不懂，看了下 MachineScheduler 中针对资源分配的优化，指令粒度规划空闲资源，很难懂，对移动端 RD 没普适的参考，建议别推荐了。

**Comment by ChengzhiHuang** [comment]
主要是搞 llvm 定制开发的朋友们看，我们偏业务开发就摸了...

也就 infra 的同学能看懂了（
