### ISSUE TITLE
EasyListView

### ISSUE THREAD

**Issue by moliya** [SwiftOldDriver/iOS-Weekly#4158]
# 推荐收录

## 链接

https://github.com/moliya/EasyListView

## 理由

基于UIScrollView实现的可快速搭建列表的库
- 可搭建静态表单、流式布局界面
- 支持添加、插入、删除元素，支持批量更新操作
- 支持添加/删除的动画

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@moliya 我们内部评估了一下，觉得通用能力有一些单薄，近期也没有额外更新，就不做推荐啦~

感谢你的自荐
