### ISSUE TITLE
Discover localizedStandardCompare()

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4159]
# 推荐收录

## 链接

https://www.swiftwithvincent.com/blog/discover-localizedstandardcompare

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by EyreFree** [comment]
看了下内容太简单了，不太适合上周报。
