### ISSUE TITLE
SwiftUI Tips：如何隐藏键盘（收起键盘）

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#4174]
# 推荐收录

https://juejin.cn/post/7268592310040199223

## 理由

整理了一下 SwiftUI 中的键盘处理方式。

**Comment by iblacksun** [comment]
### 🐎 [SwiftUI Tips：如何收起键盘](https://juejin.cn/post/7268592310040199223)

[@享耳先森](https://github.com/iblacksun)：文章列举了 `SwiftUI` 中多种收起键盘的方式，适合刚入 `SwiftUI` 的同学们。
