### ISSUE TITLE
Making your SwiftData models Codable

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4177]
# 推荐收录

## 链接

https://www.donnywals.com/making-your-swiftdata-models-codable/

## 理由

更多 SwiftData 可以看内参：https://xiaozhuanlan.com/topic/4937125086 ，质量也非常高。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
文章介绍，由于 `@Model` 引入的模板代码，Codable 协议需要通过自定义编解码方法来实现。实现方法上与非 SwiftData Class 没有本质区别，对于已经了解 Codable 的开发者是挺自然的事情。

 就像作为结尾总结所说，SwiftData 对象的序列化依赖 Codable，但没有对自身对象兼容 Codable 协议令人遗憾。SwiftData 还没有正式发布，参考内容更多侧重 CoreData 、SwiftUI 结合，Codable 兼容可能还会有变化。本文内容较常规，建议暂不推荐。

https://xiaozhuanlan.com/topic/4937125086 前两周已经推荐过


欢迎在当前 issue 留下你对 SwiftData Objects 支持 Codable 的想法和讨论
