### ISSUE TITLE
 Engineering Introducing ObservableConverter A plugin to help convert to @Observable

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4188]
# 推荐收录

## 链接

https://github.com/Lickability/ObservableConverter

https://lickability.com/blog/introducing-observableconverter

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
功能还比较基础，仅限 ObservableObject，EnvironmentObject 声明的转换，与手工修改成本区别不大。暂不推荐
