### ISSUE TITLE
不必要的 HTTP 头信息

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#419]
### 推荐收录 / 意见反馈

本文统计了30个最常见的 HTTP 头信息，逐个讨论哪些是必要的，哪些是没必要的。

#### 链接

https://www.fastly.com/blog/headers-we-dont-want

#### 理由

增加对HTTP协议的了解

**Comment by raozhizhen** [comment]
作者统计了 30 个（我数了数，其实只统计了 29 个，哈哈）最常见的 HTTP 头信息，其中很多并没有使用的必要。例如并没有什么用，只是起到注释作用的 Server、X-Powered-By、Via。有实际效果，但并不是实现该效果的最佳方式的 P3P、Expires、X-Frame-Options、X-UA-Compatible。在标准之外的不会被任何浏览器识别的 X-ASPNet-Version，X-Cache。 而一些更有用的头信息却很少网站使用，例如提高安全性的 Content-Security-Policy 和 Strict-Transport-Security，提升性能的 Link rel=preload。

**Comment by raozhizhen** [comment]
作者统计了 30 个最常见的 HTTP 头信息，其中很多并没有使用的必要。例如并没有什么用，只是起到注释作用的 Server、X-Powered-By、Via。有实际效果，但并不是实现该效果的最佳方式的 P3P、Expires、X-Frame-Options、X-UA-Compatible。在标准之外的不会被任何浏览器识别的 X-ASPNet-Version，X-Cache。 而一些更有用的头信息却很少网站使用，例如提高安全性的 Content-Security-Policy 和 Strict-Transport-Security，提升性能的 Link rel=preload。
