### ISSUE TITLE
Flutter 最优秀动画库「完全商业化」，Rive 2 你全面了解过吗？

### ISSUE THREAD

**Issue by CrazyCoderShi** [SwiftOldDriver/iOS-Weekly#4208]
# 推荐收录

## 链接

[Flutter 最优秀动画库「完全商业化」，Rive 2 你全面了解过吗？](https://juejin.cn/post/7275155682051145787)

## 理由

Rive 在 Flutter 上的体验可谓是独一份，优秀之处不必多说

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@CrazyCoderShi 这个要收钱了吧（

**Comment by CrazyCoderShi** [comment]
> @CrazyCoderShi 这个要收钱了吧（

一个月几十刀还好啦
