### ISSUE TITLE
Understanding Container Background for Widget in iOS 17

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4214]
# 推荐收录

## 链接

https://swiftsenpai.com/development/widget-container-background/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [Understanding Container Background for Widget in iOS 17](https://swiftsenpai.com/development/widget-container-background/)

[@享耳先森](https://github.com/iblacksun)：在即将发布的 iOS 17 中，Apple 扩展了 Widget 的使用范围，为了适应这一变化，引入了 `containerBackground(for:alignment:content:)` 这一 API。如果使用 Xcode 15 编译项目而 Widget 没有适配这一 API 将会报错，文章解释了这一 API 的作用及用法。
