### ISSUE TITLE
swift-sdk-generator

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4225]
# 推荐收录

## 链接

https://github.com/apple/swift-sdk-generator

## 理由

Generate Swift SDKs for cross-compilation.

**Comment by zvving** [comment]
为 Swift SDK 开发者提供跨平台编辑工具，兼容主流操作系统，提高 SDK 开发效率。 Swift 用户一般不用关注，不在周报中推荐。
