### ISSUE TITLE
A New Approach to Testing in Swift

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4226]
# 推荐收录

## 链接

https://forums.swift.org/t/a-new-approach-to-testing-in-swift/67425

**Comment by ChengzhiHuang** [comment]
https://www.pointfree.co/blog/posts/114-a-new-tool-for-testing-macros-in-swift

**Comment by ChengzhiHuang** [comment]
这里也有一个轮子，要不两个结合一起介绍？ @kemchenj
