### ISSUE TITLE
Harnessing Code Generation to Increase Reliability & Productivity on iOS at Uber

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#423]
### 推荐收录 / 意见反馈

让iOS像Android那样可以用类似注解的方式自动生成代码

#### 链接

https://eng.uber.com/code-generation/#utm_source=rss&utm_medium=rss&utm_campaign=code-generation

**Comment by 100mango** [comment]
本文的中心是利用代码自动生成能力提高 Uber iOS 上的可靠性和生产力。主要通过资源访问器（Resource accessors）和模拟（Mocks）两个例子来介绍代码自动生成能力如何提高代码可靠性和生产力。
