### ISSUE TITLE
Debugging Improvements in Swift 5.9

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4234]
# 推荐收录

## 链接

https://www.swift.org/blog/whats-new-swift-debugging-5.9/

**Comment by zvving** [comment]
三处比较细节的调试工具改动：p/po 切换更好的实现、表达式支持泛型参数、细粒度变量生命周期控制。

官方介绍内容比较笼统，周报不推荐录入。
