### ISSUE TITLE
Swift Parameter Packs

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4250]
# 推荐收录

## 链接

https://paul-samuels.com/blog/2023/09/29/swift-parameter-packs/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [Swift Parameter Packs](https://paul-samuels.com/blog/2023/09/29/swift-parameter-packs/)

[@享耳先森](https://github.com/iblacksun)：Swift 5.9 已经发布，除了广为人知的 `Macros`，还有一项比较少人提到的是 `Parameter Packs`，本文介绍了 `Parameter Packs` 的三种使用场景，如想更深入的理解 Swift 5.9 的更新，建议阅读另一篇：[What’s new in Swift 5.9?](https://www.hackingwithswift.com/articles/258/whats-new-in-swift-5-9)
