### ISSUE TITLE
简洁版 iOS 最佳实践

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#427]
#### 链接

https://ios-factor.com

**Comment by 100mango** [comment]
12-Factor 是软件即服务应用（SaaS）的一个著名方法论集合。iOS-factor 则从这个项目得到灵感，提炼出 iOS 开发相对应的方法论。本文则是阐述了这一方法论。目前总共有：依赖管理，配置，开发环境与线上环境等价，部署，本地优先于远端，向后兼容的API，版本号，持久化数据这八个类别。
