### ISSUE TITLE
介绍了 Texture

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#428]
https://medium.com/flawless-app-stories/why-i-build-my-apps-using-texture-and-why-you-should-too-99587c73f278

**Comment by kemchenj** [comment]
### [为什么我用 Texture 来搭建 App(并且你也应该)](https://medium.com/flawless-app-stories/why-i-build-my-apps-using-texture-and-why-you-should-too-99587c73f278)

作者介绍了 Texture 被创造出来的起源，并且列举了几种情况，例如 stackView 的使用，tableView 的列表反转等等，描述了为什么 Texture 比起 UIKit 更加容易构建 UI。
