### ISSUE TITLE
​浅析多模态大模型的前世今生

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4282]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/DXoeQqjVoDLxGV2oZeL95Q

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zoeGuo** [comment]
内容完全是大模型算法的内容了，没有基础的读者很难理解看懂。暂不推荐
