### ISSUE TITLE
[译文]现代 js 框架存在的根本原因

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#430]
#### 链接
https://juejin.im/post/5b111436e51d4506d06205fd

#### 理由
通过一个简单的例子演示，揭示了 Angular/Vue/React 等前端框架解决的最根本问题——UI 和 状态很难同步。

**Comment by ParsifalC** [comment]
@Awhisper 感觉这篇文章写得很好，看看能不能收录下期？

**Comment by Awhisper** [comment]
嗯哪 hold 到下周吧
