### ISSUE TITLE
Google Swift Style Guide

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#431]
#### 链接

[Google Swift Style Guide](https://google.github.io/swift/)
[Google Swift Formatter](https://github.com/google/swift/tree/format/tools/swift-format/)

#### 理由

谷歌写了一份 Swift 的代码风格指导，还顺手写了一个 Formatter（WIP）

**Comment by lacklock** [comment]
我没看懂这个Formatter怎么用，还是谷歌打算提pr给swift？

**Comment by kemchenj** [comment]
@lacklock 这个 Formatter 还在开发中，等开发完成之后应该会完善安装跟使用文档（目测用 SPM 直接生成一个 Xcode 的工程项目就可以打包一个 cli 了），然后这是一个单独的工具，只是刚好放在了 Swift 仓库里而已

- https://twitter.com/tony_allevato/status/1002948706583248896
- https://twitter.com/alfa/status/1003045522633121792
