### ISSUE TITLE
Diagnostic Improvements in Clang 17

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4316]
# 推荐收录

## 链接

https://blog.llvm.org/posts/2023-09-19-diagnostic-improvements-in-clang-17/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by aaaron7** [comment]
这篇文章整体罗列了clang17在诊断信息输入上的一些升级，类似新版本changelog。不包括其他技术原理/技术体系的介绍，也没有一些平时开发的最佳实践的内容。感觉对移动开发者价值不大，建议不推荐。
