### ISSUE TITLE
Why Do Peephole Optimizations Work?

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4320]
# 推荐收录

## 链接

https://blog.regehr.org/archives/2485

## 理由

沉迷汇编（

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by LeoMobileDeveloper** [comment]
作者主观分析的内容偏多，干货不多，不推荐了
