### ISSUE TITLE
iOS 流量监控

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#433]
http://zhoulingyu.com/2018/05/30/ios-network-traffic/

**Comment by ParsifalC** [comment]
fixed by 356223e766e83e5567ea5f1e2921d8013de1e52c.

### 🐕 [iOS 流量监控分析](http://zhoulingyu.com/2018/05/30/ios-network-traffic/)
在移动开发早期，流量监控一直是 APM 里很重要的部分。但随着 WiFi 覆盖率的提高以及流量资费的下降，客户端的流量监控渐渐显得不是那么重要了。饿了么基于自己的业务场景需要，分析比较了圈内各大已知 APM 流量监控方案的优缺点，最终实现了自己的流量监控模块。该文章对于加深理解 iOS 客户端内 HTTP 请求流程是很有帮助。
