### ISSUE TITLE
COWMacro

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4333]
# 推荐收录

## 链接

https://github.com/wezzard/COWMacro

## 理由

这个宏还是很好用的，如果 Struct 很大的话，并且作为参数传递，很容易产生非常大的包大小体积（生成的代码中大量包含了 copy 代码）。

在业务测可以通过 COW 宏快速包装（读内网一份卓立组同学的文档学到的）

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
极端情况下，一个巨大的 Struct 的 传递，就能产生 1KB 的汇编代码，什么叫包大小杀手啊（战术后仰

**Comment by Kyle-Ye** [comment]
> 极端情况下，一个巨大的 Struct 的 传递，在 <= Swift 5.8 以下，就能产生 1KB 的汇编代码，什么叫包大小杀手啊（战术后仰

它会逐个copy，特别是涉及enum case/bool的话还会反复的and 0xffff_0000 和 bfi 之类的操作来spilt & merge
点名批评 SwiftUI 的 _ViewInputs 🤡

**Comment by ChengzhiHuang** [comment]
> > 极端情况下，一个巨大的 Struct 的 传递，在 <= Swift 5.8 以下，就能产生 1KB 的汇编代码，什么叫包大小杀手啊（战术后仰
> 
> 它会逐个copy，特别是涉及enum case/bool的话还会反复的and 0xffff_0000 和 bfi 之类的操作来spilt & merge 点名批评 SwiftUI 的 _ViewInputs 🤡

那这个 issue 给你了：），你的 OpenSwiftUI 有正式 release 了也自己给自己推荐一波吧
