### ISSUE TITLE
WWDC 中提到的浏览器 Fingerprinting 有多可怕？

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#434]
https://juejin.im/post/5b17de31f265da6e397b70f4?from=timeline&isappinstalled=0

**Comment by raozhizhen** [comment]
Web 浏览器上的 fingerprinting 技术指通过 IP 地址、JavaScript 行为、Flash 与 Java 插件、字体、Canvas、WebGL 等多维度信息，来给每一个浏览器打上一个不同的 fingerprint。你修改浏览器的常见配置，fingerprint 往往并不会发生改变，而你换一台电脑，或者换一个浏览器，都会产生不同的 fingerprint。
