### ISSUE TITLE
SFSafariViewController in SwiftUI: Open webpages in-app

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4341]
# 推荐收录

## 链接

https://www.avanderlee.com/swiftui/sfsafariviewcontroller-open-webpages-in-app/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [SFSafariViewController in SwiftUI: Open webpages in-app](https://www.avanderlee.com/swiftui/sfsafariviewcontroller-open-webpages-in-app/)
[@享耳先森](https://github.com/iblacksun)：`SFSafariViewController` 常用于在 App 内打开外部链接，但目前并没有 `SwiftUI` 版本。本文深入浅出，开始使用 `UIViewRepresentable` 简单封装 UIKit 使其在 `SwiftUI` 可用，之后再结合 `View Modifier` 等特性优化。
