### ISSUE TITLE
macbootstrap

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#435]
#### 链接
https://github.com/bestswifter/macbootstrap

https://bestswifter.gitbook.io/effectivemac/
#### 理由
非常全的配置开发环境脚本集，文档配备非常齐全，当 cheetsheet 或者教程都很适合。

**Comment by kemchenj** [comment]
### [Effective Mac](https://bestswifter.gitbook.io/effectivemac/)

这是一个针对新 Mac 开发的，快速配置开发环境的脚本，里面集成了一些常用的配置。所有的配置和功能都有文档说明， 它既是使用手册，也是教学指南。

虽然环境配置是一件非常主观的事，不同的人审美和需求不一样，但也可以看看文档，了解一些好玩的用法，看看它是怎么实现的，然后把部分函数抄走并提高自己的工作效率。
