### ISSUE TITLE
苹果 iOS 分发和安装 App 的那些趣事

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4358]
# 推荐收录

## 链接

https://juejin.cn/post/7315260397371490319

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [苹果 iOS 分发和安装 App 的那些趣事](https://juejin.cn/post/7315260397371490319)
[@享耳先森](https://github.com/iblacksun)：本文介绍了苹果 iOS 应用分发和安装的一些有趣的事。讨论了不同的开发者计划和分发方式：包括企业签名、超级签名、TestFlight签名和MDM超级签名，还提到了开发者模式、企业账号、设备注册限制以及自定App和非公开App分发的解决方案。最后，讨论了欧盟的《数字市场法》对苹果的影响和可能改变苹果软件生态的可能性。
