### ISSUE TITLE
Enable upcoming Swift features in SPM

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4364]
# 推荐收录

## 链接

https://www.polpiella.dev/enable-upcoming-swift-features-in-spm/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
之前分享过类似的，这个就不重复分享了 https://github.com/SwiftOldDriver/iOS-Weekly/issues/4042
