### ISSUE TITLE
    Comparing Swift Compiler Performance on Type Inference Part I Strings, Numbers, Arrays, Dictionaries and Constructables

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4378]
# 推荐收录

## 链接

https://lucasvandongen.dev/compiler_performance.php?some=newhero

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
😆...我也学习学习 forums 里的讨论（

**Comment by kemchenj** [comment]
### [Comparing Swift Compiler Performance on Type Inference Part I Strings, Numbers, Arrays, Dictionaries and Constructables](https://lucasvandongen.dev/compiler_performance.php)

[@kemchenj](https://kemchenj.github.io/)：这篇文章比较了Swift编译器在进行类型推断时的性能，特别是在字符串、数字、数组、字典和可构建类型的初始化方面。作者通过基准测试发现，使用未类型化的字面量初始化通常最快，而使用.init()的方式最慢。特别是在复杂上下文中，例如计算属性，.init()的性能下降明显。文章还指出，不同版本的Xcode在编译性能上的差异，并提出了优化编译时间的具体建议。
