### ISSUE TITLE
AnyView’s impact on SwiftUI performance

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4382]
# 推荐收录

## 链接

https://martinmitrevski.com/2024/01/02/anyviews-impact-on-swiftui-performance/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
https://fatbobman.substack.com/p/fatbobmans-swift-weekly-014

@fatbobman 的周报最近做过介绍，单独介绍内容差别不大，直接摘用并友链推荐
