### ISSUE TITLE
Adapting your App Icon to visionOS

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4387]
# 推荐收录

## 链接

https://www.createwithswift.com/adapting-your-app-icon-to-visionos

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Adapting your App Icon to visionOS](https://www.createwithswift.com/adapting-your-app-icon-to-visionos/)

[@享耳先森](https://github.com/iblacksun)：Apple Vision Pro 即将发售，如果你的 App 准备适配 visionOS，本文介绍了如何将现有的 App Icon 进行修改已完美匹配 visionOS 规范。
