### ISSUE TITLE
Islands Architecture

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4392]
# 推荐收录

## 链接

https://jasonformat.com/islands-architecture/

## 理由

孤岛架构，来自前端的理念。其实可以泛化为一种做优化的思路。引入 Island 架构，先保证最重要的模块先加载，，并控制岛屿的渲染顺序，从而让 核心模块的资源加载优先级、（渲染优先级 iOS 没这个）都调高。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
这是纯前端领域的概念，似乎和 iOS 相关性不大，暂不推荐。
