### ISSUE TITLE
2024 Flutter 重大更新，Dart 宏（Macros）编程开始支持，JSON 序列化有救

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4405]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/WoamljZJeNN9huMdIb_Ycw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by CrazyCoderShi** [comment]
上周已经贴过了 🤣
