### ISSUE TITLE
如果你是 Apple Vision Pro 的开发者，那你一定要注意这些点

### ISSUE THREAD

**Issue by OneeMe** [SwiftOldDriver/iOS-Weekly#4406]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/sa9nUePtc2_acycubGGOjQ

## 理由

Apple Vision Pro 和以往的 iOS、iPad 设备很不同，零售版买来的设备是无法直接连接 USB 进行调试的，这篇文章就对如何使用 WIFI 进行调试，以及如何录制 App 体验以及上架到 AppStore 进行了比较完整的解释。

## 推荐人信息

御姐：https://onee.me

**Comment by ChengzhiHuang** [comment]
咱年前也推过类似的内容了，五神写的，https://mp.weixin.qq.com/s/HUrJvGzahMso4rDk2EjRAQ，下次还有其他优秀内容御姐欢迎来投稿
