### ISSUE TITLE
SR-7380, Ambiguous KeyPath 

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#441]
#### 链接

http://matt.diephouse.com/swift/0/

#### 理由

作者在写代码的时候发现了 Swift keyPath 的一个 bug，于是决定自己上手修复这个 bug，从 bug 定位到修复的过程思路清晰，非常值得一看

PS：作者是 GitHub 和 Apple 的前员工

**Comment by iblacksun** [comment]
### [SR-7380, Ambiguous KeyPath](http://matt.diephouse.com/swift/0/)

> 作者是 GitHub 和 Apple 的前员工。

作者在编码过程中发现 Swift `KeyPath` 的一个 bug，从定位和修复问题的过程非常清晰，值得一看。

Swfit 的编译前端是 `swiftc`(为什么不是 Clang ? 参考 https://www.youtube.com/watch?v=Ntj8ab-5cvE) 文章写了如何给编译器加参数让其打印出更多信息、如何生成 `AST(抽象语法树)`、`语义分析`如何做类型检查等。

> 关于 Swift 编译过程，可参考 [向开源的 Swift 贡献代码](https://academy.realm.io/cn/posts/tryswift-jesse-squires-contributing-open-source-swift/)
