### ISSUE TITLE
So You Think You Know Git - FOSDEM 2024

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4424]
# 推荐收录

## 链接

https://www.youtube.com/watch?v=aolI_Rz0ZqY

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by zvving** [comment]
GitHub 的联合创始人 Scott Chacon （也是 Pro Git 的作者）进行了一场关于 Git 的技术演讲，涵盖了如配置选项、有用的命令标志以及对大型仓库的优化等主题，也探讨了对 Git 新特性和更现代 UI 的期待。

对于国内 iOS 开发者使用 Git CLI 不多的情况，建议周报不做推荐 @ChengzhiHuang

**Comment by ChengzhiHuang** [comment]
ooook，其实最初的推荐原因是因为里面有些很有意思的命令，例如：
``shell
git blame -w -C -C -C -L 15,26 path/to/file
``
可以忽略创建文件、空格/换行提交和代码移动等无效commit来找到真正的blamer

**Comment by ChengzhiHuang** [comment]
我个人看了之后是有很多收获，不过可能确实对国内开发者没什么帮助（
