### ISSUE TITLE
The power of self-sufficient features

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4426]
# 推荐收录

## 链接

https://www.swiftindepth.com/articles/self-sufficient-features/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [The power of self-sufficient features](https://www.swiftindepth.com/articles/self-sufficient-features/)

[@享耳先森](https://github.com/iblacksun)：一个功能最好是相对独立，尽量减少对外部的依赖，本文介绍了 `self-sufficient features` 的几个原则：
1. 自身加载必须的数据，而不靠外部传入
2. 内部处理各种错误，而不向外传递
3. 不要依赖或修改堆栈
