### ISSUE TITLE
Modding Plugins back into Xcode

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4430]
# 推荐收录

## 链接

https://bryce.co/xcode-plugin-loader/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
kyo 最近有点事情，reassign 下。

**Comment by iblacksun** [comment]
### 🐢 [Modding Plugins back into Xcode](https://bryce.co/xcode-plugin-loader/)

[@享耳先森](https://github.com/iblacksun)：因 macOS 安全机制升级导致 Xcode 老的插件体系被废弃，本文写了与此相关的一些 Xcode 插件背景知识，以及提供了一些 `黑魔法` 让新版 Xcode 也可以加载老的插件，如果对 Xcode 插件开发敢兴趣，建议阅读。
