### ISSUE TITLE
WWDC18: A Basic Guide to App Store Connect API

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#444]
#### 链接

https://medium.com/xcblog/wwdc18-a-basic-guide-to-app-store-connect-api-366208651ac6

#### 理由
WWDC 2018 里，苹果宣布公开 App Store Connect API，开发者不用再通过抓包，偷偷摸摸地使用了。这篇文章是对 App Store Connect 的两篇 Session 301 303 的解读。

**Comment by lacklock** [comment]
这个session看来挺重要的。如果头条那边没人翻我们小专栏里让人翻译一下。

**Comment by tom510230** [comment]
这个我有兴趣，最近在做TF的事情
