### ISSUE TITLE
Unrestricted View Replication

### ISSUE THREAD

**Issue by Kyle-Ye** [SwiftOldDriver/iOS-Weekly#4463]
# 推荐收录

## 链接

[Unrestricted View Replication
](https://bryce.co/replicating-views/)

## 理由

一些好玩的 UIKit 黑魔法🪄

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@Kyle-Ye 你链接掉了。。。

**Comment by Kyle-Ye** [comment]
Updated
