### ISSUE TITLE
Swift Tooling: Windows Edition

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4469]
# 推荐收录

## 链接

https://speakinginswift.substack.com/p/swift-tooling-windows-edition

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
Closed by https://github.com/SwiftOldDriver/iOS-Weekly/commit/3aa781a23f365ee8dc6c899bee6a9ec414beb1a2
