### ISSUE TITLE
Sending trial notifications with provisional authorization on iOS

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4470]
# 推荐收录

## 链接

https://nilcoalescing.com/blog/TrialNotificationsWithProvisionalAuthorizationOnIOS

## 理由

临时通知用用也挺好的，毕竟不用用户手动同意，体验会好一点。

在用户觉得临时通知有意思之后再申请全部的通知，应该是个不错的可以转化的思路。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Sending trial notifications with provisional authorization on iOSX](https://nilcoalescing.com/blog/TrialNotificationsWithProvisionalAuthorizationOnIOS/)

[@享耳先森](https://github.com/iblacksun)：Push 是很好的吸引用户注意的方式，但难点是如何获取用户的授权，本文介绍了 `provisional notifications` 这一通知机制。
