### ISSUE TITLE
What’s Next for Mobile at Airbnb

### ISSUE THREAD

**Issue by chenjunpu** [SwiftOldDriver/iOS-Weekly#450]
主要介绍了 Airbnb 为什么当初会选择 React Native，以及现在为什么要放弃 React Native，和 Airbnb 移动端的未来方向，整体有 5 个 Part

[Part 1: React Native at Airbnb](https://medium.com/airbnb-engineering/react-native-at-airbnb-f95aa460be1c)
[Part 2: The Technology](https://medium.com/airbnb-engineering/react-native-at-airbnb-the-technology-dafd0b43838)
[Part 3: Building a Cross-Platform Mobile Team](https://medium.com/airbnb-engineering/building-a-cross-platform-mobile-team-3e1837b40a88)
[Part 4: Making a Decision on React Native](https://medium.com/airbnb-engineering/sunsetting-react-native-1868ba28e30a)
[Part 5: What’s Next for Mobile](https://medium.com/airbnb-engineering/whats-next-for-mobile-at-airbnb-5e71618576ab)

**Comment by lacklock** [comment]
v2ex上翻译的一些重点 https://www.v2ex.com/t/464548

**Comment by iblacksun** [comment]
### 🐢 [What’s Next for Mobile at Airbnb](https://medium.com/airbnb-engineering/react-native-at-airbnb-f95aa460be1c)

对于 `ReactNative` 社区来说，上周两大事件值得关注：Facebook 宣布[对 ReactNative 底层进行重构](https://facebook.github.io/react-native/blog/2018/06/14/state-of-react-native-2018)；Airbnb 宣布放弃 RN 并连发了五篇 blog 来解释。

- [Part 1: React Native at Airbnb](https://medium.com/airbnb-engineering/react-native-at-airbnb-f95aa460be1c)
第一篇讲为什么 Airbnb 在 2016 年决定投入 RN，比如 `比拟原生体验`、`代码可以垮平台`、`提升开发体验` 等。

- [Part 2: The Technology](https://medium.com/airbnb-engineering/react-native-at-airbnb-the-technology-dafd0b43838)
第二篇着重写 RN 在技术层面的一些优劣，优势：垮平台、迭代速度、与 Native 代码桥接方便等，劣势方面：因 JS 无类型导致不好重构、JSCore 在双平台的不一致性、App 体积、RN 初始化及首次渲染时间等。

- [Part 3: Building a Cross-Platform Mobile Team](https://medium.com/airbnb-engineering/building-a-cross-platform-mobile-team-3e1837b40a88)
第三篇从团队管理角度来讲引进 RN 之后带来的一些问题：要用好 RN 开发者还需要懂 Native，这种混合对招聘、测试、迭代都会带来很多挑战。

- [Part 4: Making a Decision on React Native](https://medium.com/airbnb-engineering/sunsetting-react-native-1868ba28e30a)
第四篇，由于 RN 在技术方面的一些问题及对团队带来的挑战不能很好的解决，Airbnb 决定 `Sunset RN`，停止用 RN 开发新功能，逐渐转向 Native。对于开源，他们会将一些项目转到 react-native-community。

- [Part 5: What’s Next for Mobile](https://medium.com/airbnb-engineering/whats-next-for-mobile-at-airbnb-5e71618576ab)
第五篇讲 Airbnb 在移动方向的未来，介绍了 Server-Driven Rendering，还有努力推进的 `Epoxy`、`MvRx` 等项目。
