### ISSUE TITLE
Customising the DocC documentation theme

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4504]
# 推荐收录

## 链接

https://swiftpackageindex.com/blog/customising-the-docc-documentation-theme

https://www.swift.org/documentation/docc/customizing-the-appearance-of-your-documentation-pages

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
This is a old feature release in 2022. I believe we can introduce some new swift-docc feature recently or wait for WWDC24 session.

**Comment by Kyle-Ye** [comment]
See https://github.com/apple/swift-docc/pull/359
