### ISSUE TITLE
Swift 6 upgrade Preparation

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4511]
# 推荐收录

## 链接

https://medium.com/jamf-engineering/swift-6-upgrade-preparation-0941fbea2db6

https://gist.github.com/ole/478874632fca61869928a0cc0a956972#file-swift-list-features-sh

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
Fixed by 27c719f
