### ISSUE TITLE
iphone only 的app在ipad上的适配在ios12上可能会有所不同

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#453]
https://bendodson.com/weblog/2018/06/20/iphone-only-apps-on-ipad/

**Comment by raozhizhen** [comment]
一个不错的消息，在 iOS 12 beta 2 上，你的 iPhone Only 应用程序将会以 16：9 的比例运行。在此之前，尽管 iOS 10 不再支持 iPhone 4S，但你依旧需要让 APP 能以 3：2 的比例运行在 iPad 上。
