### ISSUE TITLE
淘系两年半A/B实验经历，聊聊我理解的“科学实验”

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4532]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/-durED9M0UMqhT0i2S67lQ

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by wtuyp** [comment]
该内容已被发布者删除 @iostalks

**Comment by ChengzhiHuang** [comment]
@wtuyp 今天公众号刚删，我也没保留快照，昨晚还在。

我观察下后面还会不会放出，放出的话会在这个 issue 下回复你。

**Comment by ChengzhiHuang** [comment]
甚至全网其他渠道也都删除干净了，麻了
