### ISSUE TITLE
Now I’m worried our metrics aren’t correct! with special guest Holly Borla

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4533]
# 推荐收录

## 链接

https://share.transistor.fm/s/2d4b1ba7

## 理由

This week we had the opportunity to talk to Holly Borla who manages the Swift Compiler Team at Apple. We chat about upcoming Swift 6 changes and why they're a big deal, but also why you shouldn’t worry too much. Of course, all three of us pick packages, too!

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
Closed by ed993162617086c01c7e4c85aaeb287776e3c77b
