### ISSUE TITLE
Developing An Inclusive Mindset

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4541]
# 推荐收录

## 链接

https://david-smith.org/blog/2024/04/22/new-post/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### [Developing An Inclusive Mindset](https://david-smith.org/blog/2024/04/22/new-post/)

如果你的产品在考虑或已经做了无障碍适配，建议看看这个视频。作者 David Smith 是独立开发者，开发了 `Pedometer Plus+` 等应用，视频里重点介绍了他对 `包容性设计` 的认知发展过程：无障碍适配不仅仅是 `Accessibility API` 适配这么简单，而应该从更全局的角度来审视整个设计。
