### ISSUE TITLE
Always correct gradient text in UIKit

### ISSUE THREAD

**Issue by Kyle-Ye** [SwiftOldDriver/iOS-Weekly#4549]
# 推荐收录

## 链接

https://nemecek.be/blog/143/always-correct-gradient-text-in-uikit

## 理由

Gradient -> UIImage -> UIColor

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
看完了，最后 UIStackView 的 layoutSubviews 里面最好根据 bounds 是否改变做一下缓存，不然计算可能会非常频繁。
