### ISSUE TITLE
Swift 集成 KSCrash IOS 崩溃跟踪并扩展输出 Crash 日志到指定文件

### ISSUE THREAD

**Issue by PBK-B** [SwiftOldDriver/iOS-Weekly#4577]
# 推荐收录

## 链接
[Swift 集成 KSCrash IOS 崩溃跟踪并扩展输出 Crash 日志到指定文件](https://bin.zmide.com/?p=1220)

## 理由
新手投稿，请多指教

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by PBK-B** [comment]
@ChengzhiHuang @Damonvvong @linwenbang PTAL;

**Comment by ChengzhiHuang** [comment]
感谢投稿，我们周末会安排编辑看看。

**Comment by ChengzhiHuang** [comment]
看了一下，其实 KSCrash 把摘录的堆栈输出到文件，是有意义的。

有几个优化的点可以考虑：
1. 写入本地文件，文件名最好提供一些选项，例如 时间/进程名字 的组合等，目前只有一个 temp 名字有些简陋。同时可以考虑存到本地文件后，进行压缩，上报原始的 json 会浪费带宽。
2. filterReports 相关的文件操作我不确定是否在主线程，但是 IO 操作不应该在主线程执行，应该放到某个子线程，完成后再回调给外部，或者执行下一个 filter 。
3. 最好提供一份在 github 上的 KSCrashInstallationFile 等文件的实现。

**Comment by PBK-B** [comment]
> 看了一下，其实 KSCrash 把摘录的堆栈输出到文件，是有意义的。
> 
> 有几个优化的点可以考虑：
> 
> 1. 写入本地文件，文件名最好提供一些选项，例如 时间/进程名字 的组合等，目前只有一个 temp 名字有些简陋。同时可以考虑存到本地文件后，进行压缩，上报原始的 json 会浪费带宽。
> 2. filterReports 相关的文件操作我不确定是否在主线程，但是 IO 操作不应该在主线程执行，应该放到某个子线程，完成后再回调给外部，或者执行下一个 filter 。
> 3. 最好提供一份在 github 上的 KSCrashInstallationFile 等文件的实现。

@ChengzhiHuang  感谢建议，其实我在项目中是有准备做输出到文件中然后通过时间和进程名称做文件名组合的，只是因为没写完所以在博客中把那部分代码给删除了（后续我补充一下），示例代码已经提交到 <https://github.com/PBK-B/ios-sample-project/tree/master/swift-kscrash-installation-file>

**Comment by kemchenj** [comment]
### [Swift 集成 KSCrash IOS 崩溃跟踪](https://bin.zmide.com/?p=1220)

[@kemchenj](https://kemchenj.github.io/)：本篇文章讲解了在 Swift 项目中集成 KSCrash 进行 iOS 应用崩溃日志跟踪的方法，并提供了将日志输出到指定文件的解决方案。作者详细介绍了 KSCrash 的配置和自定义输出文件的实现步骤，包含代码示例，帮助开发者更好地管理和分析应用崩溃信息。

> 推荐人：[PBK-B](https://github.com/PBK-B)
