### ISSUE TITLE
iOS中的图片使用方式、内存对比和最佳实践

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#458]
https://juejin.im/post/5b2ddfa7e51d4553156be305

**Comment by 100mango** [comment]
在 WWDC 2018的[图像最佳实践](https://juejin.im/post/5b1a7c2c5188257d5a30c820)中，苹果为我们介绍了一种缩放图片的方式。本文则是对这个议题进一步探究，研究了三种创建`UIImage`的方式所占用的内存大小，结论是苹果官方提供的方式占用内存最小，推荐大家使用。
