### ISSUE TITLE
推荐三个swift工具库ZTChain，ZTStyle，ZTUIKit

### ISSUE THREAD

**Issue by willonboy** [SwiftOldDriver/iOS-Weekly#4584]
# 推荐收录
- ZTChain：一个轻量级的链式语法库，全方位支持OC、swift对象属性链式调用，只一个文件，小巧且强大。
- ZTStyle：为UIKit组件提供链式UI样式的定义及调用，方便app制定UI规范，只一个文件20行代码，小巧且强大。
- ZTUIKit：专为UIKit设计，具有类似SwiftUI的直观语法，支持类似React函数式UI组件，只两个文件，小巧且强大。

## 链接
- ZTChain [https://github.com/willonboy/ZTChain]
- ZTStyle [https://github.com/willonboy/ZTStyle]
- ZTUIKit [https://github.com/willonboy/ZTUIKit]

## 理由

这些库旨在简化和提升iOS开发工作效率，为开源贡献力量，让iOS开发变得更加愉快和高效！

## 推荐人信息

trojan zhang，以上三个开源库的作者

**Comment by zoeGuo** [comment]
开源库相对简单，暂不推荐

**Comment by willonboy** [comment]
开源库相对简单

> 感谢自荐～开源库相对简单，暂不推荐。希望代码经过更多coder验证健壮性和适用性后再推荐哦、

你这“开源库相对简单”怎么理解？我目前也没看到其他类似能这么方便实现相同目的的开源实现，你所指的“开源库相对简单”是指的什么？

**Comment by willonboy** [comment]
> 感谢自荐～开源库相对简单，暂不推荐。希望代码经过更多coder验证健壮性和适用性后再推荐哦、

你说的“开源库相对简单”怎么理解？是指功能吗？还是指这个功能的实现简单？就单链式调用能力来说，目前我还没有看到其他哪个库可以这么方便的实现包含支持OC对象的链式调用能力，而且我这认为这个能力作为日常开发是很有用的。
