### ISSUE TITLE
Create ML Tutorial: Getting Started

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#459]
https://www.raywenderlich.com/196233/create-ml-tutorial-getting-started

**Comment by XanderXu** [comment]
我把文章翻译了一下,发在了掘金上https://juejin.im/post/5b2f66a9f265da59a1172896

**Comment by kemchenj** [comment]
### 🐕[Create ML Tutorial Getting Started](https://www.raywenderlich.com/196233/create-ml-tutorial-getting-started)

Raywenderlich 家出的 Create ML 入门教学，手把手教你用 Craete ML 和 Turi Create 构建机器学习模型，体验过一遍以后大家可能对 Create ML 这门框架，并且国内有开发者已经[翻译了这篇文章](https://juejin.im/post/5b2f66a9f265da59a1172896)，感兴趣的同学可以考虑跟着wen zhang体验一次机器学习模型的训练过程。
