### ISSUE TITLE
PanelKit

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#46]
https://github.com/louisdh/panelkit

**Comment by Damonvvong** [comment]
刚下下来看了一下。这个东西做的还是比较有意思。特别是布局的地方。

但是，实用性较低，国内的app基本不会根据平台定制化设计，所以安卓实现不了这样的。除了一些定制化设计的公司或者独立开发使用的公司。刚搜了一下。确实没有 app 使用。

另外，代码还不太规范。

讨论之后，就不上周报了~
