### ISSUE TITLE
普通 iOS 开发者的第一款 Harmony Next 应用

### ISSUE THREAD

**Issue by SeaHub** [SwiftOldDriver/iOS-Weekly#4612]
# 推荐收录

## 链接

[[普通 iOS 开发者的第一款 Harmony Next 应用](https://mp.weixin.qq.com/s/KjydTcbUQAafB6zFIi7yDw)]

## 理由

近期，纯血鸿蒙开始走进终端开发者的视野。终端开发可能都比较关心，自己有没有可能在鸿蒙这片蓝海焕发第二春，从而淘金一笔呢？本篇文章以独立开发的角度，作为第一批开发纯血鸿蒙应用的开发者，为大家还原了一款简单的 Harmony Next 币种软件的开发历程，内容覆盖了从选题到上架的过程。同时也文章也分享了一些关于作者关于鸿蒙的一些看法和观点，适合摸鱼时阅读。

## 推荐人信息

文章作者自身推荐

**Comment by ChengzhiHuang** [comment]
原来你最近在做鸿蒙哈哈哈哈

**Comment by SeaHub** [comment]
> 原来你最近在做鸿蒙哈哈哈哈

牛马搬砖工，哪里有砖搬哪里
