### ISSUE TITLE
[译] 怎样（以及为什么要）保持你的 Git 提交记录的整洁

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#462]
https://juejin.im/post/5b29060ee51d4558cd2adac0

**Comment by mmoaay** [comment]
作者通过日常工作中常用的 4 个 git 使用场景，向读者解释了为什么要保持 Git 提交记录的整洁，以及保持 Git 提交记录的整洁的方法。建议读的时候跟着作者的思路操作一遍，更能加深理解！
