### ISSUE TITLE
Fix brew Error “The arm64 architecture is required for this software” on Apple Silicon Mac

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4640]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

## 理由

https://osxdaily.com/2024/07/06/fix-brew-error-the-arm64-architecture-is-required-for-this-software-on-apple-silicon-mac/

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
不推荐，x86 homebrew on arm64 CPU 的 bugfix 指南，感觉放 M1 那会儿刚出来可以推荐，现在没啥太大价值
