### ISSUE TITLE
FixedWidthPDF

### ISSUE THREAD

**Issue by GodL** [SwiftOldDriver/iOS-Weekly#4644]
# 推荐收录

## 链接

(https://github.com/GodL/FixedWidthPDF)

## 理由
使PDFView以固定的宽度去显示所有PDFPage，即使PDFPage大小不一样， 并且支持长按选择文字。

**Comment by raozhizhen** [comment]
从 readme 上来看，应用场景比较小，对周报读者意义不大～ 暂不收录～
