### ISSUE TITLE
shorebird：支持上架应用商店的 flutter 热更新框架

### ISSUE THREAD

**Issue by lightank** [SwiftOldDriver/iOS-Weekly#4652]
# 推荐收录

## 链接

https://shorebird.dev/

## 理由

支持上架应用商店的 flutter 热更新框架

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by CrazyCoderShi** [comment]
不可否认 shorebird 是一个不错的项目，但暂时不推荐，理由如下:
1. shorebird 在 iOS 平台的稳定性暂时还不够
2. bugfix 版本频率目前依然很多，这部分从 releases 中可查

**Comment by CrazyCoderShi** [comment]
比如这类 bug：
https://github.com/shorebirdtech/shorebird/issues/2358
