### ISSUE TITLE
再探 WKWebView 页面与档案资源 Preload 预载 / Cache 缓存 可行方案

### ISSUE THREAD

**Issue by zhgchgli0718** [SwiftOldDriver/iOS-Weekly#4662]
# 推荐收录

## 链接

https://medium.com/zrealm-ios-dev/ios-wkwebview-%E9%A0%81%E9%9D%A2%E8%88%87%E6%AA%94%E6%A1%88%E8%B3%87%E6%BA%90-preload-%E9%A0%90%E8%BC%89-cache-%E7%B7%A9%E5%AD%98%E7%A0%94%E7%A9%B6-5033090c18ba

## 理由

参考老司机周报前贤分享过的 WKWebView 细节，WKWebView 页面与档案资源 Preload 预载 / Cache 缓存 可行方案。

## 推荐人信息

自荐

**Comment by iostalks** [comment]
这篇文章介绍的优化方案比较全面，但重点体现的方案比较常规，暂不做推荐。
另外老司机读者主要是大陆用户，繁体字阅读体验可能不是很好。
