### ISSUE TITLE
Cross-Platform Swift: WebAssembly/View Paradigms

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4691]
# 推荐收录

## 链接

https://www.pointfree.co/episodes/ep291-cross-platform-swift-webassembly

https://www.pointfree.co/episodes/ep290-cross-platform-swift-view-paradigms

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
Works 7 days this week. Have no time to check it. I'll check and close it next weekend.
