### ISSUE TITLE
Swift Build Times and Module Verification…

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4695]
# 推荐收录

## 链接

https://pfandrade.me/blog/swift-build-times-and-module-verification/

## 理由

> This tweak brought down the build time **from 3.5 minutes to 52 seconds** 😮!

**Comment by ChengzhiHuang** [comment]
对于一些小工程，关掉 ENABLE_MODULE_VERIFIER 在 Debug 下应该确实能提升不少速度。
