### ISSUE TITLE
为超越JVM而生？深入理解Kotlin Native的梦想与可能

### ISSUE THREAD

**Issue by JonyFang** [SwiftOldDriver/iOS-Weekly#4698]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/oo7YTnW4oL1xq17cNPGhnw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
finished
