### ISSUE TITLE
Vision Pro 上的手势匹配框架 HandVector 更新 2.0 了，新增 FingerShape 功能

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4699]
# 推荐收录

## 链接

https://juejin.cn/post/7408086889591390262

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
等 2.0 relesse

**Comment by XanderXu** [comment]
> 等 2.0 relesse

2.0.1 已经 release 了

**Comment by ChengzhiHuang** [comment]
> > 等 2.0 relesse
> 
> 2.0.1 已经 release 了

好的大哥，咱这周末安排 @BluesJiang
