### ISSUE TITLE
Enum-Driven TableView Development

### ISSUE THREAD

**Issue by WXGBridgeQ** [SwiftOldDriver/iOS-Weekly#471]
#### 链接

https://www.raywenderlich.com/188692/enum-driven-tableview-development

#### 理由

很简单的一篇文章，但是非常实用，看完直接把思路拿出来重构项目代码了

**Comment by lacklock** [comment]
我个人觉得这个有点太简单了，真正对架构的意义可能不会有很大的影响，并没有真正的解决复杂度管理的问题。但是作为Enum的一个灵活运用例子也挺合适的。
@anotheren 决定有没必要收录把。

**Comment by anotheren** [comment]
我也觉得还是缺一点，如果他考虑到泛型 State<T> 我也觉得作为 Enum 的用例不错。结论：不做收入。
