### ISSUE TITLE
在 Swift 中如何正确传递 Unsafe Pointers 参数

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4720]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/xDeZ6zM7-6RfPXrs5kCqWw

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
Closed by ba37f1cc4dd91851fed9cd5b7ea497a557d0a570
