### ISSUE TITLE
Exploring SwiftUI: Creating a Custom Slider Inspired By Camera Control

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4721]
# 推荐收录

## 链接

https://www.rudrank.com/exploring-swiftui-creating-a-custom-slider-inspired-by-camera-control/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by rudrankriyam** [comment]
谢谢!
