### ISSUE TITLE
SwiftCraft 2024

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4737]
# 推荐收录

## 链接

https://www.youtube.com/playlist?list=PLugrLwuQvERqB4Kj8GOPwCnUMOLxJ0Ny9

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ZengyiMa** [comment]
@ChengzhiHuang 这个上周写过了，忘记close了😂
