### ISSUE TITLE
一款中文AI面试辅助工具，支持macOS和Windows平台

### ISSUE THREAD

**Issue by caiwb** [SwiftOldDriver/iOS-Weekly#4751]
# 推荐收录

一款中文AI面试辅助工具，支持macOS和Windows平台

## 链接

https://offerji.cn

## 理由

工具

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
@caiwb 感谢推荐，但 AI 辅助面试有道德风险，且无助于降低整体面试与求职的混乱，因此不做收录推荐。

如果有一些 AI 查询 iOS 技术问题，或者八股，或者新一点的技术的 GPT 机器人等，可以新建 issue 推荐给我们，我们认为这些是有利减少信息获取难度的。
