### ISSUE TITLE
声明一个非空的集合类型，这样取first的时候就可以确定有值

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#476]
https://www.pointfree.co/blog/posts/7-open-sourcing-nonempty
我觉得这个点子很好，但是可能最后不会用这样的方式实现。或者说这个问题要如何兼容进现有的项目可能是个问题。毕竟这是一个很小的问题

**Comment by kemchenj** [comment]
### [Non Empty](https://www.pointfree.co/blog/posts/7-open-sourcing-nonempty)

在 Swift 里很多时候你明明知道数组不为空，但还是需要为 `first` 或者 `last` 之类的属性进行解包才行，更好的方式应该是构造一种**非空集合**类型去进行约束。

Swift 教学网站 PointFree 最近就开源了一个 NonEmpty 库，通过给集合类型加上一层封装，让我们可以在类型安全的情况下，更加方便的使用非空数组，避免多余的解包。
