### ISSUE TITLE
Flutter 被分叉！团队缩水至 50 人，bug 堆积如山，前谷歌员工出手找出路

### ISSUE THREAD

**Issue by ztlyyznf001** [SwiftOldDriver/iOS-Weekly#4762]
# 推荐收录

## 链接
https://mp.weixin.qq.com/s/m6HOz5e_vnHSl2al-wNdaA

**Comment by ChengzhiHuang** [comment]
https://mp.weixin.qq.com/s/umpbaSMqWQYxm8C8mRHGKw

这篇里的态度如何？是准备作为新闻推送吗？

 @ztlyyznf001
