### ISSUE TITLE
Xcode stops fetching Swift packages

### ISSUE THREAD

**Issue by ChengzhiHuang** [SwiftOldDriver/iOS-Weekly#4782]
# 推荐收录

## 链接

https://danielsaidi.com/blog/2024/11/04/xcode-stops-fetching-swift-packages

## 理由

Source Tree 表示... 

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Kyle-Ye** [comment]
上游有一个相关issue可以贴一下 https://github.com/swiftlang/swift-package-manager/issues/8068
和 Xcode 貌似没啥关系，单纯是 SwiftPM 里的 Git 相关代码没有适配 bare-repo

- https://github.com/swiftlang/swift-package-manager/pull/8106

**Comment by ChengzhiHuang** [comment]
这个上游的 issue 我一会直接提交更新文本
