### ISSUE TITLE
检测app网络情况的“app”

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#481]
https://github.com/agrinman/sift-ios

**Comment by iblacksun** [comment]
### [Sift app - 实时监测手机所有 App 的网络情况](https://github.com/agrinman/sift-ios)

Sift 是一个开源 App，可以监测手机上的所有网络请求，根据规则屏蔽请求，最重要的是：可以作为调试工具，在手机上实时看自己 App 的网络连接状态。
