### ISSUE TITLE
Alex Sidebar：The Cursor for Xcode

### ISSUE THREAD

**Issue by faimin** [SwiftOldDriver/iOS-Weekly#4816]
# 推荐收录

## 链接

https://alexsidebar.app/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ChengzhiHuang** [comment]
This tool is free in beta , we don't know if it will be charged in future. We recommand the free tools. So maybe waiting for follow-up charging information later.
