### ISSUE TITLE
介绍了base 64 的一些知识

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#482]
https://liudanking.com/sitelog/%E9%AD%94%E9%AC%BC%E5%9C%A8%E7%BB%86%E8%8A%82%E4%B8%AD%EF%BC%9Abase64-%E4%BD%A0%E5%8F%AF%E8%83%BD%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84%E5%87%A0%E4%B8%AA%E7%BB%86%E8%8A%82/

**Comment by 100mango** [comment]
本文对Base64做了一定的深挖。但是比较狭窄，适合Google时搜到作为参考，不需要加到周报中。
