### ISSUE TITLE
Skip: Build native apps for iPhone and Android with Skip

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4821]
# 推荐收录

## 链接

https://skip.tools

## 理由

> Skip brings Swift app development to Android. It is a tool that enables developers to use a single modern programming language (Swift) and first-class development environment (Xcode) to build genuinely native apps for both iOS and Android.

只要活得久，什么事情都能见到...

**Comment by ChengzhiHuang** [comment]
这玩意靠谱吗（
