### ISSUE TITLE
MetalLibraryExplorer

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#4825]
# 推荐收录

## 链接

https://github.com/YuAo/MetalLibraryArchive?tab=readme-ov-file

## 推荐理由

online demo: https://yuao.me/MetalLibraryExplorer/

**Comment by ChengzhiHuang** [comment]
你别说，前段时间我也用过这个...

主要用来看 metalib 的版本，还挺好用的

**Comment by ChengzhiHuang** [comment]
还适合用来看生成的对不对

Metal 有一个坑的点在于，有些 API 不满足最低版本的时候，是不会在 compile 的时候报错的...只有 runtime 执行的时候才会出来（尴尬

![image](https://github.com/user-attachments/assets/0a2d9f29-9947-416f-959e-4e7f8e1809c9)

<img width="476" alt="image" src="https://github.com/user-attachments/assets/0067aad1-df40-4273-b6fe-2b6259a8b4c2" />
