### ISSUE TITLE
Parallel Programming with Swift: What could possibly go wrong?

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#483]
https://medium.com/flawless-app-stories/parallel-programming-with-swift-what-could-possibly-go-wrong-f5bcc38b1814

**Comment by raozhizhen** [comment]
文章讲述了使用 Swift 进行多线程操作，会产生的诸多问题。如非原子操作导致的数据在多个线程进行设置时，即不为线程 1 设置的值，也不为线程 2 设置的值。或者是因为 CPU 的乱序执行影响了不同线程的逻辑判断。你可以使用锁、内存屏障（Memory Barriers）、Dispatch Queues 来避免这些状况。使用锁的话又可能会产生死锁、活锁（Livelock）、线程饿死（Thread Starvation）等诸多问题。最后，你做了你能做的一切，但 Swift 编译器并不保证您的代码顺序得到保留，可能会导致您的同步机制出现其它的问题，也就是 Swift 本身并不是 100% 线程安全的。Apple 提供了一些调试并发操作的工具，如 Activity groups 和 Breadcrumbs，但它们暂时还不支持 Swift。
