### ISSUE TITLE
Zeplin 2.0 发布 — 引入组件模块

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#484]
https://zhuanlan.zhihu.com/p/38382742

**Comment by iblacksun** [comment]
### [Zeplin 2.0 发布 — 引入组件模块](https://zhuanlan.zhihu.com/p/38382742)

> Zeplin 2.0 发布，带来了全新的 Components 模块、 assets 重命名，全尺寸缩略图等诸多新特性。

随着产品思路的转变，在开发和设计过程中「组件」的有效管理变得越来越重要，而 Componets 模块要做的就是让设计师和工程师更好的共享这些组件。 Componets 模块可以将 Sketch 中的 Symbol 上传到 Zeplin，选中单个组件，数显面板会显示该组件被用于哪些 Screens。
