### ISSUE TITLE
Swift vs. Kotlin — the differences in memory management

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#487]
对比一下两个常见的内存管理机制还是挺有意思的
https://blog.indoorway.com/swift-vs-kotlin-the-differences-in-memory-management-860828edf8

**Comment by 100mango** [comment]
本文对比了 Kotlin 和 Swift 如何进行内存管理。Kotlin 使用了基于 CMS 算法的垃圾回收，而 Swift 则使用了 ARC。本文没有拘泥于过多底层细节，而是用平白的语言介绍了两者的区别。是一篇入门开发者也能阅读学习的文章。
