### ISSUE TITLE
Puppeteer best practices

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#489]
### 推荐收录 / 意见反馈

Puppeteer 是谷歌推出的 Chrome headless(无界面)浏览器，可以通过Puppeteer的提供的api直接控制Chrome模拟大部分用户操作来进行UI Test或者作为爬虫访问页面来收集数据。

#### 链接

https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html

#### 理由

本文介绍了作者的使用Puppeteer的一些经验。

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by Awhisper** [comment]
我们面向的人群 可能是移动端的开发，可能对大前端有兴趣，但这个是面向爬虫与浏览器机器人的开发，我们的受众群体感觉不太match，看的人不会太多吧，感觉
