### ISSUE TITLE
资源：The 50 Best Free Datasets for Machine Learning

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#491]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://gengo.ai/articles/the-50-best-free-datasets-for-machine-learning/

#### 理由

机器学习50个最佳免费数据集

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我觉得这个有点超纲了。我们目标用户应该大多数都用不到。
