### ISSUE TITLE
Fail-safe Algorithm for iOS DateFormatter

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#494]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://medium.com/ios-os-x-development/fail-safe-algorithm-for-ios-dateformatter-b59a1f8ebe52

#### 理由

如果网络请求失败的时候，有些时候我们可以为一些值的转换场景提供缺省值，但是有一些变量类型是很难表达的，譬如时间类型。本文提供了一种能够工作在任意场景下的时间格式转换算法

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我觉得这个实现也挺简单的，封装了一组时间格式。但是作为代码来讲，这种单纯贴一段代码的恐怕没人敢直接用。实际项目中时间的格式通常也没必要思考那么多场景。我觉得这篇的价值不大。

**Comment by mmoaay** [comment]
附议，且本期内容较多，不收录
