### ISSUE TITLE
What’s New in Swift 4.2?

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#495]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://www.raywenderlich.com/194066/whats-new-in-swift-4-2

#### 理由

《swift apprentice》的作者详细地介绍了swift4.2的各项特性，超级全面，附带code演示！

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
这个文章提到的内容其实 @kemchenj 写的和我原来转的一篇文章是差不多的。
四娘看一下要不要收进来。我个人认为意义不大。

**Comment by kemchenj** [comment]
@lacklock 我觉得可以不放，虽然这里面有一些东西提到的比较少，例如 SPM

**Comment by kemchenj** [comment]
### [What’s New in Swift 4.2?](https://www.raywenderlich.com/194066/whats-new-in-swift-4-2)

Raywenderlich 出品的 Swift 4.2 更新内容总结，功能示例代码非常齐全，而且还介绍了 SE-0193 跨模块内联函数的提案以及 SPM 的一些小更新就，目前已有的更新总结文章对于这两个方面提到的比较少，所以可以重点看一下这两个小节。
