### ISSUE TITLE
UITableView Infinite Scrolling Tutorial

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#499]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://www.raywenderlich.com/187041/uitableview-infinite-scrolling-tutorial

#### 理由

打造一个无线滚动的TableView

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我觉得这个简单了点

**Comment by 100mango** [comment]
本文是一篇新手向的文章。介绍了如何构造可无限滚动的 TableView。内容涉及了网络请求，TableView 基础知识。值得一提的是，本文使用了 iOS10后 引入的 Prefetching API，用于优化 TableView的性能和体验。
