### ISSUE TITLE
开源库：An Xcode playground demonstrating the new features in in Swift 4.2

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#501]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://github.com/ole/whats-new-in-swift-4-2

#### 理由

一个演示swfit4.2新特性的开源库

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by kemchenj** [comment]
### [Swift 4.2 功能 Playground 全展示](https://github.com/ole/whats-new-in-swift-4-2)

Ole Begemann 大神出品的 What's New in Swift 系列，使用 Playground 为我们展示 Swift 4.2 的所有新特性，让大家可以直接上手感受。需要注意的是，现在 Swift 4.2 还在开发中，大家要使用的话需要安装 Swift 4.2 的工具链或者使用 Xcode 10.0 beta。
