### ISSUE TITLE
WWDC2018：Introduction to Siri Shortcuts

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#502]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://medium.com/flawless-app-stories/wwdc-2018-for-ios-developers-siri-shortcuts-e8e4a78f0ad7

#### 理由

介绍了siri shortcuts的相关资料

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我们wwdc18专题里有人也写了这个话题。我觉得这篇没有比我们翻的那篇好。
