### ISSUE TITLE
追踪 Objective-C Block 代码定义的位置

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#503]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

http://yulingtianxia.com/blog/2018/06/24/Objective-C-Block-Mangle-Name/

#### 理由

本文通过 Mach-O 文件格式获取 Mangle Name 并根据 Clang 源码实现对其解析，探寻如何追踪 block 代码定义的位置

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by 100mango** [comment]
之前周报收录过一篇 [《追踪 Objective-C 方法中的 Block 参数对象》](http://yulingtianxia.com/blog/2018/03/31/Track-Block-Arguments-of-Objective-C-Method/)。本文则是在此基础上，通过 Mach-O 文件格式获取 Mangle Name 并根据 Clang 源码实现对其解析，探寻如何追踪 block 代码定义的位置。
