### ISSUE TITLE
如何利用Ryuk分析和挖掘macOS&iOS内核驱动漏洞

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#504]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://xzfile.aliyuncs.com/upload/zcon/2018/12_%E5%A6%82%E4%BD%95%E5%88%A9%E7%94%A8Ryuk%E5%88%86%E6%9E%90%E5%92%8C%E6%8C%96%E6%8E%98macOS%26iOS%E5%86%85%E6%A0%B8%E9%A9%B1%E5%8A%A8%E6%BC%8F%E6%B4%9E_%E7%99%BD%E5%B0%8F%E9%BE%99%26%E8%92%B8%E7%B1%B3.pdf

#### 理由

在苹果驱动中挖掘安全性漏洞并非易事，其主要原因在于苹果驱动多为闭源且大量使用面向对象编程。我们将分享一款自研的用于分析macOS及iOS内核驱动的静态分析工具Ryuk。Ryuk使用静态分析技术对苹果驱动的二进制代码进行解析，识别代码特征，能够极大地加速苹果驱动逆向和安全性分析流程，加快漏洞挖掘进程

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我觉得这个太偏了。
