### ISSUE TITLE
How to Integrate Your App with Files App in iOS 11

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#507]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://www.appcoda.com/files-app-integration/

#### 理由

本文演示了如何结合iOS 11的Files App进行调试

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by kemchenj** [comment]
### [如何在 iOS 11 里把你的 App 集成到 Files](https://www.appcoda.com/files-app-integration/)

iOS 11 里首次增加了文件管理器，让我们可以在手机和平板上更加方便地管理文件，并且提供了 API 让第三方应用集成到 Files App 里，如果你的 App 也像 Dropbox 或者 Office 那样重度依赖文件管理系统的话，那这篇文章就很适合你，作者通过 Demo 逐行代码带你走一遍接入流程，并且把过程中所有需要注意的点都非常详细地讲述了一遍，绝对是新手友好的一篇文章。
