### ISSUE TITLE
Integrating Google ML Kit in iOS for Face Detection, Text Recognition and Many More

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#509]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://www.appcoda.com/mlkit/

#### 理由

厌倦了Core ML的各种限制？Google ML可能会帮到你

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by kemchenj** [comment]
### [厌倦了Core ML？试试 Google ML](https://www.appcoda.com/mlkit/)

今年 Google I/O 上，发布了一款叫做 Google ML 的跨平台机器学习框架，最大的特点就是开箱即用，可以直接使用 Google 已经训练好的模型，包括表情识别，文字识别以及图片标识等等，感兴趣的同学可以看看这篇入门教学，写出属于你的 Not Hotdog 应用😏。
