### ISSUE TITLE
Introducing the !! "Unwrap or Die" operator to the Swift Standard Library

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#512]
#### 链接

https://github.com/apple/swift-evolution/blob/master/proposals/0217-bangbang.md

#### 理由

SE-0127 提案，加入 `!!` 操作符优化强制解包的错误提示，并且编译器也会偏向于让大家使用 `!!` 去解决 fix-it：

```swift
let url = URL(string: urlString) !! "Invalid url: \(urlString)"

// 等效于

guard let url = URL(string: urlString) else {
    fatalError("Invalid url: \(urlString)")
}
```

**Comment by lacklock** [comment]
我觉得提案没必要单独列进来，某个版本新特性的时候可以列出来说。是冗余的信息。
