### ISSUE TITLE
华为快应用引擎技术架构详解 

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#515]
https://mp.weixin.qq.com/s/JdNJifhpkGzd0VpLZhN6Eg

虽然是只有安卓平台，但对其引擎内核的研究有助于设计自研 跨平台类似RN 之类的框架

**Comment by iblacksun** [comment]
### 🐕 [华为快应用引擎技术架构详解](https://mp.weixin.qq.com/s/JdNJifhpkGzd0VpLZhN6Eg)

> 2018 年 3 月华为与小米，Oppo，Vivo 等 9 家手机厂商，联合发布快应用联盟标准。快应用是一种基于手机硬件平台的新型应用形态，无需安装，即点即用，又兼具原生应用体验（性能、系统整合、交互等）。

本文讲了华为快应用的技术架构，及通过「流式加载」来解决网络延时问题、「快照」解决首屏渲染问题。虽然都是安卓平台，但对其引擎内核的研究有助于自研或部署垮平台方案。
