### ISSUE TITLE
A look at UIView Animation Curves (Part 1)

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#516]
https://medium.com/@RobertGummesson/a-look-at-uiview-animation-curves-part-1-191d9e6de0ab?source=linkShare-c3db222ff891-1530585795

直观生动的简介了 几种动画曲线的效果

不是多复杂，但简单清晰明了

**Comment by olddonkey** [comment]
感觉可以和Part2, Part3一起，只有一个Part1内容有点不够

**Comment by lacklock** [comment]
你可以把part2、part3一起写进来。
