### ISSUE TITLE
Lottie 开源动画库

### ISSUE THREAD

**Issue by waterXu** [SwiftOldDriver/iOS-Weekly#523]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

https://github.com/airbnb/lottie-ios  开源库
 理由
让UE去实现复杂的动画，减少程序开发时间。最近在皮肤主题得应用上使用到，一套json应用不同主题颜色（需要自己额外在Lottie中实现刷色代码）

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
这个太知名了。没必要再提了。
