### ISSUE TITLE
腾讯社招iOS面试记录

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#531]
https://juejin.im/post/5b3c40f4e51d45191a0d0aae

**Comment by raozhizhen** [comment]
最新出炉的面试真题，一面常规基础问题，帮助你查漏补缺。二面聊项目，看完也可以回顾一下自的项目，是否对使用到的技术深入了解。很多人都觉得自己目前做的事情，只是没有提升的业务开发。但技术就是服务于业务的，业务也会推动技术去深入，你是否有成长，取决于你对技术的使用，问题的解决是浅尝辄止，还是层层深入，从原理层面理解技术，理解问题。
