### ISSUE TITLE
@autoclosure what, why and when

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#543]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://medium.com/ios-os-x-development/https-medium-com-pavelgnatyuk-autoclosure-what-why-and-when-swift-641dba585ece

#### 理由

@autoclosure使用指南

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by iblacksun** [comment]
### 🐎 [\@autoclosure what, why and when](https://medium.com/ios-os-x-development/https-medium-com-pavelgnatyuk-autoclosure-what-why-and-when-swift-641dba585ece)

Swift 真是门常用常新的语言，如果你之前没用过 `@autoclosure`(不是 `@autoreleasepool`)，我相信你看完本文后会说「哇，还能这样」。
