### ISSUE TITLE
iOS 界面性能优化浅析

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#544]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://coderzsq.github.io/2018/07/iOS-%E7%95%8C%E9%9D%A2%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E6%B5%85%E6%9E%90/

#### 理由

iOS性能优化心得分享

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by iblacksun** [comment]
### 🐕 [iOS 界面性能优化浅析](https://coderzsq.github.io/2018/07/iOS-%E7%95%8C%E9%9D%A2%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E6%B5%85%E6%9E%90/)

随着硬件升级及系统优化，日常开发中需要针对性的做性能优化的地方可能不多，但遇到问题时需要大量预备知识来应对。本文着重讲复杂页面的性能优化，包含了`布局预排版`、`重用池`、`图片预解码及预渲染`、`异步绘制`及在异步绘制实现时候遇到的坑，推荐阅读。
