### ISSUE TITLE
Two Years of Functional Programming in JavaScript: Lessons Learned

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#553]
https://hackernoon.com/two-years-of-functional-programming-in-javascript-lessons-learned-1851667c726

**Comment by 100mango** [comment]
本文的作者是一位有着十年以上开发经验的资深的工程师，本文是他在接触函数式编程两年后所获得的心得和体验。首次面对函数式编程应该如何入手；函数式编程的重点不在于`monads`等晦涩的概念，而在于编写简洁清晰，无副作用的函数；函数式编程在团队协作中应该如何看待；明白刚开始切换到函数式编程时的困难。作者对以上几点都做了很不错的分析和解答。这是一篇值得对函数式编程感兴趣的小伙伴们阅读的好文章。
