### ISSUE TITLE
Subclass-free view controllers in Swift

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#556]
https://www.swiftbysundell.com/posts/subclass-free-view-controllers-in-swift

**Comment by kemchenj** [comment]
### [减少 ViewController 的继承](https://www.swiftbysundell.com/posts/subclass-free-view-controllers-in-swift)

这周 Swift by Sundell 的文章尝试着不使用继承去写页面，一个 ViewController 对应一个页面已经成为我们常识，但我们很多时候其实并不需要那些 ViewController 相关的功能，尝试着打破这样常识是改善我们代码的开始。
