### ISSUE TITLE
Announcing Realm Cloud: Realm Platform as a Service Beta

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#56]
https://realm.io/blog/realm-cloud-beta-waitlist

**Comment by mmoaay** [comment]
### [Announcing Realm Cloud: Realm Platform as a Service Beta](https://realm.io/blog/realm-cloud-beta-waitlist/)

Realm 云服务新版本开始第一轮公测啦！只需要简单的配置即可接入，现在就来试试吧：[申请试用 Beta 版](https://cloud.realm.io/)，只有 500 个名额哦～申请通过的话还能以 5 折的价格购买 1 年的 Realm 云服务。
