### ISSUE TITLE
Advanced iOS Architecture: Solving the 5 Issues of the MVC, MVVM and VIPER patterns

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#563]
#### 链接

https://matteomanferdini.com/ios-architecture-lotus-mvc-pattern/

#### 理由
关于 iOS 架构的长文分析，文章指出了目前圈内流行架构的几点弊端，然后介绍了下自己的 Lotus MVC Pattern。

**Comment by iblacksun** [comment]
### 🌟🐢 [The Lotus MVC Pattern: Solving the 5 Issues of the MVC, MVVM and VIPER patterns](https://matteomanferdini.com/ios-architecture-lotus-mvc-pattern/)

> 长文宜细读。

这是一篇长文，作者分析了现有架构的优缺点，之后提出了自己的架构：Lotus MVC `(名称的由来是此架构下各模块之间的类图非常象莲花)`，文章大题分为三个部分：
- 现有 MVC、MVVM、VIPER 架构是怎么分层的，解决了哪些问题，但带来或还有哪些问题没解决；
- Lotus MVC 各模块的角色及关系；
- 通过 Github client app 来讲解 Lotus MVC。
