### ISSUE TITLE
CocoaDebug  (APP网络日志监控)

### ISSUE THREAD

**Issue by heibrother** [SwiftOldDriver/iOS-Weekly#565]
### 推荐收录 (截图)

[截图1](http://7sbo4v.com1.z0.glb.clouddn.com/11.jpg)
[截图2](http://7sbo4v.com1.z0.glb.clouddn.com/2.jpg)
[截图3](http://7sbo4v.com1.z0.glb.clouddn.com/3.jpg)
[截图4](http://7sbo4v.com1.z0.glb.clouddn.com/4.jpg)
[截图5](http://7sbo4v.com1.z0.glb.clouddn.com/5.jpg)
[截图6](http://7sbo4v.com1.z0.glb.clouddn.com/6.jpg)

#### 链接

https://github.com/CocoaDebug/CocoaDebug

#### 理由

一行代码实现APP网络日志监控，方便调试。

**Comment by olddonkey** [comment]
感觉相对来讲东西都不是很新的东西，DebugOverlay在iOS12中也不能用了，其他的功能在[GodEye](https://github.com/zixun/GodEye)中都已经实现过了，相对来讲可能重复性有点大。
