### ISSUE TITLE
CoreText 异步绘制封装推荐

### ISSUE THREAD

**Issue by syik** [SwiftOldDriver/iOS-Weekly#568]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://github.com/syik/ZJAttributedText

#### 理由

高性能+功能强大+使用简单, 解决了iOS中图混的痛点, 大佬可以帮忙宣传下

#### 意见反馈（可选）

老铁周报给力 LOL

**Comment by 100mango** [comment]
ZJAttributedText 是一个富文本框架。和YYText对比起来，更轻量级，并且能通过链式调用进行富文本的样式编辑。
