### ISSUE TITLE
Swift HTTP Server 开发体验

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#579]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

http://posts.enumsblog.com/posts/18014

#### 理由

Swift HTTP Server 开发体验

**Comment by iblacksun** [comment]
### 🐕 [Swift HTTP Server 开发体验](http://posts.enumsblog.com/posts/18014)

从 Swift 开源并支持 Linux 运行之后，Swift Server API 趋热，先后出现了 `Perfect`、`Vapor`、`Kitura` 和 `Zewo` 几个框架。

本文作者使用 `Perfect` 开发了一个 `以 MySQL 和 HDFS 作为支撑，应用了包含 Web 服务、JSON 接口服务、以及基于 Socket 的文件传输和视频直播流服务的项目` 给大家讲解开发体验及部署过程，并介绍如何接入第三方服务(以 `MySQL` 和 `HDFS` 举例)。
