### ISSUE TITLE
Writing backward compatible Swift code

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#581]
#### 链接
https://www.swiftbysundell.com/posts/writing-backward-compatible-swift-code

#### 理由
编写兼容性和扩展性更好的 Swift 代码。

**Comment by kemchenj** [comment]
### 让你的 Swift 代码保持良好的向后兼容性

重构是代码构建过程中不可避免的一个阶段，尽可能保持 API 的稳定对于平稳的迁移是一件很重要的事情，这周的 Swift Sundell 就介绍了在 Swift 里如何书写向后兼容的代码，Swift 由于其良好的语法设计，可以在修改接口的同时保持语法的向后兼容性，这篇文章里挖掘了很多相关的语法特性，强烈推荐大家阅读！！！
