### ISSUE TITLE
Password Rules / UIText​Input​Password​Rules

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#583]
#### 链接

https://nshipster.com/uitextinputpasswordrules/

#### 理由

NSHisper 复更后的第二篇，iOS 12 里引入了自动填充密码的功能，所以顺带给 `UITextInput` 加入了 `passwordRules` 的 API 以便我们自定义自动生成的密码的规则，例如长度，非法字符等等，但这个 API 是 String Base 的：

```swift
UITextInputPasswordRules(descriptor: "required: upper; required: lower; required: digit; max-consecutive: 2; minlength: 8;")
```

NSHisper 这篇文章就教我们如何使用更加安全的枚举形式去改造这一套 API：

```swift
let rules: [PasswordRule] = [
    .required(.upper),
    .required(.lower),
    .required(.special),
    .minLength(20)
]
```

**Comment by raozhizhen** [comment]
自 iOS 8 以来，Safari AutoFill 已经能够生成随机密码，但只能生成字符加数字（顶多中间补点横杠）。Apple 在 iOS 12 中的  Automatic Strong Passwords 解决了这个问题，其中包括一个新的 UITextInputPasswordRules API，以及其他一些密码管理功能，包括验证码自动填充和联合身份验证。UITextInputPasswordRules API 可以用来指定服务需要的特定密码规则，例如必须的字符种类、允许的字符种类、允许的最大连续字符数、最小密码长度、最大密码长度。但这个 API 是 String Base  的，NSHisper 这篇文章就以更加安全的枚举形式去改造这一套 API。
