### ISSUE TITLE
articles-zh-Hans for NSHipster

### ISSUE THREAD

**Issue by faimin** [SwiftOldDriver/iOS-Weekly#584]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

[https://github.com/NSHipster/articles-zh-Hans](https://github.com/NSHipster/articles-zh-Hans)

#### 理由

@mattt 大佬把 [NSHipster.cn](https://nshipster.cn/) 里文章整理到了这里，[NSHipster](https://nshipster.com/) 网站已经重启，后续应该会有新的翻译自 [nshipster.com](https://nshipster.com/) 的文章放到这里，推荐关注，希望有能力和精力的朋友提 `pr`。

**Comment by mattt** [comment]
NSHipster.cn 团队很高兴再次发表新文章。 感谢您的耐心和支持。 谢谢！
/cc @croath @rickytan @aprilnov @skyline75489 @LiLejia

**Comment by lacklock** [comment]
@mattt @faimin we'll add this to this weekly report.
