### ISSUE TITLE
Better iOS projects: Getting (nearly) rid of Xcodeproject - A (not so) short Introduction to Xcodegen

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#587]
https://www.number42.de/blog/2018/07/24/xcodegen-article.html

利用xcode gen生成project项目

**Comment by 100mango** [comment]
在我们日常开发中，绝大部分情况都是手动创建和维护`.xcodeproj`文件。但是在团队开发中，我们经常需要处理项目文件冲突，维护`target`之间依赖也是一件比较麻烦的事情。本文则是介绍了`Xcodegen`这一工具。通过创建一个描述文件，就可以自动生成项目文件，和管理依赖。
