### ISSUE TITLE
关于内容的收集提个想法供讨论

### ISSUE THREAD

**Issue by Josscii** [SwiftOldDriver/iOS-Weekly#59]
不知道老司机们是如何收集内容的呢？如果是人工的话，我这里提个想法。
最容易输出技术内容的地方不过那么几个，微博、GitHub、推特、微信公众号等。能不能写点程序自动抓取这些内容输出地比较热门的内容呢？
我之前在做毕设的时候干过这样一件事，微博和推特可以用一个专门用来抓取内容的账号，这个账号关注 iOS 圈子里面的老司机，最容易输出内容和有影响力的人，然后每天定时抓取转发数到一定量的微博进数据库，最后周末的时候就可以愉快的筛选啦。GitHub 的话最简单了，因为有趋势榜单的 API 嘛。微信公众号是最难的，不好解决。当然人工的推荐也可以作为补充嘛。
可以讨论一下。

**Comment by lacklock** [comment]
感谢你的热心反馈。你会这样思考问题很好，有优秀程序员的潜质。

我们的目标不是收集一周里最全的资讯，而是根据我们的经验、品味筛选出我们认为有价值的东西。

所以如果有一篇没人注意到的文章，我们看到了觉得不错会把它推出来。单纯的一份本周热门点击文章的对我们筛选的作用不大。

这篇周报是我们几个编辑在学习 iOS 过程中副产品。因为我们平时也会关注很多 iOS 的资料，所以我们的方式就是把我们平时觉得有价值的信息收录进来，我们一起讨论筛选。我们现在有7个编辑，可以认为是7个乐于学习分享的程序员总结的过去一周值得关注的信息。
