### ISSUE TITLE
JSON Web Token 入门教程

### ISSUE THREAD

**Issue by iblacksun** [SwiftOldDriver/iOS-Weekly#595]
#### 链接

http://www.ruanyifeng.com/blog/2018/07/json_web_token-tutorial.html

#### 理由

通用知识。

**Comment by raozhizhen** [comment]
JSON Web Token（缩写 JWT）是目前最流行的跨域认证解决方案，本文主要是介绍它的原理和用法。

对于用户认证来说，用户的 session 数据如果存在服务端，那对于服务器集群，或者是跨域的服务导向架构。session 数据的共享，会是一个比较麻烦的问题。 JWT 方案则是将不可篡改的 session 数据储存到客户端，每次请求再将 session 数据发回给服务端进行用户认证。不同服务器之间，不再需要进行 session 数据贡献，比较容易实现扩展。
