### ISSUE TITLE
推荐一个在iOS上使用XML+MVVM来开发的库

### ISSUE THREAD

**Issue by ghwghw4** [SwiftOldDriver/iOS-Weekly#598]
#### 链接

项目连接：https://github.com/ghwghw4/GICXMLLayout

在线文档连接：http://gicxmllayout.gonghaiwei.cn/index.html

#### 理由

一款基于`Texture`开发的可以使用XML+MVVM开发的类库，支持数据绑定、动画、后台解析布局渲染以及优秀的自定义能力,提供强大的布局系统(支持flex布局)，这个库在使用xml来写ui的地方做了较多的创新，并且拥有非常优秀的性能表现。使用该工具，您可以直接以XML来写界面(包括动画)，以数据绑定(提供有多种绑定模式可选)的方式来显示数据，提供了`模板`功能实现类似`h5`中模板替换的能力，在开发iOS界面变得非常的方便。该库也提供了非常优秀的自定义能力，可以较容易的扩展出你自己的UI库，使得这些UI、功能可以直接使用xml来写。该库也支持部分替换，也就是说无需整个项目、整个页面的升级改造，你甚至可以只针对项目中的某个页面的某个View单独替换，这样也就可以最小代价对现有项目进行改造。

**Comment by 100mango** [comment]
@ghwghw4 这个项目有在什么地方使用过么？需要阐述一下，为什么程序员不使用 RN, Weex。 或直接用 Yogakit 等布局工具。

**Comment by ghwghw4** [comment]
这个库在设计之初参考了多个语言平台、技术点，虽不能说博采众长，但也耗费了相当多的心血。该库是我个人所写，希望能为国内iOS的开源事业做一份贡献。谢谢




| |
龚海伟
邮箱：dagehaoshuang@163.com
|

签名由 网易邮箱大师 定制

在2018年08月05日 23:19，海伟 写道：
GICXMLlayout的底层布局是基于Texture实现的，而当结合了XML后，就可以使得原本为了实现一个布局需要写N多代码，通过xml只需几行xml代码就能实现，而且GIC的xml不仅仅只是布局，还可以直接写动画，另外也提供了强大的数据绑定支持，使得可以使用像h5那样mvvm模式来开发iOS程序，直接以数据来驱动view的显示，在viewmodel中几乎不需要关心UI，只需要关注数据即可。相对于RN、Weex等跨平台的库来说，GIC是专门为了iOS开发的，出发点就是简化iOS的UI开发，并且提供MVVM的支持。因为是采用xml来写ui，也就意味着，可以支持ui的远程更新，而且因为GIC支持使用模版的方式来自定义UI，因此你可以直接使用xml来定义一些通用的UI，最新版本已经支持样式了，也就意味着可以直接使用xml样式文件来定义app的主题。另外由于gic中布局以及UI元素是基于Texture库开发的，因此天生就具有优秀的性能，这个可以直接在sample中的模拟今日头条feeds那一个例子中就能看到。下一版更新中更会加入router以及canvas的支持。目前该库刚刚开源，并没有被其他公司使用，只在我目前所在的公司中使用！




| |
龚海伟
邮箱：dagehaoshuang@163.com
|

签名由 网易邮箱大师 定制

在2018年08月05日 22:46，100mango 写道：

@ghwghw4 这个项目有在什么地方使用过么？需要阐述一下，为什么程序员不使用 RN, Weex。 或直接用 Yogakit 等布局工具。

**Comment by tom510230** [comment]
有几个顾虑
1、现代新型的库，除非特殊原因，不然应该都是基于Swift构建或者至少支持Swift混编
2、你的开源库缺少BenchMark
3、你的开源库缺少相关Tests
4、你的库依赖的东西太多，RAC+Texture+pop，对于使用者是个极大的负担
5、缺少UICollectionView的封装

推荐你参考一下https://github.com/schibsted/layout

**Comment by ghwghw4** [comment]
您提到的这几个顾虑确实会有一定的影响，但是我个人也在考虑完善中。除了第4点短时间内无法解决以外，其他四点可以解决。目前库也在不断的完善中，会不断点加入新功能，gic本身有较优秀点自定义能力，使用者可以很方便的扩展出自己想要的功能，相对于RN、Weex来说，自定义这块的成本更低




| |
龚海伟
邮箱：dagehaoshuang@163.com
|

签名由 网易邮箱大师 定制

在2018年08月06日 05:38，tom510230 写道：

有几个顾虑
1、现代新型的库，除非特殊原因，不然应该都是基于Swift构建或者至少支持Swift混编
2、你的开源库缺少BenchMark
3、你的开源库缺少相关Tests
4、你的库依赖的东西太多，RAC+Texture+pop，对于使用者是个极大的负担
5、缺少UICollectionView的封装

推荐你参考一下https://github.com/schibsted/layout

**Comment by tom510230** [comment]
嗯嗯，那等你完善了以后我们再来review一下？

**Comment by lacklock** [comment]
感谢分享，我已经发微博介绍了这个库。
我能看出你对这个库做出的努力，封装Texture+RAC+pop，也要求过硬的技术能力。
但是目前不收录的原因主要有两个：
- 它还不够完善，因为较为复杂的技术栈，出了问题使用者不能快速的调试，所以需要有一段时间的验证
- 这个库要解决的问题比较小众
所以希望这个库在未来更加完善后我们会考虑加进去。希望到时候可以reopen这个issue。
