### ISSUE TITLE
一个可以将 JSON 转成 Swift、Objective-C 代码的 Xcode Extension

### ISSUE THREAD

**Issue by ShannonChenCHN** [SwiftOldDriver/iOS-Weekly#60]
[quicktype/quicktype-xcode](https://github.com/quicktype/quicktype-xcode)：一个可以将 JSON 数据转成 Swift, Obj-C, Obj-C++, Java 代码的 Xcode Extension。

补充：Objective-C support 正在开发调试阶段，由于作者不太了解 Objective-C 语法，所以还需要我们的帮助。

**Comment by kemchenj** [comment]
> # [老司机 iOS 周报 #2](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%232.md) 
> 
> ...
>
> ### quicktype
>
> quicktype 可以根据给出的 JSON 数据推断出数据类型，然后输出具体的类型模型，支持 Swift、C++、Go、Java、C# 等语言。支持 Xcode 9，使用得当可以给我们的开发带来一定的便利。
> 
> ...

@ShannonChenCHN  这个工具在第二期里已经提过了
