### ISSUE TITLE
Swift 4 弱引用实现

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#603]
#### 链接

https://swift.gg/2018/08/02/swift-4-weak-references/

#### 理由

Friday QA 的其中一篇，2015 年的时候其实 Mike Ash 就已经介绍过 Swift 弱引用的实现了，这次 Swift 4.0 的对象内存布局做了一些调整，加入了 side table 去存放额外的对象信息，改变了弱引用的实现，并且对 Objective-C 和 Swift 4 之前的旧实现做了对比分析。

文末还简单介绍了 side table 的应用前景，可以在不破坏 ABI 的同时，让对象存放更多信息，未来 Swift 一些功能拓展很可能都会依赖于 side table 去实现，例如在 extension 里声明存储属性(stored property)。

BTW，Mike Ash 写这篇文章的时候还是 Swift 爱好者，现在已经是 Swift 团队的一员了

**Comment by iblacksun** [comment]
### 🐕 [Swift 4 弱引用实现](https://swift.gg/2018/08/02/swift-4-weak-references/)

> 原文作者 Mike Ash，是知名博客 [Friday Q&A](https://www.mikeash.com/pyblog/) 作者，现在是 Swift 团队一员。

2015 年的时候 Mike Ash 就已经介绍过 Swift 弱引用的实现了，这次 Swift 4.0 的对象内存布局做了一些调整，加入了 side table 去存放额外的对象信息，改变了弱引用的实现。文章还对 Objective-C 和 Swift 4 之前的旧实现做了对比分析。
