### ISSUE TITLE
帮助 Perfect 加速 Server Side Swift 开发

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#605]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://perfectaccelerators.github.io
https://github.com/PerfectAccelerators/PerfectAccelerators.github.io

#### 理由

有一组 Swift Perfect 封装库，可以帮助使用 Perfect 加速 Server Side Swift 开发

**Comment by iblacksun** [comment]
### [PerfectAccelerators - 加速 Perfect Server Side Swift 开发](https://github.com/PerfectAccelerators/PerfectAccelerators.github.io)

上期我们推荐了篇文章[介绍 Perfect 开发体验](http://posts.enumsblog.com/posts/18014)，这次，给大家推荐一组 Perfect 封装库，可以帮助 Perfect 加速 Server Side Swift 开发。
