### ISSUE TITLE
iOS 11 对WKWebView的新增API

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#61]
http://www.cnblogs.com/zhanggui/p/8260136.html

新增了cookie操作，解决了WKWebView以前的大麻烦，
规则过滤，卓同学写过一篇说这个的
WK不支持的URLProtocol的某种程度的代替品 WKURLSchemeTask 与 WKURLSchemeHandler

这个O么？第一次提

**Comment by iblacksun** [comment]
+1，能写下摘要么？ @Awhisper

**Comment by Awhisper** [comment]
@iblacksun  好的  我先深入了解一下后2个东西 然后写摘要，还不太熟

**Comment by Awhisper** [comment]
介绍了三个iOS11下WKWebView的新增API：
1）WKHTTPCookieStore 操作CookieAPI，解决了WKWebView过去只能通过JS注入，修改Request2种trick方式操作cookie的问题
2）WKContentRuleListStore 内容过滤API，可以用来设立规则后过滤广告加载，早先开放给了SafariExtension，现在开放给了WKWebView
3）WKURLSchemeHandler 协议拦截API，NSURLProtocol在WKWebView失效了，开放了自定义协议头拦截API，只支持自定义协议头，但可以实现与NSURLProtocol一样的拦截后加载经过本地处理后的资源

**Comment by lacklock** [comment]
其实我挺怀疑的。这个里面的内容都来自哪个session，如果翻译的话这个节点感觉也过去了？

**Comment by Awhisper** [comment]
@lacklock 出发点确实不是新东西出来后的翻译新东西╮(╯_╰)╭ 就是最近在做，翻WKWebView相关的东西看到感觉有用，刚出iOS11的时候看这些api那会还没啥感觉看完就完了

**Comment by lacklock** [comment]
@Awhisper ok，既然你看了觉得有用就写进去好了。

**Comment by iblacksun** [comment]
@Awhisper 你好，建议对摘要进行组织下，使其更具可读性，然后添加到 #4.md ，提一个 pull request.
