### ISSUE TITLE
面试中的个人竞争力

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#611]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://xiaozhuanlan.com/topic/3670248951

小专栏的，最近小桦约稿写的

#### 理由

[此处填写您的推荐理由]

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by raozhizhen** [comment]
很多人都觉得自己没有竞争力，那相信这篇专栏会戳到你的痛点，找工作是不可能的，这辈子都不可能找工作，算法又不会，原理又不懂，只能做一个 github 的搬运工，才能维持会写代码的样子。
这篇专栏，教你如何通过简历展现个人竞争力。挑重点，用最简洁的篇幅，展现出你个人独一无二的亮点。也教你如何在面试中体现竞争力，多展现自己的思考过程，思考的深度。也是给你增加个人竞争力提供方向，就算是再平凡的工作，也能通过发现问题，探寻本源，自驱优化来锻炼自己，提升竞争力，从而赢得好机会的青睐。

**Comment by raozhizhen** [comment]
很多人都觉得自己没有竞争力，那相信这篇专栏会戳到你的痛点，找工作是不可能的，这辈子都不可能找工作，算法又不会，原理又不懂，只能做一个 github 的搬运工，才能维持会写代码的样子。
写简历要挑重点，用最简洁的篇幅，展现出你个人独一无二的亮点。面试需要多展现自己的思考过程，思考的深度。但这一切都基于过去的积累，就算是再平凡的工作，也能通过发现问题，探寻本源，自驱优化来锻炼自己，提升竞争力，从而赢得好机会的青睐。
