### ISSUE TITLE
由 NSObject *obj = [[NSObject alloc] init] 引发的一二事儿

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#614]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://juejin.im/post/5b63b857e51d455f5f4d1d74

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by iblacksun** [comment]
### 🐕 [由 NSObject \*obj = \[\[NSObject alloc\] init\] 引发的一二事儿](https://juejin.im/post/5b63b857e51d455f5f4d1d74)

这是一篇随想类型的文章，由 `[[NSObject alloc] init]` 开始讲起，覆盖了 Objective-C 内存分配、ARC、`@property`、`atomic` 等，看的过程遇到不是很清晰的知识点建议另找资料细读。
