### ISSUE TITLE
Building Fluid Interfaces

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#622]
https://medium.com/@nathangitter/building-fluid-interfaces-ios-swift-9732bb934bf5

**Comment by kemchenj** [comment]
### [构建流畅的人机交互](
https://medium.com/@nathangitter/building-fluid-interfaces-ios-swift-9732bb934bf5)

今年 iOS 花了很大的功夫在优化系统基础体验上，甚至在 WWDC 里专门开一个 session 来讲如何构建流畅的人机交互。这篇文章的作者在看了这个 session 之后有感而发写了这篇文章，在介绍和总结 session 内容的同时，还动手通过代码实现了那些 Design Tips，里面特定交互的最佳实现和动画实现的思路都非常棒，推荐一看。
