### ISSUE TITLE
ScrollingStackViewController

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#623]
https://github.com/justeat/ScrollingStackViewController

**Comment by Damonvvong** [comment]
这个库有几个问题

- 1. 关键字滥用。都是public。其实有一个属性没必要放出来
- 2. 并不是 UITableView 的替代。首先没有看到复用的地方，其次一个 card 是一个 ViewController 这也很奇怪。从我的理解上知识一个 UIStackView 的封装功能。实用性不高，因为 UIStackView 性能上还是有一些缺陷。

不建议放到 周报。我先关掉了
