### ISSUE TITLE
[32期]Migrating an Objective-C class to Swift using subclassing

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#628]
#### 链接
https://oleb.net/2018/objc-swift-subclassing/

#### 理由
30期周报中 [Migrating an Objective-C class to Swift: a piecemeal approach](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%2330-2018.08.06.md#-migrating-an-objective-c-class-to-swift-a-piecemeal-approach) 的续篇

**Comment by kemchenj** [comment]
### [把 Objective-C 类迁移到 Swift](https://oleb.net/2018/objc-swift-transition/)

30 期周报中 [Migrating an Objective-C class to Swift](
https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%2330-2018.08.06.md#-migrating-an-objective-c-class-to-swift-a-piecemeal-approach) 的续篇，在重构的同时保持原有功能并且继续添砖加瓦，除了 extension 之外最显而易见的方法就是继承，逐渐把 Objective-C 类的抽象挪到 Swift 类里就可以平滑地完成迁移，其中的优劣势可以看 Ole 给你细细分析。
