### ISSUE TITLE
最亲民的HomeKit：用Siri控制米家智能硬件

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#630]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://weibo.com/ttarticle/p/show?id=2309404272655489441995

#### 理由

这篇不算太技术，但是苹果设备用户如果想体验智能家居，可以参考。。

这个合适不合适大家看看？？

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by iblacksun** [comment]
我觉得可以。

**Comment by lacklock** [comment]
我打不开这个链接了。被删掉了？
