### ISSUE TITLE
把地址转为对应的emoji

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#636]
https://gist.github.com/cellularmitosis/d425aae5f1a2e5d9bfa1d4c1a5968d22
调试时也许有的用

**Comment by iblacksun** [comment]
### [可视化调试时将指针地址转为 emoji](https://gist.github.com/cellularmitosis/d425aae5f1a2e5d9bfa1d4c1a5968d22)

我们调试时经常需要判断两个变量是否是同一个实例，然而大部分时候 `po obj` 只能得到得到一串内存地址，需要人眼去比对。这个 gist 扩展了 `NSObject`，使得 `print obj.asPointer.asEmoji` 可以打印出 emoji 字符(比如 🌰)，而不是指针地址。
