### ISSUE TITLE
Scalable bulleted lists with UILabel or UITextView

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#640]
https://bendodson.com/weblog/2018/08/09/bulleted-lists-with-uilabel
用uilabel列表item

**Comment by raozhizhen** [comment]
一个使用 UILabel 实现段落样式的范例，主要是通过一个 NSParagraphStyle 的 headIndent 属性来完成整体段落缩进（首行除外）。
