### ISSUE TITLE
Hook static initializers

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#646]
#### 链接

https://mp.weixin.qq.com/s/5XnO5tWXK5pTtbOkPbluzw

#### 理由

在做 App 启动性能深度优化的时候，不管是静态库的链接还是动态库的加载，都需要执行到 `C++ static initializers and C/C++ __attribute__(constructor) functions`，那么我们就有必要去关注这些方法所消耗的时间了。本文介绍了如何去 hook 这些方法。

**Comment by ParsifalC** [comment]
建议与 #643 一起作为一栏推荐。

**Comment by SnailLife** [comment]
公众号被迁移 没新链接麻

**Comment by ParsifalC** [comment]
> 公众号被迁移 没新链接麻

直接点击访问文章即可。
