### ISSUE TITLE
schedule：swift timer

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#652]
https://github.com/jianstm/Schedule/blob/master/README.zh_cn.md

**Comment by 100mango** [comment]
Schedule 是一个轻量级的定时任务框架，提供了许多友好语法供开发者执行定时任务。 我们可以从下面这行代码一窥这个库的用法。

~~~swift
Schedule.every(.monday, .tuesday).at("9:00:00").do { }
~~~
