### ISSUE TITLE
[译] 构建流畅的交互界面

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#655]
https://juejin.im/post/5b7e2b34e51d4538843612cc

**Comment by lacklock** [comment]
#622 里文章的翻译

**Comment by kemchenj** [comment]
### [[译]构建流畅的交互界面](https://juejin.im/post/5b7e2b34e51d4538843612cc)

> 今年 iOS 花了很大的功夫在优化系统基础体验上，甚至在 WWDC 里专门开一个 session 来讲如何构建流畅的人机交互。这篇文章的作者在看了这个 session 之后有感而发写了这篇文章，在介绍和总结 session 内容的同时，还动手通过代码实现了那些 Design Tips，里面特定交互的最佳实现和动画实现的思路都非常棒，推荐一看。
>
> -- [#31 构建流畅的人机交互](https://github.com/SwiftOldDriver/iOS-Weekly/blob/master/Reports/%2331-2018.08.13.md#-构建流畅的人机交互) 

31 期里提到的文章`构建流畅的交互界面`通过掘金计划进行了翻译，如果是因为英文而错过了这篇文章的朋友，这次可以毫无负担地进行阅读了。
