### ISSUE TITLE
小程序全局状态管理

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#661]
### 推荐收录 / 意见反馈

自己动手实现一个小程序里的状态管理，官方有个 wxapp-redux 会比这个复杂一些，这个有助于自己理解学习

#### 链接

https://juejin.im/post/5b7643bf6fb9a009a9294af7

#### 理由

[此处填写您的推荐理由]

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by lacklock** [comment]
我觉得这个文章跟我们的读者不太匹配。不太用的上。

**Comment by iblacksun** [comment]
看了一遍，感觉没推荐的必要，小程序开发现在都有一些成熟的框架(wepy 等)，不用这么初始的方式实现状态管理。
