### ISSUE TITLE
手把手教你查看和分析 iOS 的 crash 崩溃异常

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#662]
#### 链接

https://www.jianshu.com/p/cf0945f9c1f8

#### 理由

一篇非常细致的分析 crash 崩溃方法介绍的文章，除了看第三方的闪退日志，在碰到一些毫无头绪的闪退日志时，可以尝试文中的方法。

**Comment by iblacksun** [comment]
### 🐢 [手把手教你查看和分析 iOS 的 crash 崩溃异常](https://www.jianshu.com/p/cf0945f9c1f8)

我们开发的 App 不可避免会出现闪退，可以通过集成一些第三方的闪退收集系统或 iTunesConnect 自身来收集闪退日志。有了闪退日志之后，并不是所有闪退都能快速的定位解决，特别是没有明确上下文或者没有一个函数或者方法能够被直接定位到源代码的场景，本文介绍面对这类闪退的几种可行办法，特别是通过寄存器及汇编代码来定位问题。
