### ISSUE TITLE
软件工程师需要了解的网络知识：从铜线到HTTP

### ISSUE THREAD

**Issue by darren1192** [SwiftOldDriver/iOS-Weekly#665]
### 推荐收录 / 意见反馈

请将您认为的有价值的信息、资讯、文章、工具、代码、音视频资料等以链接的形式提交给我们，我们会尽快处理。记得写上推荐的理由哦。如果有任何意见或建议也可以提交给我们，按下方对应提示填写即可，♥

#### 链接

https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/485.html
https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/486.html
https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/487.html
https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/488.html
https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/489.html

#### 理由

吕文翰大佬关于HTTP的文章，值得一读。

#### 意见反馈（可选）

[此处填写您对我们周报的意见或建议]

**Comment by Damonvvong** [comment]
首先，感谢你提供文章推荐。有几个问题我们可以探讨一下：

我认为周报更适合碎片化阅读，不太适合这种一系列的文章。

另外，文章已经是收入过了，所以有必要再推一次吗？

最后，理由是不是可以再详细一点，比如和其他相关话题的文章，有什么特殊之处？亦或者内容比较适合读者？

**Comment by lacklock** [comment]
@Damonvvong 不能假设过去每一篇我们写过的文章读者都看了。不知道也合理。
我们也从来说过周报针对的是碎片化阅读，实际上也没有。每篇文章标明大概阅读时间后，怎么阅读是读者自己的事。
