### ISSUE TITLE
Objective-C: 写一份可测试的代码

### ISSUE THREAD

**Issue by Dywane** [SwiftOldDriver/iOS-Weekly#669]
# 推荐收录
我针对OC如何编写一份可测试代码的同时，保持良好的可理解性上的一些建议，另外也提到在测试上的一些问题。

## 链接

[Objective-C: 写一份可测试的代码](https://juejin.im/post/5b87532be51d4538e6333dd0)

## 理由

对于单元测试很多人可能不理解，同时在OC上应用IoC、依赖注入等可能会导致代码复杂而难以理解，所以我针对如何在保持代码可读性的基础上，展开代码可测试性的重构，希望大家都能够写出少bug可测试的代码。

**Comment by 100mango** [comment]
本文介绍了如何编写一份可测试的代码。主要阐述了依赖注入，最小知识原则和单例在编写可测试性代码中扮演的角色，如何运用好它们来写出可读性和可测试性并存的代码。
