### ISSUE TITLE
Swift Unwrapped #42 Conditional Conformance

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#67]
https://spec.fm/podcasts/swift-unwrapped/105029

**Comment by lacklock** [comment]
https://swift.org/blog/conditional-conformance 官网的这篇博客可能也要带一下？

**Comment by kemchenj** [comment]
### [Swift Unwrapped #42 Conditional Conformance](https://spec.fm/podcasts/swift-unwrapped/105029)

这期很简短，只是简单地讲了一下 Conditional Conformance，之前 Ole 大神发过一篇文章讲了如何查看 Swift 源码，里面讲到了一个代码生成工具 gyb，主要是为了解决 Swift 泛型能力不足的问题，现在实现了 Conditional Conformance 之后就可以重构掉之前很大一部分 gyb 代码。并且**单单只是重构掉 Slice 类型，就已经让 Swift 标准库的二进制文件缩小了 5% 😱**，真是越来越期待 Swift 4.1 的发布了！！！

**Comment by kemchenj** [comment]
@lacklock 官方这篇挺硬核的，感觉会看的人自然会看，不会看的人介绍了也不会看，而且这篇东西的简介想要写的比较有营养还挺难的

**Comment by lacklock** [comment]
@kemchenj 那就在这个介绍里当做关联资料把官网的链接一起写进去。不用单独介绍了。
