### ISSUE TITLE
闲聊 Flutter

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#677]
http://blog.cnbang.net/tech/3605/

**Comment by raozhizhen** [comment]
跨平台一直是大家前赴后继不断追求的目标，原本 web 作为跨平台的解决方案很完美，但历史代码的兼容、CSS 过于复杂、DOM 接口粒度大等问题，造成 Web 技术下的跨平台方案有较明显的性能问题。而 Flutter 基于一个精简版的 web 引擎，抛弃兼容性，只保留主要功能，性能较前者快了不少。虽然 Flutter 还有包大小、缺乏动态性等问题，但一个完整的比 webkit 简单的多的引擎，源码很值得挖掘学习。
