### ISSUE TITLE
UI Test Automation: Speed Up Mobile App UI Testing with Appium

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#678]
https://www.appcoda.com/automated-ui-testing-appium/

**Comment by kemchenj** [comment]
## [UI 自动化测试：通过 Appium 加速你的客户端 UI 测试](https://www.appcoda.com/automated-ui-testing-appium/)

这篇文章里介绍了如何使用 Appium 编写一个完整的 UI 测试用例，Appium 是一个开源的 UI 测试框架，并且暴露出一套完整的 REST API 去完成测试操作，支持 iOS 和 Android，使用 Appium 编写测试时有多种语言可以选择，例如 Ruby，Python 等等。
