### ISSUE TITLE
How to effectively refactor MVC code and add unit tests

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#679]
https://clean-swift.com/how-to-effectively-refactor-mvc-code-and-add-unit-tests/

**Comment by Awhisper** [comment]
本篇文章有点散碎，全篇感觉有一个宗旨，不要在烂代码上写单元测试。。。重构了之后在写。。或者一步一步一点一点重写部分模块后写单元测试。。顺带还讨论了重构问题上的依赖注入以及单例的使用情况。。感觉不出啥有用的重点。。
