### ISSUE TITLE
iOS 上修改私有方法的几种方式解析

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#682]

**Comment by ParsifalC** [comment]
面试过程中，看到应聘者简历上有熟悉 Runtime、AOP 等描述时，就会针对性地问一些修改私有方法的东西，但大多数人只能回答到基于 mattt 的博客中的那种方式，且并不完全理解为什么这么做，对于其他 Aspect 和 fishhook 更是了解甚少。

**Comment by ParsifalC** [comment]
https://xiaozhuanlan.com/topic/1278405369
