### ISSUE TITLE
Design+Code

### ISSUE THREAD

**Issue by EyreFree** [SwiftOldDriver/iOS-Weekly#69]
Design+Code 是一个 iOS app，教你从零开始设计、开发一款 app 直到在 App Store 上架，包括 iOS 11 的设计理论例如颜色、动画以及为 iPhone X 设计，一共包含44小时的视频课程。

学习完全不需要任何编程基础，还会教你在 Sketch 里从头绘制所有的设计图，并且保证所有的设计都是自适应所有设备的，甚至包括横屏和竖屏。

当然还会教你在 Xcode 里用 Swift 4 编写完整的项目。

https://itunes.apple.com/cn/app/design-code/id1281776514?mt=8

// 来自 [@张嘉夫](https://weibo.com/u/2949394297) 的微博

**Comment by lacklock** [comment]
这个书是挺好的。少见的设计和代码兼具的书。
