### ISSUE TITLE
iOS 如何精确还原 UI 稿多行文字间距

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#690]
# 推荐收录

## 链接

http://joeshang.github.io/2018/03/29/ios-multiline-text-spacing/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐎 [iOS 如何精确还原 UI 稿多行文字间距](http://joeshang.github.io/2018/03/29/ios-multiline-text-spacing/)

大家开发中一定遇到过文字间距如何精确还原的问题，不论是 `PhotoShop + 标注工具`还是 `Sketch` 。文章介绍了通过设置 `minimumLineHeight ` `maximumLineHeight `，然后利用 `baselineOffset` 修正完美还原多行文本间距。
