### ISSUE TITLE
[新闻]10月3号起所有 App 必须在 App Store Connect 里配置隐私政策链接

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#693]
# 推荐收录

## 链接

https://developer.apple.com/news/?id=08312018a

## 理由

6 月份苹果更新了应用审核条款，其中包括一条 『必须在 App Store Connect 里配置隐私政策链接』，而在 10 月 3 日，这个条款将正式生效。

**Comment by raozhizhen** [comment]
10 月 3 日起，所有新的应用和更新的应用程序都必须在 App Store Connect 里配置隐私政策链接。隐私政策必须清晰且直白的告知用户，他们的应用会收集什么数据，以及根据他们的隐私保护协议，这些被收集好的数据会被如何利用，幷确认是否有第三方机构有权接触到这些数据。
