### ISSUE TITLE
打造高可拓展的 iOS KeyValueStore

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#695]
# 推荐收录

## 链接

https://xiangwangfeng.com/2017/01/20/%E6%89%93%E9%80%A0%E9%AB%98%E5%8F%AF%E6%8B%93%E5%B1%95%E7%9A%84-iOS-KeyValueStore/

## 理由

很好的解释了 KeyValueStore

**Comment by 100mango** [comment]
本文循序渐进地讲解了如何打造一个高可拓展的 iOS KeyValueStore。行文流畅，没有废话，值得一看。
