### ISSUE TITLE
https://swift.org/server/

### ISSUE THREAD

**Issue by 100mango** [SwiftOldDriver/iOS-Weekly#698]
# 推荐收录

## 链接

https://swift.org/server/

## 理由

Swift Server工作组现在正在进入其发展的新篇章。 这是官方在推特宣布的一个新的网页。

**Comment by kemchenj** [comment]
### [Swift Server 工作组](https://swift.org/server/)

Swift Server 工作组现在正式宣布进入下一个阶段，接下来工作组会专注于建立一个健全，健康的生态系统，让开发者可以更容易找到高质量的库和工具，工作组的成员包括了来自苹果，IBM 和 Vapor 的工程师，他们也会积极参与开发，并且希望社区也可以参与到这个过程中。

其实早在 2016 年这个工作组就已经成立了，当时的目标是创建一套通用的底层 API，让顶层的 Swift 服务端框架可以使用，这就是现在的 [Swift-NIO](https://github.com/apple/swift-nio)。

类似于 Swift 的核心开发团队，这个工作组负责提供总体的技术方向和制定标准，围绕 Swift Server 去构建一系列的服务端生态，目前[在论坛里列了一个 list] 去描述未来的工作方向，包括了官方 Docker 支持，

PS：Swift 官网把 Server Work Group 放到了 Focus Areas 那一栏里，也说明了对于服务端应用的重视。
