### ISSUE TITLE
Objc.io 的创始人 Chris 最近给某公园写的 App

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#7]
https://github.com/chriseidhof/laufpark-stechlin

**Comment by lacklock** [comment]
我没看出这个项目对普通开发者的价值

-1

**Comment by kemchenj** [comment]
@lacklock 这个项目里用了很多 Swift Talk 里讲到的技巧，ValueBinding / IBox / 简易响应式框架的搭建 / 布局语法糖等等，所以我觉得对于 Swift Talk 的观众来说，是一个很好的示例项目
