### ISSUE TITLE
苹果预计下周修正文字讯息漏洞「ChaiOS」

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#70]
https://cn.engadget.com/2018/01/18/apple-fix-for-chaios-bug-next-week-imessage/

趣味评论：修复了一个iOS越来越流畅的Bug [doge][doge]

**Comment by kemchenj** [comment]
### [苹果预计下周修正文字讯息漏洞「ChaiOS」](https://cn.engadget.com/2018/01/18/apple-fix-for-chaios-bug-next-week-imessage/)

跟之前的 iMessage 漏洞类似，收到一个特殊链接的短信之后，设备就会重启，主要是因为 iMessage 会自动加载网页信息生成预览界面，在这一个网页里嵌入几十万个不必要的字符就可以系统崩溃，[据悉这个 bug 已经在 iOS 11.2.5 beta 6 里修复了。](http://www.idownloadblog.com/2018/01/18/ios-11-2-5-beta-6-fixes-the-chaios-text-bomb-messages-bug/)
