### ISSUE TITLE
Mac 高效开发指南

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#700]
https://xiaozhuanlan.com/Effective-Mac

**Comment by raozhizhen** [comment]
星宇同学一直非常的重视工作效率，本书从系统配置、Mac 工作流、编辑器之神：Vim、Git 从入门到进阶、终极武器 Zsh 等方面去打造一个高效的工作流，致力于提高 Mac 工作效率的实用手册。不管你是入门新人，还是撸码老手，都能从书中学习到很多你平时不会注意的，提升工作效率的点。效率上去了，你才能有更多的时间，去对自我进行提升。
