### ISSUE TITLE
 Swift Knowledge Base updates for Swift 4.2

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#705]
https://www.hackingwithswift.com/articles/124/swift-knowledge-base-updates-for-swift-4-2

**Comment by kemchenj** [comment]
### [Swift Knowledge Base updates for Swift 4.2](https://www.hackingwithswift.com/articles/124/swift-knowledge-base-updates-for-swift-4-2)

Swift 4.2 正式版再过几天就要发布了，这一次更新虽然只跨了一个小版本，但还是带来了许多实用的新特性，还没来得及了解的同学推荐看一下这篇文章。
