### ISSUE TITLE
Preparing Your App For iOS 12 Notifications

### ISSUE THREAD

**Issue by RocZhang9673** [SwiftOldDriver/iOS-Weekly#707]
# 推荐收录

## 链接

https://medium.com/@cogitator/preparing-your-app-for-ios-12-notifications-7918ac010597

## 理由

iOS 12 带来了一些新的与用户通知相关的功能，如新的授权选项、动态的快速操作与在通知内进行的用户交互。了解并适配这些新特性以助于改进应用通知在 iOS 12 中的体验。

## 推荐人信息

RocZhang9673

**Comment by RocZhang9673** [comment]
哇，发现这个 medium 链接因为被指责抄袭，作者就删掉了。
看起来原始文章应该是这里：https://www.smashingmagazine.com/2018/09/preparing-your-app-for-ios-12-notifications/

抱歉。

**Comment by kemchenj** [comment]
### 🐕 [Preparing Your App For iOS 12 Notifications](https://www.smashingmagazine.com/2018/09/preparing-your-app-for-ios-12-notifications/)

iOS 12 带来了一些新的与用户通知相关的功能，如新的授权选项、动态的快速操作与在通知内进行的用户交互。了解并适配这些新特性以助于改进应用通知在 iOS 12 中的体验。

> 推荐人：[RocZhang9673](https://github.com/RocZhang9673)
