### ISSUE TITLE
Private properties in protocols

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#708]
# 推荐收录

## 链接

http://alisoftware.github.io/swift/protocols/2018/09/02/protocols-private-properties/

## 理由

Swift 的 protocols 目前不支持权限控制，但使用 fileprivate 关键字可以达到隐藏实现的类似效果。

ps：现在很少用 Swift，不知道这个是否实用，以 Swift 为主要开发语言的编辑看下决定吧。

**Comment by lacklock** [comment]
这个我昨天看了。其实不太实用。或者说我觉得这个技能太简单。就是正常使用了 fileprivate

**Comment by ParsifalC** [comment]
ok
