### ISSUE TITLE
Cabbage - iOS 视频编辑核心框架

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#711]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

https://github.com/VideoFlint/Cabbage/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E

https://github.com/VideoFlint/Cabbage

[此处填写您的推荐理由]

@VitoZiv
我的新开源项目：Cabbage - iOS 视频编辑核心框架，使用简单，不到 20 行代码写完一个最简单的视频编辑功能。功能强大，支持实时图片处理、支持视频、图片作为视频合成资源，支持转场效果、支持实时处理音频数据等等。扩展性也是极好的
项目地址：
我还写了一篇文章说明《iOS 视频编辑核心架构》：

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by vitoziv** [comment]
😍  感谢大佬推荐

（原来还能这样来推荐）
