### ISSUE TITLE
[贝聊科技]一次高效的依赖注入

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#720]
# 推荐收录

## 链接

https://juejin.im/post/5b960cbfe51d450e4f388296

## 理由

分析目前依赖注入的几种方式和问题，并提出自己的解决方案。

**Comment by 100mango** [comment]
本文分析 iOS 目前依赖注入的几个开源库。 并选择了 `EXTConcreteProtocol` 进行了详细的分析，并给出了实际项目中遇到的问题与解决方案。
