### ISSUE TITLE
你的标签是什么？

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#722]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/4mPV1lKXWXaUjXyAGm-jyA

## 理由

程序员不能一直埋头苦干，要适当建立起自己的标签，尤其对职场新人而言，让你主管对你有明确的定位很有好处。

**Comment by raozhizhen** [comment]
每个人都会被打上标签，可能是正向的善于解决问题、Web 安全专家或者是擅长创新。也可能是负向的粗心、眼高手低。可以留意一下自己可能会给人别人留下的标签，好的标签会让你脱颖而出，更多的机会会垂青于你。
