### ISSUE TITLE
How Apps Adapt to the Series 4 Apple Watch Screen Sizes

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#727]
# 推荐收录

## 链接

https://medium.com/@hacknicity/how-apps-adapt-to-the-series-4-apple-watch-screen-sizes-2be49f8ae8f5?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B369

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [How Apps Adapt to the Series 4 Apple Watch Screen Sizes](https://medium.com/@hacknicity/how-apps-adapt-to-the-series-4-apple-watch-screen-sizes-2be49f8ae8f5)

9 月 21 日新一代 Apple Watch Series 4 就要开始发货了，包含 40、44 毫米两个新屏幕尺寸，文章介绍了 watchOS App 如何适配新的设备：对于 watchOS 4 的 App， watchOS 5 默认兼容，只是还是以老的 38、44 毫米显示，以 Xcode 10 编译后，再辅以适当的调整，就能在不同屏幕尺寸上以实际大小显示。
