### ISSUE TITLE
What I Learned Making 5 ARKit Prototypes

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#729]
https://medium.com/@nathangitter/what-i-learned-making-five-arkit-prototypes-7a30c0cd3956

arkit 的几种使用场景，极具启发

**Comment by raozhizhen** [comment]
5 个基于 ARKit2 的原型，用来提升购物体验、给报纸添加视频、观看绘画时增强关键人物，使涂鸦墙能够观看历史，给穿戴设备做屏幕延展。  AR 有非常大的想象空间，（暂存）
