### ISSUE TITLE
员工之间可不可以讨论工资收入？

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#731]
# 推荐收录

## 链接

http://mrpeak.cn/blog/salary-share/

## 理由

[此处填写您的推荐理由]

**Comment by ParsifalC** [comment]
https://mp.weixin.qq.com/s/2rCfTutHddKDnpwVHxhSPw
https://mp.weixin.qq.com/s/2OZu7FApXJz7BXW66HuEaQ

之前非技术类的是这两篇，这篇应该没加过。
