### ISSUE TITLE
[译]SE-0206 Hashable 加强

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#732]
# 推荐收录

## 链接

https://xiaozhuanlan.com/topic/1470362958

## 理由

专栏文章

**Comment by lacklock** [comment]
这个下一期自己加上就好了。

**Comment by kemchenj** [comment]
### [[译]SE-0206 Hashable 加强](https://xiaozhuanlan.com/topic/1470362958)

Swift 4.2 其中一个比较大的改动就是 `Hashable` 协议，对这么一个基础的协议做改动，即使在一年出一门新语言的 Swift 大家族里也几乎是第一次🤷‍♂️，看到这篇提案的时候我就产生了这么几个疑问：

1. 为什么要用 `inout` 这种大家很陌生的概念?
2. Hasher 好像是哈希函数的抽象，那为什么它不是一个泛型，而是结构体？那应该怎么去自定义哈希函数？
3. 而且为什么要去改动这么一个基础协议？之前的协议有哪些不足？

在查阅了一些资料之后，我发现国外对于这件事情的讨论其实也不多，最好的资料还是 Swift-Evolution 的提案，所以特意翻译出来，希望能够帮助大家更好地了解这一次基础协议改动的来龙去脉。
