### ISSUE TITLE
What’s new in Swift 5.0

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#736]
# 推荐收录

https://www.hackingwithswift.com/articles/126/whats-new-in-swift-5-0?from=timeline&isappinstalled=0

## 理由

Swift 的一些新功能

**Comment by zangqilong198812** [comment]
遥遥无期

**Comment by lacklock** [comment]
这篇文章昨天参照正式版更新了！
