### ISSUE TITLE
通俗大白话来理解TCP协议的三次握手和四次分手

### ISSUE THREAD

**Issue by yuhanle** [SwiftOldDriver/iOS-Weekly#738]
# 推荐收录

## 链接

[通俗大白话来理解TCP协议的三次握手和四次分手](https://github.com/jawil/blog/issues/14)

## 理由

推荐一篇TCP协议的文章，移动端工程师也需要了解HTTP方面的一些知识，本篇文章用通俗易懂的方式讲解了平时经常听到的三次握手和四次分手究竟是什么。

## 推荐人信息

[煜寒了](https://github.com/yuhanle)

**Comment by raozhizhen** [comment]
@yuhanle 看了一下，文章排版很乱 ，且东西都是东拼西凑的，包括那些通俗易懂的例子也是直接从文章末尾的 “搬运文章” list 里挪来的，概念也是从其它地方一字不落 copy 过来。比如从 http://www.cnblogs.com/study-everyday/p/6140580.html 这个地方。

**Comment by raozhizhen** [comment]
https://mp.weixin.qq.com/s/zRelB6uSz07YaCoJoggZZA 这是 34 期推荐的 TCP没那么难吧，内容方向差不多。就先不推荐这篇了。
