### ISSUE TITLE
深入浅出 Numerics 协议

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#739]
# 推荐收录

## 链接

https://forums.swift.org/t/notes-on-numerics-in-swift/15746

**Comment by iblacksun** [comment]
### 🐢 [深入浅出 Swift Numerics](https://github.com/xwu/xwu-swift-numerics)

Swift 社区开发者 [Xiaodi Wu](https://github.com/xwu) 写了一系列文章，介绍了 Swift 中数字类型背后的设计思想(如 Int、Float 等)以及许多 `Numeric Protocols` 间的关系，建议有 Swift 开发经验的开发者们精读。
