### ISSUE TITLE
Swift 4.2 正式发布

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#743]
# 推荐收录
https://swift.org/blog/swift-4-2-released

**Comment by 100mango** [comment]
Swift4.2正式发布。我们可以通过 WWDC 2018 的 Session [What’s New in Swift ](https://developer.apple.com/videos/play/wwdc2018/401/) 快速了解新特性。Ole Begemann 总结的 [Playground](https://oleb.net/blog/2018/06/whats-new-in-swift-4-2-playground/) 也方便我们快速试验把玩。
