### ISSUE TITLE
Access Control Management with Swift

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#760]
# 推荐收录

https://medium.com/ios-os-x-development/access-control-management-with-swift-cc3c3d68cbc3

[此处替换为具体的资源地址]

## 理由

介绍了用户权限管理的抽象方式，最后的 api 感觉挺优雅的。

**Comment by raozhizhen** [comment]
本文介绍了用户权限管理的抽象方式，构建了一个基于用户属性的访问控制框架（Attribute Based Access Control），利用了 swift 中 protocol 的强大功能，以策略（Policy = Role ShouldBeAbleTo Action when Condition）的形式，对需求进行建模。该框架可以以非常小的变更成本，增加新的策略来维护权限要求，最后产生的判断用户权限的 API 也非常优雅。
