### ISSUE TITLE
关于Testflight pulic link的原创技术文章

### ISSUE THREAD

**Issue by dustturtle** [SwiftOldDriver/iOS-Weekly#762]
https://juejin.im/post/5bac3ba7e51d450e531c9d2c

dustturtle个人原创。 关注该技术很久，第一时间跟进了。

**Comment by ParsifalC** [comment]
速度很快，如果能在接下来时间内补充下实践内容就更好了，下期周报会在国庆后发布，可以利用这段时间完善下内容。目前其实只是做了个翻译+归纳，内容还有所欠缺。

**Comment by dustturtle** [comment]
已经提交了beta test版本，正在审核中... 这块我们一定会落地成完整的方案... 本来就计划补充实战的，但那时候就感觉不fresh了^__^

**Comment by dustturtle** [comment]
update: 增加了实践的整个流程和大量截图，还有个人使用的测试链接以供体验。整个流程比较简单，因此全文安利为主，干货不多，哈哈
