### ISSUE TITLE
iOS Memory Deep Dive

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#777]
# 推荐收录

## 链接

https://www.jianshu.com/p/dad9f27e412e

## 理由

作者在结合理论知识的前提下，进行了一定的实践。最后总结了一篇和 iOS 内存相关的文章

**Comment by 100mango** [comment]
这是一篇内容非常详实的文章，作者围绕着内存这个话题，从现代计算机操作系统的虚拟内存机制一步步讲到 iOS 的虚拟内存机制，最后给出了在实际开发中一些如何高性能运用内存的建议。
