### ISSUE TITLE
Amazon：smoke-framework 用Swift编写的服务器端服务框架

### ISSUE THREAD

**Issue by LeeCenY** [SwiftOldDriver/iOS-Weekly#782]
# 推荐收录

## 链接

https://github.com/amzn/smoke-framework?utm_source=gold_browser_extension

## 理由

Amazon：Smoke Framework 用Swift编程语言编写的轻量级服务器端服务框架。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by LeeCenY** [comment]
请问，这个没删掉就会添加推荐人信息吗？

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by lacklock** [comment]
@LeeCenY 不是的。只有是推荐的都会写上推荐人。如果推荐人没留下个人信息就会直接写github用户名。

**Comment by LeeCenY** [comment]
@lacklock 好的，这期只有我显示推荐人好尴尬，所以问一下情况
