### ISSUE TITLE
iOS 安装率超过50%

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#785]
# 推荐收录

https://9to5mac.com/2018/10/06/ios-12-now-installed-on-50-of-devices-outpacing-ios-11

**Comment by iblacksun** [comment]
### [仅 23 天，iOS 12 安装率超过 50% ](https://9to5mac.com/2018/10/06/ios-12-now-installed-on-50-of-devices-outpacing-ios-11/)

iOS 12 推出仅 23 天装机量超过 50%，而 iOS 11 达到这个成绩用了超过一个月。相比 iOS 11 发布后的 bug 满天飞，iOS 12 的改进赢得了用户口碑。
