### ISSUE TITLE
Panda

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#789]
# 推荐收录

## 链接

https://github.com/nangege/Panda
https://github.com/nangege/Layoutable
https://github.com/nangege/Cassowary

## 理由

作者原话：
开源一套 Layout 相关的组件，想在列表用 Autolayout 又关心滚动帧率的同学可以试试这个.
Swift 重新实现了 Cassowary 算法、Autolayout 以及一套异步绘制 UI 组件。因为不依赖 UIView，Layout 和渲染都可以在后台进行。既可以利用 Autolayout 来提高列表的开发效率又可以利用多线程提升运行效率。即使抛去多线程的影响，算法本身的效率也是略高于 Apple 的实现。即使不用的话，也可以通过源码了解 Autolayout 内部的运作原理

**Comment by iblacksun** [comment]
### [Panda - 基于 Swift 的 Autolayout 实现](https://github.com/nangege/Panda)

使用 Swift 重新实现 Cassowary 算法、不依赖 UIView 的 Autolayout 机制，使得 Layout 和渲染都可以在后台进行。抛去多线程的影响，算法本身的效率也是略高于 Apple 的实现，即使不用的话，也可以通过源码了解 Autolayout 内部的运作原理。
