### ISSUE TITLE
Optional 的各种实用扩展

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#79]
https://appventure.me/2018/01/10/optional-extensions/?utm_campaign=Revue%20newsletter&utm_medium=Newsletter&utm_source=AppCoda%20Weekly

**Comment by mmoaay** [comment]
文章分享了各种 Optional 的实用扩展。通过这些扩展，可以用更少的代码来实现判断非空、设置默认值、设置默认行为、处理异常、定义多个可选值之间的关系、判断执行以及过滤功能。文章末尾还给出了一个例子，通过代码对比的方式，鼓励大家使用扩展 Optional 的方式来实现业务逻辑。
