### ISSUE TITLE
Unleashing the power of asset catalogs and bundles on iOS

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#791]
# 推荐收录

https://rambo.codes/ios/2018/10/03/unleashing-the-power-of-asset-catalogs-and-bundles-on-ios.html

**Comment by iblacksun** [comment]
### 🐕 [Unleashing the power of asset catalogs and bundles on iOS](https://rambo.codes/ios/2018/10/03/unleashing-the-power-of-asset-catalogs-and-bundles-on-ios.html)

对于 iOS 开发者来说，`Bundles` 和 `Asset catalogs` 应该是再熟悉不过了。文章介绍了一些高级用法，特别是利用 Asset Catalogs 存储一些配置文件，可以给不同的设备配置不同的值，打开了另一个世界。文末还结合 `Bundles` 和 `Asset catalogs` 介绍了一个实际 App 中的使用场景。
