### ISSUE TITLE
Hiding Implementation Details Using internal Properties

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#805]
# 推荐收录

## 链接

https://holko.pl/2018/10/08/internal-modifier/

**Comment by kemchenj** [comment]
### [通过 internal 隐藏内部属性](Hiding Implementation Details Using internal Properties)

这篇文章介绍了作者在封装数据库时遇到的问题——如何处理 public 类型的 internal 属性，让外部调用者可以在无法得知 internal 属性的同时生成这个 public 类型的实例。在暴露必要接口的同时隐藏实现细节，是一件不容易做对的事情，文章很简短，希望大家看完之后可以更好地处理类似的接口设计问题。
