### ISSUE TITLE
ParticlesText - 文本粒子动画

### ISSUE THREAD

**Issue by MonkYU** [SwiftOldDriver/iOS-Weekly#808]
# 推荐收录

## 链接

https://github.com/MonkYU/ParticlesText

## 理由

[小而巧的文本粒子动画，灵感源于WWDC 2018 Frost, 基于Metal, 支持多项属性配置，作为一个动画特效还是蛮有意思]

**Comment by nianran** [comment]
Hello，基本看完了你的作品。
作为自己练手的Demo，我觉得写得挺好的。
但是如果以放到收录为前提，缺少亮点。
缺少必要的Metal流程注释总结和扩散计算规则的注释。

**Comment by MonkYU** [comment]
> Hello，基本看完了你的作品。
> 作为自己练手的Demo，我觉得写得挺好的。
> 但是如果以放到收录为前提，缺少亮点。
> 缺少必要的Metal流程注释总结和扩散计算规则的注释。

多谢指点，规则流程类的东西确实没有整理，疏忽了。
权当一个有意思的动画特效吧，类似FluidFun,PSO之类的群体算法，也可以尝试加入，全看个人想象力了,。
再次感谢。

**Comment by ParsifalC** [comment]
> # 推荐收录
> ## 链接
> https://github.com/MonkYU/ParticlesText
> 
> ## 理由
> [小而巧的文本粒子动画，灵感源于WWDC 2018 Frost, 基于Metal, 支持多项属性配置，作为一个动画特效还是蛮有意思]

@MonkYU 首先感谢推荐自己的作品到周报，这个粒子效果看起来很酷炫。以下几点，是我的建议：

- 作为这种 UI 组件，适用范围希望能够更广，现在提供的功能很有限；
- 以『组件』来定义的话，可以提供主流的 CocoaPods/Carthage 支持；
- 目前新组件的趋势，建议还是以 Swift 编写；
- 需要完善和规范你的 Readme，至少也要体现出 Feature，排版也能够更好一点；

另外，我觉得基于你这次实践，为大家分享一篇相关的博文，或许会更合适。
综上所述，我们暂时先关闭这个 issue，期待你更好的作品。
