### ISSUE TITLE
iOS 系统中导航栏的转场解决方案与最佳实践

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#815]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/CQ-uUJuX-nlPrM_tHBdbNQ

## 理由

美团 App 中转场的最佳实践。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🌟 🐢 [iOS 系统中导航栏的转场解决方案与最佳实践](https://mp.weixin.qq.com/s/CQ-uUJuX-nlPrM_tHBdbNQ)

在 App 开发阶段，涉及到导航栏样式改变的需求时，经常会遇到转场效果不佳或者与预期样式不符的“小问题”。本文由美团技术团队出品，详细讲解了 UINavigationBar 的生命周期、导航栏样式转换的时机，同时给出了相关最佳实践，建议仔细阅读。
