### ISSUE TITLE
Best strategies for configuring multiple environments in Xcode projects

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#826]
# 推荐收录

## 链接

https://kenb.us/best-strategies-for-configuring-multiple-environments-in-xcode-projects

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by raozhizhen** [comment]
在 Xcode 项目中配置不同环境，很多人会选择添加 Target，但这并不是一个很好的方法，太重了，你需要维护多个 Target 及它们的 Info.plist。最好的策略是添加新的 Configurations，然后给其设置该环境下的 xcconfig 配置文件。还能在 Build Settings 里为 Configuration 设置不同的 bundle identifier、产品名称，应用图标，使它们能同时运行在一个手机上，并得到很好的区分。
