### ISSUE TITLE
Running Other Apps' Siri Shortcuts Through Deep Links in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#827]
# 推荐收录

## 链接

https://swiftrocks.com/running-other-apps-siri-shortcuts-through-deep-links-in-swift.html

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
@nianran 你的

**Comment by nianran** [comment]
Get
