### ISSUE TITLE
Text Kit Tutorial: Getting Started

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#832]
# 推荐收录

## 链接

https://www.raywenderlich.com/5960-text-kit-tutorial-getting-started?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more

## 理由

TextKit的一些特性总结，跟随系统字体变化等

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐕 [Text Kit Tutorial: Getting Started](https://www.raywenderlich.com/5960-text-kit-tutorial-getting-started?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)

`TextKit` 是 iOS 7 开始推出的图文混排框架，其基于底层的 `CoreText`。`UIKit` 中的 `UILabel`、`UITextView`、`UITextField` 都构建在 `TextKit` 之上。本文介绍介绍了两部分内容：如何适配 `Dynamic Type` 特性；如何实现图文混排及文字环绕图片布局。
