### ISSUE TITLE
The power of key paths in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#833]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/the-power-of-key-paths-in-swift

## 理由

Swift key paths 的使用。

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
http://www.objc.io/blog/2018/10/30/auto-layout-with-key-paths/

这篇也是关于 key paths  的应用

**Comment by derekcoder** [comment]
> http://www.objc.io/blog/2018/10/30/auto-layout-with-key-paths/
> 
> 这篇也是关于 key paths  的应用

在自己的项目中实践过，方法名太容易忘记了，而且 Xcode 对 Key Path 的提示也不友好。最后发现还是 SnapKit 最好用。
