### ISSUE TITLE
DEAD in iOS Memory

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#836]
# 推荐收录

## 链接

https://www.jianshu.com/p/a5a25ce1dca1?utm_campaign=hugo&utm_medium=reader_share&utm_content=note&utm_source=weixin-timeline&from=timeline&isappinstalled=0

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
这个和 [39期 iOS memory deep dive](https://github.com/SwiftOldDriver/iOS-Weekly/blob/4a8a694a751929eb454f968d3c32634bea93e24d/Reports/%2339-2018.10.15.md#-ios-memory-deep-dive) 目录分类差不多，内容也大同小异，就不需要做重复推荐了。
