### ISSUE TITLE
Protocol Oriented Programming in Swift: Is it better than Object Oriented Programming?

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#839]
# 推荐收录

## 链接

https://www.appcoda.com/pop-vs-oop/

## 理由

对协议编程的看法

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by waz0820** [comment]
领养一下 @ParsifalC
