### ISSUE TITLE
Remove the single-pass requirement on Sequence

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#85]
https://twitter.com/olebegemann/status/955210332183695365
https://forums.swift.org/t/pitch-remove-the-single-pass-requirement-on-sequence/7964

**Comment by lacklock** [comment]
这是一个建议的改进吗？

**Comment by kemchenj** [comment]
@lacklock 这是一个对于 Sequence 类型的改进建议，Ole Begemann 大神在推特上说 `If you read this thread top to bottom, you’ll understand many of the subtleties around Swift’s Iterator/Sequence/Collection hierarchy.`，所以我才拉过来，其实我自己也还没仔细看完，只是大概瞄了一眼 😢

**Comment by lacklock** [comment]
我想了一下，这条相对于普通读者还是难度太大，不够直观。
先放弃吧。
