### ISSUE TITLE
String’s ABI and UTF-8

### ISSUE THREAD

**Issue by kemchenj** [SwiftOldDriver/iOS-Weekly#856]
# 推荐收录

## 链接

https://forums.swift.org/t/string-s-abi-and-utf-8/17676

## 理由

String 之前计划的 ABI 方案已经落实并且合并到主分支里了，虽然这些底层变动带来的好处不会立刻在 API 层面反映出来，目前能够直观感受到的是性能上的提升，这篇帖子就着重列举了一下相关的内容。

**Comment by nixzhu** [comment]
里面有提到中文，这方面有什么需要注意的吗？

**Comment by iblacksun** [comment]
活捉 @nixzhu ，粗略看了下，似乎对开发者来说没啥变更，是语言内部实现。
> This does not immediately surface in the API, but allows for some important performance wins and gives a more consistent basis for future APIs providing efficient and direct access to the underlying code units.

**Comment by kemchenj** [comment]
> This ABI includes some significant changes, the primary one being that native Swift strings are stored as UTF-8 where they were previously stored either as ASCII or UTF-16 depending on their contents
>
> 这次 ABI 包含了一些显著的改动，其中最主要的一点就是原生 Swift 字符串会统一使用 UTF-8 进行存储（在内存里），而之前是根据内容选择 ASCII 或者 UTF-16 进行存储。
>
> ...
>
> Strings of Chinese characters are traditionally a worst-case scenario for UTF-8 decoding performance relative to UTF-16, as UTF-8 resorts to a multi-byte encoding sequence while UTF-16 just stores the scalar value directly as a code unit. This is even worse in reverse, because a continuation-byte in UTF-8 does not communicate the distance to the start of the scalar.
> 
> 中文字符串是传统意义上 UTF-8 性能最差的场景之一（比起 UTF-16），因为 UTF-8 需要对编码序列进行重排（把多个 UTF-8 单位合并为单个 Unicode 码位），而之前可以直接把单个 UTF-16 单位当作一个 Unicode 码位。在逆序（遍历）的时候性能甚至更差，因为逆序遍历时无法从首个 UTF-8 单位里获取对应的单个 Unicode 码位长度。（顺序解码的时候，可以从首个 UTF-8 单位里获取到整个 Unicode 码位长度，加快解码速度）

@nixzhu 这是我的理解

**Comment by nixzhu** [comment]
@iblacksun @kemchenj 感谢翻译和解答

**Comment by iblacksun** [comment]
### 🐕 [String’s ABI and UTF-8](https://forums.swift.org/t/string-s-abi-and-utf-8/17676)

 近日，Michael Ilseman 在 Swift 社区论坛发文 `String’s ABI and UTF-8` 表示 String ABI 相关改动已提交到 master 分支。具体来说，这是底层实现的一次显著改动(这些改动在 API 层面无任何影响)，其中最主要的一点就是原生 Swift 字符串会统一使用 UTF-8 进行存储（在内存里），而之前是根据内容选择 ASCII 或者 UTF-16 进行存储。

 文章还特地提到：传统意义上中文字符串是 UTF-8 性能最差的场景(需对多个 UTF-8 编码进行重排合并得到 Unicode 码位)，得益于现代 CPU 的改进，这些已不再是问题。
