### ISSUE TITLE
How to remove duplication from Swift tests with helper functions

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#857]
# 推荐收录

## 链接

https://www.mokacoding.com/blog/how-to-remove-duplication-from-swift-tests-with-helper-functions/

## 理由

前半段只是说明了在编写单元测试时应该对重复代码进行封装，但后半部分提到 `#file` 和 `#line` 来在公共 Helper 方法中定位调用方就很妙了。

**Comment by nianran** [comment]
OK
