### ISSUE TITLE
Swift 5 and ABI stability

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#859]
# 推荐收录

## 链接

https://theswiftdev.com/2018/11/06/swift-5-and-abi-stability/

## 理由

介绍了 ABI 是什么，会影响到什么以及 Swift 5 ABI 稳定能带来什么。

**Comment by kemchenj** [comment]
### [Swift 5 and ABI stability](https://theswiftdev.com/2018/11/06/swift-5-and-abi-stability/)

Swift 5 的分支最近已经准备要合并到主干了，这一次合并意味着 ABI 在 Release 之前不会有大改动，并且在未来版本保持 ABI 的向后兼容性。

所以最近在 Swift 论坛上也能看到核心团队加快节奏在调整精简标准库的 API，包括加入 [Contiguous Collection Protocols](https://forums.swift.org/t/contiguous-collection-protocols/17875) 确立数组内存布局以便优化排序等操作，去除掉 [Sequence.SubSequence](https://forums.swift.org/t/se-0234-removing-sequence-subsequence/17750) 以便提升数组切片效率等等。

如果你还不了解 ABI 相关的内容，那么可以看看这篇文章，了解一下 ABI 稳定对我们日常开发的影响。
