### ISSUE TITLE
Debugging a subtle Swift bug that will make you facepalm

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#864]
# 推荐收录

## 链接

https://www.jessesquires.com/blog/debugging-subtle-swift-bug-facepalm/

## 理由

一个 typo 引起的 bug，从这方面印证了采用 Codable 的好处。

**Comment by kemchenj** [comment]
### [Debugging a subtle Swift bug that will make you facepalm](https://www.jessesquires.com/blog/debugging-subtle-swift-bug-facepalm/)

Jesse Squires 在修复一个 UI 测试的崩溃时，发现是因为 json 序列化时使用了 `[String: Any]` 作为容器，赋值时少写了一对括号导致的问题：

```swift
func toDictionary() -> [String: Any] {
    var dict: [String: Any] = [:]

    // code setting other keys and values...

    dict[JSONKeys.dateClosed] = self.dateClosed?.toMongoDate

    return dict
}

extension Date {
    func toMongoDate() -> [String: Any] {
        // return date in expected mongo date format
    }
}
```

这段代码是 Codable 之前就存在的，从这方面也印证了 Codable 的好处。
