### ISSUE TITLE
Hack 苹果系统 Api 实现 iOS TableViewCell 侧滑方案

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#868]
# 推荐收录

## 链接

http://awhisper.github.io/2018/11/08/swipe-tableviewcell/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Awhisper** [comment]
这玩意别录了吧。。。没球用。。。我close了啊
