### ISSUE TITLE
iOS复杂动画之抽丝剥茧

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#88]
https://juejin.im/post/5a31d974f265da4319564798
这是篇翻译文章，原文来自
https://www.raywenderlich.com/102590/how-to-create-a-complex-loading-animation-in-swift

这是作者的另一个原创文章
https://juejin.im/post/5a31d9696fb9a04500031005

**Comment by mmoaay** [comment]
[raywenderlich](https://www.raywenderlich.com/) 的教程一直以通俗易懂闻名，这次推荐的是一篇一步一步教你实现复杂动画的教程，使用的核心技术点是 `CAAnimationGroup`。如果你没有时间一步一步跟着实现，也可以通过[这个地址](https://koenig-media.raywenderlich.com/uploads/2015/05/SBLoader-Finished.zip)直接下载，查看完整的 Demo 工程。
