### ISSUE TITLE
Swift Static Libraries 迁移实践

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#882]
# 推荐收录

## 链接

[Swift Static Libraries 迁移实践](https://juejin.im/entry/5be5514de51d451ca670055e)

**Comment by ParsifalC** [comment]
https://juejin.im/post/5bea2cf151882579117f5b01

用这个吧

**Comment by Damonvvong** [comment]
看了一下，质量有点堪忧。就不放到周报了
