### ISSUE TITLE
Xcode and LLDB Advanced Debugging Tutorial

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#885]
# 推荐收录

## 链接
Xcode and LLDB Advanced Debugging Tutorial
[Part1](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-1-31919aa149e0)
[Part2](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-2-8bfeae4cdfdb)
[Part3](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-3-8238aca63e7c)

**Comment by raozhizhen** [comment]
作者准备了一个简易项目，演示了如何利用 Xcode 和 LLDB 进行高级调试。核心要做的是，在运行时修复错误，进行调试，而不需要停止编译器。

[第一部分](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-1-31919aa149e0)

在断点处添加调试命令，注入一行新代码进行调试。

[第二部分](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-2-8bfeae4cdfdb)

通过给属性添加观察点，当其变化的时候，会中断程序，观察到属性变化的前后值，及可以进行堆栈跟踪。

[第三部分](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-3-8238aca63e7c)

在断点中，通过调试命令新增新的断点，使断点在某些场景下才开始执行，更高效的追踪问题。
