### ISSUE TITLE
Code Friend:使用JavaScript开发Xcode Extensions

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#892]
# 推荐收录

## 链接
https://mp.weixin.qq.com/s/oQJXtZYcO4u6m4SCHZUT_w

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
重复了。
