### ISSUE TITLE
Mirror / Custom​Reflectable / Custom​Leaf​Reflectable

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#896]
# 推荐收录

## 链接

https://nshipster.com/mirror/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [Mirror / Custom​Reflectable / Custom​Leaf​Reflectable](https://nshipster.com/mirror/)

相对于 `Obective-C` 来说，Swift 没有 `Runtime` 不能实现类似 `swizzing` 功能。但得益于 `Mirror` 的`反射`功能，我们可以得到对象信息的只读访问，`Playground` 就是 `Mirror` 的一个主要场景。文章介绍了 `Mirror` 及相关的 `Custom​Reflectable` `Custom​Leaf​Reflectable` 两个 `protocol`  使用细节。
