### ISSUE TITLE
Modern C++编程挑战

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#898]
# 推荐收录

## 链接

https://boxueio.com/blackboard/128
https://boxueio.com/blackboard/127
https://boxueio.com/blackboard/124
https://boxueio.com/blackboard/123

**Comment by 100mango** [comment]
实际上和 Modern C++ 关系不大，除了最后一节的模板编程，其他都是算法相关，暂时不成体系。
