### ISSUE TITLE
一个根据已有的代码文件 / 目录和简单的配置文件来生成 Xcode project 的开源工具

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#9]
https://github.com/yonaskolb/XcodeGen

**Comment by lacklock** [comment]
虽然很酷炫，但是这个感觉没什么用啊

-1

**Comment by EyreFree** [comment]
1. 可以用来快速生成模板工程：比如 CocoaPods 的 create 目前是直接 Clone 官方仓库的（观察命令执行过程 log 可知），用 XcodeGen 的话可以实现根据配置文件本地生成；

2. 可以投入实际开发：我们可以将 .xcodeproj 从 Git 追踪中忽略，然后写个脚本丢工程目录下，每次新 Clone 仓库后，执行一下脚本就能生成工程（事实上，我之前维护的 App 即使不移除 .xcodeproj，Clone 到本地后也要脚本来执行一些基本的配置任务，比如拉取 submodule 或 pod install 等），避免引入 Git 导致的合并冲突或 .xcodeproj 文件损坏等问题；

3. 如果真的投入日常使用的话，可以方便地和他人分享自己的配置或者自己快速在自己的不同工程间重用同一套配置；

4. 快速创建支持多平台的 framework 工程（如果自己通过 Xcode 添加需要手动一个一个搞...多一个平台要多设置一次，万一改了某一项设置，同步起来还麻烦）。

PS：以上这些是我结合官方文档和自己的想法总结的，未经实际验证...

**Comment by EyreFree** [comment]
一个根据已有的代码文件 / 目录和简单的配置文件来生成 Xcode project 的开源工具，快速生成模板工程、将 .xcodeproj 从 Git 追踪中忽略、方便地和他人分享自己的工程配置等，无限可能，等你尝试。
