### ISSUE TITLE
iOS 下如何一键调试 Push

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#901]
# 推荐收录

## 链接

[iOS 下如何一键调试 Push](https://juejin.im/entry/5bed735951882518805ab68c)

**Comment by ParsifalC** [comment]
以前推过了。

https://github.com/SwiftOldDriver/iOS-Weekly/blob/48427eac5663bacdb00beddf2653ff1c32f4d5d1/Reports/%2312-2018.03.25.md
