### ISSUE TITLE
专栏文章【译】

### ISSUE THREAD

**Issue by waterXu** [SwiftOldDriver/iOS-Weekly#905]
【译】A taste of MVVM and Reactive paradigm
https://medium.com/flawless-app-stories/a-taste-of-mvvm-and-reactive-paradigm-5288a819cca1

**Comment by waterXu** [comment]
已经翻译好，等待安排

**Comment by ParsifalC** [comment]
> 已经翻译好，等待安排

这个直接发你博客吧~然后给一份 md，我们发公众号~
