### ISSUE TITLE
实用的可选项（Optional）扩展

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#906]
# 推荐收录

## 链接

https://swift.gg/2018/11/19/useful-optional-extensions/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。
https://github.com/100mango

**Comment by iblacksun** [comment]
### 🐕 [实用的可选项（Optional）扩展](https://swift.gg/2018/11/19/useful-optional-extensions/)

`Option` 是 `Swift` 最基础的内容，它迫使开发者们处理好一些临界情况，使得程序更加健壮。标准库中 `Option` 的 API 非常少，编码过程中通常需要配合 `if let` `guard let` 一起使用，这容易造成多分支。作者参考了 `Rust` `Scala` 等语言的实现，给出了一些 `Option` 扩展，或许你可以用于自己的项目中。
