### ISSUE TITLE
Extending optionals in Swift

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#914]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/extending-optionals-in-swift

**Comment by kemchenj** [comment]
### [Extending optionals in Swift](https://www.swiftbysundell.com/posts/extending-optionals-in-swift)

Swift 里的 Optional 虽然帮助我们保证了内存安全访问，但在很多情况下都需要我们解包后再进行操作，让代码显得比较啰嗦而且不连贯。

Sundell 这周就给我们带来了 Optional 的实用拓展，总结了一些 Optional 常见场景，并且构建对应的语法糖去优化 Optional 的使用。
