### ISSUE TITLE
 Using closures with the coordinator pattern

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#917]
# 推荐收录

## 链接

https://www.swiftbysundell.com/posts/extending-optionals-in-swift

**Comment by raozhizhen** [comment]
swift 中的可选值实际是定义了一个 Optional<Wrapped> 枚举，所以我们可以通过扩展枚举，让我们以一种更好的方式处理可选值。

我们可以给枚举添加一个扩展方法，当值为 nil 的时候抛出 error，直接将方法接入到调用末尾，则能轻松将缺失值转换为一个错误。
当然你也可以发挥更多想象力，添加扩展将值的逻辑判断代码、类型匹配代码等等操作封装起来，最终得到一个更好，更容易阅读的调用链。
