### ISSUE TITLE
App Store Connect Holiday Schedule

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#925]
# 推荐收录

## 链接

https://developer.apple.com/news/?id=11272018

## 理由

App Store Connect 将在 12 月 23 日至 27 日停止审核。

**Comment by iblacksun** [comment]
### [App Store Connect Holiday Schedule](https://developer.apple.com/news/?id=11272018)

因圣诞假期，App Store 将在 12 月 23 日至 27 日停止应用审核。
