### ISSUE TITLE
编程一小时

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#926]
# 推荐收录

## 链接

https://www.apple.com/cn/today/collection/hourofcode/

## 理由

在 12 月 3 日至 9 日期间，你有机会从编程基础知识入手，用 Swift 语言写代码，为机器人编程。也许这一小时的课程，将开启你对编程一生的热爱。

**Comment by iblacksun** [comment]
### [Apple 举办编程一小时活动](https://www.apple.com/cn/today/collection/hourofcode/)

在 12 月 1 日至 14 日期间，Apple 将在全国的 Apple Store 零售店举办「编程一小时」活动，现在已开放报名。你将有机会从编程基础知识入手，用 Swift 语言写代码，为机器人编程。也许这一小时的课程，将开启你对编程一生的热爱。
