### ISSUE TITLE
工具: Git Hooks for Swift projects 

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#929]
# 推荐收录

## 链接
[Git Hooks for Swift projects ](https://github.com/orta/Komondor)

**Comment by kemchenj** [comment]
### [Komondor - Git Hooks for Swift projects](https://github.com/orta/Komondor)

Komondor 是一款帮助简化 Git Hook 设置的工具，它依赖于 Swift Package Manager 的运行，只要在 Package.swift 里加上依赖，然后像这样去指定 hook 就可以完成设置：

```swift
import PackageConfig

let config = PackageConfig([
    "komondor": [
        "pre-push": "swift test",
        "pre-commit": [
            "swift test",
            "swift run swiftFormat .",
            "swift run swiftlint autocorrect --path Sources/",
            "git add .",
        ],
    ],
])
```
