### ISSUE TITLE
一道值得思考的 iOS 面试题

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#931]
# 推荐收录

## 链接

[一道值得思考的 iOS 面试题](https://juejin.im/entry/5c00f58de51d4566d067ff7a)

**Comment by waz0820** [comment]
帮忙领养一下😄 @ParsifalC

**Comment by ParsifalC** [comment]
文章中的问题是来自孙源15年的神经病院objc runtime入院考试，类似分析比较透彻比较推荐冰霜的博文，这篇文章基本是根据实验陆续推测出的结果的，还不够深入，也没有讲到 viewDidLoad 执行时具体是如何压栈的。
