### ISSUE TITLE
支付宝小程序框架浅析及如何在 mPaaS 内深度集成

### ISSUE THREAD

**Issue by nianran** [SwiftOldDriver/iOS-Weekly#935]
## 链接

[支付宝小程序框架浅析及如何在 mPaaS 内深度集成](https://mp.weixin.qq.com/s/IoBNTsomdKYHgjOv5dSfPQ)

**Comment by Awhisper** [comment]
这篇太广告了。。。我都不知道怎么下笔写。。。毫无干货。。外加 mpaas这个闭源玩意。。。
