### ISSUE TITLE
使用Repository改进View Model接口的稳定性

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#937]
# 推荐收录

## 链接

https://boxueio.com/series/build-boxue-app-in-mvvm/episode/496

**Comment by linwenbang** [comment]
泊学需要会员，并且里面没有试看部分，介绍也相当短，不太合适进行推荐，没会员的人进去会一脸懵，对于付费内容推荐的尝试，可以考虑其他的，本期不推荐
