### ISSUE TITLE
Swift Protocols: Tips and Tricks

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#948]
# 推荐收录

## 链接

https://www.hackingwithswift.com/articles/138/swift-protocols-tips-and-tricks

**Comment by iblacksun** [comment]
### 🐢 [Swift Protocols: Tips and Tricks](https://www.hackingwithswift.com/articles/138/swift-protocols-tips-and-tricks)

`Protocol` 是 `Swift` 的基础，我们可以定义方法，甚至提供默认实现。本文介绍了 `Protocol` 的一些小 tips，比如 `协议组合`、`Protocol extensions`、利用  Protocol 实现`模板方法设计模式`等。
