### ISSUE TITLE
iOS: ARM64不定函数传参问题调试剖析

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#950]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/d8-g3Gp6A3hZLa1EjV6KVQ

**Comment by raozhizhen** [comment]
从实际开发中遇到的一个平台相关的 crash 问题出发，通过代码对比，研究了在 x86-64 架构和 ARM64 架构对于不定函数参数传递的方式——特别是 iOS 系统的不同之处，同时也解答了为什么在调用带不定参数类型的 C 函数指针时，应该显示将其强转为对应参数类型的函数指针问题。
