### ISSUE TITLE
iOS App冷启动治理：来自美团外卖的实践

### ISSUE THREAD

**Issue by Damonvvong** [SwiftOldDriver/iOS-Weekly#951]
# 推荐收录

## 链接

https://mp.weixin.qq.com/s/jN3jaNrvXczZoYIRCWZs7w

**Comment by nianran** [comment]
### 🐢 [iOS App冷启动治理：来自美团外卖的实践](https://mp.weixin.qq.com/s/jN3jaNrvXczZoYIRCWZs7w)

文章整理了 APP 冷启动的三个阶段，对三个阶段分别提出了存量解决方案、管理增量方案和监控体系。下面几点是文章观点的总结：
- 冷启动阶段T1： 点击 APP 图标进入至 main 函数，这两者之间的耗时
    - 代码瘦身，废弃无用代码和资源文件
    - 延时 +load 函数，将函数延迟到合适的触发时机，比如说冷启动结束之后
- 冷启动阶段T2： main 函数后至 didFinishLaunchingWithOptions 函数执行完毕，这两者之间的耗时
    - 整理 APP 启动阶段，顺序化子项目的启动顺序
    - 分阶段启动，利用自验的 `Kylin` 项目，将子项目的注册信息（启动阶段、启动需要执行的代码等）写入 `__DATA` 数据段中，运行期读取 `__DATA` 段代码，并赋予执行。
    - 利用工具（Time Profile/自研的 Caesium）整理执行过程中的一些隐晦耗时，比如归档操作、IO操作、资源任务等
- 冷启动阶段T3： didFinishLaunchingWithOptions 函数至首页渲染完成，这两者之间的耗时
    - 将 APP 的 RootViewController 设置为闪屏，同时进行首页UI的构建，加快 RootViewController 的加载
    - 整理首页加载的串行操作，优化体验成并行操作
- 数据监控：除了上述的优化外，建立监控体系，保证持续优化成果
    - 冷启动的开始与结束时间对比，值得注意的是这里的开始时间采用了 APP 进程创建时间
    - 冷启动过程中的关键节点都有手动添加的测速点，并自动上报
