### ISSUE TITLE
使用 Metal 和 Core ML 评价照片质量

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#967]
# 推荐收录

## 链接

http://yulingtianxia.com/blog/2018/11/30/Photo-Assessment/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
@XanderXu 这篇你写下简评哈周日前完成就行
