### ISSUE TITLE
让我们构建一个Swift.Array

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#968]
# 推荐收录

## 链接

https://swift.gg/2018/12/06/friday-qa-2015-04-17-lets-build-swiftarray/

## 理由

[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by Damonvvong** [comment]
文章内容比较旧，不建议推荐
