### ISSUE TITLE
Apple’s augmented reality tool kit can now detect walls and 2D images in beta

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#97]
https://techcrunch.com/2018/01/24/apples-augmented-reality-tool-kit-can-now-detect-walls-and-2d-images-in-beta/

 TechCrunch：苹果的增强现实工具（测试版）将可以检测墙壁和 2D 图像 - “ARKit 1.5 增加了一些功能，包括一个大的功能：墙壁检测。…目前 ARKit 只提供水平面检测，使开发人员知道“地面”位置，然后用它来定位或放置 3D 空间中的物体。…通过此更新，ARKit 可以识别垂直表面并将目标放在表面上。…ARKit 也获得水平绘图的更新，以便更好地识别圆形桌子或椅子等不规则形状物体和线条检测。整体的追踪速度和准确性也得到了提高。…ARKit 还将以 1080p 显示“真实世界”（以前是720p）。…ARKit 也将有图像识别。如果场景中有 2D 图像，如墙上的海报或艺术品，ARKit 允许开发人员将其物理位置映射到空间和表面上，以便增添浮动文字或触动声音的功能。”

via. 林泰前

**Comment by lacklock** [comment]
可以一起写到11.3预览版那条新闻里。你看下怎么一起写吧。

**Comment by lacklock** [comment]
arkit 1.5 还是单独列一条新闻好了。
