### ISSUE TITLE
Why should we use Swift over Objective-C?

### ISSUE THREAD

**Issue by linwenbang** [SwiftOldDriver/iOS-Weekly#971]
# 推荐收录

## 链接

[此处替换为具体的资源地址]

## 理由

https://medium.com/@chungbkhn87/why-should-we-use-swift-over-objective-c-78b71725e63f

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by iblacksun** [comment]
### 🐢 [Why should we use Swift over Objective-C?](https://medium.com/@chungbkhn87/why-should-we-use-swift-over-objective-c-78b71725e63f)

Swift vs Objective-C，到底该怎么选？如果你正在纠结这个问题，请细读。

Objective-C 有着几十年的历史，更稳定；Swift，更现代化的语言，有许多先进特性，文章从多个角度对比了两种语言的优势和劣势。
