### ISSUE TITLE
Improving code testability with Swift protocols

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#975]
# 推荐收录

## 链接

https://medium.com/flawless-app-stories/solving-dependencies-in-swift-9ee6ad4a8941

**Comment by KyoLi** [comment]
这篇文章我打开一直是挂的状态，本周先不提了。。

**Comment by ParsifalC** [comment]
> 这篇文章我打开一直是挂的状态，本周先不提了。。

好的，应该是被墙了。我挪到下周吧。
