### ISSUE TITLE
How to convert your Xcode plugins to Xcode extensions

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#976]
# 推荐收录

## 链接

https://medium.freecodecamp.org/how-to-convert-your-xcode-plugins-to-xcode-extensions-ac90f32ae0e3

**Comment by nianran** [comment]
### 🐢 🚧 [How to convert your Xcode plugins to Xcode extensions](https://medium.freecodecamp.org/how-to-convert-your-xcode-plugins-to-xcode-extensions-ac90f32ae0e3)

Xcode 插件和扩展，是我们日常开发中工具，作者针对于 Xcode 插件和扩展的发展做了以下几点的总结：
1. 什么是插件：只是一个类型的包，Xcode 启动时的同时，会去加载指定的 Info.plist 文件
2. 优秀的插件推荐：Alcatraz（包管理工具）、Xvim（ vim 编辑器）、SCXcodeMiniMap（代码地图面板）、FuzzyAutocompletePlugin（函数模糊搜索）、KSImageNamed（图像名称列表）、ColorSense（颜色转换）、LinkedConsole（控制台打印跳转代码文件）
3. 插件的制作：作者以 [Xmas](https://github.com/onmyway133/Xmas)、[XcodeColorSense](https://github.com/onmyway133/XcodeColorSense) 和 [XcodeWay](https://github.com/onmyway133/XcodeWay/tree/1.0) 的制作为例向我们展示了如何 Hook Xcode 的方法，已经与 Xcode 中 UI 元素进行交互
4. 插件的禁止：由于 2015 年末，[XcodeGhost](https://en.wikipedia.org/wiki/XcodeGhost) 事件，苹果从 Xcode8 开始禁止加载插件。当然，你可以通过 Xcode 重签名这种方式去绕过苹果的检查，重新加载插件
5. 扩展的崛起：苹果爸爸关上了一扇门，肯定会开一扇窗。从此 Xcode8 中的扩展进入了人们的视线当中。利用现有的 XcodeKit，去获取文档信息，修改当前文档内容，但是跟以前优秀的插件相比，这个方式能实现的东西是在太少了。作者以 [XcodeColorSense2](https://github.com/onmyway133/XcodeColorSense2) 为例，向我们介绍了，如何去实现/调试/安装扩展。另外作者以 [XcodeWay](https://github.com/onmyway133/XcodeWay) 向我们介绍了如何使用去用新的扩展去调用 Apple Script
