### ISSUE TITLE
iOS客户端图片智能裁剪

### ISSUE THREAD

**Issue by ParsifalC** [SwiftOldDriver/iOS-Weekly#981]
# 推荐收录

## 链接

http://www.cnblogs.com/kenshincui/p/ios-tu-pian-zhi-neng-cai-jian.html

**Comment by nianran** [comment]
不建议添加到周报中。
作为文章或者代码都缺少一下成分
- 作者没有公开任何算法，只提供了 Framework 这个封闭的静态库
- 关于模型，作者只简单介绍使用了神经网络
- 作者还指出算法和裁剪效果都还有待优化和提升

该库需要依赖 opencv 这个仓库，是另外引入的一个 c++ 仓库。尝试下载了一下有120MB，需要另外添加依赖的仓库，势必会增加 APP 大小。

**Comment by nianran** [comment]
@ParsifalC
