### ISSUE TITLE
Optimizing Images

### ISSUE THREAD

**Issue by waz0820** [SwiftOldDriver/iOS-Weekly#986]
# 推荐收录

## 链接

[Optimizing Images](https://www.swiftjectivec.com/optimizing-images/)

**Comment by iblacksun** [comment]
### 🐢 [Optimizing Images](https://www.swiftjectivec.com/optimizing-images/)

图片一直是 App 内存消耗大户，本文从图片的`加载`、`解压`、`呈现`开始，特别介绍了列表型应用应该如何优化图片内存问题。
