### ISSUE TITLE
Cydia商店宣布关闭，这对iOS越狱有这些影响

### ISSUE THREAD

**Issue by XanderXu** [SwiftOldDriver/iOS-Weekly#987]
# 推荐收录
Cydia商店宣布关闭，这对iOS越狱有这些影响
## 链接

https://www.ithome.com/0/400/752.htm

## 理由

Cydia商店关闭对于iOS越狱社区的影响

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by nianran** [comment]
### [Cydia 商店宣布关闭，这对 iOS 越狱有这些影响](https://www.ithome.com/html/iphone/400752.htm)
- Saurik 决定关闭的仅仅只是 Cydia Store，也就是其中的支付系统，不会影响原有的安装/卸载/管理应用程序的功能，免费或已经付费的应用，依旧可以进行下载。如果希望继续购买付费应用，需要去其他存储库（如Packix，Chariz或Dynastic Repo）进行下载
- Saurik 决定关闭商店跟一个 BUG 有关，其可以通过用户的PayPal帐户启用任意Cydia Store软件包购买
- Sileo 是 Cydia 的计划替代品，但是其还在开发阶段
