### ISSUE TITLE
逆向学习微信

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#989]
# 推荐收录

https://github.com/lefex/iWeChat

[此处替换为具体的资源地址]

我们一起还原微信，探索微信的奥妙之处。微信作为 IM 领域的佼佼者，更是 APP 中的翘楚。它里面有很多值得开发者借鉴的地方，小到某个 View 的设计，大到整个APP的架构，一系列隐藏在背后的技术手段或交互设计需要我们挖掘。所以，希望通过 iWeChat 这个项目能够勾勒出微信的设计，使用到的技术手段等。最重要的是，从这个项目中，你可以学到如何分析一个第三方 APP。[此处填写您的推荐理由]

## 推荐人信息

如果收录这个资源，我们会在点评后面说明推荐信息人。

**Comment by ParsifalC** [comment]
和 #988  重复了
